### ISSUE TITLE
TypeError: Expected cv::UMat for argument 'src1'

### ISSUE THREAD

**Issue by SOITION** [LmeSzinc/AzurLaneAutoScript#112]
打开就报错，难受

**Comment by LmeSzinc** [comment]
能发一下详细的log吗

**Comment by SOITION** [comment]
2020-07-22 16:41:46.554 | INFO | Loading OCR model: ./bin/cnocr_models/cnocr
2020-07-22 16:41:46.633 | INFO | [Emotion fleet_1] 119
2020-07-22 16:41:46.633 | INFO | [Emotion fleet_2] 119
2020-07-22 16:41:46.633 | INFO | [Emotion fleet_3] 119
2020-07-22 16:41:46.634 | INFO | [Emotion_bug] 0/100
2020-07-22 16:41:46.634 | INFO | ==================== CAMPAIGN_7_2 ====================
2020-07-22 16:41:46.634 | INFO | Count: [0]
2020-07-22 16:41:47.073 | INFO | [Screen_size] 1280x720
2020-07-22 16:41:47.073 | INFO | <<< UI ENSURE >>>
2020-07-22 16:41:47.489 | INFO | [UI] page_campaign
2020-07-22 16:41:47.489 | INFO | Already at page_campaign
2020-07-22 16:41:47.490 | INFO | <<< UI ENSURE INDEX >>>
2020-07-22 16:41:47.543 | ERROR | Expected Ptr<cv::UMat> for argument 'src1'
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 24, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 99, in main
    az.run(self.config.CAMPAIGN_NAME)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 161, in run
    self.handle_campaign_ui()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 190, in handle_campaign_ui
    self.ensure_campaign_ui(name=self.stage, mode=self.config.CAMPAIGN_MODE)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_ui.py", line 85, in ensure_campaign_ui
    self.campaign_ensure_chapter(index=chapter)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_ui.py", line 24, in campaign_ensure_chapter
    fast=True, skip_first_screenshot=True, step_sleep=STAGE_SHOWN_WAIT, finish_sleep=0)
  File "C:\fakepath\AzurLaneAutoScript\module\ui\ui.py", line 227, in ui_ensure_index
    current = letter(self.device.image)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_ocr.py", line 190, in get_chapter_index
    self._get_stage_name(image)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_ocr.py", line 165, in _get_stage_name
    buttons = self.campaign_extract_name_image(image)
  File "C:\fakepath\AzurLaneAutoScript\module\base\decorator.py", line 62, in wrapper
    return record['func'](self, *args, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_ocr.py", line 109, in campaign_extract_name_image
    digits += self.campaign_match_multi(TEMPLATE_STAGE_CLEAR, image, name_offset=(75, 9), name_size=(60, 16))
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_ocr.py", line 88, in campaign_match_multi
    name = extract_letters(name, letter=name_letter, threshold=name_thresh)
  File "C:\fakepath\AzurLaneAutoScript\module\base\utils.py", line 321, in extract_letters
    r, g, b = cv2.split(cv2.subtract(image, (*letter, 0)))
TypeError: Expected Ptr<cv::UMat> for argument 'src1'
2020-07-22 16:41:47.544 | INFO | Saving error: ./log/error/1595407307544

**Comment by LmeSzinc** [comment]
更新一下就好了.

昨晚改动了一些底层函数, 出现了一些问题, 一个小时内就修了. 你可能刚好在那个时间安装了Alas, 真是不好意思.

**Comment by SOITION** [comment]
谢谢，辛苦了
