### ISSUE TITLE
找到个bug

### ISSUE THREAD

**Issue by gflong00** [LmeSzinc/AzurLaneAutoScript#122]
这是报错的记录
`

2020-07-27 00:31:25.230 | INFO | -------------------- D1 --------------------
2020-07-27 00:31:25.230 | INFO | <<< ENTER MAP >>>
2020-07-27 00:31:25.790 | INFO | Click ( 189,  280) @ d1
2020-07-27 00:31:27.730 | INFO | Set fast forward.
2020-07-27 00:31:27.730 | INFO | [Fast_Forward] on
2020-07-27 00:31:27.730 | INFO | Click ( 981,  511) @ MAP_PREPARATION
2020-07-27 00:31:28.466 | INFO | Using fleet: [1, 2, 0]
2020-07-27 00:31:28.466 | INFO | Hard Campaign. No fleet preparation
2020-07-27 00:31:28.466 | INFO | Click (1031,  589) @ FLEET_PREPARATION
2020-07-27 00:31:33.624 | INFO | Enemy searching appeared.
2020-07-27 00:31:33.624 | INFO | fleet_lock
2020-07-27 00:31:33.624 | INFO | [Fleet_Lock] on
2020-07-27 00:31:33.624 | INFO | <<< MAP INIT >>>
2020-07-27 00:31:33.625 | INFO | Map is green sea.
2020-07-27 00:31:33.633 | INFO | [HP]  98%   0%   0%  98%  98%   0%
2020-07-27 00:31:33.635 | INFO | [Map_buff] 1
2020-07-27 00:31:33.635 | INFO | Skip strategy bar check.
2020-07-27 00:31:33.635 | INFO | Ensure edge in sight.
2020-07-27 00:31:34.150 | INFO |            tile_center: 0.922 (good match)
2020-07-27 00:31:34.164 | INFO | 0.054s  _   edge_lines: 2 hori, 1 vert
2020-07-27 00:31:34.164 | INFO | Edges: /     homo_loca: ( 34,  52)
2020-07-27 00:31:34.168 | INFO |            center_loca: (3, 2)
2020-07-27 00:31:34.168 | INFO |       camera_corrected: C5 -> D3
2020-07-27 00:31:34.168 | INFO |                 Camera: D3
2020-07-27 00:31:34.168 | INFO | Full scan start
2020-07-27 00:31:34.168 | INFO | [enemy_missing] EN: 2, MY: 0, SI: 2, BO: 0, CA: 0
2020-07-27 00:31:34.168 | INFO | [enemy_may____] EN: 0, MY: 0, SI: 0, BO: 0, CA: 0
2020-07-27 00:31:34.169 | INFO | Focus to: D2
2020-07-27 00:31:34.169 | INFO | Map swipe: (0, -1)
2020-07-27 00:31:34.169 | INFO | Swipe ( 605,  272) -> ( 593,  429), 0.162
2020-07-27 00:31:35.505 | INFO |            tile_center: 0.937 (good match)
2020-07-27 00:31:35.513 | INFO | 0.050s  _   edge_lines: 2 hori, 1 vert
2020-07-27 00:31:35.513 | INFO | Edges: /     homo_loca: ( 27,  46)
2020-07-27 00:31:35.516 | INFO |            center_loca: (3, 1)
2020-07-27 00:31:35.516 | INFO |                 Camera: D2
2020-07-27 00:31:35.519 | ERROR | [Errno 2] No such file or directory: './assets/cn/template/TEMPLATE_SIREN_DD.png'
Traceback (most recent call last):
  File "D:\program\AZURAUTO\AzurLaneAutoScript\alas.py", line 24, in run
    self.__getattribute__(command.lower())()
  File "D:\program\AZURAUTO\AzurLaneAutoScript\alas.py", line 118, in event
    az.run(self.config.CAMPAIGN_EVENT, folder=self.config.EVENT_NAME)
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\campaign\run.py", line 173, in run
    self.campaign.run()
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\campaign\campaign_base.py", line 106, in run
    self.map_init(self.MAP)
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\map\fleet.py", line 373, in map_init
    self.full_scan()
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\map\fleet.py", line 260, in full_scan
    is_carrier_scan=is_carrier_scan)
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\map\camera.py", line 220, in full_scan
    self.predict(is_carrier_scan=is_carrier_scan)
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\map\camera.py", line 120, in predict
    self.view.predict()
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\map_detection\view.py", line 85, in predict
    grid.predict()
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\map_detection\grid_predictor.py", line 62, in predict
    self.enemy_genre = self.predict_enemy_genre()
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\map_detection\grid_predictor.py", line 164, in predict_enemy_genre
    if template.match(image):
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\base\template.py", line 59, in match
    res = cv2.matchTemplate(np.array(image), self.image, cv2.TM_CCOEFF_NORMED)
  File "D:\program\AZURAUTO\AzurLaneAutoScript\module\base\template.py", line 30, in image
    self._image = np.array(Image.open(self.file))
  File "C:\Users\gfl\anaconda3\envs\azur\lib\site-packages\PIL\Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './assets/cn/template/TEMPLATE_SIREN_DD.png'
2020-07-27 00:31:35.523 | INFO | Saving error: ./log/error/1595781095523
`
我找了下template里面，好像确实没有TEMPLATE_SIREN_DD.png

**Comment by LmeSzinc** [comment]
确认一下:
1. 是否使用了dev分支, 新活动永夜幻光在dev分支里, master分支还是旧的, 为了照顾EN服
2. 是否选择了活动 "永夜幻光" 的 "D1". 在 campaign/event_20200723_cn/d1.py 里设置的是 `MAP_SIREN_TEMPLATE = ['U101', 'U73', 'U552']`, 并没有 `DD`.

**Comment by gflong00** [comment]
是dev而且是永夜幻光的D1，我之前运行的挺好的，但是就这次突然报错了

**Comment by gflong00** [comment]
这是之前一点的记录
`

2020-07-27 00:31:03.855 | INFO | Research select quit
2020-07-27 00:31:03.857 | INFO | Click ( 750,  676) @ RESEARCH_SELECT_QUIT
2020-07-27 00:31:06.662 | INFO | [UI route] page_research - page_main
2020-07-27 00:31:06.662 | INFO | <<< UI CLICK >>>
2020-07-27 00:31:06.664 | INFO | Click (1232,   31) @ GOTO_MAIN
2020-07-27 00:31:10.374 | INFO | <<< MISSION REWARD >>>
2020-07-27 00:31:10.374 | INFO | [UI route] page_main - page_mission
2020-07-27 00:31:10.374 | INFO | <<< UI CLICK >>>
2020-07-27 00:31:10.375 | INFO | Click ( 859,  693) @ MAIN_GOTO_MISSION
2020-07-27 00:31:11.788 | INFO | Click (1074,   22) @ MISSION_MULTI
2020-07-27 00:31:13.020 | INFO | Click (1065,   19) @ MISSION_MULTI
2020-07-27 00:31:13.653 | INFO | Click (1015,  664) @ GET_ITEMS_2
2020-07-27 00:31:15.845 | INFO | [UI route] page_mission - page_main
2020-07-27 00:31:15.846 | INFO | <<< UI CLICK >>>
2020-07-27 00:31:15.847 | INFO | Click (1226,   39) @ GOTO_MAIN
2020-07-27 00:31:19.410 | INFO | <<< REWARD END >>>
2020-07-27 00:31:19.410 | INFO | <<< DAILY REWARD >>>
2020-07-27 00:31:19.410 | INFO | [DailyRecord_daily] Record time: 2020-07-27 00:19:11
2020-07-27 00:31:19.410 | INFO | [DailyRecord_daily] Last update: 2020-07-27 00:00:00
2020-07-27 00:31:19.410 | INFO | [DailyRecord_hard] Record time: 2020-07-27 00:25:34
2020-07-27 00:31:19.410 | INFO | [DailyRecord_hard] Last update: 2020-07-27 00:00:00
2020-07-27 00:31:19.411 | INFO | [DailyRecord_exercise] Record time: 2020-07-27 00:30:19
2020-07-27 00:31:19.411 | INFO | [DailyRecord_exercise] Last update: 2020-07-27 00:00:00
2020-07-27 00:31:19.411 | INFO | [Daily_executed] 0/5
2020-07-27 00:31:19.411 | INFO | ==================== D1 ====================
2020-07-27 00:31:19.411 | INFO | Count: [13]
2020-07-27 00:31:19.955 | INFO | <<< UI ENSURE >>>
`
是收完每日之后再点开d1的时候报错，可能这里面还有点问题

**Comment by gflong00** [comment]
感觉像是重新进d1的时候程序自己选错图了，之间的衔接可能还是旧版本没改

**Comment by LmeSzinc** [comment]
有在这个期间更新脚本吗
地图文件都是热加载的

**Comment by gflong00** [comment]
不是很确定，有可能github电脑端自动帮我更新了

**Comment by LmeSzinc** [comment]
好像丢了一个commit, 已经补上了
我另外clone了一份dev分支, 没有问题
