### ISSUE TITLE
使用UU加速器的情况下出现 ImportError: ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by Akailist** [LmeSzinc/AzurLaneAutoScript#1267]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

大佬，我在安装完最新的alas之后第三次打开时在进行 START ADB SERVICE进程的UIAUTOMATOR2 INIT步骤时出现了该错误：ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。我预估是ADB的问题，我用的是蓝叠中国5正式版模拟器，我不太懂蓝叠的ADB，也不是很熟悉python方面的专业知识，请大佬指导一下，麻烦了。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

UPDATE程序顺利完成

### 相关 Logs

```Text
"C:\Users\crazylieshen\Desktop\AzurLaneAutoScript
==================== SHOW DEPLOY CONFIG ====================
AutoUpdate: False
Language: zh-CN
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
AutoUpdate is disabled, skip
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
==================== KILL ALAS.EXE ====================
==================== KILL PYTHON.EXE ====================
+-----------------------------------------------------------+
|                    UPDATE DEPENDENCIES                    |
+-----------------------------------------------------------+
==================== CHECK PYTHON ====================
"C:/Users/crazylieshen/Desktop/AzurLaneAutoScript/toolkit/python.exe" --version
Python 3.7.6
[ success ]
==================== UPDATE DEPENDENCIES ====================
"C:/Users/crazylieshen/Desktop/AzurLaneAutoScript/toolkit/python.exe" -m pip install -r requirements.txt --disable-pip-version-check
Requirement already satisfied: adbutils==0.11.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: aiofiles==0.7.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: alas-webapp==0.3.7 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 9)) (0.3.7)
Requirement already satisfied: anyio==1.3.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: apkutils2==1.0.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: asgiref==3.4.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 12)) (3.4.1)
Requirement already satisfied: async-generator==1.10 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 13)) (1.10)
Requirement already satisfied: atomicwrites==1.4.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 14)) (1.4.0)
Requirement already satisfied: cached-property==1.5.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 15)) (1.5.2)
Requirement already satisfied: certifi==2021.5.30 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 16)) (2021.5.30)
Requirement already satisfied: cffi==1.15.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 17)) (1.15.0)
Requirement already satisfied: chardet==3.0.4 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 18)) (3.0.4)
Requirement already satisfied: cigam==0.0.3 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 19)) (0.0.3)
Requirement already satisfied: click==8.0.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 20)) (8.0.1)
Requirement already satisfied: cnocr==1.2.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 21)) (1.2.2)
Requirement already satisfied: colorama==0.4.4 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 22)) (0.4.4)
Requirement already satisfied: commonmark==0.9.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 23)) (0.9.1)
Requirement already satisfied: cycler==0.10.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 24)) (0.10.0)
Requirement already satisfied: decorator==5.1.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 25)) (5.1.0)
Requirement already satisfied: deprecated==1.2.13 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 26)) (1.2.13)
Requirement already satisfied: deprecation==2.1.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 27)) (2.1.0)
Requirement already satisfied: filelock==3.3.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 28)) (3.3.0)
Requirement already satisfied: future==0.18.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 29)) (0.18.2)
Requirement already satisfied: gevent==21.12.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 30)) (21.12.0)
Requirement already satisfied: gluoncv==0.6.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 31)) (0.6.0)
Requirement already satisfied: graphviz==0.8.4 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 32)) (0.8.4)
Requirement already satisfied: greenlet==1.1.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 33)) (1.1.2)
Requirement already satisfied: h11==0.12.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 34)) (0.12.0)
Requirement already satisfied: httptools==0.4.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 35)) (0.4.0)
Requirement already satisfied: idna==2.6 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 36)) (2.6)
Requirement already satisfied: imageio==2.9.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 37)) (2.9.0)
Requirement already satisfied: importlib-metadata==4.8.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 38)) (4.8.1)
Requirement already satisfied: inflection==0.5.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 39)) (0.5.1)
Requirement already satisfied: jellyfish==0.8.8 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 40)) (0.8.8)
Requirement already satisfied: kiwisolver==1.3.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 41)) (1.3.2)
Requirement already satisfied: logzero==1.7.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 42)) (1.7.0)
Requirement already satisfied: lxml==4.6.3 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 43)) (4.6.3)
Requirement already satisfied: lz4==3.1.3 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 44)) (3.1.3)
Requirement already satisfied: matplotlib==3.4.3 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 45)) (3.4.3)
Requirement already satisfied: msgpack==1.0.3 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 46)) (1.0.3)
Requirement already satisfied: mxnet==1.6.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 47)) (1.6.0)
Requirement already satisfied: numpy==1.16.6 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 48)) (1.16.6)
Requirement already satisfied: opencv-python==4.5.3.56 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 49)) (4.5.3.56)
Requirement already satisfied: packaging==20.9 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 50)) (20.9)
Requirement already satisfied: pillow==8.3.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 51)) (8.3.2)
Requirement already satisfied: portalocker==2.3.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 52)) (2.3.2)
Requirement already satisfied: prettytable==2.2.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 53)) (2.2.1)
Requirement already satisfied: progress==1.6 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 54)) (1.6)
Requirement already satisfied: py==1.10.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 55)) (1.10.0)
Requirement already satisfied: pycparser==2.21 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 56)) (2.21)
Requirement already satisfied: pyelftools==0.27 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 57)) (0.27)
Requirement already satisfied: pygments==2.11.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 58)) (2.11.2)
Requirement already satisfied: pyparsing==2.4.7 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 59)) (2.4.7)
Requirement already satisfied: pypresence==4.2.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 60)) (4.2.1)
Requirement already satisfied: python-dateutil==2.8.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 61)) (2.8.2)
Requirement already satisfied: python-dotenv==0.19.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 62)) (0.19.0)
Requirement already satisfied: pywebio==1.5.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 63)) (1.5.2)
Requirement already satisfied: pywin32==301 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 64)) (301)
Requirement already satisfied: pyyaml==5.4.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 65)) (5.4.1)
Requirement already satisfied: pyzmq==22.3.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 66)) (22.3.0)
Requirement already satisfied: requests==2.18.4 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 67)) (2.18.4)
Requirement already satisfied: retry==0.9.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 68)) (0.9.2)
Requirement already satisfied: retrying==1.3.3 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 69)) (1.3.3)
Requirement already satisfied: rich==11.0.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 70)) (11.0.0)
Requirement already satisfied: scipy==1.4.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 71)) (1.4.1)
Requirement already satisfied: six==1.16.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 72)) (1.16.0)
Requirement already satisfied: sniffio==1.2.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 73)) (1.2.0)
Requirement already satisfied: starlette==0.14.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 74)) (0.14.2)
Requirement already satisfied: tornado==6.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 75)) (6.1)
Requirement already satisfied: tqdm==4.62.3 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 76)) (4.62.3)
Requirement already satisfied: typing-extensions==3.10.0.2 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 77)) (3.10.0.2)
Requirement already satisfied: ua-parser==0.10.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 78)) (0.10.0)
Requirement already satisfied: uiautomator2==2.16.7 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 79)) (2.16.7)
Requirement already satisfied: urllib3==1.22 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 80)) (1.22)
Requirement already satisfied: user-agents==2.2.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 81)) (2.2.0)
Requirement already satisfied: uvicorn[standard]==0.17.6 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 82)) (0.17.6)
Requirement already satisfied: watchgod==0.7 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 83)) (0.7)
Requirement already satisfied: wcwidth==0.2.5 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 84)) (0.2.5)
Requirement already satisfied: websockets==10.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 85)) (10.0)
Requirement already satisfied: whichcraft==0.6.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 86)) (0.6.1)
Requirement already satisfied: wrapt==1.13.1 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 87)) (1.13.1)
Requirement already satisfied: xmltodict==0.12.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 88)) (0.12.0)
Requirement already satisfied: zerorpc==0.6.3 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 89)) (0.6.3)
Requirement already satisfied: zipp==3.6.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 90)) (3.6.0)
Requirement already satisfied: zope.event==4.5.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 91)) (4.5.0)
Requirement already satisfied: zope.interface==5.4.0 in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 92)) (5.4.0)
Requirement already satisfied: setuptools in c:\users\crazylieshen\desktop\azurlaneautoscript\toolkit\lib\site-packages (from gevent==21.12.0->-r requirements.txt (line 30)) (42.0.2)
[ success ]
+-------------------------------------------------------+
|                    UPDATE APP.ASAR                    |
+-------------------------------------------------------+
AutoUpdate is disabled, skip
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Task adb.exe not found
taskkill /f /im nox_adb.exe >nul 2>nul
Task nox_adb.exe not found
taskkill /f /im adb_server.exe >nul 2>nul
Task adb_server.exe not found
taskkill /f /im HD-Adb.exe >nul 2>nul
Task HD-Adb.exe not found
C:/Users/crazylieshen/Desktop/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
adb.exe: failed to check server version: protocol fault (couldn't read status): connection reset
Devices: []
C:/Users/crazylieshen/Desktop/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
adb.exe: failed to check server version: protocol fault (couldn't read status): connection reset
Devices: []
==================== UIAUTOMATOR2 INIT ====================
Traceback (most recent call last):
  File "C:\Users\crazylieshen\Desktop\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\crazylieshen\Desktop\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\crazylieshen\Desktop\AzurLaneAutoScript\deploy\installer.py", line 22, in <module>
    Installer().install()
  File "C:\Users\crazylieshen\Desktop\AzurLaneAutoScript\deploy\installer.py", line 16, in install
    self.adb_install()
  File "C:\Users\crazylieshen\Desktop\AzurLaneAutoScript\deploy\adb.py", line 55, in adb_install
    for device in adbutils.adb.iter_device():
  File "C:\Users\crazylieshen\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 445, in iter_device
    c.check_okay()
  File "C:\Users\crazylieshen\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 166, in check_okay
    data = self.read_string(4)
  File "C:\Users\crazylieshen\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 142, in read_string
    data = self.read(n).decode()
  File "C:\Users\crazylieshen\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 123, in read
    return self._read_fully(n)
  File "C:\Users\crazylieshen\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 131, in _read_fully
    chunk = self.conn.recv(t)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
```

### 截图

![QQ截图20220630010159](https://user-images.githubusercontent.com/108395410/176494339-b9210e03-d2fd-4f6e-a464-194756b9dca7.png)

### 还有别的吗？

我的配置文件：
[deploy.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9012621/deploy.txt)
我查到的python脚本出现该问题的解决办法（都不会）：
https://blog.csdn.net/IllegalName/article/details/77164521
https://cloud.tencent.com/developer/article/1614536

**Comment by LmeSzinc** [comment]
模拟器设置里的adb连接打开了吗

**Comment by Akailist** [comment]
打开了
![QQ截图20220630011056](https://user-images.githubusercontent.com/108395410/176496162-2212bddd-4f67-4e7c-801a-f6b2f0dfc76c.png)

**Comment by mikage3miya** [comment]
是否有在使用过程中开启网络加速器类软件呢？
我在开启Alas并暂停工作后开启迅游加速器就会报[WinError 10054] 远程主机强迫关闭了一个现有的连接。
关闭加速器并重启模拟器和Alas即可恢复

**Comment by Akailist** [comment]
原来如此，我在运行期间一直有开UU加速器，虽然是加速的steam商店，可能就是这个原因，谢谢大佬。

**Comment by LmeSzinc** [comment]
联动一下
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1010
