### ISSUE TITLE
活动图出现MapDetectionError: Vanish point and distant point too close

### ISSUE THREAD

**Issue by NeuWings** [LmeSzinc/AzurLaneAutoScript#166]
活动图时候出现的错误,
再次测试成功复现.
运行环境雷电模拟器4.0.29.

Logs举例,具体见附加压缩文档.因为大小问题删除了部分图片.
[1598384760909.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/5128768/1598384760909.zip)
[1598418778090.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/5128771/1598418778090.zip)
[1598419265714.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/5128774/1598419265714.zip)

2020-08-26 13:12:26.560 | INFO | -------------------- A1 --------------------
2020-08-26 13:12:26.560 | INFO | <<< ENTER MAP >>>
2020-08-26 13:12:27.825 | INFO | Click ( 321,  271) @ a1
2020-08-26 13:12:30.862 | INFO | [MAP_CLEAR_ALL_THIS_TIME] False
2020-08-26 13:12:30.862 | INFO | [Map_info] 99%, star_1, star_2, star_3, clear, 3_star, green, fast_forward
2020-08-26 13:12:30.863 | INFO | [Fast_Forward] on
2020-08-26 13:12:30.864 | INFO | Click ( 968,  496) @ MAP_PREPARATION
2020-08-26 13:12:32.706 | INFO | Using fleet: [2, 1, 1]
2020-08-26 13:12:32.707 | INFO | Click (1035,  477) @ SUBMARINE_CHOOSE
2020-08-26 13:12:33.925 | INFO | Current selected: [1]
2020-08-26 13:12:33.926 | INFO | Click (1041,  481) @ SUBMARINE_CHOOSE
2020-08-26 13:12:35.124 | INFO | Click (1058,  203) @ FLEET_1_CHOOSE
2020-08-26 13:12:36.323 | INFO | Current selected: [1, 2]
2020-08-26 13:12:36.323 | INFO | Click (1065,  181) @ FLEET_1_CHOOSE
2020-08-26 13:12:37.606 | INFO | Click (1081,  615) @ FLEET_PREPARATION
2020-08-26 13:12:44.538 | INFO | Enemy searching appeared.
2020-08-26 13:12:44.648 | INFO | [Fleet_Lock] on
2020-08-26 13:12:44.648 | INFO | Switch over
2020-08-26 13:12:44.648 | INFO | Click (1051,  692) @ SWITCH_OVER
2020-08-26 13:12:48.809 | INFO | <<< MAP INIT >>>
2020-08-26 13:12:48.820 | INFO | [HP]  98% ____ ____  98%  98%  98%
2020-08-26 13:12:48.842 | INFO | [Map_buff] 3
2020-08-26 13:12:48.843 | INFO | Strategy set: formation=3, submarine_view=False, submarine_hunt=True
2020-08-26 13:12:48.843 | INFO | Click (1215,  441) @ STRATEGY_OPEN
2020-08-26 13:12:50.151 | INFO | [Formation] 3
2020-08-26 13:12:50.183 | INFO | [Submarine_view] on
2020-08-26 13:12:50.184 | INFO | Click (1149,  448) @ SUBMARINE_VIEW_ON
2020-08-26 13:12:51.470 | INFO | [Submarine_hunt] on
2020-08-26 13:12:51.470 | INFO | Click (1230,  443) @ SUBMARINE_HUNT_ON
2020-08-26 13:12:53.361 | INFO | [Submarine_hunt] off
2020-08-26 13:12:53.365 | INFO | [Submarine_hunt] off
2020-08-26 13:12:53.366 | INFO | Click (1232,  450) @ SUBMARINE_HUNT_OFF
2020-08-26 13:12:55.325 | INFO | [Submarine_hunt] on
2020-08-26 13:12:56.097 | INFO | [Submarine_view] off
2020-08-26 13:12:56.100 | INFO | [Submarine_hunt] on
2020-08-26 13:12:56.111 | INFO | Click (1069,  336) @ STRATEGY_OPENED
2020-08-26 13:12:56.720 | INFO | Ensure edge in sight.
2020-08-26 13:12:57.947 | INFO |           vanish_point: (  634, -1424)
2020-08-26 13:12:57.947 | INFO |          distant_point: (  634, -1424)
2020-08-26 13:12:57.950 | ERROR | Vanish point and distant point too close
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 27, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 131, in daily
    az.daily_wrapper_run()
  File "C:\fakepath\AzurLaneAutoScript\module\reward\reward.py", line 243, in daily_wrapper_run
    if az.run_event_daily():
  File "C:\fakepath\AzurLaneAutoScript\module\event\campaign_ab.py", line 52, in run_event_daily
    result = self.run(name=name, folder=self.config.EVENT_NAME_AB)
  File "C:\fakepath\AzurLaneAutoScript\module\event\campaign_ab.py", line 24, in run
    super().run(name=name, folder=folder, total=1)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 167, in run
    self.campaign.run()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 119, in run
    self.map_init(self.MAP)
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 521, in map_init
    self.ensure_edge_insight(preset=self.map.in_map_swipe_preset_data)
  File "C:\fakepath\AzurLaneAutoScript\module\map\camera.py", line 154, in ensure_edge_insight
    self.update()
  File "C:\fakepath\AzurLaneAutoScript\module\map\camera.py", line 109, in update
    raise e
  File "C:\fakepath\AzurLaneAutoScript\module\map\camera.py", line 91, in update
    self.view.load(self.device.image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\view.py", line 42, in load
    super().load(image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\detector.py", line 49, in load
    self.backend.load(image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\homography.py", line 79, in load
    self.load_homography(storage=self.config.HOMO_STORAGE, image=image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\homography.py", line 102, in load_homography
    perspective_.load(image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\perspective.py", line 122, in load
    raise MapDetectionError('Vanish point and distant point too close')
module.exception.MapDetectionError: Vanish point and distant point too close
2020-08-26 13:12:58.090 | INFO | Saving error: ./log/error/1598418778090

**Comment by LmeSzinc** [comment]
更改了一些代码的执行顺序, 在A图用二队道中测试了几轮没有问题
