### ISSUE TITLE
启动 Alas.exe 后的命令行内出现报错

### ISSUE THREAD

**Issue by suxin0301** [LmeSzinc/AzurLaneAutoScript#1893]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

每次点击后都出现如下报错，并非初次安装，运作一个多月之后突然出现的情况。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
"E:\Games\AzurLaneAutoScript
==================== SHOW DEPLOY CONFIG ====================
Repository: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"E:/Games/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in E:/Games/AzurLaneAutoScript/.git/
[ success ]
==================== SET GIT PROXY ====================
"E:/Games/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"E:/Games/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
==================== SET GIT REPOSITORY ====================
"E:/Games/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"E:/Games/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
From https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
 * branch              master     -> FETCH_HEAD
[ success ]
==================== PULL REPOSITORY BRANCH ====================
"E:/Games/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" reset --hard origin/master
HEAD is now at 688b1fcd upd:[JP]MAIL_EMPTY (#1884)
[ success ]
"E:/Games/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" pull --ff-only origin master
From https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
 * branch              master     -> FETCH_HEAD
Already up to date.
[ success ]
==================== SHOW VERSION ====================
"E:/Games/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" log --no-merges -1
error: cannot spawn less: No such file or directory
commit 688b1fcd024032e0af27545cd82c3999ed66bc8c (HEAD -> master, origin/master)
Author: Bookbug <willyhappyya@gmail.com>
Date:   Fri Nov 18 18:34:30 2022 +0800

    upd:[JP]MAIL_EMPTY (#1884)
[ success ]
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
==================== KILL ALAS.EXE ====================
==================== KILL PYTHON.EXE ====================
+-----------------------------------------------------------+
|                    UPDATE DEPENDENCIES                    |
+-----------------------------------------------------------+
==================== CHECK PYTHON ====================
"E:/Games/AzurLaneAutoScript/toolkit/python.exe" --version
Python 3.7.6
[ success ]
==================== UPDATE DEPENDENCIES ====================
"E:/Games/AzurLaneAutoScript/toolkit/python.exe" -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --disable-pip-version-check
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: adbutils==0.11.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: aiofiles==0.7.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: alas-webapp==0.3.7 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 9)) (0.3.7)
Requirement already satisfied: anyio==1.3.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: apkutils2==1.0.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: asgiref==3.4.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 12)) (3.4.1)
Requirement already satisfied: async-generator==1.10 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 13)) (1.10)
Requirement already satisfied: cached-property==1.5.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 14)) (1.5.2)
Requirement already satisfied: certifi==2021.5.30 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 15)) (2021.5.30)
Requirement already satisfied: cffi==1.15.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 16)) (1.15.0)
Requirement already satisfied: chardet==3.0.4 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 17)) (3.0.4)
Requirement already satisfied: cigam==0.0.3 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 18)) (0.0.3)
Requirement already satisfied: click==8.0.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 19)) (8.0.1)
Requirement already satisfied: cnocr==1.2.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 20)) (1.2.2)
Requirement already satisfied: colorama==0.4.5 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 21)) (0.4.5)
Requirement already satisfied: commonmark==0.9.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 22)) (0.9.1)
Requirement already satisfied: cycler==0.10.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 23)) (0.10.0)
Requirement already satisfied: decorator==5.1.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 24)) (5.1.0)
Requirement already satisfied: deprecated==1.2.13 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 25)) (1.2.13)
Requirement already satisfied: deprecation==2.1.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 26)) (2.1.0)
Requirement already satisfied: filelock==3.3.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 27)) (3.3.0)
Requirement already satisfied: future==0.18.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 28)) (0.18.2)
Requirement already satisfied: gevent==21.12.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 29)) (21.12.0)
Requirement already satisfied: gluoncv==0.6.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 30)) (0.6.0)
Requirement already satisfied: graphviz==0.8.4 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 31)) (0.8.4)
Requirement already satisfied: greenlet==1.1.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 32)) (1.1.2)
Requirement already satisfied: h11==0.12.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 33)) (0.12.0)
Requirement already satisfied: httptools==0.4.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 34)) (0.4.0)
Requirement already satisfied: idna==2.6 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 35)) (2.6)
Requirement already satisfied: imageio==2.9.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 36)) (2.9.0)
Requirement already satisfied: importlib-metadata==4.8.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 37)) (4.8.1)
Requirement already satisfied: inflection==0.5.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 38)) (0.5.1)
Requirement already satisfied: jellyfish==0.8.8 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 39)) (0.8.8)
Requirement already satisfied: kiwisolver==1.3.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 40)) (1.3.2)
Requirement already satisfied: logzero==1.7.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 41)) (1.7.0)
Requirement already satisfied: lxml==4.6.3 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 42)) (4.6.3)
Requirement already satisfied: lz4==3.1.3 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 43)) (3.1.3)
Requirement already satisfied: matplotlib==3.4.3 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 44)) (3.4.3)
Requirement already satisfied: msgpack==1.0.3 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 45)) (1.0.3)
Requirement already satisfied: mxnet==1.6.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 46)) (1.6.0)
Requirement already satisfied: numpy==1.16.6 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 47)) (1.16.6)
Requirement already satisfied: onepush==1.2.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 48)) (1.2.0)
Requirement already satisfied: opencv-python==4.5.3.56 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 49)) (4.5.3.56)
Requirement already satisfied: packaging==20.9 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 50)) (20.9)
Requirement already satisfied: pillow==8.3.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 51)) (8.3.2)
Requirement already satisfied: portalocker==2.3.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 52)) (2.3.2)
Requirement already satisfied: prettytable==2.2.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 53)) (2.2.1)
Requirement already satisfied: progress==1.6 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 54)) (1.6)
Requirement already satisfied: py==1.10.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 55)) (1.10.0)
Requirement already satisfied: pycparser==2.21 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 56)) (2.21)
Requirement already satisfied: pyelftools==0.27 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 57)) (0.27)
Requirement already satisfied: pygments==2.12.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 58)) (2.12.0)
Requirement already satisfied: pyparsing==2.4.7 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 59)) (2.4.7)
Requirement already satisfied: pypresence==4.2.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 60)) (4.2.1)
Requirement already satisfied: python-dateutil==2.8.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 61)) (2.8.2)
Requirement already satisfied: python-dotenv==0.19.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 62)) (0.19.0)
Requirement already satisfied: pywebio==1.6.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 63)) (1.6.2)
Requirement already satisfied: pywin32==301 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 64)) (301)
Requirement already satisfied: pyyaml==5.4.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 65)) (5.4.1)
Requirement already satisfied: pyzmq==22.3.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 66)) (22.3.0)
Requirement already satisfied: requests==2.18.4 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 67)) (2.18.4)
Requirement already satisfied: retry==0.9.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 68)) (0.9.2)
Requirement already satisfied: retrying==1.3.3 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 69)) (1.3.3)
Requirement already satisfied: rich==11.2.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 70)) (11.2.0)
Requirement already satisfied: scipy==1.4.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 71)) (1.4.1)
Requirement already satisfied: six==1.16.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 72)) (1.16.0)
Requirement already satisfied: sniffio==1.2.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 73)) (1.2.0)
Requirement already satisfied: starlette==0.14.2 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 74)) (0.14.2)
Requirement already satisfied: tornado==6.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 75)) (6.1)
Requirement already satisfied: tqdm==4.62.3 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 76)) (4.62.3)
Requirement already satisfied: typing-extensions==4.3.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 77)) (4.3.0)
Requirement already satisfied: ua-parser==0.10.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 78)) (0.10.0)
Requirement already satisfied: uiautomator2==2.16.17 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 79)) (2.16.17)
Requirement already satisfied: urllib3==1.22 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 80)) (1.22)
Requirement already satisfied: user-agents==2.2.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 81)) (2.2.0)
Requirement already satisfied: uvicorn[standard]==0.17.6 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 82)) (0.17.6)
Requirement already satisfied: watchgod==0.7 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 83)) (0.7)
Requirement already satisfied: wcwidth==0.2.5 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 84)) (0.2.5)
Requirement already satisfied: websockets==10.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 85)) (10.0)
Requirement already satisfied: whichcraft==0.6.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 86)) (0.6.1)
Requirement already satisfied: wrapt==1.13.1 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 87)) (1.13.1)
Requirement already satisfied: xmltodict==0.12.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 88)) (0.12.0)
Requirement already satisfied: zerorpc==0.6.3 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 89)) (0.6.3)
Requirement already satisfied: zipp==3.6.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 90)) (3.6.0)
Requirement already satisfied: zope.event==4.5.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 91)) (4.5.0)
Requirement already satisfied: zope.interface==5.4.0 in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 92)) (5.4.0)
Requirement already satisfied: setuptools in e:\games\azurlaneautoscript\toolkit\lib\site-packages (from gevent==21.12.0->-r requirements.txt (line 29)) (42.0.2)
[ success ]
+-------------------------------------------------------+
|                    UPDATE APP.ASAR                    |
+-------------------------------------------------------+
Old file: E:\Games\AzurLaneAutoScript\toolkit\WebApp\resources\app.asar
New version: 0.3.7
New file: E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\alas_webapp\app.asar
app.asar is already up to date
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Task adb.exe killed
taskkill /f /im nox_adb.exe >nul 2>nul
Task nox_adb.exe not found
taskkill /f /im adb_server.exe >nul 2>nul
Task adb_server.exe not found
taskkill /f /im HD-Adb.exe >nul 2>nul
Task HD-Adb.exe not found
Emulator Nox found, instances: ['127.0.0.1:62001']
Replacing D:\Nox\bin\adb.exe
E:/Games/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe is same as D:\Nox\bin\adb.exe, skip
Replacing D:\Nox\bin\nox_adb.exe
E:/Games/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe is same as D:\Nox\bin\nox_adb.exe, skip
E:/Games/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
TimeoutExpired, stdout=b'List of devices attached\r\n\r\n', stderr=None
Devices: []
E:/Games/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
connected to 127.0.0.1:62001
Devices: ['127.0.0.1:62001', '172.31.15.180:5555']
==================== UIAUTOMATOR2 INIT ====================
[I 221122 18:35:57 init:156] uiautomator2 version: 2.16.17
[I 221122 18:35:57 init:372] Install minicap, minitouch
[D 221122 18:35:57 init:59] Use cached assets: C:\Users\Lenovo\.uiautomator2\cache\minitouch-1e3ccbf4fa\minitouch
[D 221122 18:35:57 init:238] Push to /data/local/tmp/minitouch:0755
[I 221122 18:35:57 init:376] abi:x86 not supported well, skip install minicap
[D 221122 18:35:57 init:256] apk-debug package-info: {'package_name': 'com.github.uiautomator', 'version_name': '2.3.3', 'version_code': '2003003', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2022, 11, 5, 19, 42, 25), 'last_update_time': datetime.datetime(2022, 11, 5, 19, 42, 25), 'signature': 'ae17cd86'}
[D 221122 18:35:57 init:257] apk-debug-test package-info: {'package_name': 'com.github.uiautomator.test', 'version_name': '', 'version_code': '', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2022, 11, 5, 19, 42, 28), 'last_update_time': datetime.datetime(2022, 11, 5, 19, 42, 28), 'signature': 'ae17cd86'}
[I 221122 18:35:57 init:390] Already installed com.github.uiautomator apks
[D 221122 18:35:57 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 221122 18:35:57 init:296] Real version: [0, 10, 0], Expect version: [0, 10, 0]
[D 221122 18:35:57 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 221122 18:35:57 init:350] Check atx-agent version
[D 221122 18:35:57 init:359] Forward: local:tcp:13046 -> remote:tcp:7912
[D 221122 18:35:57 init:359] Forward: local:tcp:13046 -> remote:tcp:7912
[D 221122 18:35:57 init:362] atx-agent version 0.10.0
[D 221122 18:35:57 init:365] device wlan ip: 172.16.72.15
Successfully init AdbDevice(serial=127.0.0.1:62001)
[I 221122 18:35:58 init:156] uiautomator2 version: 2.16.17
[I 221122 18:35:58 init:372] Install minicap, minitouch
[D 221122 18:35:58 init:59] Use cached assets: C:\Users\Lenovo\.uiautomator2\cache\minitouch-4575799dba\minitouch
[D 221122 18:35:58 init:238] Push to /data/local/tmp/minitouch:0755
[D 221122 18:35:58 init:59] Use cached assets: C:\Users\Lenovo\.uiautomator2\cache\minicap.so-626f19b279\minicap.so
[D 221122 18:35:58 init:238] Push to /data/local/tmp/minicap.so:0755
[D 221122 18:35:58 init:59] Use cached assets: C:\Users\Lenovo\.uiautomator2\cache\minicap-c1e34d7ae0\minicap
[D 221122 18:35:58 init:238] Push to /data/local/tmp/minicap:0755
[D 221122 18:35:58 init:256] apk-debug package-info: {'package_name': 'com.github.uiautomator', 'version_name': '2.3.3', 'version_code': '2003003', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2022, 7, 17, 9, 53, 8), 'last_update_time': datetime.datetime(2022, 7, 17, 9, 53, 8), 'signature': 'ae17cd86], past signatures:['}
[D 221122 18:35:58 init:257] apk-debug-test package-info: {'package_name': 'com.github.uiautomator.test', 'version_name': '', 'version_code': '', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2022, 7, 17, 9, 53, 13), 'last_update_time': datetime.datetime(2022, 7, 17, 9, 53, 13), 'signature': 'ae17cd86], past signatures:['}
[I 221122 18:35:58 init:390] Already installed com.github.uiautomator apks
[D 221122 18:35:58 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 221122 18:35:59 init:296] Real version: [0, 10, 0], Expect version: [0, 10, 0]
[D 221122 18:35:59 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 221122 18:35:59 init:350] Check atx-agent version
[D 221122 18:35:59 init:359] Forward: local:tcp:13073 -> remote:tcp:7912
[D 221122 18:35:59 init:359] Forward: local:tcp:13073 -> remote:tcp:7912
[D 221122 18:36:00 init:359] Forward: local:tcp:13073 -> remote:tcp:7912
[D 221122 18:36:00 init:359] Forward: local:tcp:13073 -> remote:tcp:7912
[D 221122 18:36:01 init:359] Forward: local:tcp:13073 -> remote:tcp:7912
[D 221122 18:36:01 init:359] Forward: local:tcp:13073 -> remote:tcp:7912
[D 221122 18:36:02 init:359] Forward: local:tcp:13073 -> remote:tcp:7912
[D 221122 18:36:02 init:359] Forward: local:tcp:13073 -> remote:tcp:7912
[D 221122 18:36:03 init:359] Forward: local:tcp:13073 -> remote:tcp:7912
[D 221122 18:36:03 init:359] Forward: local:tcp:13073 -> remote:tcp:7912
Traceback (most recent call last):
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Games\AzurLaneAutoScript\deploy\installer.py", line 22, in <module>
    Installer().install()
  File "E:\Games\AzurLaneAutoScript\deploy\installer.py", line 16, in install
    self.adb_install()
  File "E:\Games\AzurLaneAutoScript\deploy\adb.py", line 60, in adb_install
    init.install()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 392, in install
    self.setup_atx_agent()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 351, in setup_atx_agent
    self.check_atx_agent_version()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 361, in check_atx_agent_version
    port).text.strip()
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "E:\Games\AzurLaneAutoScript\toolkit\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by suxin0301** [comment]
询问过群内的大佬，说是可能ADB的端口被占用了，但是不知道咋修改。

**Comment by suxin0301** [comment]
夜神模拟器，win11 系统

**Comment by LmeSzinc** [comment]
`172.31.15.180:5555` 这个是什么设备？
尝试断开它的连接

**Comment by suxin0301** [comment]
> `172.31.15.180:5555` 这个是什么设备？ 尝试断开它的连接

<img width="637" alt="微信截图_20221122230515" src="https://user-images.githubusercontent.com/38642397/203348610-030793e2-3344-4314-94f3-bced5818b014.png">

大佬 这个好像就是adb的程序，我尝试杀掉进程后重新运行Alas.exe 还是一样的问题

**Comment by LmeSzinc** [comment]
截图中的 IP 地址和我上面说的 IP 地址不一样。`172.31.15.85` 是你的电脑自己，`172.31.15.180` 应该是你局域网里连接的一个安卓手机/电视盒子之类的，你需要找到你身边的这个设备，操作它，关闭它的ADB连接

**Comment by suxin0301** [comment]
> 截图中的 IP 地址和我上面说的 IP 地址不一样。`172.31.15.85` 是你的电脑自己，`172.31.15.180` 应该是你局域网里连接的一个安卓手机/电视盒子之类的，你需要找到你身边的这个设备，操作它，关闭它的ADB连接

噢噢噢噢 懂了 谢谢大佬。我找找看，但是我在酒店 该不是隔壁的吧 QAQ 233

**Comment by LmeSzinc** [comment]
双击打开 console.bat 执行 `adb disconnect 172.31.15.180:5555`，断开连接，它要自己连回来我也没办法了
