### ISSUE TITLE
请问连接蓝叠的这个报错原因是什么？

### ISSUE THREAD

**Issue by ssshooter** [LmeSzinc/AzurLaneAutoScript#191]
```
2020-09-20 14:20:37.685 | INFO | +---------------------------------------------+
2020-09-20 14:20:37.685 | INFO | |                    START                    |
2020-09-20 14:20:37.685 | INFO | +---------------------------------------------+
2020-09-20 14:20:37.686 | INFO | [Server] jp
2020-09-20 14:20:39.511 | INFO | <<< DEVICE >>>
2020-09-20 14:20:39.511 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
2020-09-20 14:20:39.601 | INFO | already connected to 127.0.0.1:5555
[32m[I 200920 14:20:43 init:159][39m uiautomator2 version: 2.9.2
Traceback (most recent call last):
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 289, in _prepare_atx_agent
    "/version", retry=False).text  # retry to prevent dead loop
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 207, in request
    return super().request(method, url, **kwargs)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 107, in request
    self).request(method, url, **kwargs)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alas_jp.pyw", line 8, in <module>
    main()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 130, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\module\config\argparser_jp.py", line 516, in main
    alas.run(command=command)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\alas.py", line 24, in run
    self.device = Device(config=self.config)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\module\device\connection.py", line 27, in __init__
    self.device = self.connect(self.serial)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\module\device\connection.py", line 97, in connect
    device = u2.connect(serial)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 1789, in connect
    return connect_usb(addr)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 1830, in connect_usb
    return Device(serial)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 242, in __init__
    wlan_ip = self.wlan_ip
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 399, in wlan_ip
    ip = self.http.get("/wlan/ip").text.strip()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 211, in request
    self.__client._prepare_atx_agent()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 293, in _prepare_atx_agent
    self._setup_atx_agent()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 301, in _setup_atx_agent
    if not _initer.check_install():
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 310, in check_install
    if d.sync.stat(self.atx_agent_path).size == 0:
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 548, in stat
    assert "STAT" == c.read(4)
AssertionError
```

**Comment by LmeSzinc** [comment]
蓝叠模拟器的设置里打开 ADB 连接

**Comment by ssshooter** [comment]
感谢，已接上
