### ISSUE TITLE
Traceback (most recent call last):   File "alas_cn.pyw", line 8, in <module>

### ISSUE THREAD

**Issue by wsyxggg** [LmeSzinc/AzurLaneAutoScript#215]
Traceback (most recent call last):
  File "alas_cn.pyw", line 8, in <module>
    main()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 124, in inner2
    return payload(*args, **kwargs)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\module\config\argparser.py", line 444, in main
    args = parser.parse_args()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_parser.py", line 116, in parse_args
    return self.parser.parse_args(args, namespace)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 119, in run_gooey
    application.run(build_spec)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\application.py", line 21, in run
    app, _ = build_app(build_spec)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\application.py", line 30, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\containers\application.py", line 43, in __init__
    self.configs = self.buildConfigPanels(self)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\containers\application.py", line 223, in buildConfigPanels
    for widgets in self.buildSpec['widgets'].values()]
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\containers\application.py", line 223, in <listcomp>
    for widgets in self.buildSpec['widgets'].values()]
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\components\config.py", line 16, in __init__
    self.layoutComponent()
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\components\config.py", line 206, in layoutComponent
    self.makeGroup(panel, sizer, group, 0, wx.EXPAND)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\components\config.py", line 147, in makeGroup
    self.makeGroup(parent, hs, subgroup, 1, wx.EXPAND)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\components\config.py", line 136, in makeGroup
    widget = self.reifyWidget(parent, item)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\components\config.py", line 188, in reifyWidget
    return widgetClass(parent, item)
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\components\widgets\bases.py", line 61, in __init__
    self.setValue(self._meta['default'])
  File "D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\gui\components\widgets\dropdown.py", line 30, in setValue
    index = self._meta['choices'].index(value) + 1
ValueError: '否' is not in list

正常安装之后，选择 CN 出现了报错

**Comment by whoamikyo** [comment]
Fixed, please update.
