### ISSUE TITLE
adb.exe: protocol fault (couldn't read status): No error

### ISSUE THREAD

**Issue by Looomo** [LmeSzinc/AzurLaneAutoScript#2152]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

似乎是adb-utils包内的adb.exe报错，详细在log中，尝试过重下、用Androidstudio的adb替换，都是一样的错。手动到该目录执行adb devices命令也提示：
`adb.exe: failed to check server version: protocol fault (couldn't read status): No error`

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

-

### 相关 Logs

```Text
"D:\myProgram\AlasApp_0.3.8_cn\AzurLaneAutoScript
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
==================== SHOW DEPLOY CONFIG ====================
Repository: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/.git/
[ success ]
==================== SET GIT PROXY ====================
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify true
[ success ]
==================== SET GIT REPOSITORY ====================
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
From https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
 * branch              master     -> FETCH_HEAD
[ success ]
==================== PULL REPOSITORY BRANCH ====================
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" reset --hard origin/master
HEAD is now at 9305de5f Upd: [EN] BATTLE_PREPARATION adding "Sortie"
[ success ]
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" pull --ff-only origin master
From https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
 * branch              master     -> FETCH_HEAD
Already up to date.
[ success ]
==================== SHOW VERSION ====================
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" log --no-merges -1
error: cannot spawn less: No such file or directory
commit 9305de5f200ca2a4871bc67cc900fbbde758c26d (HEAD -> master, origin/master)
Author: LmeSzinc <37934724+LmeSzinc@users.noreply.github.com>
Date:   Thu Jan 19 03:02:31 2023 +0800

    Upd: [EN] BATTLE_PREPARATION adding "Sortie"
[ success ]
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
==================== KILL ALAS.EXE ====================
==================== KILL PYTHON.EXE ====================
+-----------------------------------------------------------+
|                    UPDATE DEPENDENCIES                    |
+-----------------------------------------------------------+
==================== CHECK PYTHON ====================
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/python.exe" --version
Python 3.7.6
[ success ]
==================== UPDATE DEPENDENCIES ====================
"D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/python.exe" -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --disable-pip-version-check
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: adbutils==0.11.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: aiofiles==0.7.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: alas-webapp==0.3.7 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 9)) (0.3.7)
Requirement already satisfied: anyio==1.3.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: apkutils2==1.0.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: asgiref==3.4.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 12)) (3.4.1)
Requirement already satisfied: async-generator==1.10 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 13)) (1.10)
Requirement already satisfied: av==10.0.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 14)) (10.0.0)
Requirement already satisfied: cached-property==1.5.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 15)) (1.5.2)
Requirement already satisfied: certifi==2021.5.30 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 16)) (2021.5.30)
Requirement already satisfied: cffi==1.15.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 17)) (1.15.0)
Requirement already satisfied: chardet==3.0.4 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 18)) (3.0.4)
Requirement already satisfied: cigam==0.0.3 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 19)) (0.0.3)
Requirement already satisfied: click==8.0.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 20)) (8.0.1)
Requirement already satisfied: cnocr==1.2.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 21)) (1.2.2)
Requirement already satisfied: colorama==0.4.5 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 22)) (0.4.5)
Requirement already satisfied: commonmark==0.9.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 23)) (0.9.1)
Requirement already satisfied: cycler==0.10.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 24)) (0.10.0)
Requirement already satisfied: decorator==5.1.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 25)) (5.1.0)
Requirement already satisfied: deprecated==1.2.13 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 26)) (1.2.13)
Requirement already satisfied: deprecation==2.1.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 27)) (2.1.0)
Requirement already satisfied: filelock==3.3.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 28)) (3.3.0)
Requirement already satisfied: future==0.18.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 29)) (0.18.2)
Requirement already satisfied: gevent==21.12.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 30)) (21.12.0)
Requirement already satisfied: gluoncv==0.6.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 31)) (0.6.0)
Requirement already satisfied: graphviz==0.8.4 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 32)) (0.8.4)
Requirement already satisfied: greenlet==1.1.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 33)) (1.1.2)
Requirement already satisfied: h11==0.12.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 34)) (0.12.0)
Requirement already satisfied: httptools==0.4.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 35)) (0.4.0)
Requirement already satisfied: idna==2.6 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 36)) (2.6)
Requirement already satisfied: imageio==2.9.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 37)) (2.9.0)
Requirement already satisfied: importlib-metadata==4.8.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 38)) (4.8.1)
Requirement already satisfied: inflection==0.5.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 39)) (0.5.1)
Requirement already satisfied: jellyfish==0.8.8 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 40)) (0.8.8)
Requirement already satisfied: kiwisolver==1.3.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 41)) (1.3.2)
Requirement already satisfied: logzero==1.7.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 42)) (1.7.0)
Requirement already satisfied: lxml==4.6.3 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 43)) (4.6.3)
Requirement already satisfied: lz4==3.1.3 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 44)) (3.1.3)
Requirement already satisfied: matplotlib==3.4.3 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 45)) (3.4.3)
Requirement already satisfied: msgpack==1.0.3 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 46)) (1.0.3)
Requirement already satisfied: mxnet==1.6.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 47)) (1.6.0)
Requirement already satisfied: numpy==1.16.6 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 48)) (1.16.6)
Requirement already satisfied: onepush==1.2.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 49)) (1.2.0)
Requirement already satisfied: opencv-python==4.5.3.56 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 50)) (4.5.3.56)
Requirement already satisfied: packaging==20.9 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 51)) (20.9)
Requirement already satisfied: pillow==8.3.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 52)) (8.3.2)
Requirement already satisfied: portalocker==2.3.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 53)) (2.3.2)
Requirement already satisfied: prettytable==2.2.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 54)) (2.2.1)
Requirement already satisfied: progress==1.6 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 55)) (1.6)
Requirement already satisfied: psutil==5.9.3 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 56)) (5.9.3)
Requirement already satisfied: py==1.10.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 57)) (1.10.0)
Requirement already satisfied: pycparser==2.21 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 58)) (2.21)
Requirement already satisfied: pydantic==1.10.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 59)) (1.10.2)
Requirement already satisfied: pyelftools==0.27 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 60)) (0.27)
Requirement already satisfied: pygments==2.12.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 61)) (2.12.0)
Requirement already satisfied: pyparsing==2.4.7 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 62)) (2.4.7)
Requirement already satisfied: pypresence==4.2.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 63)) (4.2.1)
Requirement already satisfied: python-dateutil==2.8.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 64)) (2.8.2)
Requirement already satisfied: python-dotenv==0.19.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 65)) (0.19.0)
Requirement already satisfied: pywebio==1.6.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 66)) (1.6.2)
Requirement already satisfied: pywin32==301 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 67)) (301)
Requirement already satisfied: pyyaml==5.4.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 68)) (5.4.1)
Requirement already satisfied: pyzmq==22.3.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 69)) (22.3.0)
Requirement already satisfied: requests==2.18.4 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 70)) (2.18.4)
Requirement already satisfied: retry==0.9.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 71)) (0.9.2)
Requirement already satisfied: retrying==1.3.3 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 72)) (1.3.3)
Requirement already satisfied: rich==11.2.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 73)) (11.2.0)
Requirement already satisfied: scipy==1.4.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 74)) (1.4.1)
Requirement already satisfied: six==1.16.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 75)) (1.16.0)
Requirement already satisfied: sniffio==1.2.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 76)) (1.2.0)
Requirement already satisfied: starlette==0.14.2 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 77)) (0.14.2)
Requirement already satisfied: tornado==6.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 78)) (6.1)
Requirement already satisfied: tqdm==4.62.3 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 79)) (4.62.3)
Requirement already satisfied: typing-extensions==4.3.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 80)) (4.3.0)
Requirement already satisfied: ua-parser==0.10.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 81)) (0.10.0)
Requirement already satisfied: uiautomator2==2.16.17 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 82)) (2.16.17)
Requirement already satisfied: urllib3==1.22 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 83)) (1.22)
Requirement already satisfied: user-agents==2.2.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 84)) (2.2.0)
Requirement already satisfied: uvicorn[standard]==0.17.6 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 85)) (0.17.6)
Requirement already satisfied: watchgod==0.7 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 86)) (0.7)
Requirement already satisfied: wcwidth==0.2.5 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 87)) (0.2.5)
Requirement already satisfied: websockets==10.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 88)) (10.0)
Requirement already satisfied: whichcraft==0.6.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 89)) (0.6.1)
Requirement already satisfied: wrapt==1.13.1 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 90)) (1.13.1)
Requirement already satisfied: xmltodict==0.12.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 91)) (0.12.0)
Requirement already satisfied: zerorpc==0.6.3 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 92)) (0.6.3)
Requirement already satisfied: zipp==3.6.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 93)) (3.6.0)
Requirement already satisfied: zope.event==4.5.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 94)) (4.5.0)
Requirement already satisfied: zope.interface==5.4.0 in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 95)) (5.4.0)
Requirement already satisfied: setuptools in d:\myprogram\alasapp_0.3.8_cn\azurlaneautoscript\toolkit\lib\site-packages (from gevent==21.12.0->-r requirements.txt (line 30)) (42.0.2)
[ success ]
+-------------------------------------------------------+
|                    UPDATE APP.ASAR                    |
+-------------------------------------------------------+
Old file: D:\myProgram\AlasApp_0.3.8_cn\AzurLaneAutoScript\toolkit\WebApp\resources\app.asar
New version: 0.3.7
New file: D:\myProgram\AlasApp_0.3.8_cn\AzurLaneAutoScript\toolkit\lib\site-packages\alas_webapp\app.asar
app.asar is already up to date
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Task adb.exe not found
taskkill /f /im nox_adb.exe >nul 2>nul
Task nox_adb.exe not found
taskkill /f /im adb_server.exe >nul 2>nul
Task adb_server.exe not found
taskkill /f /im HD-Adb.exe >nul 2>nul
Task HD-Adb.exe not found
D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
adb.exe: failed to check server version: protocol fault (couldn't read status): No error
Devices: []
D:/myProgram/AlasApp_0.3.8_cn/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
adb.exe: failed to check server version: protocol fault (couldn't read status): No error
Devices: []
==================== UIAUTOMATOR2 INIT ====================
Traceback (most recent call last):
  File "D:\myProgram\AlasApp_0.3.8_cn\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\myProgram\AlasApp_0.3.8_cn\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\myProgram\AlasApp_0.3.8_cn\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "D:\myProgram\AlasApp_0.3.8_cn\AzurLaneAutoScript\deploy\installer.py", line 20, in install
    self.adb_install()
  File "D:\myProgram\AlasApp_0.3.8_cn\AzurLaneAutoScript\deploy\adb.py", line 56, in adb_install
    for device in adbutils.adb.iter_device():
  File "D:\myProgram\AlasApp_0.3.8_cn\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 445, in iter_device
    c.check_okay()
  File "D:\myProgram\AlasApp_0.3.8_cn\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 171, in check_okay
    raise AdbError("Unknown data: %s" % data)
adbutils.errors.AdbError: Unknown data:
```

### 截图

![image](https://user-images.githubusercontent.com/29702226/213403029-1454f385-ec8a-414c-ba10-ab151c3a6b5a.png)
![image](https://user-images.githubusercontent.com/29702226/213403155-97b1c2d4-80e1-4617-9e17-a0e15487477e.png)

### 还有别的吗？

--

**Comment by SaiCateDoan** [comment]
检查是否有其他程序占用了adb使用的5037端口，这通常是手机助手或其他需要连接手机的软件导致的

**Comment by Looomo** [comment]
已解决，移动云盘占用5037端口

**Comment by Qizhou-ma** [comment]
排查了好久，也没有占用5037端口的进程，哭
