### ISSUE TITLE
7-2捡垃圾时寻路出现阻碍 (Too many click for a button: A2)

### ISSUE THREAD

**Issue by NeuWings** [LmeSzinc/AzurLaneAutoScript#222]
活动空窗期7-2捡垃圾时遇到的问题,对比FAQ后进行了部分复现.
运行环境雷电模拟器4.0.29.

同为B3格子寻路A2且B2有敌方单位时出现.
[1602608677150.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/5375591/1602608677150.zip)
[1602616342697.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/5375592/1602616342697.zip)
两个压缩包都删除了部分图像,内容均为重复的B3格待机.(上传限制原因)

**Screenshots**

![2020-10-14_01-04-35-329094](https://user-images.githubusercontent.com/26756868/95943487-8e0aab80-0e18-11eb-9db7-440583417dc1.png)

**Log**

<details>
  <summary>三战时切换至B3的Log</summary>

2020-10-14 03:07:39.061 | INFO | -------------------- BATTLE_3 --------------------
2020-10-14 03:07:39.061 | INFO | Using function: battle_3
2020-10-14 03:07:39.061 | INFO | <<< CLEAR ALL MYSTERY >>>
2020-10-14 03:07:39.061 | INFO | nearby=False, ignore=[A2], sort=('cost',)
2020-10-14 03:07:39.061 | INFO | Grids: [D2]
2020-10-14 03:07:39.061 | INFO | Clear mystery: D2
2020-10-14 03:07:39.061 | INFO | [Fleet_1: G2] Fleet_2: A3
2020-10-14 03:07:39.061 | INFO | In sight: D2
2020-10-14 03:07:39.062 | INFO | Focus to: D2
2020-10-14 03:07:39.062 | INFO | Map swipe: (0, 0)
2020-10-14 03:07:39.465 | INFO | Global D2 (camera=D2) -> Local D2 (center=D2)
2020-10-14 03:07:39.466 | INFO | Click ( 618,  354) @ D2
2020-10-14 03:07:41.479 | INFO | Arrive D2
2020-10-14 03:07:41.824 | INFO | [Mystery] Get ammo
2020-10-14 03:07:46.692 | INFO | Arrive D2 confirm. Result: mystery. Expected: mystery
2020-10-14 03:07:46.693 | INFO |      A    B    C    D    E    F    G    H
2020-10-14 03:07:46.693 | INFO | 1    6 9999    2    1    2    3    4    5
2020-10-14 03:07:46.694 | INFO | 2    5 9999 9999    0    1    2    3    4
2020-10-14 03:07:46.694 | INFO | 3    4    3    2    1    2    3    4    5
2020-10-14 03:07:46.694 | INFO | 4    5    4    3    2    3    4 9999 9999
2020-10-14 03:07:46.694 | INFO | 5    6    5    4    3    4    5 9999 9999
2020-10-14 03:07:46.694 | INFO | Switch over
2020-10-14 03:07:46.694 | INFO | Click (1053,  691) @ SWITCH_OVER
2020-10-14 03:07:48.310 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:07:48.322 | INFO | 0.061s  _   edge_lines: 5 hori, 1 vert
2020-10-14 03:07:48.322 | INFO | Edges: /_    homo_loca: ( 25,  55)
2020-10-14 03:07:48.325 | INFO |            center_loca: (1, 2)
2020-10-14 03:07:48.325 | INFO |                 Camera: A3
2020-10-14 03:07:48.326 | INFO |      A    B    C    D    E    F    G    H
2020-10-14 03:07:48.327 | INFO | 1    2 9999    6    5    6    7    8    9
2020-10-14 03:07:48.327 | INFO | 2    1 9999 9999    4    5    6    7    8
2020-10-14 03:07:48.327 | INFO | 3    0    1    2    3    4    5    6    7
2020-10-14 03:07:48.327 | INFO | 4    1    2    3    4    5    6 9999 9999
2020-10-14 03:07:48.327 | INFO | 5    2    3    4    5    6    7 9999 9999
2020-10-14 03:07:48.327 | INFO | Fleet_1: D2 [Fleet_2: A3]
2020-10-14 03:07:48.328 | INFO | [HP]  98%  98%  98%  98%  98% ____
2020-10-14 03:07:48.328 | INFO | Clear mystery: A2
2020-10-14 03:07:48.328 | INFO | Fleet_1: D2 [Fleet_2: A3]
2020-10-14 03:07:48.329 | INFO | In sight: A2
2020-10-14 03:07:48.329 | INFO | Focus to: A2
2020-10-14 03:07:48.329 | INFO | Map swipe: (0, -1)
2020-10-14 03:07:48.329 | INFO | Swipe ( 579,  384) -> ( 581,  524), 0.148
2020-10-14 03:07:49.260 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:07:49.268 | INFO | 0.060s  _   edge_lines: 2 hori, 1 vert
2020-10-14 03:07:49.268 | INFO | Edges: /     homo_loca: ( 26,  56)
2020-10-14 03:07:49.271 | INFO |            center_loca: (1, 1)
2020-10-14 03:07:49.272 | INFO |                 Camera: A2
2020-10-14 03:07:49.272 | INFO | Global A2 (camera=A2) -> Local B2 (center=B2)
2020-10-14 03:07:49.273 | INFO | Click ( 625,  369) @ B2
2020-10-14 03:08:09.602 | WARNING | Walk timeout. Retrying.
2020-10-14 03:08:09.602 | INFO | Ensure edge in sight.
2020-10-14 03:08:10.017 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:08:10.027 | INFO | 0.059s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:08:10.027 | INFO | Edges: /     homo_loca: ( 26,  55)
2020-10-14 03:08:10.030 | INFO |            center_loca: (1, 1)
2020-10-14 03:08:10.030 | INFO |       camera_corrected: A2 -> B2
2020-10-14 03:08:10.030 | INFO |                 Camera: B2
2020-10-14 03:08:10.030 | INFO | In sight: A2
2020-10-14 03:08:10.030 | INFO | Focus to: B2
2020-10-14 03:08:10.031 | INFO | Map swipe: (0, 0)
2020-10-14 03:08:10.391 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:08:10.393 | INFO | Click ( 509,  357) @ A2
2020-10-14 03:08:30.621 | WARNING | Walk timeout. Retrying.
2020-10-14 03:08:30.621 | INFO | Ensure edge in sight.
2020-10-14 03:08:31.012 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:08:31.023 | INFO | 0.057s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:08:31.023 | INFO | Edges: /     homo_loca: ( 26,  56)
2020-10-14 03:08:31.025 | INFO |            center_loca: (1, 1)
2020-10-14 03:08:31.026 | INFO |                 Camera: B2
2020-10-14 03:08:31.026 | INFO | In sight: A2
2020-10-14 03:08:31.026 | INFO | Focus to: B2
2020-10-14 03:08:31.026 | INFO | Map swipe: (0, 0)
2020-10-14 03:08:31.375 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:08:31.376 | INFO | Click ( 492,  348) @ A2
2020-10-14 03:08:51.581 | WARNING | Walk timeout. Retrying.
2020-10-14 03:08:51.581 | INFO | Ensure edge in sight.
2020-10-14 03:08:51.956 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:08:51.964 | INFO | 0.056s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:08:51.964 | INFO | Edges: /     homo_loca: ( 26,  56)
2020-10-14 03:08:51.967 | INFO |            center_loca: (1, 1)
2020-10-14 03:08:51.967 | INFO |                 Camera: B2
2020-10-14 03:08:51.967 | INFO | In sight: A2
2020-10-14 03:08:51.967 | INFO | Focus to: B2
2020-10-14 03:08:51.967 | INFO | Map swipe: (0, 0)
2020-10-14 03:08:52.335 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:08:52.336 | INFO | Click ( 511,  359) @ A2
2020-10-14 03:09:12.672 | WARNING | Walk timeout. Retrying.
2020-10-14 03:09:12.672 | INFO | Ensure edge in sight.
2020-10-14 03:09:13.073 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:09:13.083 | INFO | 0.056s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:09:13.083 | INFO | Edges: /     homo_loca: ( 26,  56)
2020-10-14 03:09:13.086 | INFO |            center_loca: (1, 1)
2020-10-14 03:09:13.086 | INFO |                 Camera: B2
2020-10-14 03:09:13.086 | INFO | In sight: A2
2020-10-14 03:09:13.086 | INFO | Focus to: B2
2020-10-14 03:09:13.086 | INFO | Map swipe: (0, 0)
2020-10-14 03:09:13.424 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:09:13.426 | INFO | Click ( 518,  370) @ A2
2020-10-14 03:09:33.838 | WARNING | Walk timeout. Retrying.
2020-10-14 03:09:33.839 | INFO | Ensure edge in sight.
2020-10-14 03:09:34.240 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:09:34.248 | INFO | 0.057s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:09:34.249 | INFO | Edges: /     homo_loca: ( 26,  56)
2020-10-14 03:09:34.251 | INFO |            center_loca: (1, 1)
2020-10-14 03:09:34.251 | INFO |                 Camera: B2
2020-10-14 03:09:34.251 | INFO | In sight: A2
2020-10-14 03:09:34.251 | INFO | Focus to: B2
2020-10-14 03:09:34.251 | INFO | Map swipe: (0, 0)
2020-10-14 03:09:34.541 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:09:34.542 | INFO | Click ( 525,  359) @ A2
2020-10-14 03:09:54.641 | WARNING | Walk timeout. Retrying.
2020-10-14 03:09:54.641 | INFO | Ensure edge in sight.
2020-10-14 03:09:55.007 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:09:55.017 | INFO | 0.058s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:09:55.017 | INFO | Edges: /     homo_loca: ( 26,  55)
2020-10-14 03:09:55.020 | INFO |            center_loca: (1, 1)
2020-10-14 03:09:55.020 | INFO |                 Camera: B2
2020-10-14 03:09:55.020 | INFO | In sight: A2
2020-10-14 03:09:55.020 | INFO | Focus to: B2
2020-10-14 03:09:55.020 | INFO | Map swipe: (0, 0)
2020-10-14 03:09:55.391 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:09:55.392 | INFO | Click ( 507,  374) @ A2
2020-10-14 03:10:15.754 | WARNING | Walk timeout. Retrying.
2020-10-14 03:10:15.754 | INFO | Ensure edge in sight.
2020-10-14 03:10:16.154 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:10:16.164 | INFO | 0.058s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:10:16.164 | INFO | Edges: /     homo_loca: ( 26,  55)
2020-10-14 03:10:16.166 | INFO |            center_loca: (1, 1)
2020-10-14 03:10:16.166 | INFO |                 Camera: B2
2020-10-14 03:10:16.166 | INFO | In sight: A2
2020-10-14 03:10:16.166 | INFO | Focus to: B2
2020-10-14 03:10:16.166 | INFO | Map swipe: (0, 0)
2020-10-14 03:10:16.508 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:10:16.510 | INFO | Click ( 532,  350) @ A2
2020-10-14 03:10:36.666 | WARNING | Walk timeout. Retrying.
2020-10-14 03:10:36.666 | INFO | Ensure edge in sight.
2020-10-14 03:10:37.075 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:10:37.084 | INFO | 0.056s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:10:37.084 | INFO | Edges: /     homo_loca: ( 26,  56)
2020-10-14 03:10:37.088 | INFO |            center_loca: (1, 1)
2020-10-14 03:10:37.088 | INFO |                 Camera: B2
2020-10-14 03:10:37.088 | INFO | In sight: A2
2020-10-14 03:10:37.088 | INFO | Focus to: B2
2020-10-14 03:10:37.088 | INFO | Map swipe: (0, 0)
2020-10-14 03:10:37.442 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:10:37.442 | INFO | Click ( 491,  352) @ A2
2020-10-14 03:10:57.845 | WARNING | Walk timeout. Retrying.
2020-10-14 03:10:57.845 | INFO | Ensure edge in sight.
2020-10-14 03:10:58.227 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:10:58.237 | INFO | 0.059s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:10:58.237 | INFO | Edges: /     homo_loca: ( 26,  55)
2020-10-14 03:10:58.240 | INFO |            center_loca: (1, 1)
2020-10-14 03:10:58.240 | INFO |                 Camera: B2
2020-10-14 03:10:58.240 | INFO | In sight: A2
2020-10-14 03:10:58.240 | INFO | Focus to: B2
2020-10-14 03:10:58.240 | INFO | Map swipe: (0, 0)
2020-10-14 03:10:58.566 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:10:58.568 | INFO | Click ( 499,  353) @ A2
2020-10-14 03:11:18.783 | WARNING | Walk timeout. Retrying.
2020-10-14 03:11:18.783 | INFO | Ensure edge in sight.
2020-10-14 03:11:19.160 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:11:19.171 | INFO | 0.057s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:11:19.171 | INFO | Edges: /     homo_loca: ( 26,  55)
2020-10-14 03:11:19.172 | INFO |            center_loca: (1, 1)
2020-10-14 03:11:19.173 | INFO |                 Camera: B2
2020-10-14 03:11:19.173 | INFO | In sight: A2
2020-10-14 03:11:19.173 | INFO | Focus to: B2
2020-10-14 03:11:19.173 | INFO | Map swipe: (0, 0)
2020-10-14 03:11:19.533 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:11:19.534 | INFO | Click ( 495,  364) @ A2
2020-10-14 03:11:39.632 | WARNING | Walk timeout. Retrying.
2020-10-14 03:11:39.632 | INFO | Ensure edge in sight.
2020-10-14 03:11:40.023 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:11:40.033 | INFO | 0.058s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:11:40.033 | INFO | Edges: /     homo_loca: ( 26,  56)
2020-10-14 03:11:40.035 | INFO |            center_loca: (1, 1)
2020-10-14 03:11:40.036 | INFO |                 Camera: B2
2020-10-14 03:11:40.036 | INFO | In sight: A2
2020-10-14 03:11:40.036 | INFO | Focus to: B2
2020-10-14 03:11:40.036 | INFO | Map swipe: (0, 0)
2020-10-14 03:11:40.379 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:11:40.381 | INFO | Click ( 505,  366) @ A2
2020-10-14 03:12:00.732 | WARNING | Walk timeout. Retrying.
2020-10-14 03:12:00.733 | INFO | Ensure edge in sight.
2020-10-14 03:12:01.134 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:12:01.145 | INFO | 0.060s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:12:01.145 | INFO | Edges: /     homo_loca: ( 26,  56)
2020-10-14 03:12:01.147 | INFO |            center_loca: (1, 1)
2020-10-14 03:12:01.148 | INFO |                 Camera: B2
2020-10-14 03:12:01.148 | INFO | In sight: A2
2020-10-14 03:12:01.148 | INFO | Focus to: B2
2020-10-14 03:12:01.148 | INFO | Map swipe: (0, 0)
2020-10-14 03:12:01.479 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:12:01.480 | INFO | Click ( 520,  360) @ A2
2020-10-14 03:12:21.789 | WARNING | Walk timeout. Retrying.
2020-10-14 03:12:21.789 | INFO | Ensure edge in sight.
2020-10-14 03:12:22.211 | INFO |            tile_center: 0.920 (good match)
2020-10-14 03:12:22.222 | INFO | 0.057s  _   edge_lines: 1 hori, 1 vert
2020-10-14 03:12:22.222 | INFO | Edges: /     homo_loca: ( 26,  56)
2020-10-14 03:12:22.225 | INFO |            center_loca: (1, 1)
2020-10-14 03:12:22.225 | INFO |                 Camera: B2
2020-10-14 03:12:22.225 | INFO | In sight: A2
2020-10-14 03:12:22.225 | INFO | Focus to: B2
2020-10-14 03:12:22.225 | INFO | Map swipe: (0, 0)
2020-10-14 03:12:22.542 | INFO | Global A2 (camera=B2) -> Local A2 (center=B2)
2020-10-14 03:12:22.543 | WARNING | Too many click for a button: A2
2020-10-14 03:12:22.543 | INFO | History click: ['SWITCH_OVER', 'MAP_SWIPE_0_-1', 'B2', 'A2', 'A2', 'A2', 'A2', 'A2', 'A2', 'A2', 'A2', 'A2', 'A2', 'A2', 'A2']
2020-10-14 03:12:22.544 | ERROR | Too many click for a button: A2
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 27, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 170, in c72_mystery_farming
    az.run('campaign_7_2_mystery_farming')
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 185, in run
    self.campaign.run()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 121, in run
    self.execute_a_battle()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 92, in execute_a_battle
    result = self.battle_function()
  File "C:\fakepath\AzurLaneAutoScript\module\base\decorator.py", line 62, in wrapper
    return record['func'](self, *args, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 82, in battle_function
    result = func()
  File "C:\fakepath\AzurLaneAutoScript\campaign\campaign_main\campaign_7_2_mystery_farming.py", line 66, in battle_3
    self.fleet_2.clear_chosen_mystery(A2)
  File "C:\fakepath\AzurLaneAutoScript\module\map\map.py", line 32, in clear_chosen_mystery
    self.goto(grid, expected='mystery')
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 334, in goto
    self._goto(location, expected=expected)
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 196, in _goto
    self.device.click(grid)
  File "C:\fakepath\AzurLaneAutoScript\module\device\device.py", line 61, in click
    return super().click(button, record_check=record_check)
  File "C:\fakepath\AzurLaneAutoScript\module\device\control.py", line 53, in click
    self.click_record_check(button)
  File "C:\fakepath\AzurLaneAutoScript\module\device\control.py", line 39, in click_record_check
    raise GameTooManyClickError(f'Too many click for a button: {button}')
module.exception.GameTooManyClickError: Too many click for a button: A2
2020-10-14 03:12:22.697 | INFO | Saving error: ./log/error/1602616342697

</details>

**Comment by LmeSzinc** [comment]
log中显示到达了 A3, 而实际上是在 B3
模拟器卡顿或者游戏卡顿会导致滑动操作无效, 或者滑到一半停下. 这个是老问题了, 还没有想好怎么解决.

**Comment by NeuWings** [comment]
了解,后来闲了看了看记录大概体会到原因了,还是辛苦啦.jpg
