### ISSUE TITLE
alas无法打开adb read timeout

### ISSUE THREAD

**Issue by Snowflakestest** [LmeSzinc/AzurLaneAutoScript#2321]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

alas无法打开

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
"D:\Program Files (x86)\AzurLaneAutoScript
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
==================== SHOW DEPLOY CONFIG ====================
Repository: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
PypiMirror: https://mirrors.aliyun.com/pypi/simple/
Language: zh-CN
Theme: dark
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in D:/Program Files (x86)/AzurLaneAutoScript/.git/
[ success ]
==================== SET GIT PROXY ====================
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify true
[ success ]
==================== SET GIT REPOSITORY ====================
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
From https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
 * branch              master     -> FETCH_HEAD
[ success ]
==================== PULL REPOSITORY BRANCH ====================
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" reset --hard origin/master
HEAD is now at d7c7a29c Fix: FleetOrder in GemsFarming is default to fleet1_mob_fleet2_boss
[ success ]
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" pull --ff-only origin master
From https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
 * branch              master     -> FETCH_HEAD
Already up to date.
[ success ]
==================== SHOW VERSION ====================
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" --no-pager log --no-merges -1
commit d7c7a29cc75b5361a76b0bacf7eda4806e8d84b3 (HEAD -> master, origin/master)
Author: LmeSzinc <37934724+LmeSzinc@users.noreply.github.com>
Date:   Thu Mar 2 22:38:39 2023 +0800

    Fix: FleetOrder in GemsFarming is default to fleet1_mob_fleet2_boss
[ success ]
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
==================== KILL ALAS.EXE ====================
==================== KILL PYTHON.EXE ====================
+-----------------------------------------------------------+
|                    UPDATE DEPENDENCIES                    |
+-----------------------------------------------------------+
==================== CHECK PYTHON ====================
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/python.exe" --version
Python 3.7.6
[ success ]
==================== UPDATE DEPENDENCIES ====================
"D:/Program Files (x86)/AzurLaneAutoScript/toolkit/python.exe" -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --disable-pip-version-check
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: adbutils==0.11.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: aiofiles==0.7.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: alas-webapp==0.3.7 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 9)) (0.3.7)
Requirement already satisfied: anyio==1.3.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: apkutils2==1.0.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: asgiref==3.4.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 12)) (3.4.1)
Requirement already satisfied: async-generator==1.10 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 13)) (1.10)
Requirement already satisfied: av==10.0.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 14)) (10.0.0)
Requirement already satisfied: cached-property==1.5.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 15)) (1.5.2)
Requirement already satisfied: certifi==2021.5.30 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 16)) (2021.5.30)
Requirement already satisfied: cffi==1.15.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 17)) (1.15.0)
Requirement already satisfied: chardet==3.0.4 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 18)) (3.0.4)
Requirement already satisfied: cigam==0.0.3 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 19)) (0.0.3)
Requirement already satisfied: click==8.0.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 20)) (8.0.1)
Requirement already satisfied: cnocr==1.2.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 21)) (1.2.2)
Requirement already satisfied: colorama==0.4.5 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 22)) (0.4.5)
Requirement already satisfied: commonmark==0.9.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 23)) (0.9.1)
Requirement already satisfied: cycler==0.10.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 24)) (0.10.0)
Requirement already satisfied: decorator==5.1.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 25)) (5.1.0)
Requirement already satisfied: deprecated==1.2.13 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 26)) (1.2.13)
Requirement already satisfied: deprecation==2.1.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 27)) (2.1.0)
Requirement already satisfied: filelock==3.3.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 28)) (3.3.0)
Requirement already satisfied: future==0.18.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 29)) (0.18.2)
Requirement already satisfied: gevent==21.12.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 30)) (21.12.0)
Requirement already satisfied: gluoncv==0.6.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 31)) (0.6.0)
Requirement already satisfied: graphviz==0.8.4 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 32)) (0.8.4)
Requirement already satisfied: greenlet==1.1.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 33)) (1.1.2)
Requirement already satisfied: h11==0.12.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 34)) (0.12.0)
Requirement already satisfied: httptools==0.4.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 35)) (0.4.0)
Requirement already satisfied: idna==2.6 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 36)) (2.6)
Requirement already satisfied: imageio==2.9.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 37)) (2.9.0)
Requirement already satisfied: importlib-metadata==4.8.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 38)) (4.8.1)
Requirement already satisfied: inflection==0.5.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 39)) (0.5.1)
Requirement already satisfied: jellyfish==0.8.8 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 40)) (0.8.8)
Requirement already satisfied: kiwisolver==1.3.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 41)) (1.3.2)
Requirement already satisfied: logzero==1.7.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 42)) (1.7.0)
Requirement already satisfied: lxml==4.6.3 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 43)) (4.6.3)
Requirement already satisfied: lz4==3.1.3 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 44)) (3.1.3)
Requirement already satisfied: matplotlib==3.4.3 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 45)) (3.4.3)
Requirement already satisfied: msgpack==1.0.3 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 46)) (1.0.3)
Requirement already satisfied: mxnet==1.6.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 47)) (1.6.0)
Requirement already satisfied: numpy==1.16.6 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 48)) (1.16.6)
Requirement already satisfied: onepush==1.2.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 49)) (1.2.0)
Requirement already satisfied: opencv-python==4.5.3.56 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 50)) (4.5.3.56)
Requirement already satisfied: packaging==20.9 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 51)) (20.9)
Requirement already satisfied: pillow==8.3.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 52)) (8.3.2)
Requirement already satisfied: portalocker==2.3.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 53)) (2.3.2)
Requirement already satisfied: prettytable==2.2.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 54)) (2.2.1)
Requirement already satisfied: progress==1.6 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 55)) (1.6)
Requirement already satisfied: psutil==5.9.3 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 56)) (5.9.3)
Requirement already satisfied: py==1.10.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 57)) (1.10.0)
Requirement already satisfied: pycparser==2.21 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 58)) (2.21)
Requirement already satisfied: pydantic==1.10.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 59)) (1.10.2)
Requirement already satisfied: pyelftools==0.27 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 60)) (0.27)
Requirement already satisfied: pygments==2.12.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 61)) (2.12.0)
Requirement already satisfied: pyparsing==2.4.7 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 62)) (2.4.7)
Requirement already satisfied: pypresence==4.2.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 63)) (4.2.1)
Requirement already satisfied: python-dateutil==2.8.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 64)) (2.8.2)
Requirement already satisfied: python-dotenv==0.19.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 65)) (0.19.0)
Requirement already satisfied: pywebio==1.6.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 66)) (1.6.2)
Requirement already satisfied: pywin32==301 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 67)) (301)
Requirement already satisfied: pyyaml==5.4.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 68)) (5.4.1)
Requirement already satisfied: pyzmq==22.3.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 69)) (22.3.0)
Requirement already satisfied: requests==2.18.4 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 70)) (2.18.4)
Requirement already satisfied: retry==0.9.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 71)) (0.9.2)
Requirement already satisfied: retrying==1.3.3 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 72)) (1.3.3)
Requirement already satisfied: rich==11.2.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 73)) (11.2.0)
Requirement already satisfied: scipy==1.4.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 74)) (1.4.1)
Requirement already satisfied: six==1.16.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 75)) (1.16.0)
Requirement already satisfied: sniffio==1.2.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 76)) (1.2.0)
Requirement already satisfied: starlette==0.14.2 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 77)) (0.14.2)
Requirement already satisfied: tornado==6.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 78)) (6.1)
Requirement already satisfied: tqdm==4.62.3 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 79)) (4.62.3)
Requirement already satisfied: typing-extensions==4.3.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 80)) (4.3.0)
Requirement already satisfied: ua-parser==0.10.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 81)) (0.10.0)
Requirement already satisfied: uiautomator2==2.16.17 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 82)) (2.16.17)
Requirement already satisfied: urllib3==1.22 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 83)) (1.22)
Requirement already satisfied: user-agents==2.2.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 84)) (2.2.0)
Requirement already satisfied: uvicorn[standard]==0.17.6 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 85)) (0.17.6)
Requirement already satisfied: watchgod==0.7 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 86)) (0.7)
Requirement already satisfied: wcwidth==0.2.5 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 87)) (0.2.5)
Requirement already satisfied: websockets==10.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 88)) (10.0)
Requirement already satisfied: whichcraft==0.6.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 89)) (0.6.1)
Requirement already satisfied: wrapt==1.13.1 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 90)) (1.13.1)
Requirement already satisfied: xmltodict==0.12.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 91)) (0.12.0)
Requirement already satisfied: zerorpc==0.6.3 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 92)) (0.6.3)
Requirement already satisfied: zipp==3.6.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 93)) (3.6.0)
Requirement already satisfied: zope.event==4.5.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 94)) (4.5.0)
Requirement already satisfied: zope.interface==5.4.0 in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 95)) (5.4.0)
Requirement already satisfied: setuptools in d:\program files (x86)\azurlaneautoscript\toolkit\lib\site-packages (from gevent==21.12.0->-r requirements.txt (line 30)) (42.0.2)
[ success ]
+-------------------------------------------------------+
|                    UPDATE APP.ASAR                    |
+-------------------------------------------------------+
Old file: D:\Program Files (x86)\AzurLaneAutoScript\toolkit\WebApp\resources\app.asar
New version: 0.3.7
New file: D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\site-packages\alas_webapp\app.asar
app.asar is already up to date
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Task adb.exe not found
taskkill /f /im nox_adb.exe >nul 2>nul
Task nox_adb.exe not found
taskkill /f /im adb_server.exe >nul 2>nul
Task adb_server.exe not found
taskkill /f /im HD-Adb.exe >nul 2>nul
Task HD-Adb.exe not found
Replacing D:\Program Files (x86)\adb.exe
D:\Program Files (x86)\adb.exe not exists, skip
Replacing D:\Program Files (x86)\LDPlayer9\adb.exe
D:\Program Files (x86)\LDPlayer9\adb.exe not exists, skip
D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
Devices: ['FRU6R20320002307']
D:/Program Files (x86)/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
Devices: ['FRU6R20320002307']
==================== UIAUTOMATOR2 INIT ====================
[I 230303 11:57:09 init:156] uiautomator2 version: 2.16.17
[I 230303 11:57:09 init:372] Install minicap, minitouch
[D 230303 11:57:09 init:59] Use cached assets: C:\Users\win11\.uiautomator2\cache\minitouch-f7a806902f\minitouch
[D 230303 11:57:09 init:238] Push to /data/local/tmp/minitouch:0755
[I 230303 11:57:09 init:378] Android R (sdk:30) has no minicap resource
[D 230303 11:57:10 init:256] apk-debug package-info: None
[D 230303 11:57:10 init:257] apk-debug-test package-info: None
[I 230303 11:57:10 init:387] Install com.github.uiautomator, com.github.uiautomator.test 2.3.3
[D 230303 11:57:10 init:167] Shell: ('pm', 'uninstall', 'com.github.uiautomator')
[D 230303 11:57:10 init:167] Shell: ('pm', 'uninstall', 'com.github.uiautomator.test')
[D 230303 11:57:10 init:59] Use cached assets: C:\Users\win11\.uiautomator2\cache\app-uiautomator.apk-d3f17174fb\app-uiautomator.apk
[D 230303 11:57:10 init:238] Push to /data/local/tmp/app-uiautomator.apk:0644
[D 230303 11:57:10 init:167] Shell: ('pm', 'install', '-r', '-t', '/data/local/tmp/app-uiautomator.apk')
Traceback (most recent call last):
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 123, in read
    return self._read_fully(n)
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 131, in _read_fully
    chunk = self.conn.recv(t)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "D:\Program Files (x86)\AzurLaneAutoScript\deploy\installer.py", line 20, in install
    self.adb_install()
  File "D:\Program Files (x86)\AzurLaneAutoScript\deploy\adb.py", line 65, in adb_install
    initer.install()
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 388, in install
    self._install_uiautomator_apks()
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 330, in _install_uiautomator_apks
    self.shell("pm", "install", "-r", "-t", path)
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 168, in shell
    return self._device.shell(args, timeout=60)
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 578, in shell
    ret = self._client.shell(self._serial, cmdargs, stream=stream, timeout=timeout)
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 322, in shell
    return c.read_until_close()
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 159, in read_until_close
    chunk = self.read(4096)
  File "D:\Program Files (x86)\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 125, in read
    raise AdbTimeout("adb read timeout")
adbutils.errors.AdbTimeout: adb read timeout
```

**Comment by LmeSzinc** [comment]
把这个设备从电脑上拔了
```
FRU6R20320002307
```
