### ISSUE TITLE
Alas Deploy Tool v4 安装报错

### ISSUE THREAD

**Issue by NKDuke** [LmeSzinc/AzurLaneAutoScript#238]
'|SystemType' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'|Check' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'|Cloning' 不是内部或外部命令，也不是可运行的程序
'|initializing...Region' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Initialized empty Git repository in D:/AzurLaneAuto/AzurLaneAutoScript/.git/
'|adding' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'|adding' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'|fetching' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
**安装Python依赖时报错**

   ERROR: Command errored out with exit status 1:
     command: 'D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-30k1bxf5\\uiautomator2\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-30k1bxf5\\uiautomator2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-pip-egg-info-jb7hy572'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-30k1bxf5\uiautomator2\
    Complete output (33 lines):
    WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
    ERROR: Could not find a version that satisfies the requirement pbr (from versions: none)
    ERROR: No matching distribution found for pbr
    Traceback (most recent call last):
      File "D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\lib\subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['D:\\AzurLaneAuto\\AzurLaneAutoScript\\toolkit\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmprteyrmii', '--quiet', 'pbr']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-30k1bxf5\uiautomator2\setup.py", line 8, in <module>
        setuptools.setup(setup_requires=['pbr'], python_requires='>=3.6', pbr=True)
      File "D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\lib\site-packages\setuptools\dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\lib\site-packages\setuptools\dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "D:\AzurLaneAuto\AzurLaneAutoScript\toolkit\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['D:\\AzurLaneAuto\\AzurLaneAutoScript\\toolkit\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmprteyrmii', '--quiet', 'pbr']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by whoamikyo** [comment]
Fixed, install the new version please.

https://github.com/LmeSzinc/AzurLaneAutoScript/releases/tag/v2020.11.07v2
