### ISSUE TITLE
安装报错 ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by Imtinmin** [LmeSzinc/AzurLaneAutoScript#244]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log**
```
Collecting pygtrie
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2e/67/20784790ae704f360277d780c64ca5ea65c785504eebd869737056db5c6c/pygtrie-2.4.0.tar.gz (35 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\AzurLaneAutoScript\toolkit\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-ah95zc_r\\pygtrie\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-ah95zc_r\\pygtrie\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-pip-egg-info-5kfzplyv'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-ah95zc_r\pygtrie\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-ah95zc_r\pygtrie\setup.py", line 5, in <module>
        import packaging.version
    ModuleNotFoundError: No module named 'packaging'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Zhang-RQ** [comment]
可以在console.bat中先安装一下packaging再重新安装一下依赖

**Comment by Imtinmin** [comment]
> 可以在console.bat中先安装一下packaging再重新安装一下依赖

好了，在`requests.txt`加就行了

**Comment by noname94** [comment]
It is the issue of pygtrie package and has been fixed in version 2.4.1 which released on Nov. 11, 2020.
[https://pypi.org/project/pygtrie/](url)
这个是pygtrie包的问题，昨天发布的2.4.1版已经修复了。

**Comment by Imtinmin** [comment]
顺便问一下就是可以打作战档案的图吗

**Comment by LmeSzinc** [comment]
> 顺便问一下就是可以打作战档案的图吗

可以, 不过国服还在适配中, 要等几天.

**Comment by Imtinmin** [comment]
> > 顺便问一下就是可以打作战档案的图吗
> 
> 可以, 不过国服还在适配中, 要等几天.

期待期待
