### ISSUE TITLE
11-3无法加载

### ISSUE THREAD

**Issue by username114514** [LmeSzinc/AzurLaneAutoScript#245]
**Describe the bug**
11/20更新完后就无法加载了

**Log**
| ERROR | module 'campaign.campaign_main.campaign_11_3' has no attribute 'Campaign'
Traceback (most recent call last):
  File "D:\Tools\AzurLaneAutoScript\alas.py", line 27, in run
    self.__getattribute__(command.lower())()
  File "D:\Tools\AzurLaneAutoScript\alas.py", line 122, in main
    az.run(self.config.CAMPAIGN_NAME)
  File "D:\Tools\AzurLaneAutoScript\module\campaign\run.py", line 145, in run
    self.load_campaign(name, folder=folder)
  File "D:\Tools\AzurLaneAutoScript\module\campaign\run.py", line 60, in load_campaign
    self.campaign = self.module.Campaign(config=config, device=device)
AttributeError: module 'campaign.campaign_main.campaign_11_3' has no attribute 'Campaign'

**Comment by whoamikyo** [comment]
fixed https://github.com/LmeSzinc/AzurLaneAutoScript/commit/bd09bdbe439749d82d79ce42bc91dfe0ec0bed0b
