### ISSUE TITLE
ERROR | 'NoneType' object has no attribute 'load' Traceback (most recent call last):

### ISSUE THREAD

**Issue by 1095141917** [LmeSzinc/AzurLaneAutoScript#253]
遇到错误无法运行，删除重新下还有有错误，这是我哪里设置不对
![GIT ~7%~~PZ{A1)H@ CP_40](https://user-images.githubusercontent.com/40393458/100866311-620ebc80-3490-11eb-8b3a-2d15492ed8f7.png)

2020-12-02 19:01:17.735 | INFO | +---------------------------------------------+
2020-12-02 19:01:17.736 | INFO | |                    START                    |
2020-12-02 19:01:17.736 | INFO | +---------------------------------------------+
2020-12-02 19:01:17.740 | INFO | [Server] cn
2020-12-02 19:01:20.047 | INFO | [Command] C72_mystery_farming
2020-12-02 19:01:20.048 | INFO | <<< DEVICE >>>
2020-12-02 19:01:20.050 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
2020-12-02 19:01:20.124 | INFO | Active code page: 65001

already connected to 127.0.0.1:7555
2020-12-02 19:01:24.546 | INFO | [Emotion fleet_1] 119
2020-12-02 19:01:24.546 | INFO | [Emotion fleet_2] 119
2020-12-02 19:01:24.546 | INFO | [Emotion fleet_3] 119
2020-12-02 19:01:24.547 | INFO | [Emotion_bug] 0/72
2020-12-02 19:01:24.547 | INFO | ==================== CAMPAIGN_7_2_MYSTERY_FARMING ====================
2020-12-02 19:01:24.547 | INFO | Count: [0]
2020-12-02 19:02:21.052 | ERROR | 'NoneType' object has no attribute 'load'
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\alas.py", line 195, in c72_mystery_farming
    az.run('campaign_7_2_mystery_farming')
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\run.py", line 182, in run
    self.device.screenshot()
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\device\device.py", line 49, in screenshot
    super().screenshot()
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\device\screenshot.py", line 70, in screenshot
    self.image.load()
AttributeError: 'NoneType' object has no attribute 'load'
2020-12-02 19:02:21.054 | INFO | Saving error: ./log/error/1606906941054

**Comment by LmeSzinc** [comment]
1. 把 module/device/screenshot.py line 52 的 `@retry(wait_fixed=5000, stop_max_attempt_number=10)` 删掉再运行, 看看 log.
2. 尝试更改 设备设置 - ADB设置 - 设备截图方案 为 ascreencap.

**Comment by 1095141917** [comment]
谢谢大佬。我按你说的改然后看log发现应该是和我之前用注册表吧控制台的语言改为使用65001 UTF-8有关，我把注册表之前设置删掉就好了
