### ISSUE TITLE
运行收菜的时候会卡在出击界面然后脚本因为长时间等待而停止运行

### ISSUE THREAD

**Issue by lvzhenbo** [LmeSzinc/AzurLaneAutoScript#273]
**Describe the bug**
运行收菜后，脚本启动游戏，点击到出击界面，然后就卡住，最后停止运行

**To Reproduce**

**Expected behavior**
能够正常运行收菜

**Screenshots**

**Log**
2020-12-23 12:23:44.186 | INFO | +---------------------------------------------+
2020-12-23 12:23:44.187 | INFO | |                    START                    |
2020-12-23 12:23:44.187 | INFO | +---------------------------------------------+
2020-12-23 12:23:44.188 | INFO | [Server] cn
2020-12-23 12:23:45.867 | INFO | [Command] Reward
2020-12-23 12:23:45.867 | INFO | <<< DEVICE >>>
2020-12-23 12:23:45.868 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
2020-12-23 12:23:45.949 | INFO | already connected to 127.0.0.1:62001
command = reward
enable_reward = yes
reward_interval = 10, 40
reward_stop_game_during_interval = no
enable_daily_reward = no
enable_oil_reward = yes
enable_coin_reward = yes
enable_mission_reward = yes
enable_commission_reward = yes
enable_tactical_reward = yes
enable_dorm_reward = yes
enable_dorm_feed = yes
dorm_feed_interval = 278, 480
dorm_collect_interval = 60, 180
dorm_feed_filter = 1000 > 2000 > 3000 > 5000 > 10000 > 20000
commission_time_limit = 0
duration_shorter_than_2 = 11
duration_longer_than_6 = -11
expire_shorter_than_2 = 11
expire_longer_than_6 = -11
daily_comm = 120
major_comm = 0
extra_drill = 20
extra_part = 60
extra_cube = 80
extra_oil = 90
extra_book = 70
urgent_drill = 45
urgent_part = 95
urgent_cube = 165
urgent_book = 95
urgent_box = 195
urgent_gem = 205
urgent_ship = 155
doa_daily = 500
tactical_book_tier_max = 3
tactical_book_tier_min = 2
tactical_exp_first = yes
tactical_if_no_book_satisfied = cancel_tactical
enable_research_reward = no
research_use_cube = no
research_use_coin = yes
research_use_part = yes
research_filter_preset = series_3_than_2
research_filter_string = 
buy_meowfficer = 0
enable_data_key_collect = yes
enable_train_meowfficer = no
2020-12-23 12:23:48.068 | INFO | <<< REWARD SETTINGS SAVED >>>
2020-12-23 12:23:50.677 | INFO | <<< REWARD LOOP >>>
2020-12-23 12:23:50.677 | INFO | <<< REWARD START >>>
2020-12-23 12:23:50.677 | INFO | <<< UI ENSURE >>>
2020-12-23 12:23:53.177 | INFO | [Screen_size] 1280x720
2020-12-23 12:23:54.549 | INFO | Unknown ui page
2020-12-23 12:23:54.580 | INFO | Unable to goto page_main
2020-12-23 12:23:54.580 | INFO | [DEVICE_SCREENSHOT_METHOD] ADB
2020-12-23 12:23:54.580 | INFO | [DEVICE_CONTROL_METHOD] uiautomator2
2020-12-23 12:23:54.580 | INFO | [SERVER] cn
2020-12-23 12:23:54.580 | WARNING | Starting from current page is not supported
2020-12-23 12:23:54.580 | WARNING | Supported page: ['page_main', 'page_campaign_menu', 'page_campaign', 'page_fleet', 'page_exercise', 'page_daily', 'page_event', 'page_sp', 'page_mission', 'page_raid', 'page_reward', 'page_reshmenu', 'page_research', 'page_dormmenu', 'page_dorm', 'page_meowfficer', 'page_archives']
2020-12-23 12:23:54.580 | WARNING | Supported page: Any page with a "HOME" button on the upper-right
2020-12-23 12:23:54.625 | INFO | [Package_name] com.vphone.launcher
2020-12-23 12:23:54.625 | WARNING | Game not running
2020-12-23 12:23:54.625 | INFO | <<< APP RESTART >>>
2020-12-23 12:23:54.625 | INFO | App stop: com.bilibili.azurlane
2020-12-23 12:23:55.284 | INFO | App start: com.bilibili.azurlane
2020-12-23 12:23:56.527 | INFO | <<< APP LOGIN >>>
2020-12-23 12:24:50.612 | INFO | Click ( 825,  518) @ LOGIN_GAME_UPDATE
[D 201223 12:24:50 __init__:585] kill process(ps): uiautomator
[D 201223 12:24:54 __init__:604] uiautomator-v2 is starting ... left: 40.0s
[D 201223 12:24:55 __init__:604] uiautomator-v2 is starting ... left: 39.0s
[D 201223 12:24:56 __init__:604] uiautomator-v2 is starting ... left: 38.0s
[D 201223 12:24:57 __init__:604] uiautomator-v2 is starting ... left: 37.0s
[D 201223 12:24:58 __init__:604] uiautomator-v2 is starting ... left: 36.0s
[D 201223 12:24:59 __init__:604] uiautomator-v2 is starting ... left: 34.9s
[D 201223 12:25:00 __init__:604] uiautomator-v2 is starting ... left: 33.9s
[D 201223 12:25:01 __init__:604] uiautomator-v2 is starting ... left: 32.9s
[I 201223 12:25:01 __init__:568] uiautomator back to normal
2020-12-23 12:25:25.275 | INFO | Click ( 483,  334) @ LOGIN_CHECK
2020-12-23 12:25:25.387 | INFO | Login success
2020-12-23 12:25:30.752 | INFO | Click ( 498,  364) @ LOGIN_CHECK
2020-12-23 12:25:35.856 | INFO | Click ( 493,  358) @ LOGIN_CHECK
2020-12-23 12:25:39.631 | INFO | Click (  57,   58) @ BACK_ARROW
2020-12-23 12:25:40.281 | INFO | Click (1235,   43) @ GOTO_MAIN
2020-12-23 12:25:44.918 | INFO | Click (  48,   63) @ BACK_ARROW
2020-12-23 12:25:45.543 | INFO | Click (1241,   44) @ GOTO_MAIN
2020-12-23 12:25:46.709 | INFO | Click (1205,   68) @ LOGIN_ANNOUNCE
2020-12-23 12:25:50.117 | INFO | Login to main confirm
2020-12-23 12:25:50.117 | INFO | <<< UI CLICK >>>
2020-12-23 12:25:50.125 | INFO | Click (1087,  388) @ MAIN_GOTO_CAMPAIGN
2020-12-23 12:26:50.492 | WARNING | Wait too long
2020-12-23 12:26:50.492 | WARNING | Waiting for {'POPUP_CANCEL', 'CAMPAIGN_CHECK', 'MAIN_GOTO_CAMPAIGN', 'EVENT_CHECK', 'WITHDRAW', 'SP_CHECK'}
Traceback (most recent call last):
  File "D:\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "D:\AzurLaneAutoScript\alas.py", line 103, in reward
    self.reward_when_finished()
  File "D:\AzurLaneAutoScript\alas.py", line 80, in reward_when_finished
    az.reward_loop()
  File "D:\AzurLaneAutoScript\module\reward\reward.py", line 207, in reward_loop
    self.reward()
  File "D:\AzurLaneAutoScript\module\reward\reward.py", line 41, in reward
    self.ui_goto_main()
  File "D:\AzurLaneAutoScript\module\ui\ui.py", line 188, in ui_goto_main
    return self.ui_ensure(destination=page_main)
  File "D:\AzurLaneAutoScript\module\ui\ui.py", line 178, in ui_ensure
    self.ui_get_current_page()
  File "D:\AzurLaneAutoScript\module\ui\ui.py", line 109, in ui_get_current_page
    raise GameNotRunningError('Game not running')
module.exception.GameNotRunningError: Game not running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alas_cn.pyw", line 8, in <module>
    main()
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "D:\AzurLaneAutoScript\module\config\argparser.py", line 497, in main
    alas.run(command=command)
  File "D:\AzurLaneAutoScript\alas.py", line 34, in run
    az.ensure_no_unfinished_campaign()
  File "D:\AzurLaneAutoScript\module\handler\login.py", line 121, in ensure_no_unfinished_campaign
    confirm_wait=confirm_wait, skip_first_screenshot=True)
  File "D:\AzurLaneAutoScript\module\ui\ui.py", line 64, in ui_click
    self.device.screenshot()
  File "D:\AzurLaneAutoScript\module\device\device.py", line 48, in screenshot
    self.stuck_record_check()
  File "D:\AzurLaneAutoScript\module\device\device.py", line 111, in stuck_record_check
    raise GameStuckError(f'Wait too long')
module.exception.GameStuckError: Wait too long

**Comment by LmeSzinc** [comment]
已修复
