### ISSUE TITLE
[TW]  Run error after update

### ISSUE THREAD

**Issue by zeropizero** [LmeSzinc/AzurLaneAutoScript#274]
**Describe the bug**

Execution error 
Other servers work normally

**To Reproduce**

1. Select Server [4] TW
2. ENTER

**Expected behavior**

**Screenshots**

![202012230336](https://user-images.githubusercontent.com/76511490/102973249-c4af2180-453f-11eb-8e65-d92e0b1adbe3.png)

**Log**

Python Found in C:\AzurLaneAutoScript\toolkit\python.exe Proceeding..
Opening alas_tw.pyw in C:\AzurLaneAutoScript
2020-12-23 16:18:05.475 | INFO | +---------------------------------------------+
2020-12-23 16:18:05.475 | INFO | |                    START                    |
2020-12-23 16:18:05.476 | INFO | +---------------------------------------------+
2020-12-23 16:18:05.492 | INFO | [Server] tw
Traceback (most recent call last):
  File "alas_tw.pyw", line 5, in <module>
    from module.config.argparser_tw import main
  File "C:\AzurLaneAutoScript\module\config\argparser_tw.py", line 7, in <module>
    from alas import AzurLaneAutoScript
  File "C:\AzurLaneAutoScript\alas.py", line 9, in <module>
    from module.handler.login import LoginHandler
  File "C:\AzurLaneAutoScript\module\handler\login.py", line 5, in <module>
    from module.combat.combat import Combat
  File "C:\AzurLaneAutoScript\module\combat\combat.py", line 14, in <module>
    from module.retire.retirement import Retirement
  File "C:\AzurLaneAutoScript\module\retire\retirement.py", line 8, in <module>
    from module.retire.enhancement import Enhancement
  File "C:\AzurLaneAutoScript\module\retire\enhancement.py", line 12, in <module>
    from module.retire.dock import Dock, CARD_GRIDS
  File "C:\AzurLaneAutoScript\module\retire\dock.py", line 2, in <module>
    from module.equipment.equipment import Equipment
  File "C:\AzurLaneAutoScript\module\equipment\equipment.py", line 6, in <module>
    from module.ui.ui import UI
  File "C:\AzurLaneAutoScript\module\ui\ui.py", line 12, in <module>
    class UI(InfoHandler):
  File "C:\AzurLaneAutoScript\module\ui\ui.py", line 14, in UI
    ui_pages = [page_main, page_campaign_menu, page_campaign, page_fleet,
NameError: name 'page_campaign_menu' is not defined
Press any key to back main menu

**Comment by LmeSzinc** [comment]
已修复
最近更新了大世界, 台服好像没有更新. 我尽量保持了台服不变, 有什么问题请再提出.
