### ISSUE TITLE
出擊設定問題

### ISSUE THREAD

**Issue by Zorachristine** [LmeSzinc/AzurLaneAutoScript#278]
有2個問題
1.出擊艦隊設定為輪型陣時會出現問題，若設為其他兩個陣型則順利儲存設定。
```
2020-12-24 21:13:47.269 | INFO | [Server] tw
Traceback (most recent call last):
  File "alas_tw.pyw", line 8, in <module>
    main()
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "D:\AzurLaneAutoScript\module\config\argparser_tw.py", line 502, in main
    alas = AzurLaneAutoScript(ini_name=ini_name)
  File "D:\AzurLaneAutoScript\alas.py", line 19, in __init__
    self.config = AzurLaneConfig(ini_name)
  File "D:\AzurLaneAutoScript\module\config\config.py", line 821, in __init__
    self.load_config_file(ini_name)
  File "D:\AzurLaneAutoScript\module\config\config.py", line 521, in load_config_file
    self.load_from_config(self.config)
  File "D:\AzurLaneAutoScript\module\config\config.py", line 581, in load_from_config
    self.__setattr__(f'FLEET_{n}_FORMATION', int(option[f'fleet_formation_{n}'].split('_')[1]))
IndexError: list index out of range
```

2.若潛艇一同出擊，在進入地圖時會一直重複點擊紅框處。
![Screenshot_2020-12-24-21-10-01](https://user-images.githubusercontent.com/73385275/103091209-69a82800-462e-11eb-8192-9588585fd0a2.png)

**Comment by LmeSzinc** [comment]
1. 是翻译的问题, 已修复. GUI 中是 `輪型陣` , 翻译字典中是 `輪形陣`
2. 国服正常, 检查一下台服的图标是否有不一样.

**Comment by Zorachristine** [comment]
確認是圖標問題，已解決。之後會找時間上傳。

另外我想問以後是否會支援單隊出擊呢？比如8-4可4+1BOSS戰解決，有時實在是懶得編第二隊打王，
