### ISSUE TITLE
ALAS启动时报错：ConnectionRefusedError

### ISSUE THREAD

**Issue by QuiltDiver** [LmeSzinc/AzurLaneAutoScript#2895]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在打开ALAS后，等待软件初始化的过程中报错：
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

暂未找到可行的解决方法。

### 如何复现

1. 双击ALAS
2. 等待初始化
3. 出现问题

### 相关 Logs

```Text
"D:\Cheats\AzurLaneAutoScript
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/uiautomator2/init.py minicap_urls no need to patch
./toolkit/Lib/site-packages/uiautomator2/init.py appdir already patched
./toolkit/Lib/site-packages/adbutils/mixin.py apkutils2 no need to patch
==================== SHOW DEPLOY CONFIG ====================
Repository: git://git.lyoko.io/AzurLaneAutoScript
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"D:/Cheats/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in D:/Cheats/AzurLaneAutoScript/.git/
[ success ]
==================== SET GIT PROXY ====================
"D:/Cheats/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"D:/Cheats/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
"D:/Cheats/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify true
[ success ]
==================== SET GIT REPOSITORY ====================
"D:/Cheats/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin git://git.lyoko.io/AzurLaneAutoScript
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"D:/Cheats/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
From git://git.lyoko.io/AzurLaneAutoScript
 * branch              master     -> FETCH_HEAD
[ success ]
==================== PULL REPOSITORY BRANCH ====================
"D:/Cheats/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" reset --hard origin/master
HEAD is now at c892b3be Fix: [TW] SHOP_CHECK
[ success ]
"D:/Cheats/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" pull --ff-only origin master
From git://git.lyoko.io/AzurLaneAutoScript
 * branch              master     -> FETCH_HEAD
Already up to date.
[ success ]
==================== SHOW VERSION ====================
"D:/Cheats/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" --no-pager log --no-merges -1
commit c892b3be22ca0014d79de51a3b58da2a5a9e4c20 (HEAD -> master, origin/master)
Author: xzjjasper <1155091886@link.cuhk.edu.hk>
Date:   Sat Jul 15 20:45:29 2023 +0800

    Fix: [TW] SHOP_CHECK
[ success ]
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
==================== KILL ALAS.EXE ====================
==================== KILL PYTHON.EXE ====================
+-----------------------------------------------------------+
|                    UPDATE DEPENDENCIES                    |
+-----------------------------------------------------------+
==================== CHECK PYTHON ====================
"D:/Cheats/AzurLaneAutoScript/toolkit/python.exe" --version
Python 3.7.6
[ success ]
==================== UPDATE DEPENDENCIES ====================
"D:/Cheats/AzurLaneAutoScript/toolkit/python.exe" -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --disable-pip-version-check
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: adbutils==0.11.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: aiofiles==0.7.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: alas-webapp==0.3.7 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 9)) (0.3.7)
Requirement already satisfied: anyio==1.3.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: apkutils2==1.0.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: asgiref==3.4.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 12)) (3.4.1)
Requirement already satisfied: async-generator==1.10 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 13)) (1.10)
Requirement already satisfied: av==10.0.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 14)) (10.0.0)
Requirement already satisfied: cached-property==1.5.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 15)) (1.5.2)
Requirement already satisfied: certifi==2021.5.30 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 16)) (2021.5.30)
Requirement already satisfied: cffi==1.15.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 17)) (1.15.0)
Requirement already satisfied: chardet==3.0.4 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 18)) (3.0.4)
Requirement already satisfied: cigam==0.0.3 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 19)) (0.0.3)
Requirement already satisfied: click==8.0.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 20)) (8.0.1)
Requirement already satisfied: cnocr==1.2.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 21)) (1.2.2)
Requirement already satisfied: colorama==0.4.5 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 22)) (0.4.5)
Requirement already satisfied: commonmark==0.9.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 23)) (0.9.1)
Requirement already satisfied: cycler==0.10.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 24)) (0.10.0)
Requirement already satisfied: decorator==5.1.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 25)) (5.1.0)
Requirement already satisfied: deprecated==1.2.13 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 26)) (1.2.13)
Requirement already satisfied: deprecation==2.1.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 27)) (2.1.0)
Requirement already satisfied: filelock==3.3.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 28)) (3.3.0)
Requirement already satisfied: future==0.18.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 29)) (0.18.2)
Requirement already satisfied: gevent==21.12.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 30)) (21.12.0)
Requirement already satisfied: gluoncv==0.6.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 31)) (0.6.0)
Requirement already satisfied: graphviz==0.8.4 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 32)) (0.8.4)
Requirement already satisfied: greenlet==1.1.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 33)) (1.1.2)
Requirement already satisfied: h11==0.12.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 34)) (0.12.0)
Requirement already satisfied: httptools==0.4.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 35)) (0.4.0)
Requirement already satisfied: idna==2.6 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 36)) (2.6)
Requirement already satisfied: imageio==2.27.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 37)) (2.27.0)
Requirement already satisfied: importlib-metadata==4.8.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 38)) (4.8.1)
Requirement already satisfied: inflection==0.5.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 39)) (0.5.1)
Requirement already satisfied: jellyfish==0.8.8 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 40)) (0.8.8)
Requirement already satisfied: kiwisolver==1.3.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 41)) (1.3.2)
Requirement already satisfied: logzero==1.7.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 42)) (1.7.0)
Requirement already satisfied: lxml==4.6.3 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 43)) (4.6.3)
Requirement already satisfied: lz4==3.1.3 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 44)) (3.1.3)
Requirement already satisfied: matplotlib==3.4.3 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 45)) (3.4.3)
Requirement already satisfied: msgpack==1.0.3 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 46)) (1.0.3)
Requirement already satisfied: mxnet==1.6.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 47)) (1.6.0)
Requirement already satisfied: numpy==1.16.6 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 48)) (1.16.6)
Requirement already satisfied: onepush==1.2.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 49)) (1.2.0)
Requirement already satisfied: opencv-python==4.5.3.56 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 50)) (4.5.3.56)
Requirement already satisfied: packaging==20.9 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 51)) (20.9)
Requirement already satisfied: pillow==8.3.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 52)) (8.3.2)
Requirement already satisfied: portalocker==2.3.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 53)) (2.3.2)
Requirement already satisfied: prettytable==2.2.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 54)) (2.2.1)
Requirement already satisfied: progress==1.6 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 55)) (1.6)
Requirement already satisfied: psutil==5.9.3 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 56)) (5.9.3)
Requirement already satisfied: py==1.10.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 57)) (1.10.0)
Requirement already satisfied: pycparser==2.21 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 58)) (2.21)
Requirement already satisfied: pydantic==1.10.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 59)) (1.10.2)
Requirement already satisfied: pyelftools==0.27 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 60)) (0.27)
Requirement already satisfied: pygments==2.12.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 61)) (2.12.0)
Requirement already satisfied: pyparsing==2.4.7 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 62)) (2.4.7)
Requirement already satisfied: pypresence==4.2.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 63)) (4.2.1)
Requirement already satisfied: python-dateutil==2.8.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 64)) (2.8.2)
Requirement already satisfied: python-dotenv==0.19.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 65)) (0.19.0)
Requirement already satisfied: pywebio==1.6.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 66)) (1.6.2)
Requirement already satisfied: pywin32==301 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 67)) (301)
Requirement already satisfied: pyyaml==5.4.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 68)) (5.4.1)
Requirement already satisfied: pyzmq==22.3.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 69)) (22.3.0)
Requirement already satisfied: requests==2.18.4 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 70)) (2.18.4)
Requirement already satisfied: retry==0.9.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 71)) (0.9.2)
Requirement already satisfied: retrying==1.3.3 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 72)) (1.3.3)
Requirement already satisfied: rich==11.2.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 73)) (11.2.0)
Requirement already satisfied: scipy==1.4.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 74)) (1.4.1)
Requirement already satisfied: six==1.16.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 75)) (1.16.0)
Requirement already satisfied: sniffio==1.2.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 76)) (1.2.0)
Requirement already satisfied: starlette==0.14.2 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 77)) (0.14.2)
Requirement already satisfied: tornado==6.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 78)) (6.1)
Requirement already satisfied: tqdm==4.62.3 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 79)) (4.62.3)
Requirement already satisfied: typing-extensions==4.3.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 80)) (4.3.0)
Requirement already satisfied: ua-parser==0.10.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 81)) (0.10.0)
Requirement already satisfied: uiautomator2==2.16.17 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 82)) (2.16.17)
Requirement already satisfied: uiautomator2cache==0.3.0.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 83)) (0.3.0.1)
Requirement already satisfied: urllib3==1.22 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 84)) (1.22)
Requirement already satisfied: user-agents==2.2.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 85)) (2.2.0)
Requirement already satisfied: uvicorn[standard]==0.17.6 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 86)) (0.17.6)
Requirement already satisfied: watchgod==0.7 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 87)) (0.7)
Requirement already satisfied: wcwidth==0.2.5 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 88)) (0.2.5)
Requirement already satisfied: websockets==10.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 89)) (10.0)
Requirement already satisfied: whichcraft==0.6.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 90)) (0.6.1)
Requirement already satisfied: wrapt==1.13.1 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 91)) (1.13.1)
Requirement already satisfied: xmltodict==0.12.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 92)) (0.12.0)
Requirement already satisfied: zerorpc==0.6.3 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 93)) (0.6.3)
Requirement already satisfied: zipp==3.6.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 94)) (3.6.0)
Requirement already satisfied: zope.event==4.5.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 95)) (4.5.0)
Requirement already satisfied: zope.interface==5.4.0 in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 96)) (5.4.0)
Requirement already satisfied: setuptools in d:\cheats\azurlaneautoscript\toolkit\lib\site-packages (from gevent==21.12.0->-r requirements.txt (line 30)) (42.0.2)
[ success ]
+-------------------------------------------------------+
|                    UPDATE APP.ASAR                    |
+-------------------------------------------------------+
Old file: D:\Cheats\AzurLaneAutoScript\toolkit\WebApp\resources\app.asar
New version: 0.3.7
New file: D:\Cheats\AzurLaneAutoScript\toolkit\lib\site-packages\alas_webapp\app.asar
app.asar is already up to date
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Task adb.exe not found
taskkill /f /im nox_adb.exe >nul 2>nul
Task nox_adb.exe not found
taskkill /f /im adb_server.exe >nul 2>nul
Task adb_server.exe not found
taskkill /f /im HD-Adb.exe >nul 2>nul
Task HD-Adb.exe not found
Emulator Nox found, instances: ['127.0.0.1:62001']
Replacing D:\Nox\bin\adb.exe
D:/Cheats/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe is same as D:\Nox\bin\adb.exe, skip
Replacing D:\Nox\bin\nox_adb.exe
D:/Cheats/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe is same as D:\Nox\bin\nox_adb.exe, skip
D:/Cheats/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
adb.exe: failed to check server version: cannot connect to daemon
Devices: []
D:/Cheats/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:5037
* daemon not running; starting now at tcp:5037
* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
error: cannot connect to daemon
could not read ok from ADB Server
* failed to start daemon
adb.exe: failed to check server version: cannot connect to daemon
Devices: []
==================== UIAUTOMATOR2 INIT ====================
* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
error: cannot connect to daemon
Traceback (most recent call last):
  File "D:\Cheats\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 103, in _safe_connect
    return self._create_socket()
  File "D:\Cheats\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 95, in _create_socket
    s.connect((adb_host, adb_port))
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Cheats\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Cheats\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Cheats\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "D:\Cheats\AzurLaneAutoScript\deploy\installer.py", line 20, in install
    self.adb_install()
  File "D:\Cheats\AzurLaneAutoScript\deploy\adb.py", line 56, in adb_install
    for device in adbutils.adb.iter_device():
  File "D:\Cheats\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 443, in iter_device
    with self._connect() as c:
  File "D:\Cheats\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 189, in _connect
    _conn = _AdbStreamConnection(self.__host, self.__port)
  File "D:\Cheats\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 88, in __init__
    self.__conn = self._safe_connect()
  File "D:\Cheats\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 106, in _safe_connect
    return self._create_socket()
  File "D:\Cheats\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 95, in _create_socket
    s.connect((adb_host, adb_port))
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
```

**Comment by QuiltDiver** [comment]
应该是端口占用，重启系统后问题消失。
