### ISSUE TITLE
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by robin087** [LmeSzinc/AzurLaneAutoScript#3057]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

解压后双击alas，但是更新失败

ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

### 如何复现

下载后双击alas开始更新，直接报这个错误

### 预期行为

按理说应该是能更新完然后运行的

### 相关 Logs

```Text
"G:\application\alas\AzurLaneAutoScript
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/uiautomator2/init.py minicap_urls no need to patch
./toolkit/Lib/site-packages/uiautomator2/init.py appdir already patched
./toolkit/Lib/site-packages/adbutils/mixin.py apkutils2 no need to patch
==================== SHOW DEPLOY CONFIG ====================
Repository: git://git.lyoko.io/AzurLaneAutoScript
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"G:/application/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in G:/application/alas/AzurLaneAutoScript/.git/
[ success ]
==================== SET GIT PROXY ====================
"G:/application/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"G:/application/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
"G:/application/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify true
[ success ]
==================== SET GIT REPOSITORY ====================
"G:/application/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin git://git.lyoko.io/AzurLaneAutoScript
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"G:/application/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
remote: Enumerating objects: 141, done.
remote: Counting objects: 100% (141/141), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 99 (delta 73), reused 0 (delta 0)0 KiB/s
Unpacking objects: 100% (99/99), 76.04 KiB | 17.00 KiB/s, done.
From git://git.lyoko.io/AzurLaneAutoScript
 * branch              master     -> FETCH_HEAD
   b912536f..3f3d5b85  master     -> origin/master
[ success ]
==================== PULL REPOSITORY BRANCH ====================
"G:/application/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" reset --hard origin/master
Updating files: 100% (6400/6400), done.
HEAD is now at 3f3d5b85 Merge pull request #3056 from LmeSzinc/dev
[ success ]
"G:/application/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" pull --ff-only origin master
From git://git.lyoko.io/AzurLaneAutoScript
 * branch              master     -> FETCH_HEAD
Already up to date.
[ success ]
==================== SHOW VERSION ====================
"G:/application/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" --no-pager log --no-merges -1
commit 8987c9253b3cdb54848003d703f4305fc1ae49ba
Author: LmeSzinc <37934724+LmeSzinc@users.noreply.github.com>
Date:   Mon Aug 28 17:16:24 2023 +0800

    Add: Disable multi-instances on phone cloud environment
[ success ]
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
==================== KILL ALAS.EXE ====================
Traceback (most recent call last):
  File "G:\application\alas\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "G:\application\alas\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\application\alas\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "G:\application\alas\AzurLaneAutoScript\deploy\installer.py", line 17, in install
    self.alas_kill()
  File "G:\application\alas\AzurLaneAutoScript\deploy\alas.py", line 63, in alas_kill
    self.kill_by_name('alas.exe')
  File "G:\application\alas\AzurLaneAutoScript\deploy\alas.py", line 57, in kill_by_name
    for row in self.iter_process_by_name(name):
  File "G:\application\alas\AzurLaneAutoScript\deploy\alas.py", line 27, in iter_process_by_name
    from win32com.client import GetObject
  File "C:\Users\lc20\AppData\Roaming\Python\Python37\site-packages\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。
```

### 还有别的吗？

参考了
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2111
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1623
是64位的windows，以及多次尝试重新安装，都失败了

**Comment by robin087** [comment]
解决了，把AppData\Roaming下的python移除就好了，但是不知道会不会对洽谈的应用产生影响。。。
