### ISSUE TITLE
复刻神圣的悲喜剧，活动图从b1开始每关都出现walk out of step问题

### ISSUE THREAD

**Issue by IceJames** [LmeSzinc/AzurLaneAutoScript#323]
**Describe the bug**
复刻神圣的悲喜剧，活动图从b1开始每关都出现walk out of step问题，模拟点击多次尝试点击角色可移动范围外的位置，且该位置没有敌船。

**To Reproduce**
1. 进入地图
2. 开始上下左右滑动查找
3. 找到一个位置
4. 点击移动到该位置时出现错误

**Expected behavior**

**Screenshots**

**Log**
2021-01-29 23:23:57.947 | INFO | +---------------------------------------------+
2021-01-29 23:23:57.947 | INFO | |                    START                    |
2021-01-29 23:23:57.947 | INFO | +---------------------------------------------+
2021-01-29 23:23:57.949 | INFO | [Server] cn
2021-01-29 23:24:01.208 | INFO | [Command] Event
2021-01-29 23:24:01.208 | INFO | <<< DEVICE >>>
2021-01-29 23:24:01.208 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
2021-01-29 23:24:01.773 | INFO | already connected to 127.0.0.1:5555
2021-01-29 23:24:04.959 | INFO | [Emotion fleet_1] 99
2021-01-29 23:24:04.959 | INFO | [Emotion fleet_2] 119
2021-01-29 23:24:04.964 | INFO | [Emotion_bug] 0/84
2021-01-29 23:24:04.964 | INFO | ==================== B3 ====================
2021-01-29 23:24:04.965 | INFO | Count: [0/2]
2021-01-29 23:24:06.554 | INFO | [Screen_size] 1280x720
2021-01-29 23:24:06.555 | INFO | Already in map, skip ensure_campaign_ui.
2021-01-29 23:24:06.605 | INFO | -------------------- DEFAULT_BUTTON --------------------
2021-01-29 23:24:06.606 | INFO | <<< ENTER MAP >>>
2021-01-29 23:24:07.833 | INFO | Already in map, skip enter_map.
2021-01-29 23:24:07.860 | INFO | No fleet lock option.
2021-01-29 23:24:07.860 | INFO | <<< MAP INIT >>>
2021-01-29 23:24:07.862 | INFO | Load map_data, has_loop=False, use_loop=False
2021-01-29 23:24:07.862 | INFO | Load spawn_data, has_loop=False, use_loop=False
2021-01-29 23:24:07.862 | INFO | Load mechanism, land_base=False
2021-01-29 23:24:07.862 | INFO | grid_connection: wall=False, portal=False
2021-01-29 23:24:07.868 | INFO | [Map_buff] 2
2021-01-29 23:24:07.868 | INFO | Skip strategy bar check.
2021-01-29 23:24:09.395 | INFO |           vanish_point: (  647, -1728)
2021-01-29 23:24:09.395 | INFO |          distant_point: (-2326, -1728)
2021-01-29 23:24:09.447 | INFO | 0.319s      Horizontal: 7 (7 inner, 1 edge)
2021-01-29 23:24:09.447 | INFO | Edges: /_\    Vertical: 9 (9 inner, 2 edge)
2021-01-29 23:24:09.448 | INFO | [homo_storage] ((8, 6), [(245.604, 90.831), (1147.353, 90.831), (127.28, 626.477), (1294.468, 626.477)])
2021-01-29 23:24:09.589 | INFO |            tile_center: 0.918 (good match)
2021-01-29 23:24:09.615 | INFO | 0.161s      edge_lines: 2 hori, 2 vert
2021-01-29 23:24:09.615 | INFO | Edges: /_\   homo_loca: ( 27,  77)
2021-01-29 23:24:09.620 | INFO |            center_loca: (3, 3)
2021-01-29 23:24:09.621 | INFO |                 Camera: A1
2021-01-29 23:24:09.625 | INFO | [HP]  96%  98%  98%  98%  98%  98%
2021-01-29 23:24:09.626 | INFO | Ensure edge in sight.
2021-01-29 23:24:11.179 | INFO |            tile_center: 0.918 (good match)
2021-01-29 23:24:11.209 | INFO | 0.170s      edge_lines: 2 hori, 2 vert
2021-01-29 23:24:11.210 | INFO | Edges: /_\   homo_loca: ( 27,  77)
2021-01-29 23:24:11.229 | INFO |            center_loca: (3, 3)
2021-01-29 23:24:11.229 | INFO |       camera_corrected: A1 -> D5
2021-01-29 23:24:11.230 | INFO |                 Camera: D5
2021-01-29 23:24:11.230 | INFO | Full scan start, mode=normal
2021-01-29 23:24:11.231 | INFO | [enemy_missing] EN: 2, MY: 0, SI: 2, BO: 0, CA: 0
2021-01-29 23:24:11.231 | INFO | [enemy_may____] EN: 0, MY: 0, SI: 0, BO: 0, CA: 0
2021-01-29 23:24:11.232 | INFO | Focus to: D5
2021-01-29 23:24:11.232 | INFO | Map swipe: (0, 0)
2021-01-29 23:24:12.862 | INFO | 0.307s         predict: 47
2021-01-29 23:24:12.862 | INFO | -- -- -- -- -- -- 1M 2M
2021-01-29 23:24:12.863 | INFO | -- -- -- -- 2L -- -- --
2021-01-29 23:24:12.863 | INFO | -- -- -- -- -- -- -- --
2021-01-29 23:24:12.863 | INFO | -- -- -- -- -- -- -- --
2021-01-29 23:24:12.864 | INFO | -- -- -- -- -- -- -- 3E
2021-01-29 23:24:12.864 | INFO | -- 3M -- -- -- 3M -- ..
2021-01-29 23:24:12.868 | INFO | [enemy_missing] EN:-4, MY: 0, SI: 2, BO: 0, CA: 0
2021-01-29 23:24:12.869 | INFO | [enemy_may____] EN: 0, MY: 0, SI: 0, BO: 0, CA: 0
2021-01-29 23:24:12.870 | INFO | Focus to: E5
2021-01-29 23:24:12.871 | INFO | Map swipe: (1, 0)
2021-01-29 23:24:12.876 | INFO | Swipe ( 639,  470) -> ( 445,  454), 0.185
2021-01-29 23:24:15.213 | INFO |            tile_center: 0.918 (good match)
2021-01-29 23:24:15.249 | INFO | 0.174s      edge_lines: 2 hori, 1 vert
2021-01-29 23:24:15.250 | INFO | Edges:   \   homo_loca: ( 26,  59)
2021-01-29 23:24:15.263 | INFO |           grids_offset: (1, 0)
2021-01-29 23:24:15.265 | INFO |            center_loca: (3, 3)
2021-01-29 23:24:15.266 | INFO |                 Camera: E5
2021-01-29 23:24:15.455 | INFO | 0.187s         predict: 42
2021-01-29 23:24:15.456 | INFO | -- -- -- -- -- 1E 2M
2021-01-29 23:24:15.456 | INFO | -- -- -- 2L -- -- --
2021-01-29 23:24:15.456 | INFO | -- -- -- -- -- -- --
2021-01-29 23:24:15.456 | INFO | -- -- -- -- -- -- --
2021-01-29 23:24:15.456 | INFO | -- -- -- -- -- -- 3L
2021-01-29 23:24:15.456 | INFO | 3M -- -- -- 3M -- --
2021-01-29 23:24:15.459 | INFO | [enemy_missing] EN:-4, MY: 0, SI: 2, BO: 0, CA: 0
2021-01-29 23:24:15.459 | INFO | [enemy_may____] EN: 0, MY: 0, SI: 0, BO: 0, CA: 0
2021-01-29 23:24:15.460 | INFO | Focus to: E2
2021-01-29 23:24:15.461 | INFO | Map swipe: (0, -2)
2021-01-29 23:24:15.463 | INFO | Swipe ( 523,  327) -> ( 524,  593), 0.17
2021-01-29 23:24:17.656 | INFO |            tile_center: 0.902 (good match)
2021-01-29 23:24:17.676 | INFO | 0.143s  _   edge_lines: 2 hori, 1 vert
2021-01-29 23:24:17.677 | INFO | Edges:   \   homo_loca: ( 30,  15)
2021-01-29 23:24:17.693 | INFO |           grids_offset: (1, 0)
2021-01-29 23:24:17.695 | INFO |            center_loca: (3, 2)
2021-01-29 23:24:17.695 | INFO |                 Camera: E3
2021-01-29 23:24:17.696 | INFO | Map swipe: (0, -1)
2021-01-29 23:24:17.696 | INFO | Swipe ( 804,  293) -> ( 799,  463), 0.155
2021-01-29 23:24:19.773 | INFO |            tile_center: 0.901 (good match)
2021-01-29 23:24:19.795 | INFO | 0.157s  _   edge_lines: 2 hori, 1 vert
2021-01-29 23:24:19.796 | INFO | Edges:   \   homo_loca: ( 25,  24)
2021-01-29 23:24:19.807 | INFO |           grids_offset: (1, 0)
2021-01-29 23:24:19.809 | INFO |            center_loca: (3, 1)
2021-01-29 23:24:19.810 | INFO |                 Camera: E2
2021-01-29 23:24:19.810 | INFO | Re-focus to grid center.
2021-01-29 23:24:19.811 | INFO | Map swipe: (0, 0)
2021-01-29 23:24:19.812 | INFO | Swipe ( 756,  361) -> ( 758,  394), 0.163
2021-01-29 23:24:21.913 | INFO |            tile_center: 0.902 (good match)
2021-01-29 23:24:21.945 | INFO | 0.166s  _   edge_lines: 2 hori, 1 vert
2021-01-29 23:24:21.945 | INFO | Edges:   \   homo_loca: ( 25,  49)
2021-01-29 23:24:21.958 | INFO |           grids_offset: (1, 0)
2021-01-29 23:24:21.961 | INFO |            center_loca: (3, 1)
2021-01-29 23:24:21.962 | INFO |                 Camera: E2
2021-01-29 23:24:22.122 | INFO | 0.160s         predict: 28
2021-01-29 23:24:22.123 | INFO | -- -- -- -- -- -- --
2021-01-29 23:24:22.123 | INFO | Fl -- -- -- -- 1M 2M
2021-01-29 23:24:22.123 | INFO | -- -- -- 2L -- -- --
2021-01-29 23:24:22.123 | INFO | -- -- -- -- -- -- --
2021-01-29 23:24:22.124 | INFO | [enemy_missing] EN:-4, MY: 0, SI: 2, BO: 0, CA: 0
2021-01-29 23:24:22.124 | INFO | [enemy_may____] EN: 0, MY: 0, SI: 0, BO: 0, CA: 1
2021-01-29 23:24:22.125 | INFO | Focus to: D2
2021-01-29 23:24:22.125 | INFO | Map swipe: (-1, 0)
2021-01-29 23:24:22.125 | INFO | Swipe ( 470,  430) -> ( 664,  440), 0.146
2021-01-29 23:24:24.308 | INFO |            tile_center: 0.953 (good match)
2021-01-29 23:24:24.357 | INFO | 0.208s  _   edge_lines: 2 hori, 2 vert
2021-01-29 23:24:24.358 | INFO | Edges: / \   homo_loca: ( 12,  58)
2021-01-29 23:24:24.366 | INFO |            center_loca: (3, 1)
2021-01-29 23:24:24.367 | INFO |                 Camera: D2
2021-01-29 23:24:24.569 | INFO | 0.201s         predict: 31
2021-01-29 23:24:24.570 | INFO | -- -- -- -- -- -- -- --
2021-01-29 23:24:24.570 | INFO | -- FL -- -- -- -- 1M 2M
2021-01-29 23:24:24.570 | INFO | Fl -- -- -- 2L -- -- --
2021-01-29 23:24:24.571 | INFO | .. -- -- -- -- -- -- --
2021-01-29 23:24:24.573 | INFO | [enemy_missing] EN:-4, MY: 0, SI: 2, BO: 0, CA: 0
2021-01-29 23:24:24.574 | INFO | [enemy_may____] EN: 0, MY: 0, SI: 0, BO: 0, CA: 2
2021-01-29 23:24:24.575 | INFO |    A  B  C  D  E  F  G  H
2021-01-29 23:24:24.575 | INFO | 1 -- -- -- -- -- -- -- --
2021-01-29 23:24:24.576 | INFO | 2 -- FL ++ -- -- -- 1M 2M
2021-01-29 23:24:24.576 | INFO | 3 Fl -- -- -- 2L ++ ++ ++
2021-01-29 23:24:24.577 | INFO | 4 -- -- -- -- -- -- -- --
2021-01-29 23:24:24.577 | INFO | 5 -- -- -- -- -- ++ ++ ++
2021-01-29 23:24:24.577 | INFO | 6 -- -- ++ ++ -- -- -- 3L
2021-01-29 23:24:24.578 | INFO | 7 -- 3M ++ ++ -- 3M -- --
2021-01-29 23:24:24.578 | INFO | Predict fleet_2 to be A3
2021-01-29 23:24:24.578 | INFO | <<< FIND CURRENT FLEET >>>
2021-01-29 23:24:24.578 | INFO | Fleets: [A3]
2021-01-29 23:24:24.579 | INFO | Fleet_2 not detected.
2021-01-29 23:24:24.579 | INFO | Predict fleet to be spawn point
2021-01-29 23:24:24.579 | INFO | [Fleet_1: A5] Fleet_2: A3
2021-01-29 23:24:24.588 | INFO |      A    B    C    D    E    F    G    H
2021-01-29 23:24:24.588 | INFO | 1    4    5    6    7    8    9   10   11
2021-01-29 23:24:24.588 | INFO | 2    3    4 9999    6    7    8    9   12
2021-01-29 23:24:24.588 | INFO | 3    2    3    4    5    6 9999 9999 9999
2021-01-29 23:24:24.588 | INFO | 4    1    2    3    4    5    6    7    8
2021-01-29 23:24:24.589 | INFO | 5    0    1    2    3    4 9999 9999 9999
2021-01-29 23:24:24.589 | INFO | 6    1    2 9999 9999    5    6    7    8
2021-01-29 23:24:24.589 | INFO | 7    2    3 9999 9999    6    7    8    9
2021-01-29 23:24:24.589 | INFO | -------------------- BATTLE_0 --------------------
2021-01-29 23:24:24.589 | INFO | Using function: battle_0
2021-01-29 23:24:24.590 | INFO | <<< CLEAR ENEMY >>>
2021-01-29 23:24:24.590 | INFO | Grids: [B7, E3, F7, H6, G2, H2]
2021-01-29 23:24:24.590 | INFO | Clear enemy: B7
2021-01-29 23:24:24.590 | INFO | [Fleet_1: A5] Fleet_2: A3
2021-01-29 23:24:24.593 | INFO | Full path: [A5, A6, A7, B7]
2021-01-29 23:24:24.595 | INFO | Path: [B7]
2021-01-29 23:24:24.595 | INFO | In sight: B7
2021-01-29 23:24:24.596 | INFO | Focus to: D5
2021-01-29 23:24:24.596 | INFO | Map swipe: (0, 2)
2021-01-29 23:24:24.597 | INFO | Swipe ( 966,  532) -> ( 986,  270), 0.141
2021-01-29 23:24:26.913 | INFO |            tile_center: 0.918 (good match)
2021-01-29 23:24:26.957 | INFO | 0.205s  _   edge_lines: 2 hori, 2 vert
2021-01-29 23:24:26.957 | INFO | Edges: / \   homo_loca: ( 27,  95)
2021-01-29 23:24:26.969 | INFO |            center_loca: (3, 3)
2021-01-29 23:24:26.970 | INFO |                 Camera: D4
2021-01-29 23:24:26.971 | INFO | Map swipe: (0, 1)
2021-01-29 23:24:26.971 | INFO | Swipe ( 700,  410) -> ( 699,  241), 0.137
2021-01-29 23:24:29.079 | INFO |            tile_center: 0.905 (good match)
2021-01-29 23:24:29.103 | INFO | 0.140s      edge_lines: 2 hori, 2 vert
2021-01-29 23:24:29.103 | INFO | Edges: /_\   homo_loca: ( 25,  64)
2021-01-29 23:24:29.113 | INFO |            center_loca: (3, 3)
2021-01-29 23:24:29.114 | INFO |                 Camera: D5
2021-01-29 23:24:29.115 | INFO | Global B7 (camera=D5) -> Local B6 (center=D4)
2021-01-29 23:24:29.125 | INFO | Click ( 379,  572) @ B6
2021-01-29 23:24:30.479 | WARNING | Map walk out of step.
2021-01-29 23:24:36.944 | WARNING | Map walk error.
2021-01-29 23:24:36.945 | INFO | Ensure edge in sight.
2021-01-29 23:24:38.277 | INFO |            tile_center: 0.905 (good match)
2021-01-29 23:24:38.303 | INFO | 0.140s      edge_lines: 2 hori, 2 vert
2021-01-29 23:24:38.303 | INFO | Edges: /_\   homo_loca: ( 25,  64)
2021-01-29 23:24:38.318 | INFO |            center_loca: (3, 3)
2021-01-29 23:24:38.318 | INFO |                 Camera: D5
2021-01-29 23:24:38.318 | INFO | Full path: [A5, A6, A7, B7]
2021-01-29 23:24:38.319 | INFO | Path: [A6, A7, B7]
2021-01-29 23:24:38.319 | INFO | In sight: A6
2021-01-29 23:24:38.319 | INFO | Focus to: D5
2021-01-29 23:24:38.320 | INFO | Map swipe: (0, 0)
2021-01-29 23:24:39.568 | INFO | Global A6 (camera=D5) -> Local A5 (center=D4)
2021-01-29 23:24:39.572 | INFO | Click ( 240,  456) @ A5
2021-01-29 23:24:40.942 | WARNING | Map walk out of step.
2021-01-29 23:24:43.325 | ERROR | walk_out_of_step
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 324, in goto
    self._goto(node, expected=expected if node == nodes[-1] else '')
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 257, in _goto
    raise MapWalkError('walk_out_of_step')
module.exception.MapWalkError: walk_out_of_step

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 148, in event
    az.run(self.config.EVENT_STAGE, folder=self.config.EVENT_NAME)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 221, in run
    self.campaign.run()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 139, in run
    self.execute_a_battle()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 96, in execute_a_battle
    result = self.battle_function()
  File "C:\fakepath\AzurLaneAutoScript\module\base\decorator.py", line 63, in wrapper
    return record['func'](self, *args, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 86, in battle_function
    result = func()
  File "C:\fakepath\AzurLaneAutoScript\campaign\event_20210121_cn\b3.py", line 66, in battle_0
    return self.battle_default()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 15, in battle_default
    if self.clear_enemy():
  File "C:\fakepath\AzurLaneAutoScript\module\map\map.py", line 191, in clear_enemy
    self.clear_chosen_enemy(grids[0])
  File "C:\fakepath\AzurLaneAutoScript\module\map\map.py", line 20, in clear_chosen_enemy
    self.goto(grid, expected=expected)
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 330, in goto
    self._goto(node_, expected=expected if node == nodes[-1] else '')
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 257, in _goto
    raise MapWalkError('walk_out_of_step')
module.exception.MapWalkError: walk_out_of_step
2021-01-29 23:24:43.327 | INFO | Saving error: ./log/error/1611933883327

**Comment by LmeSzinc** [comment]
Log:
```
2021-01-29 23:24:06.555 | INFO | Already in map, skip ensure_campaign_ui.
2021-01-29 23:24:06.605 | INFO | -------------------- DEFAULT_BUTTON --------------------
2021-01-29 23:24:06.606 | INFO | <<< ENTER MAP >>>
2021-01-29 23:24:07.833 | INFO | Already in map, skip enter_map.
```
README 中, 使用注意事项 一节已经提到过:
```
当你的图打到一半的时候, 需要手动打完或者手动撤退, 再启动 Alas.
```

**Comment by IceJames** [comment]
谢谢，已查看。问题已解决。
不过不能全自动运行吗?

**Comment by LmeSzinc** [comment]
不太理解 不能全自动运行 是什么意思. 如果你希望全自动运行, 就不要手动进图, 再开脚本.

**Comment by IceJames** [comment]
明白了，原来是手动进图导致的。
我以为“当你图打到一半的时候”是指脚本打到一半的时候。

**Comment by IceJames** [comment]
谢谢!
