### ISSUE TITLE
每日舰队快速换装BUG

### ISSUE THREAD

**Issue by clarkgap** [LmeSzinc/AzurLaneAutoScript#324]
**Describe the bug**
每日舰队快速换装设置为1,1,1,1,1,1（全部换为记录1）时，系统会先进入编队界面，然后卡在第一舰队上。

**Screenshots**
这是我的设置：
![屏幕截图(160)](https://user-images.githubusercontent.com/78226031/106306453-5256ee80-621b-11eb-8826-006831e9d4fc.png)

卡在这里
![com bilibili azurlane_Screenshot_2021 01 29_10 12 44](https://user-images.githubusercontent.com/78226031/106306467-58e56600-621b-11eb-9bcb-14c81e0abb8e.png)

**Log**
2021-01-29 10:11:52.043 | INFO | +---------------------------------------------+
2021-01-29 10:11:52.043 | INFO | |                    START                    |
2021-01-29 10:11:52.043 | INFO | +---------------------------------------------+
2021-01-29 10:11:52.044 | INFO | [Server] cn
2021-01-29 10:11:53.164 | INFO | [Command] Daily
2021-01-29 10:11:53.164 | INFO | <<< DEVICE >>>
2021-01-29 10:11:53.164 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
2021-01-29 10:11:53.230 | INFO | already connected to 127.0.0.1:5555
2021-01-29 10:11:55.449 | INFO | [DailyRecord_daily] Record time: 2020-01-01 00:00:00
2021-01-29 10:11:55.449 | INFO | [DailyRecord_daily] Last update: 2021-01-29 09:00:00
2021-01-29 10:11:55.450 | INFO | <<< UI ENSURE >>>
2021-01-29 10:11:55.888 | INFO | [Screen_size] 1280x720
2021-01-29 10:11:55.897 | INFO | [UI] page_main
2021-01-29 10:11:55.897 | INFO | Goto page_fleet
2021-01-29 10:11:55.897 | INFO | [UI route] page_main - page_fleet
2021-01-29 10:11:55.897 | INFO | <<< UI CLICK >>>
2021-01-29 10:11:56.288 | INFO | Click ( 875,  379) @ MAIN_GOTO_FLEET
2021-01-29 10:11:57.494 | INFO | <<< UI ENSURE INDEX >>>
2021-01-29 10:11:57.831 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
2021-01-29 10:11:57.870 | INFO | [OCR_FLEET_INDEX 0.051s] 1
2021-01-29 10:11:57.870 | INFO | [Index] 1
2021-01-29 10:11:57.870 | ERROR | unsupported operand type(s) for -: 'list' and 'int'
Traceback (most recent call last):
  File "D:\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "D:\AzurLaneAutoScript\alas.py", line 138, in daily
    az.daily_wrapper_run()
  File "D:\AzurLaneAutoScript\module\reward\reward.py", line 252, in daily_wrapper_run
    az.run()
  File "D:\AzurLaneAutoScript\module\daily\daily.py", line 169, in run
    self.equipment_take_on()
  File "D:\AzurLaneAutoScript\module\equipment\fleet_equipment.py", line 20, in equipment_take_on
    self.ui_ensure_index(self.config.FLEET_DAILY, letter=OCR_FLEET_INDEX, next_button=FLEET_NEXT, prev_button=FLEET_PREV)
  File "D:\AzurLaneAutoScript\module\ui\ui.py", line 243, in ui_ensure_index
    diff = index - current
TypeError: unsupported operand type(s) for -: 'list' and 'int'
2021-01-29 10:11:57.871 | INFO | Saving error: ./log/error/1611940317871

**Comment by LmeSzinc** [comment]
已修复, 现在只会对第一支设定的队伍更换装备

**Comment by clarkgap** [comment]
大大，虽然这次只给序列里第一支舰队（队伍4-用于商船护送）更换了装备，但却先用没换装的（队伍3-用于其他每日任务）打了战术研修的炮击，是不是每日任务的顺序匹配没改？还是因为我之前手动打了一次商船护送？

**设定**
![屏幕截图(164)](https://user-images.githubusercontent.com/78226031/106365013-fa3dec00-62ef-11eb-8760-7c3b13124982.png)

**队伍3**
![com bilibili azurlane_Screenshot_2021 01 30_11 30 40](https://user-images.githubusercontent.com/78226031/106365035-2194b900-62f0-11eb-9591-5314dd02c2cb.png)

**队伍4**
![com bilibili azurlane_Screenshot_2021 01 30_11 30 46](https://user-images.githubusercontent.com/78226031/106365038-28233080-62f0-11eb-8586-05778a8e1a93.png)

**每日任务界面**
![com bilibili azurlane_Screenshot_2021 01 30_11 37 07](https://user-images.githubusercontent.com/78226031/106365045-2f4a3e80-62f0-11eb-881d-c49fdf553bbc.png)

**Log**
2021-01-30 11:32:04.705 | INFO | +---------------------------------------------+
2021-01-30 11:32:04.705 | INFO | |                    START                    |
2021-01-30 11:32:04.705 | INFO | +---------------------------------------------+
2021-01-30 11:32:04.706 | INFO | [Server] cn
2021-01-30 11:32:05.816 | INFO | [Command] Daily
2021-01-30 11:32:05.816 | INFO | <<< DEVICE >>>
2021-01-30 11:32:05.816 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
2021-01-30 11:32:05.886 | INFO | already connected to 127.0.0.1:5555
2021-01-30 11:32:08.070 | INFO | [DailyRecord_exercise] Record time: 2021-01-30 11:04:16
2021-01-30 11:32:08.070 | INFO | [DailyRecord_exercise] Last update: 2021-01-30 09:00:00
2021-01-30 11:32:08.071 | INFO | [DailyRecord_daily] Record time: 2021-01-29 10:21:41
2021-01-30 11:32:08.071 | INFO | [DailyRecord_daily] Last update: 2021-01-30 09:00:00
2021-01-30 11:32:08.071 | INFO | <<< UI ENSURE >>>
2021-01-30 11:32:08.532 | INFO | [Screen_size] 1280x720
2021-01-30 11:32:08.541 | INFO | [UI] page_main
2021-01-30 11:32:08.541 | INFO | Goto page_fleet
2021-01-30 11:32:08.541 | INFO | [UI route] page_main - page_fleet
2021-01-30 11:32:08.541 | INFO | <<< UI CLICK >>>
2021-01-30 11:32:08.966 | INFO | Click ( 828,  391) @ MAIN_GOTO_FLEET
2021-01-30 11:32:10.111 | INFO | Multiple daily fleets are set, change equipment only for the first one. fleet: [4, 3, 3, 3, 0]
2021-01-30 11:32:10.111 | INFO | <<< UI ENSURE INDEX >>>
2021-01-30 11:32:10.458 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
2021-01-30 11:32:10.495 | INFO | [OCR_FLEET_INDEX 0.050s] 1
2021-01-30 11:32:10.495 | INFO | [Index] 1
2021-01-30 11:32:10.495 | INFO | Click (1242,  339) @ FLEET_NEXT
2021-01-30 11:32:10.779 | INFO | Click (1245,  340) @ FLEET_NEXT
2021-01-30 11:32:11.058 | INFO | Click (1240,  334) @ FLEET_NEXT
2021-01-30 11:32:11.745 | INFO | [OCR_FLEET_INDEX 0.008s] 4
2021-01-30 11:32:11.745 | INFO | [Index] 4
2021-01-30 11:32:12.417 | INFO | <<< EQUIPMENT TAKE ON >>>
2021-01-30 11:32:12.417 | INFO | Click ( 511,  482) @ FLEET_ENTER, 1.647
2021-01-30 11:32:14.710 | INFO | Click (1226,  165) @ EQUIPMENT_OPEN
2021-01-30 11:32:15.482 | INFO | Click (1229,  383) @ EQUIP_2
2021-01-30 11:32:20.319 | INFO | Swipe ( 517,  322) -> ( 257,  332), 0.111
2021-01-30 11:32:21.364 | INFO | New ship detected on swipe
2021-01-30 11:32:21.665 | INFO | Click (1218,  146) @ EQUIPMENT_OPEN
2021-01-30 11:32:22.386 | INFO | Click (1251,  284) @ EQUIP_1
2021-01-30 11:32:23.460 | INFO | <<< UI CLICK >>>
2021-01-30 11:32:23.802 | INFO | Click (  46,   53) @ BACK_ARROW
2021-01-30 11:32:26.177 | INFO | <<< UI ENSURE >>>
2021-01-30 11:32:26.519 | INFO | [UI] page_fleet
2021-01-30 11:32:26.519 | INFO | Goto page_daily
2021-01-30 11:32:26.519 | INFO | [UI route] page_fleet - page_main - page_campaign_menu - page_daily
2021-01-30 11:32:26.519 | INFO | <<< UI CLICK >>>
2021-01-30 11:32:26.882 | INFO | Click (1237,   36) @ GOTO_MAIN
2021-01-30 11:32:28.879 | INFO | <<< UI CLICK >>>
2021-01-30 11:32:28.882 | INFO | Click (1052,  317) @ MAIN_GOTO_CAMPAIGN
2021-01-30 11:32:30.118 | INFO | <<< UI CLICK >>>
2021-01-30 11:32:30.130 | INFO | Click ( 739,  616) @ CAMPAIGN_MENU_GOTO_DAILY
2021-01-30 11:32:31.900 | INFO | Checked_list: [0]
2021-01-30 11:32:31.900 | INFO | [Daily_1] active
2021-01-30 11:32:31.911 | INFO | [OCR_REMAIN 0.012s] 3
2021-01-30 11:32:31.912 | INFO | <<< DAILY 1 >>>
2021-01-30 11:32:31.912 | INFO | [Fleet] 3
2021-01-30 11:32:31.912 | INFO | <<< UI CLICK >>>
2021-01-30 11:32:32.280 | INFO | Click ( 681,  453) @ DAILY_ENTER
2021-01-30 11:32:33.341 | INFO | <<< COUNT 1 >>>
2021-01-30 11:32:33.341 | INFO | <<< UI CLICK >>>
2021-01-30 11:32:33.639 | INFO | Click ( 605,  370) @ DAILY_MISSION_2
2021-01-30 11:32:35.409 | INFO | <<< UI ENSURE INDEX >>>
2021-01-30 11:32:35.421 | INFO | [OCR_DAILY_FLEET_INDEX 0.012s] 3
2021-01-30 11:32:35.421 | INFO | [Index] 3
2021-01-30 11:32:36.093 | INFO | Combat preparation.
2021-01-30 11:32:36.093 | INFO | [Automation] ON
2021-01-30 11:32:36.106 | INFO | Click (1148,  642) @ BATTLE_PREPARATION
2021-01-30 11:32:36.944 | INFO | [Automation] ON
2021-01-30 11:32:44.545 | INFO | Combat execute
2021-01-30 11:32:44.546 | INFO | Screenshot interval set to 1.0s
2021-01-30 11:32:50.561 | INFO | Combat auto check timer reached

**Comment by LmeSzinc** [comment]
你设置的 `4, 3, 3, 3`, 意思是 商船护送用 4 队, 海域突进用 3 队, 斩首行动用 3 队, 战术研修用 3 队
快速换装那里只有一个空, 所以只能对第一支设定的队伍 (也就是 4 队) 更换装备, 不能换多个队伍的.

在每日任务中, 有 4 种每日需要设定, 每支队伍又有 6 个快速换装需要设置. 没有必要将问题复杂化, 所以:
- 要么只用一支队伍, 使用快速换装
- 要么对不同每日使用不同队伍, 不使用快速换装
