### ISSUE TITLE
自动化安装出错 _pickle.UnpicklingError: invalid load key, '\x00'.

### ISSUE THREAD

**Issue by kaoleer** [LmeSzinc/AzurLaneAutoScript#3357]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

自动化安装到kill  alas.exe 显示pickle模块错误

### 如何复现

点击自动展开程序
弹出错误

### 相关 Logs

```Text
"F:\AzurLaneAutoScript
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/uiautomator2/init.py minicap_urls no need to patch
./toolkit/Lib/site-packages/uiautomator2/init.py appdir already patched
./toolkit/Lib/site-packages/adbutils/mixin.py apkutils2 no need to patch
==================== SHOW DEPLOY CONFIG ====================
Repository: git://git.lyoko.io/AzurLaneAutoScript
PypiMirror: https://pypi.douban.com/simple/
Language: zh-CN
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
[CurrentCommit] a9719b1d023bf9102c7ddbd232fdc18bab76322c
Fetch url: https://vip.123pan.cn/1818706573/pack/LmeSzinc_AzurLaneAutoScript_master/latest.json
[LatestCommit] a9719b1d023bf9102c7ddbd232fdc18bab76322c
Already up to date
Execute: ['F:/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe', 'reset', '--hard', 'origin/master']
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
==================== KILL ALAS.EXE ====================
Traceback (most recent call last):
  File "F:\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "F:\AzurLaneAutoScript\deploy\installer.py", line 17, in install
    self.alas_kill()
  File "F:\AzurLaneAutoScript\deploy\alas.py", line 63, in alas_kill
    self.kill_by_name('alas.exe')
  File "F:\AzurLaneAutoScript\deploy\alas.py", line 57, in kill_by_name
    for row in self.iter_process_by_name(name):
  File "F:\AzurLaneAutoScript\deploy\alas.py", line 27, in iter_process_by_name
    from win32com.client import GetObject
  File "F:\AzurLaneAutoScript\toolkit\lib\site-packages\win32com\client\__init__.py", line 11, in <module>
    from . import gencache
  File "F:\AzurLaneAutoScript\toolkit\lib\site-packages\win32com\client\gencache.py", line 655, in <module>
    __init__()
  File "F:\AzurLaneAutoScript\toolkit\lib\site-packages\win32com\client\gencache.py", line 57, in __init__
    _LoadDicts()
  File "F:\AzurLaneAutoScript\toolkit\lib\site-packages\win32com\client\gencache.py", line 110, in _LoadDicts
    version = p.load()
_pickle.UnpicklingError: invalid load key, '\x00'.
```

### 截图

![捕获](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/97716191/e58e81fd-3289-4e1b-9885-7de590a2c35f)

**Comment by kaoleer** [comment]
![捕获](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/97716191/e14ab732-201d-464d-84a7-efa536dc9383)

**Comment by LmeSzinc** [comment]
#2382

**Comment by kaoleer** [comment]
感谢
