### ISSUE TITLE
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

### ISSUE THREAD

**Issue by Zhenye-Na** [LmeSzinc/AzurLaneAutoScript#3371]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

```
Devices: []
==================== UIAUTOMATOR2 INIT ====================
Traceback (most recent call last):
  File "C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\95183\Downloads\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "C:\Users\95183\Downloads\AzurLaneAutoScript\deploy\installer.py", line 20, in install
    self.adb_install()
  File "C:\Users\95183\Downloads\AzurLaneAutoScript\deploy\adb.py", line 56, in adb_install
    for device in adbutils.adb.iter_device():
  File "C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 443, in iter_device
    with self._connect() as c:
  File "C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 189, in _connect
    _conn = _AdbStreamConnection(self.__host, self.__port)
  File "C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 88, in __init__
    self.__conn = self._safe_connect()
  File "C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 103, in _safe_connect
    return self._create_socket()
  File "C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 95, in _create_socket
    s.connect((adb_host, adb_port))
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

**Comment by LmeSzinc** [comment]
打开 console.bat 执行：
```
netstat -ano | findstr "5037"
```
找到占用 5037 端口的程序 PID，杀掉它

**Comment by Zhenye-Na** [comment]
> 打开 console.bat 执行：
> 
> ```
> netstat -ano | findstr "5037"
> ```
>
> 找到占用 5037 端口的程序 PID，杀掉它


```
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Task adb.exe not found
taskkill /f /im nox_adb.exe >nul 2>nul
Task nox_adb.exe not found
taskkill /f /im adb_server.exe >nul 2>nul
Task adb_server.exe not found
taskkill /f /im HD-Adb.exe >nul 2>nul
Task HD-Adb.exe not found
Emulator MEmu found, instances: ['127.0.0.1:21503']
Replacing C:\Softwares\Microvirt\MEmu\adb.exe
C:/Users/95183/Downloads/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe is same as C:\Softwares\Microvirt\MEmu\adb.exe, skip
C:/Users/95183/Downloads/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
Devices: []
C:/Users/95183/Downloads/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:5037
* daemon not running; starting now at tcp:5037
connected to 127.0.0.1:7555
could not read ok from ADB Server
* failed to start daemon
adb.exe: failed to check server version: cannot connect to daemo
```

好像 adb 没有正确运行, 会是系统或者模拟器的问题吗?

11月使用是正常的, 中间有一段时间没有使用过

**Comment by Zhenye-Na** [comment]
```
netstat -ano | findstr "5037"
```

找到的是 `adb.exe`

**Comment by Zhenye-Na** [comment]
Alas 的 log

```
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     20:27:10.276 │ Start scheduler loop: alas                                 
INFO     20:27:10.278 │ [Server] cn                                                
INFO     20:27:10.293 │ Bind task {'General', 'Alas'}                              
INFO     20:27:10.724 │ Server "XXX" is available.                              
INFO     20:27:10.728 │ Pending tasks: ['Restart', 'Commission', 'Tactical',       
         'Research', 'Exercise', 'Dorm', 'Meowfficer', 'Guild', 'Reward',          
         'Minigame', 'OpsiExplore', 'OpsiAshBeacon', 'OpsiDaily', 'OpsiShop',      
         'OpsiVoucher', 'OpsiAbyssal', 'OpsiStronghold', 'OpsiObscure', 'Hard',    
         'OpsiAshAssist', 'OpsiMonthBoss', 'Event']                                
INFO     20:27:10.729 │ [Task] Restart (Enable, 2020-01-01 00:00:00)               
INFO     20:27:10.730 │ Bind task {'Restart', 'General', 'Alas'}                   
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     20:27:12.154 │ DEVICE                                                     
INFO     20:27:12.155 │ [IS_ON_PHONE_CLOUD] False                                  
INFO     20:27:12.157 │ [AdbBinary] C:\Users\95183\Downloads\AzurLaneAutoScript\too
         lkit\Lib\site-packages\adbutils\binaries\adb.exe                          
INFO     20:27:12.159 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     20:27:12.160 │ <<< DETECT DEVICE >>>                                      
INFO     20:27:12.162 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     20:27:12.165 │ No available devices                                       
ERROR    20:27:12.168 │ OSError: [WinError 10048] Only one usage of each socket    
         address (protocol/network address/port) is normally permitted             
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\module\device\connection.p │
         │ y:38 in retry_wrapper                                                  │
         │                                                                        │
         │    36 │   │   │   │   │   retry_sleep(_)                               │
         │    37 │   │   │   │   │   init()                                       │
         │ ❱  38 │   │   │   │   return func(self, *args, **kwargs)               │
         │    39 │   │   │   # Can't handle                                       │
         │    40 │   │   │   except RequestHumanTakeover:                         │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │      _ = 0                                                         │ │
         │ │   args = ()                                                        │ │
         │ │      e = OSError(10048, 'Only one usage of each socket address     │ │
         │ │          (protocol/network address/port) is normally permitted',   │ │
         │ │          None, 10048, None)                                        │ │
         │ │   func = <function Connection.list_device at 0x000001827FC15828>   │ │
         │ │   init = None                                                      │ │
         │ │ kwargs = {}                                                        │ │
         │ │   self = <module.device.device.Device object at                    │ │
         │ │          0x000001823B71B188>                                       │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\module\device\connection.p │
         │ y:725 in list_device                                                   │
         │                                                                        │
         │   723 │   │   devices = []                                             │
         │   724 │   │   try:                                                     │
         │ ❱ 725 │   │   │   with self.adb_client._connect() as c:                │
         │   726 │   │   │   │   c.send_command("host:devices")                   │
         │   727 │   │   │   │   c.check_okay()                                   │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ devices = []                                                       │ │
         │ │    self = <module.device.device.Device object at                   │ │
         │ │           0x000001823B71B188>                                      │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\ │
         │ adbutils\__init__.py:189 in _connect                                   │
         │                                                                        │
         │   187 │                                                                │
         │   188 │   def _connect(self, timeout: float = None) -> _AdbStreamConne │
         │ ❱ 189 │   │   _conn = _AdbStreamConnection(self.__host, self.__port)   │
         │   190 │   │   if timeout:                                              │
         │   191 │   │   │   _conn.conn.settimeout(timeout)                       │
         │                                                                        │
         │ ╭────────────────────────── locals ───────────────────────────╮        │
         │ │    self = <adbutils.AdbClient object at 0x000001827F998C08> │        │
         │ │ timeout = None                                              │        │
         │ ╰─────────────────────────────────────────────────────────────╯        │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\ │
         │ adbutils\__init__.py:88 in __init__                                    │
         │                                                                        │
         │    86 │   │   self.__host = host                                       │
         │    87 │   │   self.__port = port                                       │
         │ ❱  88 │   │   self.__conn = self._safe_connect()                       │
         │    89 │                                                                │
         │    90 │   def _create_socket(self):                                    │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ host = '127.0.0.1'                                                 │ │
         │ │ port = 5037                                                        │ │
         │ │ self = <adbutils._AdbStreamConnection object at                    │ │
         │ │        0x000001827F99E848>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\ │
         │ adbutils\__init__.py:103 in _safe_connect                              │
         │                                                                        │
         │   101 │   def _safe_connect(self):                                     │
         │   102 │   │   try:                                                     │
         │ ❱ 103 │   │   │   return self._create_socket()                         │
         │   104 │   │   except ConnectionRefusedError:                           │
         │   105 │   │   │   subprocess.run([adb_path(), "start-server"], timeout │
         │       enough for adb start                                             │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ self = <adbutils._AdbStreamConnection object at                    │ │
         │ │        0x000001827F99E848>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\ │
         │ adbutils\__init__.py:95 in _create_socket                              │
         │                                                                        │
         │    93 │   │   s = socket.socket()                                      │
         │    94 │   │   try:                                                     │
         │ ❱  95 │   │   │   s.connect((adb_host, adb_port))                      │
         │    96 │   │   │   return s                                             │
         │    97 │   │   except:                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ adb_host = '127.0.0.1'                                             │ │
         │ │ adb_port = 5037                                                    │ │
         │ │        s = <socket.socket [closed] fd=-1,                          │ │
         │ │            family=AddressFamily.AF_INET,                           │ │
         │ │            type=SocketKind.SOCK_STREAM, proto=0>                   │ │
         │ │     self = <adbutils._AdbStreamConnection object at                │ │
         │ │            0x000001827F99E848>                                     │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         OSError: [WinError 10048] Only one usage of each socket address           
         (protocol/network address/port) is normally permitted                     
ERROR    20:27:12.368 │ OSError: [WinError 10048] Only one usage of each socket    
         address (protocol/network address/port) is normally permitted             
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\alas.py:46 in device       │
         │                                                                        │
         │    44 │   │   try:                                                     │
         │    45 │   │   │   from module.device.device import Device              │
         │ ❱  46 │   │   │   device = Device(config=self.config)                  │
         │    47 │   │   │   return device                                        │
         │    48 │   │   except RequestHumanTakeover:                             │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ Device = <class 'module.device.device.Device'>                     │ │
         │ │      e = OSError(10048, 'Only one usage of each socket address     │ │
         │ │          (protocol/network address/port) is normally permitted',   │ │
         │ │          None, 10048, None)                                        │ │
         │ │   self = <alas.AzurLaneAutoScript object at 0x000001823BC18D88>    │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\module\device\device.py:71 │
         │ in __init__                                                            │
         │                                                                        │
         │    69 │                                                                │
         │    70 │   def __init__(self, *args, **kwargs):                         │
         │ ❱  71 │   │   super().__init__(*args, **kwargs)                        │
         │    72 │   │   self.screenshot_interval_set()                           │
         │    73                                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ __class__ = <class 'module.device.device.Device'>                  │ │
         │ │      args = ()                                                     │ │
         │ │    kwargs = {                                                      │ │
         │ │             │   'config': <module.config.config.AzurLaneConfig     │ │
         │ │             object at 0x000001823B71B208>                          │ │
         │ │             }                                                      │ │
         │ │      self = <module.device.device.Device object at                 │ │
         │ │             0x000001823B71B188>                                    │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\module\device\connection.p │
         │ y:99 in __init__                                                       │
         │                                                                        │
         │    97 │   │                                                            │
         │    98 │   │   # Connect                                                │
         │ ❱  99 │   │   self.adb_connect(self.serial)                            │
         │   100 │   │   logger.attr('AdbDevice', self.adb)                       │
         │   101                                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ __class__ = <class 'module.device.connection.Connection'>          │ │
         │ │    config = <module.config.config.AzurLaneConfig object at         │ │
         │ │             0x000001823B71B208>                                    │ │
         │ │      self = <module.device.device.Device object at                 │ │
         │ │             0x000001823B71B188>                                    │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\module\device\emulator.py: │
         │ 215 in adb_connect                                                     │
         │                                                                        │
         │   213 │   def adb_connect(self, serial):                               │
         │   214 │   │   try:                                                     │
         │ ❱ 215 │   │   │   return super(EmulatorManager, self).adb_connect(seri │
         │   216 │   │   except EmulatorNotRunningError:                          │
         │   217 │   │   │   raise RequestHumanTakeover                           │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ __class__ = <class 'module.device.emulator.EmulatorManager'>       │ │
         │ │      self = <module.device.device.Device object at                 │ │
         │ │             0x000001823B71B188>                                    │ │
         │ │    serial = '127.0.0.1:16384'                                      │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\module\base\decorator.py:7 │
         │ 0 in wrapper                                                           │
         │                                                                        │
         │    68 │   │   │   │   │   │   continue                                 │
         │    69 │   │   │   │   │                                                │
         │ ❱  70 │   │   │   │   │   return record['func'](self, *args, **kwargs) │
         │    71 │   │   │   │                                                    │
         │    72 │   │   │   │   logger.warning(f'No option fits for {name}, usin │
         │       func.')                                                          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │   args = ('127.0.0.1:16384',)                                      │ │
         │ │    cls = <class 'module.base.decorator.Config'>                    │ │
         │ │   flag = [True]                                                    │ │
         │ │   func = <function Connection.adb_connect at 0x000001827FC150D8>   │ │
         │ │ kwargs = {}                                                        │ │
         │ │ logger = <Logger alas (INFO)>                                      │ │
         │ │   name = 'adb_connect'                                             │ │
         │ │ record = {                                                         │ │
         │ │          │   'options': {'DEVICE_OVER_HTTP': False},               │ │
         │ │          │   'func': <function Connection.adb_connect at           │ │
         │ │          0x000001827FC10F78>                                       │ │
         │ │          }                                                         │ │
         │ │   self = <module.device.device.Device object at                    │ │
         │ │          0x000001823B71B188>                                       │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\module\device\connection.p │
         │ y:554 in adb_connect                                                   │
         │                                                                        │
         │   552 │   │   # Try to connect                                         │
         │   553 │   │   for _ in range(3):                                       │
         │ ❱ 554 │   │   │   msg = self.adb_client.connect(serial)                │
         │   555 │   │   │   logger.info(msg)                                     │
         │   556 │   │   │   if 'connected' in msg:                               │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │      _ = 0                                                         │ │
         │ │   self = <module.device.device.Device object at                    │ │
         │ │          0x000001823B71B188>                                       │ │
         │ │ serial = '127.0.0.1:16384'                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\ │
         │ adbutils\__init__.py:263 in connect                                    │
         │                                                                        │
         │   261 │   │   │   - "failed to connect to '1.2.3.4:4567': Operation ti │
         │   262 │   │   """                                                      │
         │ ❱ 263 │   │   with self._connect(timeout=timeout) as c:                │
         │   264 │   │   │   c.send_command("host:connect:" + addr)               │
         │   265 │   │   │   c.check_okay()                                       │
         │                                                                        │
         │ ╭────────────────────────── locals ───────────────────────────╮        │
         │ │    addr = '127.0.0.1:16384'                                 │        │
         │ │    self = <adbutils.AdbClient object at 0x000001827F998C08> │        │
         │ │ timeout = None                                              │        │
         │ ╰─────────────────────────────────────────────────────────────╯        │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\ │
         │ adbutils\__init__.py:189 in _connect                                   │
         │                                                                        │
         │   187 │                                                                │
         │   188 │   def _connect(self, timeout: float = None) -> _AdbStreamConne │
         │ ❱ 189 │   │   _conn = _AdbStreamConnection(self.__host, self.__port)   │
         │   190 │   │   if timeout:                                              │
         │   191 │   │   │   _conn.conn.settimeout(timeout)                       │
         │                                                                        │
         │ ╭────────────────────────── locals ───────────────────────────╮        │
         │ │    self = <adbutils.AdbClient object at 0x000001827F998C08> │        │
         │ │ timeout = None                                              │        │
         │ ╰─────────────────────────────────────────────────────────────╯        │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\ │
         │ adbutils\__init__.py:88 in __init__                                    │
         │                                                                        │
         │    86 │   │   self.__host = host                                       │
         │    87 │   │   self.__port = port                                       │
         │ ❱  88 │   │   self.__conn = self._safe_connect()                       │
         │    89 │                                                                │
         │    90 │   def _create_socket(self):                                    │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ host = '127.0.0.1'                                                 │ │
         │ │ port = 5037                                                        │ │
         │ │ self = <adbutils._AdbStreamConnection object at                    │ │
         │ │        0x000001827FD74648>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\ │
         │ adbutils\__init__.py:103 in _safe_connect                              │
         │                                                                        │
         │   101 │   def _safe_connect(self):                                     │
         │   102 │   │   try:                                                     │
         │ ❱ 103 │   │   │   return self._create_socket()                         │
         │   104 │   │   except ConnectionRefusedError:                           │
         │   105 │   │   │   subprocess.run([adb_path(), "start-server"], timeout │
         │       enough for adb start                                             │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ self = <adbutils._AdbStreamConnection object at                    │ │
         │ │        0x000001827FD74648>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\Users\95183\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\ │
         │ adbutils\__init__.py:95 in _create_socket                              │
         │                                                                        │
         │    93 │   │   s = socket.socket()                                      │
         │    94 │   │   try:                                                     │
         │ ❱  95 │   │   │   s.connect((adb_host, adb_port))                      │
         │    96 │   │   │   return s                                             │
         │    97 │   │   except:                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ adb_host = '127.0.0.1'                                             │ │
         │ │ adb_port = 5037                                                    │ │
         │ │        s = <socket.socket [closed] fd=-1,                          │ │
         │ │            family=AddressFamily.AF_INET,                           │ │
         │ │            type=SocketKind.SOCK_STREAM, proto=0>                   │ │
         │ │     self = <adbutils._AdbStreamConnection object at                │ │
         │ │            0x000001827FD74648>                                     │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         OSError: [WinError 10048] Only one usage of each socket address           
         (protocol/network address/port) is normally permitted                     

```

**Comment by Zhenye-Na** [comment]
今天自动更新后使用正常了!
