### ISSUE TITLE
ALAS启动进入update然后发生错误

### ISSUE THREAD

**Issue by gao199607** [LmeSzinc/AzurLaneAutoScript#3412]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [X] I am using the latest version of Alas

### Describe the bug

今天出现这个问题，重新安装以及重启多次没有效果

### Relevant log output

```Text
"C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/uiautomator2/init.py minicap_urls no need to patch
./toolkit/Lib/site-packages/uiautomator2/init.py appdir already patched
./toolkit/Lib/site-packages/adbutils/mixin.py apkutils2 no need to patch
==================== SHOW DEPLOY CONFIG ====================
Repository: git://git.lyoko.io/AzurLaneAutoScript
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
[CurrentCommit] 944190c46e1adccaa96c516a087c3e9c0afeb02e
Fetch url: https://vip.123pan.cn/1818706573/pack/LmeSzinc_AzurLaneAutoScript_master/latest.json
[LatestCommit] 944190c46e1adccaa96c516a087c3e9c0afeb02e
Already up to date
Execute: ['C:/Users/Administrator/Downloads/ALAS新/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe', 'reset', '--hard', 'origin/master']
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
==================== KILL ALAS.EXE ====================
==================== KILL PYTHON.EXE ====================
+-----------------------------------------------------------+
|                    UPDATE DEPENDENCIES                    |
+-----------------------------------------------------------+
==================== CHECK PYTHON ====================
"C:/Users/Administrator/Downloads/ALAS新/AzurLaneAutoScript/toolkit/python.exe" --version
Python 3.7.6
[ success ]
==================== UPDATE DEPENDENCIES ====================
"C:/Users/Administrator/Downloads/ALAS新/AzurLaneAutoScript/toolkit/python.exe" -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --disable-pip-version-check
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: adbutils==0.11.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 8)) (0.11.0)
Requirement already satisfied: aiofiles==0.7.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 9)) (0.7.0)
Requirement already satisfied: alas-webapp==0.3.7 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 10)) (0.3.7)
Requirement already satisfied: anyio==1.3.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 11)) (1.3.1)
Requirement already satisfied: apkutils2==1.0.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 12)) (1.0.0)
Requirement already satisfied: asgiref==3.4.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 13)) (3.4.1)
Requirement already satisfied: async-generator==1.10 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 14)) (1.10)
Requirement already satisfied: av==10.0.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 15)) (10.0.0)
Requirement already satisfied: cached-property==1.5.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 16)) (1.5.2)
Requirement already satisfied: certifi==2021.5.30 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 17)) (2021.5.30)
Requirement already satisfied: cffi==1.15.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 18)) (1.15.0)
Requirement already satisfied: chardet==3.0.4 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 19)) (3.0.4)
Requirement already satisfied: cigam==0.0.3 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 20)) (0.0.3)
Requirement already satisfied: click==8.0.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 21)) (8.0.1)
Requirement already satisfied: cnocr==1.2.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 22)) (1.2.2)
Requirement already satisfied: colorama==0.4.5 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 23)) (0.4.5)
Requirement already satisfied: commonmark==0.9.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 24)) (0.9.1)
Requirement already satisfied: cycler==0.10.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 25)) (0.10.0)
Requirement already satisfied: decorator==5.1.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 26)) (5.1.0)
Requirement already satisfied: deprecated==1.2.13 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 27)) (1.2.13)
Requirement already satisfied: deprecation==2.1.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 28)) (2.1.0)
Requirement already satisfied: filelock==3.3.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 29)) (3.3.0)
Requirement already satisfied: future==0.18.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 30)) (0.18.2)
Requirement already satisfied: gevent==21.12.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 31)) (21.12.0)
Requirement already satisfied: gluoncv==0.6.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 32)) (0.6.0)
Requirement already satisfied: graphviz==0.8.4 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 33)) (0.8.4)
Requirement already satisfied: greenlet==1.1.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 34)) (1.1.2)
Requirement already satisfied: h11==0.12.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 35)) (0.12.0)
Requirement already satisfied: httptools==0.4.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 36)) (0.4.0)
Requirement already satisfied: idna==2.6 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 37)) (2.6)
Requirement already satisfied: imageio==2.27.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 38)) (2.27.0)
Requirement already satisfied: importlib-metadata==4.8.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 39)) (4.8.1)
Requirement already satisfied: inflection==0.5.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 40)) (0.5.1)
Requirement already satisfied: jellyfish==0.11.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 41)) (0.11.2)
Requirement already satisfied: kiwisolver==1.3.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 42)) (1.3.2)
Requirement already satisfied: logzero==1.7.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 43)) (1.7.0)
Requirement already satisfied: lxml==4.6.3 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 44)) (4.6.3)
Requirement already satisfied: lz4==3.1.3 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 45)) (3.1.3)
Requirement already satisfied: matplotlib==3.4.3 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 46)) (3.4.3)
Requirement already satisfied: msgpack==1.0.3 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 47)) (1.0.3)
Requirement already satisfied: mxnet==1.6.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 48)) (1.6.0)
Requirement already satisfied: numpy==1.16.6 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 49)) (1.16.6)
Requirement already satisfied: onepush==1.2.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 50)) (1.2.0)
Requirement already satisfied: opencv-python==4.5.3.56 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 51)) (4.5.3.56)
Requirement already satisfied: packaging==20.9 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 52)) (20.9)
Requirement already satisfied: pillow==8.3.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 53)) (8.3.2)
Requirement already satisfied: portalocker==2.3.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 54)) (2.3.2)
Requirement already satisfied: prettytable==2.2.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 55)) (2.2.1)
Requirement already satisfied: progress==1.6 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 56)) (1.6)
Requirement already satisfied: psutil==5.9.3 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 57)) (5.9.3)
Requirement already satisfied: py==1.10.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 58)) (1.10.0)
Requirement already satisfied: pycparser==2.21 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 59)) (2.21)
Requirement already satisfied: pydantic==1.10.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 60)) (1.10.2)
Requirement already satisfied: pyelftools==0.27 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 61)) (0.27)
Requirement already satisfied: pygments==2.12.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 62)) (2.12.0)
Requirement already satisfied: pyparsing==2.4.7 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 63)) (2.4.7)
Requirement already satisfied: pypresence==4.2.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 64)) (4.2.1)
Requirement already satisfied: python-dateutil==2.8.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 65)) (2.8.2)
Requirement already satisfied: python-dotenv==0.19.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 66)) (0.19.0)
Requirement already satisfied: pywebio==1.6.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 67)) (1.6.2)
Requirement already satisfied: pywin32==301 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 68)) (301)
Requirement already satisfied: pyyaml==5.4.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 69)) (5.4.1)
Requirement already satisfied: pyzmq==22.3.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 70)) (22.3.0)
Requirement already satisfied: requests==2.18.4 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 71)) (2.18.4)
Requirement already satisfied: retry==0.9.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 72)) (0.9.2)
Requirement already satisfied: retrying==1.3.3 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 73)) (1.3.3)
Requirement already satisfied: rich==11.2.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 74)) (11.2.0)
Requirement already satisfied: scipy==1.4.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 75)) (1.4.1)
Requirement already satisfied: six==1.16.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 76)) (1.16.0)
Requirement already satisfied: sniffio==1.2.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 77)) (1.2.0)
Requirement already satisfied: starlette==0.14.2 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 78)) (0.14.2)
Requirement already satisfied: tornado==6.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 79)) (6.1)
Requirement already satisfied: tqdm==4.62.3 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 80)) (4.62.3)
Requirement already satisfied: typing-extensions==4.3.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 81)) (4.3.0)
Requirement already satisfied: ua-parser==0.10.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 82)) (0.10.0)
Requirement already satisfied: uiautomator2==2.16.17 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 83)) (2.16.17)
Requirement already satisfied: uiautomator2cache==0.3.0.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 84)) (0.3.0.1)
Requirement already satisfied: urllib3==1.22 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 85)) (1.22)
Requirement already satisfied: user-agents==2.2.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 86)) (2.2.0)
Requirement already satisfied: uvicorn[standard]==0.17.6 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 87)) (0.17.6)
Requirement already satisfied: watchgod==0.7 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 88)) (0.7)
Requirement already satisfied: wcwidth==0.2.5 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 89)) (0.2.5)
Requirement already satisfied: websockets==10.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 90)) (10.0)
Requirement already satisfied: whichcraft==0.6.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 91)) (0.6.1)
Requirement already satisfied: wrapt==1.13.1 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 92)) (1.13.1)
Requirement already satisfied: xmltodict==0.12.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 93)) (0.12.0)
Requirement already satisfied: zerorpc==0.6.3 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 94)) (0.6.3)
Requirement already satisfied: zipp==3.6.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 95)) (3.6.0)
Requirement already satisfied: zope.event==4.5.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 96)) (4.5.0)
Requirement already satisfied: zope.interface==5.4.0 in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 97)) (5.4.0)
Requirement already satisfied: setuptools in c:\users\administrator\downloads\alas新\azurlaneautoscript\toolkit\lib\site-packages (from gevent==21.12.0->-r requirements.txt (line 31)) (42.0.2)
[ success ]
+-------------------------------------------------------+
|                    UPDATE APP.ASAR                    |
+-------------------------------------------------------+
Old file: C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\toolkit\WebApp\resources\app.asar
New version: 0.3.7
New file: C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\toolkit\lib\site-packages\alas_webapp\app.asar
app.asar is already up to date
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Task adb.exe killed
taskkill /f /im nox_adb.exe >nul 2>nul
Task nox_adb.exe not found
taskkill /f /im adb_server.exe >nul 2>nul
Task adb_server.exe not found
taskkill /f /im HD-Adb.exe >nul 2>nul
Task HD-Adb.exe not found
Emulator Nox found, instances: ['127.0.0.1:62001', '127.0.0.1:62001', '127.0.0.1:62001', '127.0.0.1:62001', '127.0.0.1:62001']
Replacing E:\Program Files\Nox\bin\adb.exe
C:/Users/Administrator/Downloads/ALAS新/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe is same as E:\Program Files\Nox\bin\adb.exe, skip
Replacing E:\Program Files\Nox\bin\nox_adb.exe
C:/Users/Administrator/Downloads/ALAS新/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe is same as E:\Program Files\Nox\bin\nox_adb.exe, skip
C:/Users/Administrator/Downloads/ALAS新/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
Devices: ['HRBDFUN']
connected to 127.0.0.1:62001
already connected to 127.0.0.1:62001
already connected to 127.0.0.1:62001
C:/Users/Administrator/Downloads/ALAS新/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
already connected to 127.0.0.1:62001
already connected to 127.0.0.1:62001
Devices: ['HRBDFUN', '127.0.0.1:62001']
==================== UIAUTOMATOR2 INIT ====================
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\deploy\installer.py", line 20, in install
    self.adb_install()
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\deploy\adb.py", line 57, in adb_install
    initer = init.Initer(device, loglevel=logging.DEBUG)
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 146, in __init__
    self.sdk = d.getprop('ro.build.version.sdk')
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\mixin.py", line 322, in getprop
    return self._run(['getprop', prop]).strip()
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\mixin.py", line 28, in _run
    return self.shell(cmd)
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 578, in shell
    ret = self._client.shell(self._serial, cmdargs, stream=stream, timeout=timeout)
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 318, in shell
    c.check_okay()
  File "C:\Users\Administrator\Downloads\ALAS新\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 168, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: closed
```

**Comment by LmeSzinc** [comment]
移除设备 `HRBDFUN` （物理意义上的拔掉）

**Comment by gao199607** [comment]
拔出后已解决，这个USB是水冷显示屏的，如果要保留的话怎么解决呢

**Comment by gao199607** [comment]
刚开始是没有问题的，1.6号突然发生这个问题

**Comment by LmeSzinc** [comment]
关闭它的安卓调试功能 或者 在设备上允许你的电脑对它进行安卓调试
