### ISSUE TITLE
7-2打着打着出现程序错误

### ISSUE THREAD

**Issue by nh632343** [LmeSzinc/AzurLaneAutoScript#359]
[1613794951000.zip](https://github.com/nh632343/hello_world/blob/master/1613794951000.zip)

**Describe**
进入准备战斗界面有时会程序错误

2021-02-20 12:02:39.842 | ERROR | zero-size array to reduction operation minimum which has no identity
Traceback (most recent call last)
  File "D:\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "D:\AzurLaneAutoScript\alas.py", line 129, in main
    az.run(self.config.CAMPAIGN_NAME)
  File "D:\AzurLaneAutoScript\module\campaign\run.py", line 213, in run
    self.campaign.run()
  File "D:\AzurLaneAutoScript\module\campaign\campaign_base.py", line 125, in run
    self.execute_a_battle()
  File "D:\AzurLaneAutoScript\module\campaign\campaign_base.py", line 95, in execute_a_battle
    result = self.battle_function()
  File "D:\AzurLaneAutoScript\module\base\decorator.py", line 63, in wrapper
    return record['func'](self, *args, **kwargs)
  File "D:\AzurLaneAutoScript\module\campaign\campaign_base.py", line 85, in battle_function
    result = func()
  File "D:\AzurLaneAutoScript\campaign\campaign_main\campaign_7_2.py", line 71, in battle_0
    if self.clear_enemy(strongest=True):
  File "D:\AzurLaneAutoScript\module\map\map.py", line 191, in clear_enemy
    self.clear_chosen_enemy(grids[0])
  File "D:\AzurLaneAutoScript\module\map\map.py", line 20, in clear_chosen_enemy
    self.goto(grid, expected=expected)
  File "D:\AzurLaneAutoScript\module\map\fleet.py", line 330, in goto
    self._goto(node, expected=expected if node == nodes[-1] else '')
  File "D:\AzurLaneAutoScript\module\map\fleet.py", line 227, in _goto
    self.combat(expected_end=self._expected_combat_end(expected), fleet_index=self.fleet_current_index)
  File "D:\AzurLaneAutoScript\module\combat\combat.py", line 390, in combat
    balance_hp=balance_hp, emotion_reduce=emotion_reduce, auto=auto_mode, fleet_index=fleet_index)
  File "D:\AzurLaneAutoScript\module\combat\combat.py", line 116, in combat_preparation
    if balance_hp and self.handle_emergency_repair_use():
  File "D:\AzurLaneAutoScript\module\combat\combat.py", line 179, in handle_emergency_repair_use
    if np.min(np.array(self.hp)[np.array(self.hp) > 0.001]) < self.config.EMERGENCY_REPAIR_SINGLE_THRESHOLD \
  File "D:\AzurLaneAutoScript\myvenv\lib\site-packages\numpy\core\fromnumeric.py", line 2618, in amin
    initial=initial)
  File "D:\AzurLaneAutoScript\myvenv\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

**Comment by LmeSzinc** [comment]
更新一下
你 log 里血量读不出来, 这个问题一个月前就修过了 9a1b2d8383d1022af02d9a05a98abb75f6a64823
```
2021-02-20 12:00:55.459 | WARNING | HP invalid: [0.0, 0.0, 0.0]
2021-02-20 12:02:13.525 | INFO | [HP] ____ ____ ____ ____ ____ ____
```

**Comment by nh632343** [comment]
OK
