### ISSUE TITLE
3-4寻敌时读取完地图数据后出现问题

### ISSUE THREAD

**Issue by he110W0r1d-shell** [LmeSzinc/AzurLaneAutoScript#369]
脚本在移动视角获取完地图数据后出现如下问题

2021-02-26 23:41:52.344 | ERROR | ()
Traceback (most recent call last):
  File "D:\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "D:\AzurLaneAutoScript\alas.py", line 137, in main
    az.run(self.config.CAMPAIGN_NAME)
  File "D:\AzurLaneAutoScript\module\campaign\run.py", line 229, in run
    self.campaign.run()
  File "D:\AzurLaneAutoScript\module\campaign\campaign_base.py", line 139, in run
    self.execute_a_battle()
  File "D:\AzurLaneAutoScript\module\campaign\campaign_base.py", line 96, in execute_a_battle
    result = self.battle_function()
  File "D:\AzurLaneAutoScript\module\base\decorator.py", line 63, in wrapper
    return record['func'](self, *args, **kwargs)
  File "D:\AzurLaneAutoScript\module\campaign\campaign_base.py", line 86, in battle_function
    result = func()
  File "D:\AzurLaneAutoScript\campaign\campaign_main\campaign_3_4.py", line 59, in battle_0
    self.fleet_2_push_forward()
  File "D:\AzurLaneAutoScript\module\map\map.py", line 518, in fleet_2_push_forward
    fleets = SelectedGrids([self.map[self.fleet_1_location], self.map[self.fleet_2_location]])
  File "D:\AzurLaneAutoScript\module\map\map_base.py", line 44, in __getitem__
    return self.grids[tuple(item)]
KeyError: ()
2021-02-26 23:41:52.349 | INFO | Saving error: ./log/error/1614354112349

在这之前我曾手动进行过一次操作，就是在结算界面手动点了确定，因为它一直卡在那里不动并警告了wait too long

**Comment by LmeSzinc** [comment]
需要完整 log

**Comment by he110W0r1d-shell** [comment]
> 需要完整 log

不好意思，脚本没有问题，是我的操作问题。我把模拟器界面缩小到底部任务栏了，所以才会出现卡着不动的情况。顺便想问一下，可以做到让游戏在后台运行的情况下使用脚本吗？

**Comment by LmeSzinc** [comment]
> > 需要完整 log
> 
> 不好意思，脚本没有问题，是我的操作问题。我把模拟器界面缩小到底部任务栏了，所以才会出现卡着不动的情况。顺便想问一下，可以做到让游戏在后台运行的情况下使用脚本吗？

最小化模拟器是可以正常运行的

**Comment by he110W0r1d-shell** [comment]
> > > 需要完整 log
> > 
> > 
> > 不好意思，脚本没有问题，是我的操作问题。我把模拟器界面缩小到底部任务栏了，所以才会出现卡着不动的情况。顺便想问一下，可以做到让游戏在后台运行的情况下使用脚本吗？
> 
> 最小化模拟器是可以正常运行的

谢谢解答，问题已经解决了。

**Comment by he110W0r1d-shell** [comment]
我是伞兵
