### ISSUE TITLE
每日演习error

### ISSUE THREAD

**Issue by HarutoEip** [LmeSzinc/AzurLaneAutoScript#375]
**Describe the bug**
演习结束之后会出现停下

**To Reproduce**
每次跑到演习的时候会提示| ERROR | No module named 'notifypy'

**Screenshots**
![image](https://user-images.githubusercontent.com/74737586/110196099-30393780-7e7d-11eb-86fa-028ac1372b93.png)
![image](https://user-images.githubusercontent.com/74737586/110196128-62e33000-7e7d-11eb-9106-346c765c4334.png)
[](url)

**Log**
2021-03-06 12:41:08.271 | INFO | Click (  58,   39) @ BACK_ARROW
2021-03-06 12:41:09.007 | INFO | [Order] [2 3 1 0]
2021-03-06 12:41:09.007 | INFO | <<< OPPONENT: 2 >>>
2021-03-06 12:41:09.556 | INFO | Click ( 668,  222) @ OPPONENT_2_0
2021-03-06 12:41:10.819 | INFO | Click ( 674,  563) @ EXERCISE_PREPARATION
2021-03-06 12:41:12.183 | INFO | <<< TRY: 1 >>>
2021-03-06 12:41:12.183 | INFO | Combat preparation
2021-03-06 12:41:12.881 | INFO | Click (1168,  640) @ BATTLE_PREPARATION
2021-03-06 12:41:14.389 | INFO | Click (1149,  643) @ BATTLE_PREPARATION
2021-03-06 12:41:18.681 | INFO | Combat execute
2021-03-06 12:41:19.381 | INFO | [97% - 96%]
2021-03-06 12:41:24.832 | INFO | [97% - 72%]
2021-03-06 12:41:30.150 | INFO | [97% - 15%]
2021-03-06 12:41:35.304 | INFO | [97% - 00%]
2021-03-06 12:41:39.946 | INFO | Click (1034,  670) @ BATTLE_STATUS_S
2021-03-06 12:41:40.725 | INFO | Click (1035,  670) @ GET_ITEMS_1
2021-03-06 12:41:41.624 | INFO | Click (1013,  658) @ CLICK_SAFE_AREA
2021-03-06 12:41:42.363 | INFO | Click (1016,  658) @ CLICK_SAFE_AREA
2021-03-06 12:41:43.166 | INFO | Click (1018,  659) @ CLICK_SAFE_AREA
2021-03-06 12:41:43.831 | INFO | <<< COMBAT END >>>
2021-03-06 12:41:44.415 | INFO | [OCR_EXERCISE_REMAIN 0.015s] 0
2021-03-06 12:41:44.426 | ERROR | No module named 'notifypy'
Traceback (most recent call last):
  File "C:\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\AzurLaneAutoScript\alas.py", line 111, in reward
    self.reward_when_finished()
  File "C:\AzurLaneAutoScript\alas.py", line 88, in reward_when_finished
    az.reward_loop()
  File "C:\AzurLaneAutoScript\module\reward\reward.py", line 218, in reward_loop
    self.reward()
  File "C:\AzurLaneAutoScript\module\reward\reward.py", line 84, in reward
    count = self.daily_wrapper_run()
  File "C:\AzurLaneAutoScript\module\reward\reward.py", line 247, in daily_wrapper_run
    self.device.send_notification('Daily Exercises', 'Exercise daily finished.')
  File "C:\AzurLaneAutoScript\module\device\device.py", line 23, in send_notification
    from notifypy import Notify
ModuleNotFoundError: No module named 'notifypy'
2021-03-06 12:41:44.436 | INFO | Saving error: ./log/error/1615005704436

**Comment by whoamikyo** [comment]
rum `pip install notify-py`

**Comment by HarutoEip** [comment]
> run `pip install notify-py`
I just run it in Power shell. I guess this will work out fine.
BTW, u answer it so fast lol

**Comment by HarutoEip** [comment]
> run `pip install notify-py`
Thanks for the help!
