### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte

### ISSUE THREAD

**Issue by krmma-qyp** [LmeSzinc/AzurLaneAutoScript#3857]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

初次使用，下载了最新的0.4.6版本，但是无法启动脚本，连脚本UI界面都无法进入。搜索了issues有相似问题，但是他的是gbk编码错误，而我的是utf-8错误。

### 如何复现

按照安装教程启动Alas.exe就会出现这种情况，路径无特殊符号和中文名，以管理员模式启动。

### 预期行为

能正常运行使用。

### 相关 Logs

```Text
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Task adb.exe killed
taskkill /f /im nox_adb.exe >nul 2>nul
Task nox_adb.exe not found
taskkill /f /im adb_server.exe >nul 2>nul
Task adb_server.exe not found
taskkill /f /im HD-Adb.exe >nul 2>nul
Task HD-Adb.exe not found
Emulator Nox found, instances: ['127.0.0.1:62001']
Replacing D:\yeshen\Nox\bin\adb.exe
F:/ChromeDown/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe is same as D:\yeshen\Nox\bin\adb.exe, skip
Replacing D:\yeshen\Nox\bin\nox_adb.exe
F:/ChromeDown/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe is same as D:\yeshen\Nox\bin\nox_adb.exe, skip
F:/ChromeDown/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
Traceback (most recent call last):
  File "F:\ChromeDown\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\ChromeDown\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\ChromeDown\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "F:\ChromeDown\AzurLaneAutoScript\deploy\installer.py", line 20, in install
    self.adb_install()
  File "F:\ChromeDown\AzurLaneAutoScript\deploy\adb.py", line 36, in adb_install
    emulator.adb_replace()
  File "F:\ChromeDown\AzurLaneAutoScript\deploy\emulator.py", line 360, in adb_replace
    self.brute_force_connect()
  File "F:\ChromeDown\AzurLaneAutoScript\deploy\emulator.py", line 336, in brute_force_connect
    self.devices()
  File "F:\ChromeDown\AzurLaneAutoScript\deploy\emulator.py", line 281, in devices
    result = self._execute([self.adb_binary, 'devices']).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte
```

### 截图

![VFNL{L`_1C$SWMC9 0E_%@Q](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/58722679/a97a9791-393c-40a2-a698-757b8acef38b)

### 还有别的吗？

系统版本win10，模拟器使用夜神模拟器的安卓9

**Comment by Studentkjb** [comment]
同问我也是一样的问题用的mumu12

**Comment by LmeSzinc** [comment]
打开 console.bat 执行
```
adb devices
```
发结果

**Comment by krmma-qyp** [comment]
![捕获](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/58722679/ef3de600-25f9-4eb1-a1b6-beab72b2f884)
@LmeSzinc

**Comment by LmeSzinc** [comment]
删除这里两条注册表中的 Autorun
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1748#issuecomment-1287766368

**Comment by krmma-qyp** [comment]
解决了，谢谢
