### ISSUE TITLE
启动报错AdbError

### ISSUE THREAD

**Issue by Mamboing** [LmeSzinc/AzurLaneAutoScript#3875]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

Alas启动失败，感觉和电脑环境有关系但又不清楚是哪个影响的，换另一台电脑能够正常运行，在出现问题的电脑上，重新从github下载、以及从正常运行电脑上拷贝过来，也一直启动失败，具体报错如图，希望能帮忙看下哪里出现的问题谢谢，模拟器是MuMu12

### 如何复现

1. 点击Alas图标启动
2. 出现问题（没有跑出来GUI界面）

### 预期行为

出现GUI界面

### 相关 Logs

```Text
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Task adb.exe killed
taskkill /f /im nox_adb.exe >nul 2>nul
Task nox_adb.exe not found
taskkill /f /im adb_server.exe >nul 2>nul
Task adb_server.exe not found
taskkill /f /im HD-Adb.exe >nul 2>nul
Task HD-Adb.exe not found
D:/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:9595
* daemon started successfully
Devices: ['HRBDFUN']
D:/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
Devices: ['HRBDFUN']
==================== UIAUTOMATOR2 INIT ====================
Init device AdbDevice(serial=HRBDFUN)
Traceback (most recent call last):
  File "D:\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "D:\AzurLaneAutoScript\deploy\installer.py", line 20, in install
    self.adb_install()
  File "D:\AzurLaneAutoScript\deploy\adb.py", line 63, in adb_install
    initer = init.Initer(device, loglevel=logging.DEBUG)
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 146, in __init__
    self.sdk = d.getprop('ro.build.version.sdk')
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\mixin.py", line 322, in getprop
    return self._run(['getprop', prop]).strip()
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\mixin.py", line 28, in _run
    return self.shell(cmd)
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 578, in shell
    ret = self._client.shell(self._serial, cmdargs, stream=stream, timeout=timeout)
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 318, in shell
    c.check_okay()
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 168, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: closed
```

### 截图

![屏幕截图 2024-06-10 135755](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/51279227/9b0a9f00-cb51-467f-8be2-95fdd729884e)

**Comment by Mamboing** [comment]
执行ADB SERVICE结果
![屏幕截图 2024-06-10 140738](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/51279227/b681b404-41e8-4098-bea9-0546ef4a36f7)

**Comment by Mamboing** [comment]
执行adb services后结果
![屏幕截图 2024-06-10 141705](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/51279227/11c8d336-8000-4742-984a-0dd2731d148e)

**Comment by LmeSzinc** [comment]
#3412

**Comment by Mamboing** [comment]
已解决，同样是水冷显示屏软件导致的，将软件打开连接显示屏就可以正常启动Alas了，谢谢
