### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by mayu1995-zj** [LmeSzinc/AzurLaneAutoScript#39]
Traceback (most recent call last):
  File "H:\Azure\AzurLaneAutoScript-master\alas.py", line 23, in run
    self.__getattribute__(command.lower())()
  File "H:\Azure\AzurLaneAutoScript-master\alas.py", line 134, in c72_mystery_farming
    az.run('campaign_7_2_mystery_farming')
  File "H:\Azure\AzurLaneAutoScript-master\module\campaign\run.py", line 156, in run
    self.handle_campaign_ui()
  File "H:\Azure\AzurLaneAutoScript-master\module\campaign\run.py", line 185, in handle_campaign_ui
    self.ensure_campaign_ui(name=self.stage, mode=self.config.CAMPAIGN_MODE)
  File "H:\Azure\AzurLaneAutoScript-master\module\campaign\campaign_ui.py", line 83, in ensure_campaign_ui
    self.ui_weigh_anchor()
  File "H:\Azure\AzurLaneAutoScript-master\module\ui\ui.py", line 141, in ui_weigh_anchor
    if self.ui_ensure(destination=page_campaign):
  File "H:\Azure\AzurLaneAutoScript-master\module\ui\ui.py", line 125, in ui_ensure
    if self.ui_current == destination:
AttributeError: 'CampaignRun' object has no attribute 'ui_current'
2020-06-18 14:45:10.387 | INFO | Saving error: ./log/error/1592462710387

执行7-2捡垃圾就出现这个情况

**Comment by LmeSzinc** [comment]
检查一下启动alas时的游戏界面
alas可以在以下界面启动:
主界面, 出击, 编队, 演习, 每日任务, 活动, SP活动, 任务界面
`[page_main, page_campaign, page_fleet, page_exercise, page_daily, page_event, page_sp, page_mission]`
alas也可以在右上角有"一键回港"按钮的界面下启动, 游戏中大部分界面都有这个按钮, 除了主界面本身, 后宅, 指挥喵.

**Comment by mayu1995-zj** [comment]
> 检查一下启动alas时的游戏界面
> alas可以在以下界面启动:
> 主界面, 出击, 编队, 演习, 每日任务, 活动, SP活动, 任务界面
> `[page_main, page_campaign, page_fleet, page_exercise, page_daily, page_event, page_sp, page_mission]`
> alas也可以在右上角有"一键回港"按钮的界面下启动, 游戏中大部分界面都有这个按钮, 除了主界面本身, 后宅, 指挥喵.

我用夜神模拟器  adb也配置好环境变量了  需要替换夜神环境下的adb.ext和nox_adb.ext吗

**Comment by LmeSzinc** [comment]
如果环境变量的ADB和夜神模拟器版本一致的话, 无需替换.
如果发现启动另一个模拟器实例时, 发生adb连接断开的情况, 就应该考虑替换, 或者更换环境中的ADB

**Comment by mayu1995-zj** [comment]
> 如果环境变量的ADB和夜神模拟器自带的ADB版本一致的话, 无需替换.
> 如果发现启动另一个模拟器实例时, 发生adb连接断开的情况, 就应该考虑替换, 或者更换环境中的ADB

嗯  adb我调试好了  已经能运行了 但是出现以下问题
![image](https://user-images.githubusercontent.com/58935150/84991610-59902700-b179-11ea-819a-b7c1904b7bd9.png)
![image](https://user-images.githubusercontent.com/58935150/84991662-6e6cba80-b179-11ea-99ff-32cd4e1cb857.png)
可以进去 但是不会点击移动。

**Comment by LmeSzinc** [comment]
检查一下`出击设置`中的`心情控制`, 在log中alas正在等待心情回复
设置完成后需要点击`开始`来保存设置, 然后点击`编辑`返回

**Comment by mayu1995-zj** [comment]
> 检查一下`出击设置`中的`心情控制`, 在log中alas正在等待心情回复
> 设置完成后需要点击`开始`来保存设置, 然后点击`编辑`返回

嗯  好的 谢谢大佬指点
