### ISSUE TITLE
win10弹窗显示包缺失

### ISSUE THREAD

**Issue by rfzmiaoling** [LmeSzinc/AzurLaneAutoScript#392]
开启win10的弹窗功能的时候会发生这个错误。
尝试直接安装notifypy包并直接复制进module文件夹并没有什么用。

2021-03-26 09:01:15.393 | ERROR | No module named 'notifypy'
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\alas.py", line 203, in c72_mystery_farming
    az.run('campaign_7_2_mystery_farming')
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\run.py", line 229, in run
    self.campaign.run()
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\campaign_base.py", line 140, in run
    self.execute_a_battle()
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\campaign_base.py", line 96, in execute_a_battle
    result = self.battle_function()
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\base\decorator.py", line 63, in wrapper
    return record['func'](self, *args, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\campaign_base.py", line 86, in battle_function
    result = func()
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\campaign\campaign_main\campaign_7_2_mystery_farming.py", line 83, in battle_3
    self.withdraw()
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\map\map_operation.py", line 184, in withdraw
    if self.handle_in_stage():
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\handler\enemy_searching.py", line 34, in handle_in_stage
    self.device.send_notification('Sortie finished', 'Map cleared')
  File "C:\fakepath\AzurLaneAutoScript\AzurLaneAutoScript\module\device\device.py", line 23, in send_notification
    from notifypy import Notify
ModuleNotFoundError: No module named 'notifypy'

**Comment by rfzmiaoling** [comment]
修改了device的引用
from notifypy import 改成了from module.notifypy import 
现在不报错了，但是弹窗功能仍然没有

**Comment by LmeSzinc** [comment]
双击打开 console.bat
`pip install notify-py`
