### ISSUE TITLE
由于目标计算机积极拒绝，无法连接

### ISSUE THREAD

**Issue by makuralymi** [LmeSzinc/AzurLaneAutoScript#3989]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

无法打开

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Task adb.exe not found
taskkill /f /im nox_adb.exe >nul 2>nul
Task nox_adb.exe not found
taskkill /f /im adb_server.exe >nul 2>nul
Task adb_server.exe not found
taskkill /f /im HD-Adb.exe >nul 2>nul
Task HD-Adb.exe not found
E:/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
adb.exe: failed to check server version: cannot connect to daemon
Devices: []
E:/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
* daemon not running; starting now at tcp:5037
* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
adb.exe: failed to check server version: cannot connect to daemon
Devices: []
==================== UIAUTOMATOR2 INIT ====================
* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
error: cannot connect to daemon
Traceback (most recent call last):
  File "E:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 103, in _safe_connect
    return self._create_socket()
  File "E:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 95, in _create_socket
    s.connect((adb_host, adb_port))
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "E:\AzurLaneAutoScript\deploy\installer.py", line 20, in install
    self.adb_install()
  File "E:\AzurLaneAutoScript\deploy\adb.py", line 61, in adb_install
    for device in adbutils.adb.iter_device():
  File "E:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 443, in iter_device
    with self._connect() as c:
  File "E:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 189, in _connect
    _conn = _AdbStreamConnection(self.__host, self.__port)
  File "E:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 88, in __init__
    self.__conn = self._safe_connect()
  File "E:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 106, in _safe_connect
    return self._create_socket()
  File "E:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 95, in _create_socket
    s.connect((adb_host, adb_port))
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
```

### 还有别的吗？

无

**Comment by Frocean** [comment]
之前的issue有 #712
个人平常遇到是重启电脑就完事儿了

**Comment by LmeSzinc** [comment]
打开 console.bat 执行
```
netstat -ano | findstr 5037
```
查找 5037 端口的程序的 pid，杀掉它

**Comment by makuralymi** [comment]
> 打开 console.bat 执行
> ```
> netstat -ano | findstr 5037
> ```
> 查找占用 5037 端口的程序的 pid，杀掉它

5037端口没有程序占用
