### ISSUE TITLE
无法连接模拟器

### ISSUE THREAD

**Issue by SheerYin** [LmeSzinc/AzurLaneAutoScript#416]
使用的是mumu模拟器

`=======================================================================================================================
== | Language: en
== | Region: cn
== | SystemType: 64
== | DeployMode: New
== | KeepLocalChanges: disable
== | RealtimeMode: disable
== | AutoMode: disable
== | IsUsingGit: yes
== | Serial: 7555
=======================================================================================================================
==============================================| Alas Run Tool 3.0 |====================================================
=======================================================================================================================

=======================================================================================================================

 [*] Select your Server/GUI Language
   |
   |-- [1] EN
   |
   |-- [2] CN
   |
   |-- [3] JP
   |
   |-- [4] TW

 [5] Updater

 [6] Settings
=======================================================================================================================
Please input the option and press ENTER:2
=======================================================================================================================
=======================================================================================================================
== NemuHeadless.exe is running
=======================================================================================================================
* daemon not running; starting now at tcp:5037
* daemon started successfully
=======================================================================================================================
Traceback (most recent call last):
  File "I:\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "I:\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__main__.py", line 246, in <module>
    main()
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__main__.py", line 236, in main
    actions[args.subparser](args)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__main__.py", line 33, in cmd_init
    init = Initer(device, loglevel=logging.DEBUG)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 150, in __init__
    self.sdk = d.getprop('ro.build.version.sdk')
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\mixin.py", line 322, in getprop
    return self._run(['getprop', prop]).strip()
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\mixin.py", line 28, in _run
    return self.shell(cmd)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 507, in shell
    ret = self._client.shell(self._serial, cmdargs, stream=stream, timeout=timeout)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 264, in shell
    c.check_okay()
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 165, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: device '(no serial number)' not found
=======================================================================================================================
== The connection was Successful on SERIAL: 7555
=======================================================================================================================
Python Found in I:\AzurLaneAutoScript\toolkit\python.exe Proceeding..
Opening alas_cn.pyw in I:\AzurLaneAutoScript
2021-04-24 07:47:00.402 | INFO | +---------------------------------------------+
2021-04-24 07:47:00.403 | INFO | |                    START                    |
2021-04-24 07:47:00.403 | INFO | +---------------------------------------------+
2021-04-24 07:47:00.405 | INFO | [Server] cn
`

即使进入界面进行设置

`2021-04-24 07:50:01.079 | INFO | +---------------------------------------------+
2021-04-24 07:50:01.079 | INFO | |                    START                    |
2021-04-24 07:50:01.079 | INFO | +---------------------------------------------+
2021-04-24 07:50:01.080 | INFO | [Server] cn
2021-04-24 07:50:02.094 | INFO | [Command] Emulator
2021-04-24 07:50:02.095 | INFO | <<< DEVICE >>>
2021-04-24 07:50:02.095 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
Traceback (most recent call last):
  File "alas_cn.pyw", line 8, in <module>
    main()
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "I:\AzurLaneAutoScript\module\config\argparser.py", line 523, in main
    alas.run(command=command)
  File "I:\AzurLaneAutoScript\alas.py", line 25, in run
    self.device = Device(config=self.config)
  File "I:\AzurLaneAutoScript\module\device\connection.py", line 27, in __init__
    self.device = self.connect(self.serial)
  File "I:\AzurLaneAutoScript\module\device\connection.py", line 96, in connect
    self._adb_connect(serial)
  File "I:\AzurLaneAutoScript\module\device\connection.py", line 80, in _adb_connect
    msg = self.adb_command(['connect', serial]).decode("utf-8")
  File "I:\AzurLaneAutoScript\module\device\connection.py", line 60, in adb_command
    return process.communicate(timeout=10)[0]
  File "I:\AzurLaneAutoScript\toolkit\lib\subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "I:\AzurLaneAutoScript\toolkit\lib\subprocess.py", line 1298, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['.\\toolkit\\Lib\\site-packages\\adbutils\\binaries\\adb.exe', '-s', '127.0.0.1:7555', 'connect', '127.0.0.1:7555']' timed out after 10 seconds
2021-04-24 07:50:36.149 | INFO | +---------------------------------------------+
2021-04-24 07:50:36.149 | INFO | |                    START                    |
2021-04-24 07:50:36.149 | INFO | +---------------------------------------------+
2021-04-24 07:50:36.150 | INFO | [Server] cn
2021-04-24 07:50:37.158 | INFO | [Command] Emulator
2021-04-24 07:50:37.158 | INFO | <<< DEVICE >>>
2021-04-24 07:50:37.158 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
2021-04-24 07:50:37.178 | INFO | already connected to 127.0.0.1:7555
Traceback (most recent call last):
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 206, in request
    url = self.__client.path2url(url) # may raise adbutils.AdbError
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 268, in path2url
    return urlparse.urljoin(self._get_atx_agent_url(), path)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 252, in _get_atx_agent_url
    lport = self._adb_device.forward_port(7912) # this method is so fast, only take 0.2ms
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 531, in forward_port
    self._client.forward(self._serial, "tcp:" + str(local_port), remote)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 354, in forward
    c.check_okay()
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 165, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alas_cn.pyw", line 8, in <module>
    main()
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "I:\AzurLaneAutoScript\module\config\argparser.py", line 523, in main
    alas.run(command=command)
  File "I:\AzurLaneAutoScript\alas.py", line 25, in run
    self.device = Device(config=self.config)
  File "I:\AzurLaneAutoScript\module\device\connection.py", line 27, in __init__
    self.device = self.connect(self.serial)
  File "I:\AzurLaneAutoScript\module\device\connection.py", line 98, in connect
    device = u2.connect(serial)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 1789, in connect
    return connect_usb(addr)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 1830, in connect_usb
    return Device(serial)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 242, in __init__
    wlan_ip = self.wlan_ip
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 399, in wlan_ip
    ip = self.http.get("/wlan/ip").text.strip()
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 211, in request
    self.__client._prepare_atx_agent()
  File "I:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 284, in _prepare_atx_agent
    raise RuntimeError("USB device %s is offline" % self._serial)
RuntimeError: USB device 127.0.0.1:7555 is offline
`

**Comment by SheerYin** [comment]
已自行解决：
把AzurLaneAutoScript放在盘目录
不支持中文文件夹
替换adb
