### ISSUE TITLE
找不到SP图入口

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#425]
![2021-04-27_14-13-49-730390](https://user-images.githubusercontent.com/70339606/116194106-f5f46400-a762-11eb-9f44-2cbd343e72e7.png)
2021-04-27 14:13:16.439 | INFO | +---------------------------------------------+
2021-04-27 14:13:16.439 | INFO | |                    START                    |
2021-04-27 14:13:16.439 | INFO | +---------------------------------------------+
2021-04-27 14:13:16.440 | INFO | [Server] jp
2021-04-27 14:13:17.425 | INFO | [Command] Daily
2021-04-27 14:13:17.425 | INFO | <<< DEVICE >>>
2021-04-27 14:13:17.425 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
2021-04-27 14:13:17.483 | INFO | already connected to 127.0.0.1:5555
2021-04-27 14:13:21.580 | INFO | [DailyRecord_exercise] Record time: 2021-04-27 13:48:08
2021-04-27 14:13:21.580 | INFO | [DailyRecord_exercise] Last update: 2021-04-27 11:00:00
2021-04-27 14:13:21.581 | INFO | [DailyRecord_daily] Record time: 2021-04-27 14:05:46
2021-04-27 14:13:21.581 | INFO | [DailyRecord_daily] Last update: 2021-04-26 23:00:00
2021-04-27 14:13:21.594 | INFO | [DailyRecord_hard] Record time: 2021-04-26 10:51:03
2021-04-27 14:13:21.594 | INFO | [DailyRecord_hard] Last update: 2021-04-26 23:00:00
2021-04-27 14:13:21.594 | INFO | ==================== CAMPAIGN HARD ====================
2021-04-27 14:13:21.595 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:21.969 | INFO | [Screen_size] 1280x720
2021-04-27 14:13:21.976 | INFO | [UI] page_main
2021-04-27 14:13:21.976 | INFO | Goto page_campaign
2021-04-27 14:13:21.976 | INFO | [UI route] page_main - page_campaign_menu - page_campaign
2021-04-27 14:13:21.976 | INFO | <<< UI CLICK >>>
2021-04-27 14:13:22.356 | INFO | Click (1097,  337) @ MAIN_GOTO_CAMPAIGN
2021-04-27 14:13:23.517 | INFO | <<< UI CLICK >>>
2021-04-27 14:13:23.535 | INFO | Click ( 390,  340) @ CAMPAIGN_MENU_GOTO_CAMPAIGN
2021-04-27 14:13:25.843 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:26.095 | INFO | [UI] page_campaign
2021-04-27 14:13:26.095 | INFO | Already at page_campaign
2021-04-27 14:13:26.111 | INFO | [Mode_switch_1] normal
2021-04-27 14:13:26.111 | INFO | Click (  77,  672) @ SWITCH_1_NORMAL
2021-04-27 14:13:27.605 | INFO | [Mode_switch_1] hard
2021-04-27 14:13:27.605 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:27.715 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
2021-04-27 14:13:27.767 | INFO | [campaign 0.062s] ['11--3', '11--1', '11--4', '11--2']
2021-04-27 14:13:27.767 | INFO | [Chapter] 11
2021-04-27 14:13:27.767 | INFO | [Stage] 11-3, 11-1, 11-4, 11-2
2021-04-27 14:13:27.767 | INFO | [Index] 11
2021-04-27 14:13:27.769 | INFO | [Mode_switch_1] hard
2021-04-27 14:13:27.769 | INFO | Click (  95,  662) @ SWITCH_1_HARD
2021-04-27 14:13:29.290 | INFO | [Mode_switch_1] normal
2021-04-27 14:13:29.291 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:29.415 | INFO | [campaign 0.026s] ['11--3', '11--1', '11--4', '11--2']
2021-04-27 14:13:29.415 | INFO | [Chapter] 11
2021-04-27 14:13:29.415 | INFO | [Stage] 11-3, 11-1, 11-4, 11-2
2021-04-27 14:13:29.415 | INFO | [Index] 11
2021-04-27 14:13:29.424 | INFO | [OCR_HARD_REMAIN 0.009s] 0
2021-04-27 14:13:29.425 | INFO | [Remain] 0
2021-04-27 14:13:29.458 | INFO | [EventABRecord_sp] Record time: 2020-01-01 00:00:00
2021-04-27 14:13:29.458 | INFO | [EventABRecord_sp] Last update: 2021-04-26 23:00:00
2021-04-27 14:13:29.493 | INFO | [Emotion fleet_1] 119
2021-04-27 14:13:29.493 | INFO | [Emotion fleet_2] 119
2021-04-27 14:13:29.494 | INFO | [Emotion_bug] 0/86
2021-04-27 14:13:29.494 | INFO | ==================== SP ====================
2021-04-27 14:13:29.494 | INFO | Count: [0]
2021-04-27 14:13:29.810 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:30.133 | INFO | [UI] page_campaign
2021-04-27 14:13:30.133 | INFO | Goto page_event
2021-04-27 14:13:30.133 | INFO | [UI route] page_campaign - page_campaign_menu - page_event
2021-04-27 14:13:30.133 | INFO | <<< UI CLICK >>>
2021-04-27 14:13:30.416 | INFO | Click (  66,   51) @ BACK_ARROW
2021-04-27 14:13:30.848 | INFO | <<< UI CLICK >>>
2021-04-27 14:13:30.890 | INFO | Click ( 688,  207) @ CAMPAIGN_MENU_GOTO_EVENT
2021-04-27 14:13:32.764 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:32.764 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:32.881 | INFO | [campaign 0.018s] ['C1', 'C3', 'C2']
2021-04-27 14:13:32.881 | INFO | [Chapter] c
2021-04-27 14:13:32.882 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:32.882 | INFO | [Index] 1
2021-04-27 14:13:32.882 | WARNING | Stage not found: sp
2021-04-27 14:13:33.229 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:33.592 | INFO | [UI] page_event
2021-04-27 14:13:33.592 | INFO | Already at page_event
2021-04-27 14:13:33.593 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:33.593 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:33.706 | INFO | [campaign 0.017s] ['C1', 'C3', 'C2']
2021-04-27 14:13:33.707 | INFO | [Chapter] c
2021-04-27 14:13:33.707 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:33.707 | INFO | [Index] 1
2021-04-27 14:13:33.707 | WARNING | Stage not found: sp
2021-04-27 14:13:34.063 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:34.507 | INFO | [UI] page_event
2021-04-27 14:13:34.507 | INFO | Already at page_event
2021-04-27 14:13:34.507 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:34.507 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:34.620 | INFO | [campaign 0.015s] ['C1', 'C3', 'C2']
2021-04-27 14:13:34.620 | INFO | [Chapter] c
2021-04-27 14:13:34.620 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:34.620 | INFO | [Index] 1
2021-04-27 14:13:34.620 | WARNING | Stage not found: sp
2021-04-27 14:13:34.993 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:35.407 | INFO | [UI] page_event
2021-04-27 14:13:35.407 | INFO | Already at page_event
2021-04-27 14:13:35.408 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:35.408 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:35.521 | INFO | [campaign 0.016s] ['C1', 'C3', 'C2']
2021-04-27 14:13:35.521 | INFO | [Chapter] c
2021-04-27 14:13:35.521 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:35.521 | INFO | [Index] 1
2021-04-27 14:13:35.521 | WARNING | Stage not found: sp
2021-04-27 14:13:35.924 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:36.298 | INFO | [UI] page_event
2021-04-27 14:13:36.298 | INFO | Already at page_event
2021-04-27 14:13:36.299 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:36.299 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:36.411 | INFO | [campaign 0.015s] ['C1', 'C3', 'C2']
2021-04-27 14:13:36.411 | INFO | [Chapter] c
2021-04-27 14:13:36.411 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:36.411 | INFO | [Index] 1
2021-04-27 14:13:36.411 | WARNING | Stage not found: sp
2021-04-27 14:13:36.813 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:37.161 | INFO | [UI] page_event
2021-04-27 14:13:37.161 | INFO | Already at page_event
2021-04-27 14:13:37.162 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:37.162 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:37.275 | INFO | [campaign 0.016s] ['C1', 'C3', 'C2']
2021-04-27 14:13:37.275 | INFO | [Chapter] c
2021-04-27 14:13:37.275 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:37.275 | INFO | [Index] 1
2021-04-27 14:13:37.275 | WARNING | Stage not found: sp
2021-04-27 14:13:37.676 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:38.028 | INFO | [UI] page_event
2021-04-27 14:13:38.028 | INFO | Already at page_event
2021-04-27 14:13:38.029 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:38.029 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:38.144 | INFO | [campaign 0.016s] ['C1', 'C3', 'C2']
2021-04-27 14:13:38.144 | INFO | [Chapter] c
2021-04-27 14:13:38.144 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:38.144 | INFO | [Index] 1
2021-04-27 14:13:38.144 | WARNING | Stage not found: sp
2021-04-27 14:13:38.500 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:38.844 | INFO | [UI] page_event
2021-04-27 14:13:38.844 | INFO | Already at page_event
2021-04-27 14:13:38.845 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:38.845 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:38.960 | INFO | [campaign 0.016s] ['C1', 'C3', 'C2']
2021-04-27 14:13:38.960 | INFO | [Chapter] c
2021-04-27 14:13:38.960 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:38.960 | INFO | [Index] 1
2021-04-27 14:13:38.960 | WARNING | Stage not found: sp
2021-04-27 14:13:39.373 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:39.787 | INFO | [UI] page_event
2021-04-27 14:13:39.787 | INFO | Already at page_event
2021-04-27 14:13:39.788 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:39.788 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:39.902 | INFO | [campaign 0.015s] ['C1', 'C3', 'C2']
2021-04-27 14:13:39.902 | INFO | [Chapter] c
2021-04-27 14:13:39.902 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:39.902 | INFO | [Index] 1
2021-04-27 14:13:39.902 | WARNING | Stage not found: sp
2021-04-27 14:13:40.274 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:40.637 | INFO | [UI] page_event
2021-04-27 14:13:40.637 | INFO | Already at page_event
2021-04-27 14:13:40.638 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:40.638 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:40.752 | INFO | [campaign 0.015s] ['C1', 'C3', 'C2']
2021-04-27 14:13:40.752 | INFO | [Chapter] c
2021-04-27 14:13:40.752 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:40.752 | INFO | [Index] 1
2021-04-27 14:13:40.752 | WARNING | Stage not found: sp
2021-04-27 14:13:41.112 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:41.506 | INFO | [UI] page_event
2021-04-27 14:13:41.506 | INFO | Already at page_event
2021-04-27 14:13:41.507 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:41.507 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:41.620 | INFO | [campaign 0.015s] ['C1', 'C3', 'C2']
2021-04-27 14:13:41.620 | INFO | [Chapter] c
2021-04-27 14:13:41.620 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:41.620 | INFO | [Index] 1
2021-04-27 14:13:41.620 | WARNING | Stage not found: sp
2021-04-27 14:13:42.031 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:42.388 | INFO | [UI] page_event
2021-04-27 14:13:42.388 | INFO | Already at page_event
2021-04-27 14:13:42.389 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:42.389 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:42.505 | INFO | [campaign 0.017s] ['C1', 'C3', 'C2']
2021-04-27 14:13:42.505 | INFO | [Chapter] c
2021-04-27 14:13:42.505 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:42.505 | INFO | [Index] 1
2021-04-27 14:13:42.505 | WARNING | Stage not found: sp
2021-04-27 14:13:42.861 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:43.267 | INFO | [UI] page_event
2021-04-27 14:13:43.267 | INFO | Already at page_event
2021-04-27 14:13:43.267 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:43.267 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:43.383 | INFO | [campaign 0.017s] ['C1', 'C3', 'C2']
2021-04-27 14:13:43.383 | INFO | [Chapter] c
2021-04-27 14:13:43.383 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:43.383 | INFO | [Index] 1
2021-04-27 14:13:43.383 | WARNING | Stage not found: sp
2021-04-27 14:13:43.767 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:44.100 | INFO | [UI] page_event
2021-04-27 14:13:44.100 | INFO | Already at page_event
2021-04-27 14:13:44.101 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:44.101 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:44.217 | INFO | [campaign 0.015s] ['C1', 'C3', 'C2']
2021-04-27 14:13:44.218 | INFO | [Chapter] c
2021-04-27 14:13:44.218 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:44.218 | INFO | [Index] 1
2021-04-27 14:13:44.218 | WARNING | Stage not found: sp
2021-04-27 14:13:44.635 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:44.977 | INFO | [UI] page_event
2021-04-27 14:13:44.977 | INFO | Already at page_event
2021-04-27 14:13:44.977 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:44.977 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:45.098 | INFO | [campaign 0.016s] ['C1', 'C3', 'C2']
2021-04-27 14:13:45.098 | INFO | [Chapter] c
2021-04-27 14:13:45.098 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:45.098 | INFO | [Index] 1
2021-04-27 14:13:45.098 | WARNING | Stage not found: sp
2021-04-27 14:13:45.453 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:45.808 | INFO | [UI] page_event
2021-04-27 14:13:45.808 | INFO | Already at page_event
2021-04-27 14:13:45.809 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:45.809 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:45.930 | INFO | [campaign 0.017s] ['C1', 'C3', 'C2']
2021-04-27 14:13:45.930 | INFO | [Chapter] c
2021-04-27 14:13:45.930 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:45.930 | INFO | [Index] 1
2021-04-27 14:13:45.930 | WARNING | Stage not found: sp
2021-04-27 14:13:46.301 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:46.706 | INFO | [UI] page_event
2021-04-27 14:13:46.707 | INFO | Already at page_event
2021-04-27 14:13:46.707 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:46.707 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:46.821 | INFO | [campaign 0.014s] ['C1', 'C3', 'C2']
2021-04-27 14:13:46.821 | INFO | [Chapter] c
2021-04-27 14:13:46.821 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:46.821 | INFO | [Index] 1
2021-04-27 14:13:46.821 | WARNING | Stage not found: sp
2021-04-27 14:13:47.214 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:47.551 | INFO | [UI] page_event
2021-04-27 14:13:47.552 | INFO | Already at page_event
2021-04-27 14:13:47.552 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:47.552 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:47.665 | INFO | [campaign 0.015s] ['C1', 'C3', 'C2']
2021-04-27 14:13:47.666 | INFO | [Chapter] c
2021-04-27 14:13:47.666 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:47.666 | INFO | [Index] 1
2021-04-27 14:13:47.666 | WARNING | Stage not found: sp
2021-04-27 14:13:48.032 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:48.436 | INFO | [UI] page_event
2021-04-27 14:13:48.436 | INFO | Already at page_event
2021-04-27 14:13:48.437 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:48.437 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:48.550 | INFO | [campaign 0.015s] ['C1', 'C3', 'C2']
2021-04-27 14:13:48.550 | INFO | [Chapter] c
2021-04-27 14:13:48.551 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:48.551 | INFO | [Index] 1
2021-04-27 14:13:48.551 | WARNING | Stage not found: sp
2021-04-27 14:13:48.914 | INFO | <<< UI ENSURE >>>
2021-04-27 14:13:49.256 | INFO | [UI] page_event
2021-04-27 14:13:49.256 | INFO | Already at page_event
2021-04-27 14:13:49.257 | WARNING | Trying to goto EX, but no EX mode switch
2021-04-27 14:13:49.257 | INFO | <<< UI ENSURE INDEX >>>
2021-04-27 14:13:49.372 | INFO | [campaign 0.015s] ['C1', 'C3', 'C2']
2021-04-27 14:13:49.372 | INFO | [Chapter] c
2021-04-27 14:13:49.372 | INFO | [Stage] c1, c3, c2
2021-04-27 14:13:49.372 | INFO | [Index] 1
2021-04-27 14:13:49.373 | WARNING | Stage not found: sp
2021-04-27 14:13:49.730 | WARNING | Campaign name error
2021-04-27 14:13:49.730 | ERROR | Campaign name error
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 146, in daily
    az.daily_wrapper_run()
  File "C:\fakepath\AzurLaneAutoScript\module\reward\reward.py", line 270, in daily_wrapper_run
    if az.run_event_daily_sp():
  File "C:\fakepath\AzurLaneAutoScript\module\event\campaign_sp.py", line 28, in run_event_daily_sp
    self.run(name='sp', folder=self.config.EVENT_NAME_AB, total=1)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 214, in run
    mode=self.config.CAMPAIGN_MODE if self.config.COMMAND.lower() == 'main' else 'normal'
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_ui.py", line 124, in ensure_campaign_ui
    raise ScriptEnd('Campaign name error')
module.exception.ScriptEnd: Campaign name error
2021-04-27 14:13:49.741 | INFO | Saving error: ./log/error/1619504029741

**Comment by LmeSzinc** [comment]
#421
