### ISSUE TITLE
启动过程中uiautomator2安装部分出现问题

### ISSUE THREAD

**Issue by 2V-ALK** [LmeSzinc/AzurLaneAutoScript#4359]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

启动时进行到check atx-agent version后会报错，导致无法启动。尝试重装Alas和重启系统以及重置网络都无效。最后在config/deploy.yaml中将 InstallUiautomator2: true 改为false后解决。

### 如何复现

1. 启动程序
2. 出现问题

### 预期行为

正常启动

### 相关 Logs

```Text
==================== UIAUTOMATOR2 INIT ====================
Init device AdbDevice(serial=104537A5018758)
[I 241107 18:08:39 init:156] uiautomator2 version: 2.16.17
[I 241107 18:08:39 init:372] Install minicap, minitouch
[D 241107 18:08:39 init:59] Use cached assets: C:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2cache\cache\minitouch-4575799dba\minitouch
[D 241107 18:08:39 init:238] Push to /data/local/tmp/minitouch:0755
[D 241107 18:08:39 init:256] apk-debug package-info: None
[D 241107 18:08:39 init:257] apk-debug-test package-info: None
[I 241107 18:08:39 init:387] Install com.github.uiautomator, com.github.uiautomator.test 2.3.3
[D 241107 18:08:39 init:167] Shell: ('pm', 'uninstall', 'com.github.uiautomator')
[D 241107 18:08:39 init:167] Shell: ('pm', 'uninstall', 'com.github.uiautomator.test')
[D 241107 18:08:39 init:59] Use cached assets: C:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2cache\cache\app-uiautomator.apk-d3f17174fb\app-uiautomator.apk
[D 241107 18:08:39 init:238] Push to /data/local/tmp/app-uiautomator.apk:0644
[D 241107 18:08:39 init:167] Shell: ('pm', 'install', '-r', '-t', '/data/local/tmp/app-uiautomator.apk')
[I 241107 18:08:39 init:331] - app-uiautomator.apk installed
[D 241107 18:08:39 init:59] Use cached assets: C:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2cache\cache\app-uiautomator-test.apk-652bf9e13c\app-uiautomator-test.apk
[D 241107 18:08:39 init:238] Push to /data/local/tmp/app-uiautomator-test.apk:0644
[D 241107 18:08:39 init:167] Shell: ('pm', 'install', '-r', '-t', '/data/local/tmp/app-uiautomator-test.apk')
[I 241107 18:08:39 init:331] - app-uiautomator-test.apk installed
[D 241107 18:08:39 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[I 241107 18:08:39 init:346] Install atx-agent 0.10.0
[D 241107 18:08:39 init:59] Use cached assets: C:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2cache\cache\atx-agent_0.10.0_linux_armv7.tar.gz-cf3333ae7b\atx-agent_0.10.0_linux_armv7.tar.gz
[D 241107 18:08:39 init:238] Push to /data/local/tmp/atx-agent:0755
[D 241107 18:08:41 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 241107 18:08:41 init:350] Check atx-agent version
[D 241107 18:08:41 init:359] Forward: local:tcp:57933 -> remote:tcp:7912
[D 241107 18:08:41 init:359] Forward: local:tcp:57933 -> remote:tcp:7912
[D 241107 18:08:42 init:359] Forward: local:tcp:57933 -> remote:tcp:7912
[D 241107 18:08:42 init:359] Forward: local:tcp:57933 -> remote:tcp:7912
[D 241107 18:08:43 init:359] Forward: local:tcp:57933 -> remote:tcp:7912
[D 241107 18:08:43 init:359] Forward: local:tcp:57933 -> remote:tcp:7912
[D 241107 18:08:44 init:359] Forward: local:tcp:57933 -> remote:tcp:7912
[D 241107 18:08:44 init:359] Forward: local:tcp:57933 -> remote:tcp:7912
[D 241107 18:08:45 init:359] Forward: local:tcp:57933 -> remote:tcp:7912
[D 241107 18:08:45 init:359] Forward: local:tcp:57933 -> remote:tcp:7912
Traceback (most recent call last):
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\AzurLaneAutoScript\deploy\installer.py", line 26, in <module>
    Installer().install()
  File "C:\AzurLaneAutoScript\deploy\installer.py", line 20, in install
    self.adb_install()
  File "C:\AzurLaneAutoScript\deploy\adb.py", line 85, in adb_install
    initer.install()
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 392, in install
    self.setup_atx_agent()
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 351, in setup_atx_agent
    self.check_atx_agent_version()
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 361, in check_atx_agent_version
    port).text.strip()
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by MikeLiang2** [comment]
一样有类似的问题M1 MAC，NFO     03:58:28.040 │ Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')        
INFO     03:58:28.046 │ Check atx-agent version                                                                            
INFO     03:58:28.047 │ Forward: local:tcp:56945 -> remote:tcp:7912                                                        
INFO     03:58:28.555 │ Forward: local:tcp:56945 -> remote:tcp:7912                                                        
INFO     03:58:29.072 │ Forward: local:tcp:56945 -> remote:tcp:7912                                                        
INFO     03:58:29.584 │ Forward: local:tcp:56945 -> remote:tcp:7912                                                        
INFO     03:58:30.095 │ Forward: local:tcp:56945 -> remote:tcp:7912                                                        
INFO     03:58:30.610 │ Forward: local:tcp:56945 -> remote:tcp:7912                                                        
INFO     03:58:31.120 │ Forward: local:tcp:56945 -> remote:tcp:7912                                                        
INFO     03:58:31.631 │ Forward: local:tcp:56945 -> remote:tcp:7912                                                        
INFO     03:58:32.139 │ Forward: local:tcp:56945 -> remote:tcp:7912                                                        
INFO     03:58:32.648 │ Forward: local:tcp:56945 -> remote:tcp:7912                                                        
ERROR    03:58:32.655 │ ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without  
         response'))   
         
         卡这儿了

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/3412#issuecomment-1880112413

**Comment by SakuraToErii** [comment]
跟楼主重复了一样的问题
`❯ python -m uiautomator2 init
[I 250517 13:39:39 init:156] uiautomator2 version: 2.16.17
[I 250517 13:39:39 init:372] Install minicap, minitouch
[D 250517 13:39:39 init:59] Use cached assets: /Users/ordis/.uiautomator2/cache/minitouch-f7a806902f/minitouch
[D 250517 13:39:39 init:238] Push to /data/local/tmp/minitouch:0755
[I 250517 13:39:39 init:378] Android R (sdk:30) has no minicap resource
[D 250517 13:39:39 init:256] apk-debug package-info: {'package_name': 'com.github.uiautomator', 'version_name': '2.3.3', 'version_code': '2003003', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2025, 5, 17, 13, 25, 33), 'last_update_time': datetime.datetime(2025, 5, 17, 13, 25, 33), 'signature': 'ae17cd86], past signatures:['}
[D 250517 13:39:39 init:257] apk-debug-test package-info: {'package_name': 'com.github.uiautomator.test', 'version_name': '', 'version_code': '', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2025, 5, 17, 13, 25, 33), 'last_update_time': datetime.datetime(2025, 5, 17, 13, 25, 33), 'signature': 'ae17cd86], past signatures:['}
[I 250517 13:39:39 init:390] Already installed com.github.uiautomator apks
[D 250517 13:39:39 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[I 250517 13:39:40 init:346] Install atx-agent 0.10.0
[D 250517 13:39:40 init:59] Use cached assets: /Users/ordis/.uiautomator2/cache/atx-agent_0.10.0_linux_armv7.tar.gz-cf3333ae7b/atx-agent_0.10.0_linux_armv7.tar.gz
[D 250517 13:39:40 init:238] Push to /data/local/tmp/atx-agent:0755
[D 250517 13:39:40 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 250517 13:39:40 init:350] Check atx-agent version
[D 250517 13:39:40 init:359] Forward: local:tcp:61386 -> remote:tcp:7912
[D 250517 13:39:40 init:359] Forward: local:tcp:61386 -> remote:tcp:7912
[D 250517 13:39:41 init:359] Forward: local:tcp:61386 -> remote:tcp:7912
[D 250517 13:39:42 init:359] Forward: local:tcp:61386 -> remote:tcp:7912
[D 250517 13:39:42 init:359] Forward: local:tcp:61386 -> remote:tcp:7912
[D 250517 13:39:43 init:359] Forward: local:tcp:61386 -> remote:tcp:7912
[D 250517 13:39:43 init:359] Forward: local:tcp:61386 -> remote:tcp:7912
[D 250517 13:39:44 init:359] Forward: local:tcp:61386 -> remote:tcp:7912
[D 250517 13:39:44 init:359] Forward: local:tcp:61386 -> remote:tcp:7912
[D 250517 13:39:45 init:359] Forward: local:tcp:61386 -> remote:tcp:7912
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/uiautomator2/__main__.py", line 289, in <module>
    main()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/uiautomator2/__main__.py", line 279, in main
    actions[args.subparser](args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/uiautomator2/__main__.py", line 36, in cmd_init
    init.install()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/uiautomator2/init.py", line 392, in install
    self.setup_atx_agent()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/uiautomator2/init.py", line 351, in setup_atx_agent
    self.check_atx_agent_version()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/uiautomator2/init.py", line 360, in check_atx_agent_version
    version = requests.get("http://127.0.0.1:%d/version" %
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/alas/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
`
ATX 小黄车显示
java.net.ConnectException: Failed to connect to /127.0.0.1:7912
注释掉了 UIAUTOMATOR2 包里面 init.py 
# self.check_atx_agent_version()
后解决
