### ISSUE TITLE
[收菜] 每天0点刷新后重启，APP弹出用户协议，脚本失效

### ISSUE THREAD

**Issue by SF-monkey** [LmeSzinc/AzurLaneAutoScript#446]
**Describe the bug**
这个理应是官方APP的问题，脚本目前失效。
贴吧也有人反应过此问题：
https://tieba.baidu.com/p/7363522178
https://tieba.baidu.com/p/7363814239

**To Reproduce**
1. 选收菜
2. 玩上一段时间，例如刷7-2，触发心情bug脚本会重启APP；或者其他重启app的操作，需要一定时间间隔。
3. 重启APP后会先弹出用户协议，跟首次打开APP一样

**Screenshots**
![](https://i.imgur.com/eq82vUC.jpg)

**Solution**
相比于重启app，主界面->设置->注销重新登录，可以避免重启app。心情bug，每日0点日活等也会刷新。

**Log**
2021-05-22 08:56:25.432 | INFO | [RewardRecord_guild] Record time: 2021-05-22 08:46:08
2021-05-22 08:56:25.432 | INFO | [RewardRecord_guild] Next update: 2021-05-22 09:01:08
2021-05-22 08:56:25.432 | INFO | <<< REWARD END >>>
2021-05-22 08:56:25.432 | INFO | Reward loop wait
2021-05-22 08:56:25.432 | INFO | [Reward_loop_wait] 5 min 0 sec
2021-05-22 09:01:25.432 | INFO | <<< TRIGGERED RESTART NEW DAY >>>
2021-05-22 09:01:25.432 | INFO | <<< APP RESTART >>>
2021-05-22 09:01:25.432 | INFO | App stop: com.bilibili.azurlane
2021-05-22 09:01:26.063 | INFO | App start: com.bilibili.azurlane
2021-05-22 09:01:26.633 | INFO | <<< APP LOGIN >>>
2021-05-22 09:02:26.777 | WARNING | Wait too long
2021-05-22 09:02:26.777 | WARNING | Waiting for {'GET_MISSION', 'MAINTENANCE_ANNOUNCE', 'GET_ITEMS_1', 'EVENT_LIST_CHECK', 'LOGIN_GAME_UPDATE', 'LOGIN_CHECK', 'GET_ITEMS_2', 'LOGIN_ANNOUNCE', 'LOGIN_RETURN_SIGN', 'LOGIN_CONFIRM', 'POPUP_CANCEL', 'GOTO_MAIN', 'MAIN_GOTO_CAMPAIGN', 'GET_SHIP', 'GUILD_POPUP_CONFIRM'}
2021-05-22 09:02:26.778 | WARNING | Wait too long
2021-05-22 09:02:26.778 | WARNING | com.bilibili.azurlane will be restart in 10 seconds
2021-05-22 09:02:26.778 | WARNING | If you are playing by hand, please stop Alas
2021-05-22 09:02:36.778 | INFO | <<< APP RESTART >>>
2021-05-22 09:02:36.778 | INFO | App stop: com.bilibili.azurlane
2021-05-22 09:02:37.289 | INFO | App start: com.bilibili.azurlane
2021-05-22 09:02:37.789 | INFO | <<< APP LOGIN >>>
2021-05-22 09:03:37.789 | WARNING | Wait too long
2021-05-22 09:03:37.789 | WARNING | Waiting for {'GET_MISSION', 'MAINTENANCE_ANNOUNCE', 'GET_ITEMS_1', 'EVENT_LIST_CHECK', 'LOGIN_GAME_UPDATE', 'LOGIN_CHECK', 'GET_ITEMS_2', 'LOGIN_ANNOUNCE', 'LOGIN_RETURN_SIGN', 'LOGIN_CONFIRM', 'POPUP_CANCEL', 'GOTO_MAIN', 'MAIN_GOTO_CAMPAIGN', 'GET_SHIP', 'GUILD_POPUP_CONFIRM'}
Traceback (most recent call last):
  File "E:\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "E:\AzurLaneAutoScript\alas.py", line 111, in reward
    self.reward_when_finished()
  File "E:\AzurLaneAutoScript\alas.py", line 88, in reward_when_finished
    az.reward_loop()
  File "E:\AzurLaneAutoScript\module\reward\reward.py", line 216, in reward_loop
    self.app_restart()
  File "E:\AzurLaneAutoScript\module\handler\login.py", line 96, in app_restart
    self.handle_app_login()
  File "E:\AzurLaneAutoScript\module\handler\login.py", line 80, in handle_app_login
    self._handle_app_login()
  File "E:\AzurLaneAutoScript\module\handler\login.py", line 26, in _handle_app_login
    self.device.screenshot()
  File "E:\AzurLaneAutoScript\module\device\device.py", line 59, in screenshot
    self.stuck_record_check()
  File "E:\AzurLaneAutoScript\module\device\device.py", line 122, in stuck_record_check
    raise GameStuckError(f'Wait too long')
module.exception.GameStuckError: Wait too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alas_cn.pyw", line 8, in <module>
    main()
  File "E:\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 130, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "E:\AzurLaneAutoScript\module\config\argparser.py", line 547, in main
    alas.run(command=command)
  File "E:\AzurLaneAutoScript\alas.py", line 46, in run
    az.handle_game_stuck()
  File "E:\AzurLaneAutoScript\module\handler\login.py", line 134, in handle_game_stuck
    self.app_restart()
  File "E:\AzurLaneAutoScript\module\handler\login.py", line 96, in app_restart
    self.handle_app_login()
  File "E:\AzurLaneAutoScript\module\handler\login.py", line 80, in handle_app_login
    self._handle_app_login()
  File "E:\AzurLaneAutoScript\module\handler\login.py", line 26, in _handle_app_login
    self.device.screenshot()
  File "E:\AzurLaneAutoScript\module\device\device.py", line 59, in screenshot
    self.stuck_record_check()
  File "E:\AzurLaneAutoScript\module\device\device.py", line 122, in stuck_record_check
    raise GameStuckError(f'Wait too long')
module.exception.GameStuckError: Wait too long

**Comment by SF-monkey** [comment]
遇上这bug的不是所有人，听说是B站用户协议接口出问题了才老弹，所以黄鸡短期内可能不修。
只能尝试这样了：
```
AzurLaneAutoScript\module\handler\login.py", line 96, in app_restart
        #self.device.app_stop()
        #self.device.app_start()
        #self.handle_app_login()
```
