### ISSUE TITLE
修改为aScreenCap模式时报错

### ISSUE THREAD

**Issue by lho555** [LmeSzinc/AzurLaneAutoScript#450]
**Describe the bug**
使用的是蓝叠国际版5 64位版本. 修改成aScreenCap模式时候报错.辛苦了.
日志如下:

**Log**
2021-05-24 13:41:38.224 | INFO | +---------------------------------------------+
2021-05-24 13:41:38.224 | INFO | |                    START                    |
2021-05-24 13:41:38.224 | INFO | +---------------------------------------------+
2021-05-24 13:41:38.225 | INFO | [Server] cn
2021-05-24 13:41:39.290 | INFO | [Command] Emulator
2021-05-24 13:41:39.290 | INFO | <<< DEVICE >>>
2021-05-24 13:41:39.290 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
2021-05-24 13:41:39.328 | INFO | already connected to 127.0.0.1:5555
command = emulator
serial = 127.0.0.1:5555
package_name = com.bilibili.azurlane
enable_error_log_and_screenshot_save = yes
enable_perspective_error_image_save = no
device_screenshot_method = aScreenCap
device_control_method = minitouch
combat_screenshot_interval = 3.
enable_update_check = yes
update_method = web
update_proxy = 
github_token = <sensitive_infomation>
2021-05-24 13:41:41.397 | INFO | <<< EMULATOR SAVED >>>
2021-05-24 13:41:41.476 | INFO | [Package_name] com.bilibili.azurlane
2021-05-24 13:42:28.148 | ERROR | OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-dn5w5exm\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
Traceback (most recent call last):
  File "G:\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "G:\AzurLaneAutoScript\alas.py", line 129, in emulator
    az.device.screenshot()
  File "G:\AzurLaneAutoScript\module\device\device.py", line 60, in screenshot
    super().screenshot()
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 212, in call
    raise attempt.get()
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "G:\AzurLaneAutoScript\module\device\screenshot.py", line 64, in screenshot
    self.image = self._screenshot_ascreencap()
  File "G:\AzurLaneAutoScript\module\device\ascreencap.py", line 73, in _screenshot_ascreencap
    return self._ascreencap_execute()
  File "G:\AzurLaneAutoScript\module\device\ascreencap.py", line 67, in _ascreencap_execute
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-dn5w5exm\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by LmeSzinc** [comment]
ascreencap 返回了空的图片。
[ascreencap](https://github.com/ClnViewer/Android-fast-screen-capture) 本身就是一个兼容性不高且不再维护的程序，用不了的话换 adb 就行了，在蓝叠模拟器上的速度基本没差别的。
