### ISSUE TITLE
找不到指定模块，请求帮助

### ISSUE THREAD

**Issue by ticktwain** [LmeSzinc/AzurLaneAutoScript#456]
Traceback (most recent call last):
  File "alas_cn.pyw", line 5, in <module>
    from module.config.argparser import main
  File "D:\AzurLaneAutoScript\module\config\argparser.py", line 7, in <module>
    from alas import AzurLaneAutoScript
  File "D:\AzurLaneAutoScript\alas.py", line 9, in <module>
    from module.handler.login import LoginHandler
  File "D:\AzurLaneAutoScript\module\handler\login.py", line 5, in <module>
    from module.combat.combat import Combat
  File "D:\AzurLaneAutoScript\module\combat\combat.py", line 11, in <module>
    from module.handler.auto_search import AutoSearchHandler
  File "D:\AzurLaneAutoScript\module\handler\auto_search.py", line 4, in <module>
    from module.handler.enemy_searching import EnemySearchingHandler
  File "D:\AzurLaneAutoScript\module\handler\enemy_searching.py", line 5, in <module>
    from module.handler.info_handler import InfoHandler
  File "D:\AzurLaneAutoScript\module\handler\info_handler.py", line 1, in <module>
    from scipy import signal
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\__init__.py", line 156, in <module>
    from . import fft
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "D:\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\_lib\_uarray\_backend.py", line 15, in <module>
    from . import _uarray  # type: ignore
ImportError: DLL load failed: 找不到指定的模块。
Press any key to back main menu

**Comment by razhh** [comment]
deinstall phyton install anaconda3 whit PATH
