### ISSUE TITLE
脚本缺少notify

### ISSUE THREAD

**Issue by Ragecks** [LmeSzinc/AzurLaneAutoScript#481]
刷图的时候脚本只能刷一次（通关的那种，已设定出击次数且不为一），然后自动停止运行
以下为记录
2021-06-12 11:11:29.326 | WARNING | Map walk out of step.
2021-06-12 11:11:32.552 | ERROR | No module named 'notifypy'
Traceback (most recent call last):
  File "D:\tools\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "D:\tools\AzurLaneAutoScript\alas.py", line 156, in event
    az.run(self.config.EVENT_STAGE, folder=self.config.EVENT_NAME)
  File "D:\tools\AzurLaneAutoScript\module\campaign\run.py", line 229, in run
    self.campaign.run()
  File "D:\tools\AzurLaneAutoScript\module\campaign\campaign_base.py", line 140, in run
    self.execute_a_battle()
  File "D:\tools\AzurLaneAutoScript\module\campaign\campaign_base.py", line 96, in execute_a_battle
    result = self.battle_function()
  File "D:\tools\AzurLaneAutoScript\module\base\decorator.py", line 69, in wrapper
    return record['func'](self, *args, **kwargs)
  File "D:\tools\AzurLaneAutoScript\module\campaign\campaign_base.py", line 86, in battle_function
    result = func()
  File "D:\tools\AzurLaneAutoScript\campaign\event_20210527_cn\b1.py", line 76, in battle_0
    return self.battle_default()
  File "D:\tools\AzurLaneAutoScript\module\campaign\campaign_base.py", line 15, in battle_default
    if self.clear_enemy():
  File "D:\tools\AzurLaneAutoScript\module\map\map.py", line 191, in clear_enemy
    self.clear_chosen_enemy(grids[0])
  File "D:\tools\AzurLaneAutoScript\module\map\map.py", line 20, in clear_chosen_enemy
    self.goto(grid, expected=expected)
  File "D:\tools\AzurLaneAutoScript\module\map\fleet.py", line 411, in goto
    self._goto(node, expected=expected if node == nodes[-1] else '')
  File "D:\tools\AzurLaneAutoScript\module\map\fleet.py", line 331, in _goto
    self.device.send_notification('MapWalkError', 'Walk out of step error, please check GUI.')
  File "D:\tools\AzurLaneAutoScript\module\device\device.py", line 23, in send_notification
    from notifypy import Notify
ModuleNotFoundError: No module named 'notifypy'
2021-06-12 11:11:32.553 | INFO | Saving error: ./log/error/1623467492553

**Comment by AlexHalogen** [comment]
我也遇到这个问题，临时解决方法是双击console.bat，然后在里面运行
`pip install -r requirements.txt`
----------
自动安装脚本引用的是toolkit/requirements.txt，里面缺了notify-py的dependency，会不会是这个原因？

**Comment by Ragecks** [comment]
有可能，我在运行自动安装脚本时最后总会提示找不到文件，应该就是脚本引用的文件缺了东西

**Comment by Ragecks** [comment]
不过我在试着照您的解决方法运行console.bat时，又出现了如下错误代码，求解答
D:\tools\AzurLaneAutoScript
>>>pip install -r requirements.txt
Requirement already satisfied: numpy==1.16.6 in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 1)) (1.16.6)
Requirement already satisfied: scipy==1.4.1 in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 2)) (1.4.1)
Requirement already satisfied: pillow in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 3)) (8.2.0)
Requirement already satisfied: opencv-python in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 4)) (4.5.2.54)
Requirement already satisfied: scikit-image==0.16.2 in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 5)) (0.16.2)
Requirement already satisfied: lz4 in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 6)) (3.1.3)
Requirement already satisfied: tqdm in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 7)) (4.61.0)
Requirement already satisfied: requests<2.19.0,>=2.18.4 in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 8)) (2.18.4)
Requirement already satisfied: uiautomator2==2.9.2 in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 9)) (2.9.2)
Requirement already satisfied: retrying in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 10)) (1.3.3)
Requirement already satisfied: mxnet==1.6.0 in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 11)) (1.6.0)
Requirement already satisfied: cnocr==1.2.2 in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 12)) (1.2.2)
Requirement already satisfied: gooey in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 13)) (1.0.8)
Requirement already satisfied: colored in d:\tools\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 14)) (1.4.2)
ERROR: Exception:
Traceback (most recent call last):
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\cli\req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\commands\install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 128, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 30, in _iter_built
    for version, func in infos:
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 272, in iter_index_candidate_infos
    hashes=hashes,
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\index\package_finder.py", line 879, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\index\package_finder.py", line 824, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\index\package_finder.py", line 783, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\index\collector.py", line 512, in fetch_page
    return _get_html_page(location, session=self.session)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\index\collector.py", line 422, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\index\collector.py", line 137, in _get_html_response
    "Cache-Control": "max-age=0",
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_internal\network\session.py", line 449, in request
    return super().request(method, url, *args, **kwargs)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\urllib3\connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "D:\tools\AzurLaneAutoScript\toolkit\lib\ssl.py", line 827, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by AlexHalogen** [comment]
> 不过我在试着照您的解决方法运行console.bat时，又出现了如下错误代码，求解答

`pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/`
多运行几次试试看，排除一下网络问题

**Comment by Ragecks** [comment]
> > 不过我在试着照您的解决方法运行console.bat时，又出现了如下错误代码，求解答
> 
> `pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/`
> 多运行几次试试看，排除一下网络问题

依然出现上述情况，后来发现问题报告最后的ValueError: check_hostname requires server_hostname
经查找发现这个问题的原因是urllib3版本太高，新版的urllib3修改了一些东西，所以会报错
具体解决方法如下：
打开命令行，运行：
pip install urllib3==1.25.11
如果无法安装也可以尝试运行
pip install urllib3==1.25.11 -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
来通过国内的源来安装，速度快并且不会出现连接问题
安装完成后再次运行console.bat用您的上述代码就成功安装没有报错了
感谢您的帮助，希望能帮到更多人吧

**Comment by sissiunino** [comment]
成功解决问题了，非常感谢！
