### ISSUE TITLE
ImportError: DLL load failed:???

### ISSUE THREAD

**Issue by razhh** [LmeSzinc/AzurLaneAutoScript#497]
2021-06-24 21:46:33.678 | INFO | +---------------------------------------------+

2021-06-24 21:46:33.683 | INFO | |                    START                    |

2021-06-24 21:46:33.685 | INFO | +---------------------------------------------+

2021-06-24 21:46:33.690 | INFO | [Server] en
Traceback (most recent call last):
  File "alas_en.pyw", line 5, in <module>
    from module.config.argparser_en import main
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\config\argparser_en.py",
line 7, in <module>
    from alas import AzurLaneAutoScript
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\alas.py", line 9, in <module>
    from module.handler.login import LoginHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\login.py", line 5
, in <module>
    from module.combat.combat import Combat
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\combat\combat.py", line 1
1, in <module>
    from module.handler.auto_search import AutoSearchHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\auto_search.py",
line 4, in <module>
    from module.handler.enemy_searching import EnemySearchingHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\enemy_searching.p
y", line 5, in <module>
    from module.handler.info_handler import InfoHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\info_handler.py",
 line 1, in <module>
    from scipy import signal
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
__init__.py", line 156, in <module>
    from . import fft
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
_lib\_uarray\_backend.py", line 15, in <module>
    from . import _uarray  # type: ignore
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

hello for any time its worket... now i have this problem 
what is my problem????
 regards

**Comment by LmeSzinc** [comment]
Dependencies are broken, re-install them should work.

Open console.bat
`pip install -r requirements.txt`

**Comment by razhh** [comment]
so i have reinstall easy mode

maked:

pip install -r requirements.txt over console


================================================================================
=======================================
== | Language: en
== | Region: origin
== | SystemType: 64
== | DeployMode: New
== | KeepLocalChanges: disable
== | RealtimeMode: disable
== | AutoMode: disable
== | IsUsingGit: yes
== | Serial: 127.0.0.1:5555
================================================================================
=======================================
==============================================| Alas Run Tool 3.0 |=============
=======================================
================================================================================
=======================================

================================================================================
=======================================

 [*] Select your Server/GUI Language
   |
   |-- [1] EN
   |
   |-- [2] CN
   |
   |-- [3] JP
   |
   |-- [4] TW


 [5] Updater

 [6] Settings
================================================================================
=======================================
Please input the option and press ENTER:1
================================================================================
=======================================
================================================================================
=======================================
== Bluestacks.exe is running
================================================================================
=======================================
== Bluestacks is detected
* daemon not running; starting now at tcp:5037
* daemon started successfully
================================================================================
=======================================
[I 210626 14:31:23 init:159] uiautomator2 version: 2.9.2
[I 210626 14:31:23 init:356] Install minitouch
[D 210626 14:31:23 init:60] Use cached assets: C:\Users\rAz\.uiautomator2\cache\
minitouch-7b41fbda87\minitouch
[D 210626 14:31:23 init:236] Push to /data/local/tmp/minitouch:0755
[D 210626 14:31:23 init:254] apk-debug package-info: {'package_name': 'com.githu
b.uiautomator', 'version_name': '2.3.1', 'version_code': '2003001', 'flags': ['D
EBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install
_time': datetime.datetime(2020, 8, 21, 13, 30, 19), 'last_update_time': datetime
.datetime(2020, 8, 21, 13, 30, 19), 'signature': '8376b3fb'}
[D 210626 14:31:23 init:255] apk-debug-test package-info: {'package_name': 'com.
github.uiautomator.test', 'version_name': '', 'version_code': '', 'flags': ['DEB
UGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_t
ime': datetime.datetime(2020, 8, 21, 13, 30, 20), 'last_update_time': datetime.d
atetime(2020, 8, 21, 13, 30, 20), 'signature': '8376b3fb'}
[I 210626 14:31:23 init:366] Already installed com.github.uiautomator apks
[D 210626 14:31:23 init:295] Real version: [0, 9, 4], Expect version: [0, 9, 4]
[D 210626 14:31:23 init:166] Shell: ('/data/local/tmp/atx-agent', 'server', '--n
ouia', '-d')
[I 210626 14:31:23 init:373] Check atx-agent version
[D 210626 14:31:23 init:383] Forward: local:tcp:50816 -> remote:tcp:7912
[D 210626 14:31:23 init:386] atx-agent version 0.9.4
Successfully init AdbDevice(serial=127.0.0.1:5555)
[I 210626 14:31:23 init:159] uiautomator2 version: 2.9.2
[I 210626 14:31:23 init:356] Install minitouch
[D 210626 14:31:23 init:60] Use cached assets: C:\Users\rAz\.uiautomator2\cache\
minitouch-7b41fbda87\minitouch
[D 210626 14:31:23 init:236] Push to /data/local/tmp/minitouch:0755
[D 210626 14:31:23 init:254] apk-debug package-info: {'package_name': 'com.githu
b.uiautomator', 'version_name': '2.3.1', 'version_code': '2003001', 'flags': ['D
EBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install
_time': datetime.datetime(2020, 8, 21, 13, 30, 19), 'last_update_time': datetime
.datetime(2020, 8, 21, 13, 30, 19), 'signature': '8376b3fb'}
[D 210626 14:31:23 init:255] apk-debug-test package-info: {'package_name': 'com.
github.uiautomator.test', 'version_name': '', 'version_code': '', 'flags': ['DEB
UGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_t
ime': datetime.datetime(2020, 8, 21, 13, 30, 20), 'last_update_time': datetime.d
atetime(2020, 8, 21, 13, 30, 20), 'signature': '8376b3fb'}
[I 210626 14:31:23 init:366] Already installed com.github.uiautomator apks
[D 210626 14:31:23 init:295] Real version: [0, 9, 4], Expect version: [0, 9, 4]
[D 210626 14:31:23 init:166] Shell: ('/data/local/tmp/atx-agent', 'server', '--n
ouia', '-d')
[I 210626 14:31:23 init:373] Check atx-agent version
[D 210626 14:31:23 init:383] Forward: local:tcp:50830 -> remote:tcp:7912
[D 210626 14:31:23 init:386] atx-agent version 0.9.4
Successfully init AdbDevice(serial=emulator-5554)
================================================================================
=======================================
== The connection was Successful on SERIAL: 127.0.0.1:5555
================================================================================
=======================================
Python Found in C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\python.exe Proce
eding..
Opening alas_en.pyw in C:\Users\rAz\Desktop\AzurLaneAutoScript
2021-06-26 14:31:23.906 | INFO | +---------------------------------------------+

2021-06-26 14:31:23.908 | INFO | |                    START                    |

2021-06-26 14:31:23.910 | INFO | +---------------------------------------------+

2021-06-26 14:31:23.912 | INFO | [Server] en
Traceback (most recent call last):
  File "alas_en.pyw", line 5, in <module>
    from module.config.argparser_en import main
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\config\argparser_en.py",
line 7, in <module>
    from alas import AzurLaneAutoScript
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\alas.py", line 9, in <module>
    from module.handler.login import LoginHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\login.py", line 5
, in <module>
    from module.combat.combat import Combat
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\combat\combat.py", line 1
1, in <module>
    from module.handler.auto_search import AutoSearchHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\auto_search.py",
line 4, in <module>
    from module.handler.enemy_searching import EnemySearchingHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\enemy_searching.p
y", line 5, in <module>
    from module.handler.info_handler import InfoHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\info_handler.py",
 line 1, in <module>
    from scipy import signal
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
__init__.py", line 156, in <module>
    from . import fft
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
_lib\_uarray\_backend.py", line 15, in <module>
    from . import _uarray  # type: ignore
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

**Comment by LmeSzinc** [comment]
In console.bat, try:
```
pip uninstall scipy
pip install scipy==1.4.1
```

**Comment by razhh** [comment]
hey now console




C:\Users\rAz\Desktop\AzurLaneAutoScript
>>>pip uninstall scipy
Found existing installation: scipy 1.4.1
Uninstalling scipy-1.4.1:
  Would remove:
    c:\users\raz\desktop\azurlaneautoscript\toolkit\lib\site-packages\scipy-1.4.
1.dist-info\*
    c:\users\raz\desktop\azurlaneautoscript\toolkit\lib\site-packages\scipy\*
Proceed (y/n)? y
  Successfully uninstalled scipy-1.4.1

C:\Users\rAz\Desktop\AzurLaneAutoScript
>>>pip install scipy==1.4.1
Collecting scipy==1.4.1
  Using cached scipy-1.4.1-cp37-cp37m-win_amd64.whl (30.9 MB)
Requirement already satisfied: numpy>=1.13.3 in c:\users\raz\desktop\azurlaneaut
oscript\toolkit\lib\site-packages (from scipy==1.4.1) (1.16.6)
Installing collected packages: scipy
Successfully installed scipy-1.4.1

C:\Users\rAz\Desktop\AzurLaneAutoScript



###############




and the error :: 


2021-06-26 14:58:57.424 | INFO | [Server] en
Traceback (most recent call last):
  File "alas_en.pyw", line 5, in <module>
    from module.config.argparser_en import main
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\config\argparser_en.py",
line 7, in <module>
    from alas import AzurLaneAutoScript
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\alas.py", line 9, in <module>
    from module.handler.login import LoginHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\login.py", line 5
, in <module>
    from module.combat.combat import Combat
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\combat\combat.py", line 1
1, in <module>
    from module.handler.auto_search import AutoSearchHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\auto_search.py",
line 4, in <module>
    from module.handler.enemy_searching import EnemySearchingHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\enemy_searching.p
y", line 5, in <module>
    from module.handler.info_handler import InfoHandler
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\module\handler\info_handler.py",
 line 1, in <module>
    from scipy import signal
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
__init__.py", line 156, in <module>
    from . import fft
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "C:\Users\rAz\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\scipy\
_lib\_uarray\_backend.py", line 15, in <module>
    from . import _uarray  # type: ignore
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

**Comment by LmeSzinc** [comment]
Sorry, I don't know how to fix this. Google `scipy dll load failed` may help.

Possible reason:
- Failed to install scipy, but re-install can't fix.
- That DLL file has been deleted for unknown reason.
- DLL file exists, but unable to access.

**Comment by razhh** [comment]
ok thank you LME whit your help i googled and found the fix
i deinstalled python and install Anaconda3 whit PATH and now it running

**Comment by Actue** [comment]
I fixed this bug after I upgraded my scipy to version 1.6.0, maybe you can try this way.
And I'm wondering how to change ALAS preset scipy version, I try to rewrite requirements.txt but failed.
