### ISSUE TITLE
GET_SHIP called after LOGIN_ANNOUNCE, breaks script

### ISSUE THREAD

**Issue by markmarkyesyes** [LmeSzinc/AzurLaneAutoScript#540]
**Describe the bug**
On app reset, when the script logs in, it sends the game to the build window, but expects the game to still be on the home screen. Doesn't seem to always happen, possibly race condition or bad logic. Fails the script

**To Reproduce**
1. Set a reward loop or enter a state that closes the app and restarts it.
2. Hit scenario where GET_SHIP is called during login

**Expected behavior**
Expect and app restart to put the game in a state the script expects

**Screenshots**

**Log**
`2021-07-19 00:25:04.005 | INFO | Click (1168,  298) @ GUILD_MISSION
2021-07-19 00:25:04.309 | INFO | No guild mission found, mission of this week may not started
2021-07-19 00:25:04.309 | INFO | Guild mission choose found
2021-07-19 00:25:04.494 | INFO | No guild mission found, mission of this week may not started
2021-07-19 00:25:04.494 | INFO | Guild mission choose found
2021-07-19 00:25:04.676 | INFO | No guild mission found, mission of this week may not started
2021-07-19 00:25:04.676 | INFO | Guild mission choose found
2021-07-19 00:25:04.676 | INFO | Click (1185,  292) @ GUILD_MISSION
2021-07-19 00:25:04.969 | INFO | No guild mission found, mission of this week may not started
2021-07-19 00:25:04.969 | INFO | Guild mission choose found
2021-07-19 00:25:05.179 | INFO | No guild mission found, mission of this week may not started
2021-07-19 00:25:05.179 | INFO | Guild mission choose found
2021-07-19 00:25:05.388 | INFO | No guild mission found, mission of this week may not started
2021-07-19 00:25:05.389 | INFO | Guild mission choose found
2021-07-19 00:25:05.389 | WARNING | Too many click for a button: GUILD_MISSION
2021-07-19 00:25:05.389 | INFO | History click: ['GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION', 'GUILD_MISSION']
2021-07-19 00:25:05.389 | WARNING | Too many click for a button: GUILD_MISSION
2021-07-19 00:25:05.389 | INFO | Saving error: ./log/error/1626679505389
2021-07-19 00:25:12.798 | WARNING | com.YoStarEN.AzurLane will be restart in 10 seconds
2021-07-19 00:25:12.798 | WARNING | If you are playing by hand, please stop Alas
2021-07-19 00:25:22.802 | INFO | <<< APP RESTART >>>
2021-07-19 00:25:22.802 | INFO | App stop: com.YoStarEN.AzurLane
2021-07-19 00:25:23.003 | INFO | App start: com.YoStarEN.AzurLane
2021-07-19 00:25:23.313 | INFO | <<< APP LOGIN >>>
2021-07-19 00:25:35.727 | INFO | Click (1133,  618) @ LOGIN_CHECK
2021-07-19 00:25:35.835 | INFO | Login success
2021-07-19 00:25:40.808 | INFO | Click (1113,  604) @ LOGIN_CHECK
2021-07-19 00:25:43.935 | INFO | Click (1186,   55) @ LOGIN_ANNOUNCE
2021-07-19 00:25:49.021 | INFO | Click (1180,   58) @ LOGIN_ANNOUNCE
2021-07-19 00:25:50.685 | INFO | Click (1023,  665) @ GET_SHIP
2021-07-19 00:25:51.115 | INFO | Login to main confirm
2021-07-19 00:25:51.115 | INFO | <<< UI CLICK >>>
2021-07-19 00:25:51.118 | INFO | Click (1093,  340) @ MAIN_GOTO_CAMPAIGN
2021-07-19 00:26:51.186 | WARNING | Wait too long
2021-07-19 00:26:51.187 | WARNING | Waiting for {'WITHDRAW', 'CAMPAIGN_MENU_CHECK', 'POPUP_CANCEL', 'MAIN_GOTO_CAMPAIGN', 'EVENT_CHECK', 'SP_CHECK', 'CAMPAIGN_CHECK'}
Traceback (most recent call last):
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\alas.py", line 203, in c72_mystery_farming
    az.run('campaign_7_2_mystery_farming')
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\campaign\run.py", line 185, in run
    if self.handle_reward():
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\reward\reward.py", line 95, in handle_reward
    flag = self.reward()
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\reward\reward.py", line 86, in reward
    return self.reward()
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\reward\reward.py", line 76, in reward
    self.handle_guild()
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\guild\guild_reward.py", line 62, in handle_guild
    if self.guild_logistics():
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\guild\logistics.py", line 561, in guild_logistics
    checked = self._guild_logistics_collect()
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\guild\logistics.py", line 313, in _guild_logistics_collect
    self.device.click(GUILD_MISSION)
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\device\device.py", line 72, in click
    return super().click(button, record_check=record_check)
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\device\control.py", line 64, in click
    self.click_record_check(button)
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\device\control.py", line 48, in click_record_check
    raise GameTooManyClickError(f'Too many click for a button: {count[0][0]}')
module.exception.GameTooManyClickError: Too many click for a button: GUILD_MISSION

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alas_en.pyw", line 8, in <module>
    main()
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\config\argparser_en.py", line 645, in main
    alas.run(command=command)
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\alas.py", line 40, in run
    az.handle_game_stuck()
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\handler\login.py", line 142, in handle_game_stuck
    self.ensure_no_unfinished_campaign()
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\handler\login.py", line 132, in ensure_no_unfinished_campaign
    confirm_wait=confirm_wait, skip_first_screenshot=True)
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\ui\ui.py", line 65, in ui_click
    self.device.screenshot()
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\device\device.py", line 59, in screenshot
    self.stuck_record_check()
  File "C:\Users\weebrig\Desktop\AzurLaneAutoScript\module\device\device.py", line 122, in stuck_record_check
    raise GameStuckError(f'Wait too long')
module.exception.GameStuckError: Wait too long
`

**Comment by markmarkyesyes** [comment]
further testing says this only happens with daily enabled on the reward menu. Daily settings as below
![Capture](https://user-images.githubusercontent.com/18623918/126778076-f37d5d97-bf9d-469f-a3af-79e73c98f7e2.PNG)

**Comment by markmarkyesyes** [comment]
It's happening here now too, has been kicking me out ~ every 30 minutes
```2021-07-23 12:51:13.087 | INFO | -------------------- BATTLE_4 --------------------
2021-07-23 12:51:13.087 | INFO | Auto search moving
2021-07-23 12:51:13.087 | INFO | Fleet: 2, fleet_current_index: 2
2021-07-23 12:51:15.039 | INFO | <<< CAMPAIGN END >>>
2021-07-23 12:51:15.044 | INFO | Click ( 456,  628) @ AUTO_SEARCH_MENU_EXIT
2021-07-23 12:51:15.836 | INFO | <<< REWARD START >>>
2021-07-23 12:51:15.836 | INFO | <<< UI ENSURE >>>
2021-07-23 12:51:16.111 | INFO | [UI] page_campaign
2021-07-23 12:51:16.111 | INFO | Goto page_main
2021-07-23 12:51:16.111 | INFO | [UI route] page_campaign - page_main
2021-07-23 12:51:16.111 | INFO | <<< UI CLICK >>>
2021-07-23 12:51:16.404 | INFO | Click (1234,   39) @ GOTO_MAIN
2021-07-23 12:51:16.798 | INFO | Click (1231,   25) @ GOTO_MAIN
2021-07-23 12:51:18.526 | INFO | Click (1018,  666) @ GET_SHIP
2021-07-23 12:51:18.956 | INFO | [UI route] page_main - page_reward
2021-07-23 12:51:18.956 | INFO | <<< UI CLICK >>>
2021-07-23 12:51:18.957 | INFO | Click (  13,  171) @ MAIN_GOTO_REWARD
2021-07-23 12:52:19.162 | WARNING | Wait too long
2021-07-23 12:52:19.162 | WARNING | Waiting for {'RESEARCH_CHECK', 'REWARD_CHECK', 'GUILD_POPUP_CONFIRM', 'MAIN_GOTO_REWARD', 'SHIPYARD_CHECK', 'GET_SHIP', 'EVENT_LIST_CHECK', 'GET_ITEMS_1', 'LOGIN_ANNOUNCE', 'LOGIN_RETURN_SIGN', 'RESHMENU_CHECK', 'POPUP_CANCEL'}
2021-07-23 12:52:19.163 | WARNING | Wait too long
2021-07-23 12:52:19.163 | INFO | Saving error: ./log/error/1627069939163
2021-07-23 12:52:31.138 | WARNING | com.YoStarEN.AzurLane will be restart in 10 seconds
2021-07-23 12:52:31.138 | WARNING | If you are playing by hand, please stop Alas
```

**Comment by LmeSzinc** [comment]
The call of this, has been deleted in ad6a2447aea59cad4f064f6fd6e299e8638926f0. It should be fine now.
```
2021-07-19 00:25:05.388 | INFO | No guild mission found, mission of this week may not started
2021-07-19 00:25:05.389 | INFO | Guild mission choose found
```

About the second one, can you send the last screenshot saved in `./log/error/1627069939163`
```
2021-07-23 12:51:18.956 | INFO | [UI route] page_main - page_reward
2021-07-23 12:51:18.956 | INFO | <<< UI CLICK >>>
2021-07-23 12:51:18.957 | INFO | Click (  13,  171) @ MAIN_GOTO_REWARD
2021-07-23 12:52:19.162 | WARNING | Wait too long
2021-07-23 12:52:19.162 | WARNING | Waiting for {'RESEARCH_CHECK', 'REWARD_CHECK', 'GUILD_POPUP_CONFIRM', 'MAIN_GOTO_REWARD', 'SHIPYARD_CHECK', 'GET_SHIP', 'EVENT_LIST_CHECK', 'GET_ITEMS_1', 'LOGIN_ANNOUNCE', 'LOGIN_RETURN_SIGN', 'RESHMENU_CHECK', 'POPUP_CANCEL'}
2021-07-23 12:52:19.163 | WARNING | Wait too long
2021-07-23 12:52:19.163 | INFO | Saving error: ./log/error/1627069939163
```

**Comment by markmarkyesyes** [comment]
It's a little lewd for github, but its just a screenshot of the default build screen on the event banner. In fact, all of the screenshots in that folder are the same. I've attached the log text from that folder below.
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/6872516/log.txt)
Thanks so much for the quick response and feedback!

**Comment by markmarkyesyes** [comment]
Just an update that this is still broken for me, rewards are essentially not usable unattended with this bug

**Comment by markmarkyesyes** [comment]
Closing this issue since last in game update. GET_SHIP is still called, but the screen is exited successfully resulting in no ALAS stoppage. Thanks again for the responses.
