### ISSUE TITLE
执行大世界每月全清时，误进入深渊海域

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#542]
大世界全清侵蚀上限已调整为6。
最近几个版本的脚本无法切换至与深渊海域/隐秘海域重叠的探索海域，而且没有正确处理弹出深渊海域进入确认对话框。
![2021-07-19_14-41-58-865440](https://user-images.githubusercontent.com/70339606/126238625-168d7ede-d6de-488b-8780-6cb41bf0d6f9.png)
![2021-07-19_14-41-59-836702](https://user-images.githubusercontent.com/70339606/126238631-d9979293-3fca-4aa2-8d1c-5a49a927c02f.png)
![2021-07-19_14-42-00-655354](https://user-images.githubusercontent.com/70339606/126238635-df39fc05-051c-4078-a6c0-10ec8aa18475.png)
![2021-07-19_14-42-02-915717](https://user-images.githubusercontent.com/70339606/126238644-f1cab83c-f60e-4f72-a225-7a83d6da06ab.png)
![2021-07-19_14-42-03-833697](https://user-images.githubusercontent.com/70339606/126238652-65a1951d-2290-4d9e-afcb-ee2f50c5c1b8.png)

2021-07-19 14:40:13.461 | INFO | [battle_count] 11
2021-07-19 14:40:13.461 | INFO | Auto search combat loading
2021-07-19 14:40:13.461 | INFO | Screenshot interval set to 1.0s
2021-07-19 14:40:21.430 | INFO | Auto Search combat execute
2021-07-19 14:40:46.389 | INFO | Click (1250,  584) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
2021-07-19 14:40:48.318 | INFO | Click ( 635,  610) @ AUTO_SEARCH_REWARD
2021-07-19 14:40:51.406 | INFO | Get OS auto search reward
2021-07-19 14:40:52.388 | INFO | OS auto search finished
2021-07-19 14:40:52.435 | INFO | No akashi on this map
2021-07-19 14:40:52.437 | INFO | [HP]  98%  98%  98%  98%  98%  98%
2021-07-19 14:40:52.437 | INFO | No ship found to be below threshold 40%, continue OS exploration
2021-07-19 14:40:52.437 | INFO | <<< GLOBE GOTO: [52|东南洋脊B|SOUTHEAST OCEAN RIDGE B|南東海嶺B] >>>
2021-07-19 14:40:52.439 | INFO | <<< UI CLICK >>>
2021-07-19 14:40:52.441 | INFO | Click (1154,  663) @ MAP_GOTO_GLOBE
2021-07-19 14:40:57.481 | INFO | Swipe ( 482,  470) -> ( 533,  423), 0.153
2021-07-19 14:41:01.618 | INFO |           globe_center: (1399.0, 1524.0)
2021-07-19 14:41:01.619 | INFO | 0.103s      similarity: 0.495
2021-07-19 14:41:01.619 | INFO | [Globe_center] [63|NA海域东南C|NA Ocean SE Sector C|NA海域南東C]
2021-07-19 14:41:01.619 | INFO | Globe focus_to: [52|东南洋脊B|Southeast Ocean Ridge B|南東海嶺B]
2021-07-19 14:41:01.621 | INFO | Click ( 525,  254) @ ZONE_52
2021-07-19 14:41:02.611 | INFO |           globe_center: (1389.0, 1312.0)
2021-07-19 14:41:02.611 | INFO | 0.100s      similarity: 0.383
2021-07-19 14:41:02.612 | INFO | [Globe_center] [63|NA海域东南C|NA Ocean SE Sector C|NA海域南東C]
2021-07-19 14:41:03.593 | INFO |           globe_center: (1389.0, 1312.0)
2021-07-19 14:41:03.593 | INFO | 0.101s      similarity: 0.353
2021-07-19 14:41:03.594 | INFO | [Globe_center] [63|NA海域东南C|NA Ocean SE Sector C|NA海域南東C]
2021-07-19 14:41:03.595 | INFO | [Globe_pinned] [52|东南洋脊B|Southeast Ocean Ridge B|南東海嶺B]
2021-07-19 14:41:03.596 | INFO | Zone is safe, stopped
2021-07-19 14:41:03.597 | INFO | Swipe ( 441,  430) -> ( 489,  378), 0.16
2021-07-19 14:41:06.513 | INFO | <<< GLOBE GOTO: [53|东南洋脊C|SOUTHEAST OCEAN RIDGE C|南東海嶺C] >>>
2021-07-19 14:41:07.639 | INFO |           globe_center: (1363.0, 1344.0)
2021-07-19 14:41:07.639 | INFO | 0.099s      similarity: 0.481
2021-07-19 14:41:07.639 | INFO | [Globe_center] [63|NA海域东南C|NA Ocean SE Sector C|NA海域南東C]
2021-07-19 14:41:07.639 | INFO | Globe focus_to: [53|东南洋脊C|Southeast Ocean Ridge C|南東海嶺C]
2021-07-19 14:41:07.642 | INFO | Click ( 323,  556) @ ZONE_53
2021-07-19 14:41:08.626 | INFO |           globe_center: (1207.0, 1478.0)
2021-07-19 14:41:08.626 | INFO | 0.104s      similarity: 0.425
2021-07-19 14:41:08.627 | INFO | [Globe_center] [52|东南洋脊B|Southeast Ocean Ridge B|南東海嶺B]
2021-07-19 14:41:09.632 | INFO |           globe_center: (1207.0, 1478.0)
2021-07-19 14:41:09.632 | INFO | 0.103s      similarity: 0.364
2021-07-19 14:41:09.632 | INFO | [Globe_center] [52|东南洋脊B|Southeast Ocean Ridge B|南東海嶺B]
2021-07-19 14:41:09.633 | INFO | [Globe_pinned] [53|东南洋脊C|Southeast Ocean Ridge C|南東海嶺C]
2021-07-19 14:41:09.633 | INFO | Zone is safe, stopped
2021-07-19 14:41:09.634 | INFO | Swipe ( 516,  458) -> ( 572,  406), 0.156
2021-07-19 14:41:12.540 | INFO | <<< GLOBE GOTO: [51|东南洋脊A|SOUTHEAST OCEAN RIDGE A|南東海嶺A] >>>
2021-07-19 14:41:13.633 | INFO |           globe_center: (1175.0, 1512.0)
2021-07-19 14:41:13.633 | INFO | 0.102s      similarity: 0.512
2021-07-19 14:41:13.634 | INFO | [Globe_center] [53|东南洋脊C|Southeast Ocean Ridge C|南東海嶺C]
2021-07-19 14:41:13.634 | INFO | Globe focus_to: [51|东南洋脊A|Southeast Ocean Ridge A|南東海嶺A]
2021-07-19 14:41:13.636 | INFO | Click ( 545,  245) @ ZONE_51
2021-07-19 14:41:14.668 | INFO |           globe_center: (1191.0, 1276.0)
2021-07-19 14:41:14.668 | INFO | 0.099s      similarity: 0.479
2021-07-19 14:41:14.668 | INFO | [Globe_center] [159|NA海域深处H|NA Ocean Depths H|NA海域深部H]
2021-07-19 14:41:15.637 | INFO |           globe_center: (1191.0, 1276.0)
2021-07-19 14:41:15.637 | INFO | 0.104s      similarity: 0.397
2021-07-19 14:41:15.637 | INFO | [Globe_center] [159|NA海域深处H|NA Ocean Depths H|NA海域深部H]
2021-07-19 14:41:15.637 | INFO | [Globe_pinned] [51|东南洋脊A|Southeast Ocean Ridge A|南東海嶺A]
2021-07-19 14:41:15.638 | INFO | Zone is safe, stopped
2021-07-19 14:41:15.639 | INFO | Swipe ( 479,  430) -> ( 528,  379), 0.179
2021-07-19 14:41:18.634 | INFO | <<< GLOBE GOTO: [13|卡利比安海C|CARIBBEAN SEA C|カリブ海C] >>>
2021-07-19 14:41:19.720 | INFO |           globe_center: (1163.0, 1310.0)
2021-07-19 14:41:19.720 | INFO | 0.102s      similarity: 0.548
2021-07-19 14:41:19.721 | INFO | [Globe_center] [159|NA海域深处H|NA Ocean Depths H|NA海域深部H]
2021-07-19 14:41:19.721 | INFO | Globe focus_to: [13|卡利比安海C|Caribbean Sea C|カリブ海C]
2021-07-19 14:41:19.723 | INFO | Swipe (  62,  432) -> ( 880,  295), 0.149
2021-07-19 14:41:21.040 | INFO |           globe_center: (693.0, 1400.0)
2021-07-19 14:41:21.040 | INFO | 0.109s      similarity: 0.631
2021-07-19 14:41:21.040 | INFO | [Globe_center] [31|西南洋脊A|Southwest Ocean Ridge A|南西海嶺A]
2021-07-19 14:41:21.040 | INFO | Click ( 182,  551) @ ZONE_13
2021-07-19 14:41:22.027 | INFO |           globe_center: (411.0, 1530.0)
2021-07-19 14:41:22.027 | INFO | 0.110s      similarity: 0.465
2021-07-19 14:41:22.027 | INFO | [Globe_center] [14|卡利比安海D|Caribbean Sea D|カリブ海D]
2021-07-19 14:41:23.017 | INFO |           globe_center: (411.0, 1530.0)
2021-07-19 14:41:23.017 | INFO | 0.105s      similarity: 0.393
2021-07-19 14:41:23.018 | INFO | [Globe_center] [14|卡利比安海D|Caribbean Sea D|カリブ海D]
2021-07-19 14:41:23.019 | INFO | [Globe_pinned] [13|卡利比安海C|Caribbean Sea C|カリブ海C]
2021-07-19 14:41:23.020 | INFO | Zone is safe, stopped
2021-07-19 14:41:23.020 | INFO | Swipe ( 460,  456) -> ( 508,  401), 0.176
2021-07-19 14:41:25.964 | INFO | <<< GLOBE GOTO: [12|卡利比安海B|CARIBBEAN SEA B|カリブ海B] >>>
2021-07-19 14:41:27.084 | INFO |           globe_center: (381.0, 1568.0)
2021-07-19 14:41:27.085 | INFO | 0.107s      similarity: 0.499
2021-07-19 14:41:27.085 | INFO | [Globe_center] [14|卡利比安海D|Caribbean Sea D|カリブ海D]
2021-07-19 14:41:27.085 | INFO | Globe focus_to: [12|卡利比安海B|Caribbean Sea B|カリブ海B]
2021-07-19 14:41:27.087 | INFO | Click ( 515,  285) @ ZONE_12
2021-07-19 14:41:28.096 | INFO |           globe_center: (359.0, 1398.0)
2021-07-19 14:41:28.096 | INFO | 0.109s      similarity: 0.501
2021-07-19 14:41:28.096 | INFO | [Globe_center] [24|NA海域西南D|NA Ocean SW Sector D|NA海域南西D]
2021-07-19 14:41:29.093 | INFO |           globe_center: (359.0, 1398.0)
2021-07-19 14:41:29.094 | INFO | 0.110s      similarity: 0.448
2021-07-19 14:41:29.094 | INFO | [Globe_center] [24|NA海域西南D|NA Ocean SW Sector D|NA海域南西D]
2021-07-19 14:41:29.095 | INFO | [Globe_pinned] [12|卡利比安海B|Caribbean Sea B|カリブ海B]
2021-07-19 14:41:29.096 | INFO | Zone is safe, stopped
2021-07-19 14:41:29.097 | INFO | Swipe ( 533,  461) -> ( 580,  413), 0.134
2021-07-19 14:41:31.979 | INFO | <<< GLOBE GOTO: [102|西北航道B|NORTHWEST PASSAGE B|北西航路B] >>>
2021-07-19 14:41:33.106 | INFO |           globe_center: (333.0, 1428.0)
2021-07-19 14:41:33.107 | INFO | 0.107s      similarity: 0.561
2021-07-19 14:41:33.107 | INFO | [Globe_center] [24|NA海域西南D|NA Ocean SW Sector D|NA海域南西D]
2021-07-19 14:41:33.107 | INFO | Globe focus_to: [102|西北航道B|Northwest Passage B|北西航路B]
2021-07-19 14:41:33.109 | INFO | Swipe ( 553,  249) -> ( 465,  592), 0.134
2021-07-19 14:41:34.310 | INFO |           globe_center: (379.0, 1218.0)
2021-07-19 14:41:34.310 | INFO | 0.106s      similarity: 0.581
2021-07-19 14:41:34.311 | INFO | [Globe_center] [44|西大陆架D|West Continental Shelf D|西大陸棚D]
2021-07-19 14:41:34.311 | INFO | Swipe ( 307,  259) -> ( 279,  602), 0.155
2021-07-19 14:41:35.623 | INFO |           globe_center: (379.0, 1218.0)
2021-07-19 14:41:35.623 | INFO | 0.107s      similarity: 0.581
2021-07-19 14:41:35.623 | INFO | [Globe_center] [44|西大陆架D|West Continental Shelf D|西大陸棚D]
2021-07-19 14:41:35.624 | INFO | Swipe ( 730,  249) -> ( 702,  592), 0.152
2021-07-19 14:41:36.952 | INFO |           globe_center: (395.0, 988.0)
2021-07-19 14:41:36.952 | INFO | 0.103s      similarity: 0.531
2021-07-19 14:41:36.953 | INFO | [Globe_center] [0|NY|NY City|NYシティ]
2021-07-19 14:41:36.953 | INFO | Swipe ( 571,  252) -> ( 564,  595), 0.175
2021-07-19 14:41:38.328 | INFO |           globe_center: (399.0, 774.0)
2021-07-19 14:41:38.328 | INFO | 0.104s      similarity: 0.533
2021-07-19 14:41:38.328 | INFO | [Globe_center] [42|西大陆架B|West Continental Shelf B|西大陸棚B]
2021-07-19 14:41:38.329 | INFO | Swipe ( 633,  242) -> ( 632,  585), 0.152
2021-07-19 14:41:39.590 | INFO |           globe_center: (399.0, 544.0)
2021-07-19 14:41:39.590 | INFO | 0.104s      similarity: 0.625
2021-07-19 14:41:39.592 | INFO | [Globe_center] [103|西北航道C|Northwest Passage C|北西航路C]
2021-07-19 14:41:39.592 | INFO | Swipe ( 235,  259) -> ( 234,  503), 0.139
2021-07-19 14:41:40.824 | INFO |           globe_center: (399.0, 544.0)
2021-07-19 14:41:40.824 | INFO | 0.102s      similarity: 0.624
2021-07-19 14:41:40.824 | INFO | [Globe_center] [103|西北航道C|Northwest Passage C|北西航路C]
2021-07-19 14:41:40.825 | INFO | Swipe ( 402,  314) -> ( 401,  558), 0.126
2021-07-19 14:41:42.028 | INFO |           globe_center: (399.0, 380.0)
2021-07-19 14:41:42.028 | INFO | 0.102s      similarity: 0.572
2021-07-19 14:41:42.028 | INFO | [Globe_center] [103|西北航道C|Northwest Passage C|北西航路C]
2021-07-19 14:41:42.029 | INFO | Click ( 370,  295) @ ZONE_102
2021-07-19 14:41:43.024 | INFO |           globe_center: (221.0, 214.0)
2021-07-19 14:41:43.024 | INFO | 0.104s      similarity: 0.370
2021-07-19 14:41:43.024 | INFO | [Globe_center] [103|西北航道C|Northwest Passage C|北西航路C]
2021-07-19 14:41:44.010 | INFO |           globe_center: (221.0, 214.0)
2021-07-19 14:41:44.010 | INFO | 0.104s      similarity: 0.363
2021-07-19 14:41:44.010 | INFO | [Globe_center] [103|西北航道C|Northwest Passage C|北西航路C]
2021-07-19 14:41:44.011 | INFO | [Globe_pinned] [102|西北航道B|Northwest Passage B|北西航路B]
2021-07-19 14:41:44.012 | INFO | Zone is safe, stopped
2021-07-19 14:41:44.013 | INFO | Swipe ( 512,  466) -> ( 564,  413), 0.142
2021-07-19 14:41:46.922 | INFO | <<< GLOBE GOTO: [101|西北航道A|NORTHWEST PASSAGE A|北西航路A] >>>
2021-07-19 14:41:48.019 | INFO |           globe_center: (191.0, 250.0)
2021-07-19 14:41:48.019 | INFO | 0.103s      similarity: 0.399
2021-07-19 14:41:48.020 | INFO | [Globe_center] [102|西北航道B|Northwest Passage B|北西航路B]
2021-07-19 14:41:48.020 | INFO | Globe focus_to: [101|西北航道A|Northwest Passage A|北西航路A]
2021-07-19 14:41:48.022 | INFO | Click ( 602,  225) @ ZONE_101
2021-07-19 14:41:49.009 | INFO |           globe_center: (273.0, -22.0)
2021-07-19 14:41:49.009 | INFO | 0.109s      similarity: 0.242
2021-07-19 14:41:49.009 | INFO | [Globe_center] [101|西北航道A|Northwest Passage A|北西航路A]
2021-07-19 14:41:50.049 | INFO |           globe_center: (273.0, -22.0)
2021-07-19 14:41:50.049 | INFO | 0.107s      similarity: 0.238
2021-07-19 14:41:50.049 | INFO | [Globe_center] [101|西北航道A|Northwest Passage A|北西航路A]
2021-07-19 14:41:50.050 | INFO | [Globe_pinned] [101|西北航道A|Northwest Passage A|北西航路A]
2021-07-19 14:41:50.051 | INFO | Zone is safe, stopped
2021-07-19 14:41:50.052 | INFO | Swipe ( 458,  429) -> ( 509,  373), 0.166
2021-07-19 14:41:53.089 | INFO | <<< GLOBE GOTO: [144|东北航道D|NORTHEAST PASSAGE D|北東航路D] >>>
2021-07-19 14:41:54.187 | INFO |           globe_center: (247.0, 14.0)
2021-07-19 14:41:54.187 | INFO | 0.106s      similarity: 0.322
2021-07-19 14:41:54.188 | INFO | [Globe_center] [101|西北航道A|Northwest Passage A|北西航路A]
2021-07-19 14:41:54.188 | INFO | Globe focus_to: [144|东北航道D|Northeast Passage D|北東航路D]
2021-07-19 14:41:54.190 | INFO | Swipe ( 871,  531) -> (  53,  273), 0.144
2021-07-19 14:41:55.427 | INFO |           globe_center: (685.0, 174.0)
2021-07-19 14:41:55.427 | INFO | 0.107s      similarity: 0.470
2021-07-19 14:41:55.428 | INFO | [Globe_center] [104|西北航道D|Northwest Passage D|北西航路D]
2021-07-19 14:41:55.428 | INFO | Swipe ( 848,  547) -> (  30,  450), 0.143
2021-07-19 14:41:56.675 | INFO |           globe_center: (1117.0, 232.0)
2021-07-19 14:41:56.675 | INFO | 0.106s      similarity: 0.531
2021-07-19 14:41:56.676 | INFO | [Globe_center] [92|NA海域西北B|NA Ocean NW Sector B|NA海域北西B]
2021-07-19 14:41:56.676 | INFO | Swipe ( 849,  494) -> (  31,  456), 0.151
2021-07-19 14:41:57.951 | INFO |           globe_center: (1575.0, 258.0)
2021-07-19 14:41:57.951 | INFO | 0.108s      similarity: 0.571
2021-07-19 14:41:57.952 | INFO | [Globe_center] [143|东北航道C|Northeast Passage C|北東航路C]
2021-07-19 14:41:57.952 | INFO | Click ( 982,  363) @ ZONE_144
2021-07-19 14:41:58.969 | INFO |           globe_center: (2007.0, 192.0)
2021-07-19 14:41:58.969 | INFO | 0.104s      similarity: 0.515
2021-07-19 14:41:58.971 | INFO | [Globe_center] [144|东北航道D|Northeast Passage D|北東航路D]
2021-07-19 14:41:59.938 | INFO |           globe_center: (2067.0, 182.0)
2021-07-19 14:41:59.938 | INFO | 0.102s      similarity: 0.333
2021-07-19 14:41:59.939 | INFO | [Globe_center] [144|东北航道D|Northeast Passage D|北東航路D]
2021-07-19 14:41:59.940 | INFO | [Globe_pinned] [144|东北航道D|Northeast Passage D|北東航路D]
2021-07-19 14:41:59.942 | INFO | Zone has no type to select, skip
2021-07-19 14:41:59.946 | INFO | Click ( 467,  305) @ ZONE_ENTRANCE
2021-07-19 14:42:00.667 | INFO | Click ( 780,  509) @ POPUP_CONFIRM_GLOBE_ENTER
2021-07-19 14:42:05.883 | INFO | [MAP_NAME 0.040s] 北東航路D異常海域
2021-07-19 14:42:05.883 | INFO | Map name processed: 北東航路D異常
2021-07-19 14:42:05.884 | WARNING | Unable to find OS globe zone: 北東航路d異常
2021-07-19 14:42:05.884 | ERROR | Unable to find OS globe zone: 北東航路d異常
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 237, in os_world_clear
    az.run_clear_os_world()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\os_run.py", line 49, in run_clear_os_world
    self.campaign.clear_os_world()
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 248, in clear_os_world
    self._clear_os_world()
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 231, in _clear_os_world
    if not self.globe_goto(zone, stop_if_safe=True):
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 93, in globe_goto
    self.get_current_zone()
  File "C:\fakepath\AzurLaneAutoScript\module\os\map_operation.py", line 86, in get_current_zone
    self.zone = self.name_to_zone(name)
  File "C:\fakepath\AzurLaneAutoScript\module\os\globe_zone.py", line 113, in name_to_zone
    raise ScriptError(f'Unable to find OS globe zone: {name}')
module.exception.ScriptError: Unable to find OS globe zone: 北東航路d異常
2021-07-19 14:42:05.893 | INFO | Saving error: ./log/error/1626730925893

**Comment by LmeSzinc** [comment]
日服未更新 ZONE_SWITCH
更新可参照 #537

**Comment by railzy** [comment]
> 日服未更新 ZONE_SWITCH
> 更新可参照 #537

有一个疑问，文字部分是半透明的，因此截取部分会由于底层海域状态的不同而产生一些差别，是否会影响识别呢
![image](https://user-images.githubusercontent.com/57893649/126259429-1ec1c7f4-61f8-421d-a025-9adbec6d22b6.png)
