### ISSUE TITLE
出现伏击舰队时，脚本停止运行

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#543]
出现伏击舰队界面时，识图工作不正常，判定此时不在作战海域中（| WARNING | Image to detect is not in_map）
随后立刻出现 | ERROR | Failed to find a free tile ，脚本终止。

![2021-07-19_17-16-25-339733](https://user-images.githubusercontent.com/70339606/126244840-e41de9f3-b4d8-421b-9a71-e644c776c4a8.png)
![2021-07-19_17-16-26-478514](https://user-images.githubusercontent.com/70339606/126244847-46d33adc-1338-4d52-846d-05733a8bd2ff.png)
![2021-07-19_17-16-27-779533](https://user-images.githubusercontent.com/70339606/126244852-f721f842-1cec-4ea3-887e-ef4679e9cdb0.png)

2021-07-19 17:15:53.168 | INFO | ==================== CAMPAIGN_7_2 ====================
2021-07-19 17:15:53.168 | INFO | Count: [0]
2021-07-19 17:15:53.531 | INFO | <<< UI ENSURE >>>
2021-07-19 17:15:53.923 | INFO | [UI] page_main
2021-07-19 17:15:53.923 | INFO | Goto page_campaign
2021-07-19 17:15:53.923 | INFO | [UI route] page_main - page_campaign_menu - page_campaign
2021-07-19 17:15:53.923 | INFO | <<< UI CLICK >>>
2021-07-19 17:15:54.290 | INFO | Click (1086,  322) @ MAIN_GOTO_CAMPAIGN
2021-07-19 17:15:55.563 | INFO | <<< UI CLICK >>>
2021-07-19 17:15:55.572 | INFO | Click ( 322,  405) @ CAMPAIGN_MENU_GOTO_CAMPAIGN
2021-07-19 17:15:57.735 | INFO | [Mode_switch_1] hard
2021-07-19 17:15:57.735 | INFO | <<< UI ENSURE INDEX >>>
2021-07-19 17:15:57.857 | INFO | [campaign 0.022s] ['7--2', '7--3', '7--4', '7--1']
2021-07-19 17:15:57.857 | INFO | [Chapter] 7
2021-07-19 17:15:57.857 | INFO | [Stage] 7-2, 7-3, 7-4, 7-1
2021-07-19 17:15:57.857 | INFO | [Index] 7
2021-07-19 17:15:57.877 | INFO | [OCR_OIL 0.017s] 8810
2021-07-19 17:15:57.877 | INFO | -------------------- 7-2 --------------------
2021-07-19 17:15:57.877 | INFO | <<< ENTER MAP >>>
2021-07-19 17:15:58.179 | INFO | Click ( 448,  211) @ 7-2
2021-07-19 17:15:59.791 | INFO | [MAP_CLEAR_ALL_THIS_TIME] False
2021-07-19 17:15:59.792 | INFO | [Map_info] 99%, star_1, star_2, star_3, clear, 3_star, green, fast_forward
2021-07-19 17:15:59.792 | INFO | [STOP_IF_MAP_REACH] no
2021-07-19 17:15:59.792 | INFO | [Fast_Forward] off
2021-07-19 17:15:59.819 | INFO | No auto search option.
2021-07-19 17:15:59.819 | INFO | Click ( 927,  511) @ MAP_PREPARATION
2021-07-19 17:16:00.335 | INFO | Using fleet: [1, 2, 0]
2021-07-19 17:16:00.335 | INFO | [Light_orange_line] 0
2021-07-19 17:16:00.335 | INFO | Click (1102,  340) @ FLEET_2_CLEAR
2021-07-19 17:16:00.973 | INFO | Click (1041,  192) @ FLEET_1_CHOOSE
2021-07-19 17:16:01.620 | INFO | Current selected: [1]
2021-07-19 17:16:01.620 | INFO | Click (1035,  191) @ FLEET_1_CHOOSE
2021-07-19 17:16:02.258 | INFO | Click (1029,  330) @ FLEET_2_CHOOSE
2021-07-19 17:16:02.890 | INFO | Current selected: [1]
2021-07-19 17:16:02.890 | INFO | Click (1047,  426) @ FLEET_2_BAR_INDEX_2
2021-07-19 17:16:03.565 | INFO | Click (1036,  617) @ FLEET_PREPARATION
2021-07-19 17:16:09.213 | INFO | Enemy searching appeared.
2021-07-19 17:16:09.495 | INFO | No fleet lock option.
2021-07-19 17:16:09.495 | INFO | <<< MAP INIT >>>
2021-07-19 17:16:09.496 | INFO | Load map_data, has_loop=False, use_loop=False
2021-07-19 17:16:09.496 | INFO | Load spawn_data, has_loop=False, use_loop=False
2021-07-19 17:16:09.496 | INFO | grid_connection: wall=False, portal=False
2021-07-19 17:16:09.496 | INFO | Load mechanism, land_base=False, maze=False
2021-07-19 17:16:09.501 | INFO | [Map_buff] 2
2021-07-19 17:16:09.501 | INFO | Skip strategy bar check.
2021-07-19 17:16:09.912 | INFO |           vanish_point: (  624, -1744)
2021-07-19 17:16:09.912 | INFO |          distant_point: (-2340, -1744)
2021-07-19 17:16:09.936 | INFO | 0.132s  _   Horizontal: 6 (6 inner, 2 edge)
2021-07-19 17:16:09.936 | INFO | Edges: /_\    Vertical: 9 (10 inner, 2 edge)
2021-07-19 17:16:09.936 | INFO | [homo_storage] ((8, 5), [(227.7, 151.178), (1158.289, 151.178), (130.908, 613.267), (1288.372, 613.267)])
2021-07-19 17:16:09.987 | INFO |            tile_center: 0.942 (good match)
2021-07-19 17:16:09.998 | INFO | 0.061s  _   edge_lines: 3 hori, 2 vert
2021-07-19 17:16:09.998 | INFO | Edges: /_\   homo_loca: ( 18,  51)
2021-07-19 17:16:10.001 | INFO |            center_loca: (3, 2)
2021-07-19 17:16:10.001 | INFO |                 Camera: A1
2021-07-19 17:16:10.013 | INFO | [HP]  98% ____ ____  98%  98% ____
2021-07-19 17:16:10.059 | INFO | [LevelOcr 0.037s] [108, 0, 0, 113, 98, 0]
2021-07-19 17:16:10.059 | INFO | [LEVEL] 108, 0, 0, 113, 98, 0
2021-07-19 17:16:10.059 | INFO | Ensure edge in sight.
2021-07-19 17:16:10.347 | INFO |            tile_center: 0.942 (good match)
2021-07-19 17:16:10.355 | INFO | 0.044s  _   edge_lines: 3 hori, 2 vert
2021-07-19 17:16:10.355 | INFO | Edges: /_\   homo_loca: ( 18,  51)
2021-07-19 17:16:10.358 | INFO |            center_loca: (3, 2)
2021-07-19 17:16:10.358 | INFO |       camera_corrected: A1 -> D3
2021-07-19 17:16:10.359 | INFO |                 Camera: D3
2021-07-19 17:16:10.359 | INFO | Full scan start, mode=normal
2021-07-19 17:16:10.359 | INFO | [enemy_missing] EN: 3, MY: 0, SI: 0, BO: 0, CA: 0
2021-07-19 17:16:10.359 | INFO | [enemy_may____] EN: 0, MY: 0, SI: 0, BO: 0, CA: 0
2021-07-19 17:16:10.359 | INFO | Focus to: D3
2021-07-19 17:16:10.359 | INFO | Map swipe: (0, 0)
2021-07-19 17:16:10.701 | INFO | 0.085s         predict: 39
2021-07-19 17:16:10.701 | INFO | -- -- -- -- -- -- -- Fl
2021-07-19 17:16:10.701 | INFO | -- -- -- -- -- -- 1L --
2021-07-19 17:16:10.701 | INFO | -- -- 2M -- -- -- -- --
2021-07-19 17:16:10.701 | INFO | -- 1M -- -- -- -- -- --
2021-07-19 17:16:10.701 | INFO | FL -- -- -- -- -- -- ..
2021-07-19 17:16:10.702 | INFO | [enemy_missing] EN: 0, MY: 0, SI: 0, BO: 0, CA: 0
2021-07-19 17:16:10.702 | INFO | [enemy_may____] EN: 1, MY: 0, SI: 0, BO: 0, CA: 1
2021-07-19 17:16:10.702 | INFO | Continue scanning.
2021-07-19 17:16:10.702 | INFO | Focus to: D2
2021-07-19 17:16:10.702 | INFO | Map swipe: (0, -1)
2021-07-19 17:16:10.703 | INFO | Swipe ( 639,  308) -> ( 646,  455), 0.148
2021-07-19 17:16:11.822 | INFO |            tile_center: 0.935 (good match)
2021-07-19 17:16:11.831 | INFO | 0.046s  _   edge_lines: 2 hori, 2 vert
2021-07-19 17:16:11.831 | INFO | Edges: / \   homo_loca: ( 22,  44)
2021-07-19 17:16:11.834 | INFO |            center_loca: (3, 1)
2021-07-19 17:16:11.881 | INFO | Map swipe predict: (0, -1) (0.048s, 5 matches)
2021-07-19 17:16:11.881 | INFO |                 Camera: D2
2021-07-19 17:16:11.881 | INFO |                 Camera: D2
2021-07-19 17:16:11.881 | INFO | Map swipe: (0, 0)
2021-07-19 17:16:12.176 | INFO | 0.034s         predict: 31
2021-07-19 17:16:12.176 | INFO | -- -- -- -- -- -- -- Fl
2021-07-19 17:16:12.176 | INFO | -- -- -- -- -- -- 1L --
2021-07-19 17:16:12.176 | INFO | -- -- 2M -- -- -- -- --
2021-07-19 17:16:12.176 | INFO | -- 1M -- -- -- -- -- ..
2021-07-19 17:16:12.177 | INFO | [enemy_missing] EN: 0, MY: 0, SI: 0, BO: 0, CA: 0
2021-07-19 17:16:12.177 | INFO | [enemy_may____] EN: 1, MY: 0, SI: 0, BO: 0, CA: 1
2021-07-19 17:16:12.177 | INFO |     A  B  C  D  E  F  G  H
2021-07-19 17:16:12.177 | INFO |  1 -- ++ -- -- -- -- -- Fl
2021-07-19 17:16:12.177 | INFO |  2 -- ++ ++ -- -- -- 1L --
2021-07-19 17:16:12.177 | INFO |  3 -- -- 2M -- -- -- -- --
2021-07-19 17:16:12.177 | INFO |  4 -- 1M -- -- -- -- ++ ++
2021-07-19 17:16:12.177 | INFO |  5 FL -- -- -- -- -- ++ ++
2021-07-19 17:16:12.177 | INFO | Predict fleet_2 to be H1
2021-07-19 17:16:12.177 | INFO | <<< FIND CURRENT FLEET >>>
2021-07-19 17:16:12.178 | INFO | Fleets: [H1, A5]
2021-07-19 17:16:12.178 | INFO | [Fleet_1: A5] Fleet_2: H1
2021-07-19 17:16:12.179 | INFO |       A    B    C    D    E    F    G    H
2021-07-19 17:16:12.180 | INFO |  1   13 9999   26   25   26   27   37   47
2021-07-19 17:16:12.180 | INFO |  2   12 9999 9999   15   25   35   27   37
2021-07-19 17:16:12.180 | INFO |  3   11   21   15   14   15   25   26   27
2021-07-19 17:16:12.180 | INFO |  4   10   11   21   13   23   24 9999 9999
2021-07-19 17:16:12.180 | INFO |  5    0   10   11   12   22   23 9999 9999
2021-07-19 17:16:12.180 | INFO | -------------------- BATTLE_0 --------------------
2021-07-19 17:16:12.180 | INFO | Using function: battle_0
2021-07-19 17:16:12.180 | INFO | Fleet 2 step on
2021-07-19 17:16:12.183 | INFO | Fleet_2 step on A3
2021-07-19 17:16:12.183 | INFO | Switch over
2021-07-19 17:16:12.184 | INFO | Click (1019,  688) @ SWITCH_OVER
2021-07-19 17:16:14.151 | INFO |            tile_center: 0.937 (good match)
2021-07-19 17:16:14.157 | INFO | 0.041s      edge_lines: 2 hori, 1 vert
2021-07-19 17:16:14.157 | INFO | Edges:   \   homo_loca: ( 20,  54)
2021-07-19 17:16:14.159 | INFO |           grids_offset: (1, 0)
2021-07-19 17:16:14.159 | INFO |            center_loca: (3, 3)
2021-07-19 17:16:14.160 | INFO |                 Camera: H1
2021-07-19 17:16:14.161 | INFO |       A    B    C    D    E    F    G    H
2021-07-19 17:16:14.162 | INFO |  1   60 9999   23   22   12   11   10    0
2021-07-19 17:16:14.162 | INFO |  2   59 9999 9999   23   22   21   11   10
2021-07-19 17:16:14.162 | INFO |  3   58   68   25   24   23   22   12   11
2021-07-19 17:16:14.162 | INFO |  4   57   36   35   25   33   23 9999 9999
2021-07-19 17:16:14.162 | INFO |  5   47   37   27   26   34   24 9999 9999
2021-07-19 17:16:14.162 | INFO | Fleet_1: A5 [Fleet_2: H1]
2021-07-19 17:16:14.171 | INFO | [HP]  98% ____ ____  98%  98% ____
2021-07-19 17:16:14.207 | INFO | [LevelOcr 0.034s] [118, 0, 0, 118, 111, 0]
2021-07-19 17:16:14.208 | INFO | [LEVEL] 118, 0, 0, 118, 111, 0
2021-07-19 17:16:14.208 | INFO | [Map_buff] 2
2021-07-19 17:16:14.208 | INFO | Skip strategy bar check.
2021-07-19 17:16:14.208 | INFO | Full path: [H1, H2, H3, G3, F3, E3, D3, D4, D5, C5, B5, A5, A4, A3]
2021-07-19 17:16:14.208 | INFO | Path_node_avoid: A5
2021-07-19 17:16:14.208 | INFO | Path: [D3, B5, A4, A3]
2021-07-19 17:16:14.208 | INFO | In sight: D3
2021-07-19 17:16:14.209 | INFO | Focus to: G1
2021-07-19 17:16:14.209 | INFO | Map swipe: (-1, 0)
2021-07-19 17:16:14.209 | INFO | Swipe ( 476,  283) -> ( 685,  284), 0.171
2021-07-19 17:16:15.328 | INFO |            tile_center: 0.922 (good match)
2021-07-19 17:16:15.335 | INFO | 0.041s      edge_lines: 2 hori, 1 vert
2021-07-19 17:16:15.335 | INFO | Edges:   \   homo_loca: ( 22,  54)
2021-07-19 17:16:15.337 | INFO |           grids_offset: (1, 0)
2021-07-19 17:16:15.338 | INFO |            center_loca: (3, 3)
2021-07-19 17:16:15.348 | INFO | Map swipe predict: (-1, 0) (0.010s, current fleet match)
2021-07-19 17:16:15.349 | INFO |                 Camera: G1
2021-07-19 17:16:15.349 | INFO |                 Camera: G1
2021-07-19 17:16:15.349 | INFO | Map swipe: (0, 0)
2021-07-19 17:16:15.599 | INFO | Global D3 (camera=G1) -> Local A6 (center=D4)
2021-07-19 17:16:15.600 | INFO | Click ( 207,  573) @ A6
2021-07-19 17:16:19.281 | INFO | Arrive D3
2021-07-19 17:16:19.979 | INFO | Arrive D3 confirm. Result: nothing. Expected: 
2021-07-19 17:16:19.981 | INFO | In sight: B5
2021-07-19 17:16:19.981 | INFO | Focus to: E3
2021-07-19 17:16:19.981 | INFO | Map swipe: (-2, 2)
2021-07-19 17:16:19.982 | INFO | Swipe ( 582,  556) -> ( 994,  272), 0.128
2021-07-19 17:16:20.998 | INFO |            tile_center: 0.970 (good match)
2021-07-19 17:16:21.005 | INFO | 0.043s  _   edge_lines: 3 hori, 1 vert
2021-07-19 17:16:21.005 | INFO | Edges:  _\   homo_loca: (115, 107)
2021-07-19 17:16:21.008 | INFO |            center_loca: (3, 2)
2021-07-19 17:16:21.018 | INFO | Map swipe predict: (-2, 2) (0.011s, current fleet match)
2021-07-19 17:16:21.018 | INFO |                 Camera: E3
2021-07-19 17:16:21.018 | INFO |                 Camera: E3
2021-07-19 17:16:21.019 | INFO | Map swipe: (0, 0)
2021-07-19 17:16:21.019 | INFO | Swipe ( 614,  427) -> ( 685,  373), 0.135
2021-07-19 17:16:22.060 | INFO |            tile_center: 0.970 (good match)
2021-07-19 17:16:22.068 | INFO | 0.042s  _   edge_lines: 3 hori, 1 vert
2021-07-19 17:16:22.068 | INFO | Edges:  _\   homo_loca: ( 15,  64)
2021-07-19 17:16:22.071 | INFO |           grids_offset: (1, 0)
2021-07-19 17:16:22.071 | INFO |            center_loca: (3, 2)
2021-07-19 17:16:22.071 | INFO |                 Camera: E3
2021-07-19 17:16:22.072 | INFO | Global B5 (camera=E3) -> Local A5 (center=D3)
2021-07-19 17:16:22.072 | INFO | Click ( 202,  575) @ A5
2021-07-19 17:16:24.805 | INFO | Arrive B5
2021-07-19 17:16:25.344 | INFO | Arrive B5 confirm. Result: nothing. Expected: 
2021-07-19 17:16:25.346 | INFO | In sight: A4
2021-07-19 17:16:25.346 | INFO | Focus to: D3
2021-07-19 17:16:25.346 | INFO | Map swipe: (-1, 0)
2021-07-19 17:16:25.347 | INFO | Swipe ( 602,  407) -> ( 819,  398), 0.155
2021-07-19 17:16:26.516 | INFO |            tile_center: 0.609 (bad match)
2021-07-19 17:16:26.643 | INFO |            tile_corner: 0.884 (3 matches)
2021-07-19 17:16:26.648 | INFO | 0.168s      edge_lines: 2 hori, 0 vert
2021-07-19 17:16:26.648 | INFO | Edges:       homo_loca: ( 70,  72)
2021-07-19 17:16:26.652 | INFO |            center_loca: (4, 3)
2021-07-19 17:16:26.724 | INFO | Map swipe predict: None (0.071s, no match)
2021-07-19 17:16:26.725 | INFO |                 Camera: D3
2021-07-19 17:16:26.725 | INFO |                 Camera: D3
2021-07-19 17:16:26.725 | INFO | Map swipe: (0, 0)
2021-07-19 17:16:26.725 | INFO | Swipe ( 760,  415) -> ( 689,  397), 0.161
2021-07-19 17:16:27.816 | INFO |            tile_center: 0.615 (bad match)
2021-07-19 17:16:27.928 | INFO |            tile_corner: 0.795 (bad match)
2021-07-19 17:16:27.998 | INFO |         tile_rectangle: 0 rectangles (bad match)
2021-07-19 17:16:28.000 | WARNING | Image to detect is not in_map
2021-07-19 17:16:28.001 | ERROR | Failed to find a free tile
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 137, in main
    az.run(self.config.CAMPAIGN_NAME)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 224, in run
    self.campaign.run()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 140, in run
    self.execute_a_battle()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 96, in execute_a_battle
    result = self.battle_function()
  File "C:\fakepath\AzurLaneAutoScript\module\base\decorator.py", line 69, in wrapper
    return record['func'](self, *args, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 86, in battle_function
    result = func()
  File "C:\fakepath\AzurLaneAutoScript\campaign\campaign_main\campaign_7_2.py", line 53, in battle_0
    if self.fleet_2_step_on(FLEET_2_STEP_ON, roadblocks=[ROAD_MAIN]):
  File "C:\fakepath\AzurLaneAutoScript\module\map\map.py", line 464, in fleet_2_step_on
    self.fleet_2.goto(grid)
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 411, in goto
    self._goto(node, expected=expected if node == nodes[-1] else '')
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 250, in _goto
    self.in_sight(location, sight=self._walk_sight)
  File "C:\fakepath\AzurLaneAutoScript\module\map\camera.py", line 306, in in_sight
    self.focus_to((self.camera[0] + x, self.camera[1] + y))
  File "C:\fakepath\AzurLaneAutoScript\module\map\camera.py", line 232, in focus_to
    self.map_swipe(swipe)
  File "C:\fakepath\AzurLaneAutoScript\module\map\camera.py", line 64, in map_swipe
    self._map_swipe(vector)
  File "C:\fakepath\AzurLaneAutoScript\module\map\camera.py", line 45, in _map_swipe
    self.update()
  File "C:\fakepath\AzurLaneAutoScript\module\map\camera.py", line 122, in update
    raise e
  File "C:\fakepath\AzurLaneAutoScript\module\map\camera.py", line 102, in update
    self.view.load(self.device.image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\view.py", line 57, in load
    super().load(image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\detector.py", line 49, in load
    self.backend.load(image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\homography.py", line 81, in load
    self.detect(image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\homography.py", line 179, in detect
    raise MapDetectionError('Failed to find a free tile')
module.exception.MapDetectionError: Failed to find a free tile
2021-07-19 17:16:28.017 | INFO | Saving error: ./log/error/1626740188017

**Comment by railzy** [comment]
我遇到的没识别某个按钮导致的错误一般都是报 Wait too long
报 Failed to find a free tile 都是因为模拟器运行出错导致游戏短暂黑屏/退出/重启而产生的，而这种情况产生的报错不会在截图中反映
我是在bluestacks4上跑的，时不时就会出现这种状况
你是看着运行到这一步报错，还是打开发现卡住了然后再去看error log的？

**Comment by DebuAqua** [comment]
> 我遇到的没识别某个按钮导致的错误一般都是报 Wait too long
> 报 Failed to find a free tile 都是因为模拟器运行出错导致游戏短暂黑屏/退出/重启而产生的，而这种情况产生的报错不会在截图中反映
> 我是在bluestacks4上跑的，时不时就会出现这种状况
> 你是看着运行到这一步报错，还是打开发现卡住了然后再去看error log的？

人离开电脑一段时间，回来时发现脚本停止

**Comment by railzy** [comment]
我观察了下遇到伏击舰队能够正常处理
报 Failed to find a free tile 这个问题我感觉可能是模拟器运行出错导致的，感觉可以集中讨论下
我在bluestacks4和5上都出现过这种问题，设置截图用的是uiautomator2，控制用的是minitouch
