### ISSUE TITLE
开启潜艇图每日，打潜艇图时重复触发潜艇图每日收获，导致出错

### ISSUE THREAD

**Issue by railzy** [LmeSzinc/AzurLaneAutoScript#605]
**Describe the bug**
设置中打开了在每日中加入潜艇图，设置如下
```ini
[Sos]
do_sos_in_daily = yes
sos_chapter = 3
sos_fleet_1 = 4
sos_fleet_2 = 0
sos_submarine = 0
```
运行7-2三战捡垃圾，完成几次后脚本触发了每日任务收获，清收获的过程中没有出现错误
清完所有每日后，脚本没有继续回去刷7-2三战捡垃圾，而是不检查救援信号就直接尝试进入潜艇图，出错

只有收获每日任务的过程中打了潜艇图才会出这个bug，如果当天已存在清潜艇图记录，脚本收获过程没进去打潜艇图，则不会出现该bug

**Expected behavior**
清完每日后回去刷原来的图

**Screenshots**
报错前的页面变化截图（省略重复页面）
![2021-09-06_15-29-39-076649](https://user-images.githubusercontent.com/57893649/132195425-aa978a74-4a71-4024-8d5b-fe8c3945de61.png)
![2021-09-06_15-29-43-008052](https://user-images.githubusercontent.com/57893649/132195439-acaa2603-760c-418f-9d02-2449dc896d0d.png)
![2021-09-06_15-29-46-251825](https://user-images.githubusercontent.com/57893649/132195442-585499ff-64b5-4843-934a-f2b1ca43d600.png)
![2021-09-06_15-29-51-259770](https://user-images.githubusercontent.com/57893649/132195445-14f76f58-d9d5-48f7-be30-2d789d94f34f.png)
![2021-09-06_15-29-53-249756](https://user-images.githubusercontent.com/57893649/132195361-7d4bbd85-25d4-4b5f-b138-5d7a6942076e.png)

**Log**
```
2021-09-06 15:29:32.875 | INFO | [UI route] page_guild - page_main
2021-09-06 15:29:32.875 | INFO | <<< UI CLICK >>>
2021-09-06 15:29:33.859 | INFO | Click (1241,   37) @ GOTO_MAIN
2021-09-06 15:29:37.097 | INFO | [RewardRecord_shop_general] Record time: 2021-09-06 14:23:18
2021-09-06 15:29:37.097 | INFO | [RewardRecord_shop_general] Last update: 2021-09-06 11:00:00
2021-09-06 15:29:37.097 | INFO | [RewardRecord_shop_guild] Record time: 2021-09-06 14:24:30
2021-09-06 15:29:37.097 | INFO | [RewardRecord_shop_guild] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.098 | INFO | [RewardRecord_shop_merit] Record time: 2021-09-06 14:23:24
2021-09-06 15:29:37.098 | INFO | [RewardRecord_shop_merit] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.098 | INFO | [RewardRecord_shop_medal] Record time: 2021-09-06 14:24:49
2021-09-06 15:29:37.098 | INFO | [RewardRecord_shop_medal] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.098 | INFO | [RewardRecord_shipyard] Record time: 2021-09-06 14:25:25
2021-09-06 15:29:37.098 | INFO | [RewardRecord_shipyard] Last update: 2021-09-06 03:00:00
2021-09-06 15:29:37.098 | INFO | <<< MISSION REWARD >>>
2021-09-06 15:29:37.099 | INFO | No mission reward
2021-09-06 15:29:37.099 | INFO | <<< REWARD END >>>
2021-09-06 15:29:37.099 | INFO | <<< DAILY REWARD >>>
2021-09-06 15:29:37.099 | INFO | [DailyRecord_os_obscure_finish] Current time: 2021-09-06 15:29:37
2021-09-06 15:29:37.099 | INFO | [DailyRecord_os_obscure_finish] Next run: 2021-09-06 23:00:00
2021-09-06 15:29:37.099 | INFO | [DailyRecord_exercise] Record time: 2021-09-06 14:45:45
2021-09-06 15:29:37.099 | INFO | [DailyRecord_exercise] Last update: 2021-09-06 11:00:00
2021-09-06 15:29:37.100 | INFO | [DailyRecord_daily] Record time: 2021-09-06 14:47:12
2021-09-06 15:29:37.100 | INFO | [DailyRecord_daily] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.100 | INFO | [DailyRecord_hard] Record time: 2021-09-06 14:54:19
2021-09-06 15:29:37.100 | INFO | [DailyRecord_hard] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.100 | INFO | [DailyRecord_sos] Record time: 2021-09-06 15:12:43
2021-09-06 15:29:37.100 | INFO | [DailyRecord_sos] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.101 | INFO | [DailyRecord_ash] Record time: 2021-09-06 15:19:51
2021-09-06 15:29:37.101 | INFO | [DailyRecord_ash] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.101 | INFO | [DailyRecord_os_mission_accept] Record time: 2021-09-06 15:23:14
2021-09-06 15:29:37.101 | INFO | [DailyRecord_os_mission_accept] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.101 | INFO | [DailyRecord_os_supply_buy] Record time: 2021-09-06 15:23:14
2021-09-06 15:29:37.101 | INFO | [DailyRecord_os_supply_buy] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.101 | INFO | [DailyRecord_os_mission_finish] Record time: 2021-09-06 15:28:48
2021-09-06 15:29:37.101 | INFO | [DailyRecord_os_mission_finish] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.101 | INFO | [Daily_executed] 0/6
2021-09-06 15:29:37.120 | INFO | [OCR_SIGNAL 0.016s] 0
2021-09-06 15:29:37.120 | INFO | [remain] 0
2021-09-06 15:29:37.120 | INFO | All SOS signals cleared
2021-09-06 15:29:37.123 | INFO | [DailyRecord_ash] Record time: 2021-09-06 15:19:51
2021-09-06 15:29:37.124 | INFO | [DailyRecord_ash] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.124 | INFO | [DailyRecord_os_mission_accept] Record time: 2021-09-06 15:23:14
2021-09-06 15:29:37.124 | INFO | [DailyRecord_os_mission_accept] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.125 | INFO | [DailyRecord_os_supply_buy] Record time: 2021-09-06 15:23:14
2021-09-06 15:29:37.125 | INFO | [DailyRecord_os_supply_buy] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.125 | INFO | [DailyRecord_os_mission_finish] Record time: 2021-09-06 15:28:48
2021-09-06 15:29:37.125 | INFO | [DailyRecord_os_mission_finish] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:37.125 | INFO | [Daily_executed] 1/6
2021-09-06 15:29:37.126 | INFO | <<< REWARD START >>>
2021-09-06 15:29:37.126 | INFO | <<< UI ENSURE >>>
2021-09-06 15:29:38.083 | INFO | [UI] page_main
2021-09-06 15:29:38.083 | INFO | Already at page_main
2021-09-06 15:29:38.083 | INFO | [UI route] page_main - page_reward
2021-09-06 15:29:38.083 | INFO | <<< UI CLICK >>>
2021-09-06 15:29:38.085 | INFO | Click (  23,  158) @ MAIN_GOTO_REWARD
2021-09-06 15:29:40.898 | INFO | <<< REWARD RECEIVE >>>
2021-09-06 15:29:43.010 | INFO | Uploading screenshots to AzurStat, amount: 0
2021-09-06 15:29:43.012 | INFO | No research finished or pending
2021-09-06 15:29:43.012 | INFO | No tactical class reward.
2021-09-06 15:29:43.012 | INFO | No commission pending
2021-09-06 15:29:43.013 | INFO | [UI route] page_reward - page_main
2021-09-06 15:29:43.013 | INFO | <<< UI CLICK >>>
2021-09-06 15:29:43.015 | INFO | Click (1072,  615) @ REWARD_GOTO_MAIN
2021-09-06 15:29:46.253 | INFO | [RewardRecord_dorm_collect] Record time: 2021-09-06 15:12:25
2021-09-06 15:29:46.253 | INFO | [RewardRecord_dorm_collect] Next update: 2021-09-06 15:48:09
2021-09-06 15:29:46.253 | INFO | [RewardRecord_dorm_feed] Record time: 2021-09-06 14:20:58
2021-09-06 15:29:46.253 | INFO | [RewardRecord_dorm_feed] Next update: 2021-09-06 18:21:31
2021-09-06 15:29:46.254 | INFO | [RewardRecord_meowfficer] Record time: 2021-09-06 14:21:45
2021-09-06 15:29:46.254 | INFO | [RewardRecord_meowfficer] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.254 | INFO | [RewardRecord_data_key] Record time: 2021-09-06 14:22:00
2021-09-06 15:29:46.254 | INFO | [RewardRecord_data_key] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.254 | INFO | [RewardRecord_guild] Record time: 2021-09-06 15:29:32
2021-09-06 15:29:46.254 | INFO | [RewardRecord_guild] Next update: 2021-09-06 15:54:58
2021-09-06 15:29:46.254 | INFO | [RewardRecord_shop_general] Record time: 2021-09-06 14:23:18
2021-09-06 15:29:46.255 | INFO | [RewardRecord_shop_general] Last update: 2021-09-06 11:00:00
2021-09-06 15:29:46.255 | INFO | [RewardRecord_shop_guild] Record time: 2021-09-06 14:24:30
2021-09-06 15:29:46.255 | INFO | [RewardRecord_shop_guild] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.255 | INFO | [RewardRecord_shop_merit] Record time: 2021-09-06 14:23:24
2021-09-06 15:29:46.256 | INFO | [RewardRecord_shop_merit] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.256 | INFO | [RewardRecord_shop_medal] Record time: 2021-09-06 14:24:49
2021-09-06 15:29:46.256 | INFO | [RewardRecord_shop_medal] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.257 | INFO | [RewardRecord_shipyard] Record time: 2021-09-06 14:25:25
2021-09-06 15:29:46.257 | INFO | [RewardRecord_shipyard] Last update: 2021-09-06 03:00:00
2021-09-06 15:29:46.257 | INFO | <<< MISSION REWARD >>>
2021-09-06 15:29:46.257 | INFO | No mission reward
2021-09-06 15:29:46.258 | INFO | <<< REWARD END >>>
2021-09-06 15:29:46.258 | INFO | <<< DAILY REWARD >>>
2021-09-06 15:29:46.258 | INFO | [DailyRecord_os_obscure_finish] Current time: 2021-09-06 15:29:46
2021-09-06 15:29:46.258 | INFO | [DailyRecord_os_obscure_finish] Next run: 2021-09-06 23:00:00
2021-09-06 15:29:46.259 | INFO | [DailyRecord_exercise] Record time: 2021-09-06 14:45:45
2021-09-06 15:29:46.259 | INFO | [DailyRecord_exercise] Last update: 2021-09-06 11:00:00
2021-09-06 15:29:46.259 | INFO | [DailyRecord_daily] Record time: 2021-09-06 14:47:12
2021-09-06 15:29:46.259 | INFO | [DailyRecord_daily] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.259 | INFO | [DailyRecord_hard] Record time: 2021-09-06 14:54:19
2021-09-06 15:29:46.259 | INFO | [DailyRecord_hard] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.260 | INFO | [DailyRecord_sos] Record time: 2021-09-06 15:29:37
2021-09-06 15:29:46.260 | INFO | [DailyRecord_sos] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.260 | INFO | [DailyRecord_ash] Record time: 2021-09-06 15:19:51
2021-09-06 15:29:46.260 | INFO | [DailyRecord_ash] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.261 | INFO | [DailyRecord_os_mission_accept] Record time: 2021-09-06 15:23:14
2021-09-06 15:29:46.261 | INFO | [DailyRecord_os_mission_accept] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.261 | INFO | [DailyRecord_os_supply_buy] Record time: 2021-09-06 15:23:14
2021-09-06 15:29:46.261 | INFO | [DailyRecord_os_supply_buy] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.261 | INFO | [DailyRecord_os_mission_finish] Record time: 2021-09-06 15:28:48
2021-09-06 15:29:46.262 | INFO | [DailyRecord_os_mission_finish] Last update: 2021-09-05 23:00:00
2021-09-06 15:29:46.262 | INFO | [Daily_executed] 0/6
2021-09-06 15:29:46.262 | INFO | ==================== CAMPAIGN_3_5 ====================
2021-09-06 15:29:46.262 | INFO | Count: [0]
2021-09-06 15:29:47.265 | INFO | <<< UI ENSURE >>>
2021-09-06 15:29:48.332 | INFO | [UI] page_main
2021-09-06 15:29:48.332 | INFO | Goto page_campaign
2021-09-06 15:29:48.332 | INFO | [UI route] page_main - page_campaign_menu - page_campaign
2021-09-06 15:29:48.332 | INFO | <<< UI CLICK >>>
2021-09-06 15:29:49.297 | INFO | Click (1125,  404) @ MAIN_GOTO_CAMPAIGN
2021-09-06 15:29:51.261 | INFO | <<< UI CLICK >>>
2021-09-06 15:29:51.275 | INFO | Click ( 279,  238) @ CAMPAIGN_MENU_GOTO_CAMPAIGN
2021-09-06 15:29:55.344 | INFO | [Mode_switch_1] hard
2021-09-06 15:29:55.344 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:29:55.550 | INFO | [campaign 0.041s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:29:55.550 | INFO | [Chapter] 3
2021-09-06 15:29:55.551 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:29:55.551 | INFO | [Index] 3
2021-09-06 15:29:56.331 | INFO | <<< UI ENSURE >>>
2021-09-06 15:29:56.809 | INFO | [UI] page_campaign
2021-09-06 15:29:56.810 | INFO | Already at page_campaign
2021-09-06 15:29:56.812 | INFO | [Mode_switch_1] hard
2021-09-06 15:29:56.812 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:29:57.007 | INFO | [campaign 0.039s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:29:57.007 | INFO | [Chapter] 3
2021-09-06 15:29:57.007 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:29:57.007 | INFO | [Index] 3
2021-09-06 15:29:57.642 | INFO | <<< UI ENSURE >>>
2021-09-06 15:29:58.370 | INFO | [UI] page_campaign
2021-09-06 15:29:58.371 | INFO | Already at page_campaign
2021-09-06 15:29:58.373 | INFO | [Mode_switch_1] hard
2021-09-06 15:29:58.373 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:29:58.566 | INFO | [campaign 0.037s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:29:58.566 | INFO | [Chapter] 3
2021-09-06 15:29:58.566 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:29:58.566 | INFO | [Index] 3
2021-09-06 15:29:59.408 | INFO | <<< UI ENSURE >>>
2021-09-06 15:29:59.906 | INFO | [UI] page_campaign
2021-09-06 15:29:59.906 | INFO | Already at page_campaign
2021-09-06 15:29:59.910 | INFO | [Mode_switch_1] hard
2021-09-06 15:29:59.910 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:00.106 | INFO | [campaign 0.035s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:00.107 | INFO | [Chapter] 3
2021-09-06 15:30:00.107 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:00.107 | INFO | [Index] 3
2021-09-06 15:30:00.708 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:01.438 | INFO | [UI] page_campaign
2021-09-06 15:30:01.438 | INFO | Already at page_campaign
2021-09-06 15:30:01.441 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:01.441 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:01.640 | INFO | [campaign 0.042s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:01.640 | INFO | [Chapter] 3
2021-09-06 15:30:01.640 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:01.640 | INFO | [Index] 3
2021-09-06 15:30:02.466 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:03.517 | INFO | [UI] page_campaign
2021-09-06 15:30:03.517 | INFO | Already at page_campaign
2021-09-06 15:30:03.520 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:03.520 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:03.712 | INFO | [campaign 0.037s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:03.712 | INFO | [Chapter] 3
2021-09-06 15:30:03.712 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:03.712 | INFO | [Index] 3
2021-09-06 15:30:04.510 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:05.055 | INFO | [UI] page_campaign
2021-09-06 15:30:05.056 | INFO | Already at page_campaign
2021-09-06 15:30:05.060 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:05.060 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:05.253 | INFO | [campaign 0.038s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:05.253 | INFO | [Chapter] 3
2021-09-06 15:30:05.254 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:05.254 | INFO | [Index] 3
2021-09-06 15:30:05.856 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:06.698 | INFO | [UI] page_campaign
2021-09-06 15:30:06.698 | INFO | Already at page_campaign
2021-09-06 15:30:06.701 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:06.701 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:06.912 | INFO | [campaign 0.045s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:06.912 | INFO | [Chapter] 3
2021-09-06 15:30:06.913 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:06.913 | INFO | [Index] 3
2021-09-06 15:30:08.045 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:08.537 | INFO | [UI] page_campaign
2021-09-06 15:30:08.537 | INFO | Already at page_campaign
2021-09-06 15:30:08.540 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:08.541 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:08.731 | INFO | [campaign 0.037s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:08.731 | INFO | [Chapter] 3
2021-09-06 15:30:08.732 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:08.732 | INFO | [Index] 3
2021-09-06 15:30:09.609 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:10.110 | INFO | [UI] page_campaign
2021-09-06 15:30:10.110 | INFO | Already at page_campaign
2021-09-06 15:30:10.113 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:10.113 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:10.310 | INFO | [campaign 0.037s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:10.310 | INFO | [Chapter] 3
2021-09-06 15:30:10.311 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:10.311 | INFO | [Index] 3
2021-09-06 15:30:10.895 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:11.632 | INFO | [UI] page_campaign
2021-09-06 15:30:11.632 | INFO | Already at page_campaign
2021-09-06 15:30:11.637 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:11.637 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:11.826 | INFO | [campaign 0.036s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:11.826 | INFO | [Chapter] 3
2021-09-06 15:30:11.827 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:11.827 | INFO | [Index] 3
2021-09-06 15:30:12.689 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:13.181 | INFO | [UI] page_campaign
2021-09-06 15:30:13.181 | INFO | Already at page_campaign
2021-09-06 15:30:13.184 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:13.185 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:13.384 | INFO | [campaign 0.041s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:13.384 | INFO | [Chapter] 3
2021-09-06 15:30:13.384 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:13.384 | INFO | [Index] 3
2021-09-06 15:30:13.991 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:14.705 | INFO | [UI] page_campaign
2021-09-06 15:30:14.705 | INFO | Already at page_campaign
2021-09-06 15:30:14.711 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:14.711 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:14.903 | INFO | [campaign 0.040s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:14.903 | INFO | [Chapter] 3
2021-09-06 15:30:14.903 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:14.904 | INFO | [Index] 3
2021-09-06 15:30:15.717 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:16.219 | INFO | [UI] page_campaign
2021-09-06 15:30:16.220 | INFO | Already at page_campaign
2021-09-06 15:30:16.222 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:16.222 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:16.418 | INFO | [campaign 0.038s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:16.418 | INFO | [Chapter] 3
2021-09-06 15:30:16.418 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:16.418 | INFO | [Index] 3
2021-09-06 15:30:16.983 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:17.740 | INFO | [UI] page_campaign
2021-09-06 15:30:17.740 | INFO | Already at page_campaign
2021-09-06 15:30:17.744 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:17.744 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:17.941 | INFO | [campaign 0.041s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:17.942 | INFO | [Chapter] 3
2021-09-06 15:30:17.942 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:17.942 | INFO | [Index] 3
2021-09-06 15:30:18.789 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:20.288 | INFO | [UI] page_campaign
2021-09-06 15:30:20.288 | INFO | Already at page_campaign
2021-09-06 15:30:20.291 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:20.292 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:20.485 | INFO | [campaign 0.036s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:20.486 | INFO | [Chapter] 3
2021-09-06 15:30:20.486 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:20.486 | INFO | [Index] 3
2021-09-06 15:30:21.078 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:21.868 | INFO | [UI] page_campaign
2021-09-06 15:30:21.868 | INFO | Already at page_campaign
2021-09-06 15:30:21.871 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:21.872 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:22.073 | INFO | [campaign 0.041s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:22.074 | INFO | [Chapter] 3
2021-09-06 15:30:22.074 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:22.074 | INFO | [Index] 3
2021-09-06 15:30:22.870 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:23.375 | INFO | [UI] page_campaign
2021-09-06 15:30:23.375 | INFO | Already at page_campaign
2021-09-06 15:30:23.378 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:23.378 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:23.573 | INFO | [campaign 0.036s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:23.574 | INFO | [Chapter] 3
2021-09-06 15:30:23.574 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:23.574 | INFO | [Index] 3
2021-09-06 15:30:24.186 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:24.908 | INFO | [UI] page_campaign
2021-09-06 15:30:24.908 | INFO | Already at page_campaign
2021-09-06 15:30:24.911 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:24.912 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:25.113 | INFO | [campaign 0.042s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:25.113 | INFO | [Chapter] 3
2021-09-06 15:30:25.113 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:25.114 | INFO | [Index] 3
2021-09-06 15:30:25.921 | INFO | <<< UI ENSURE >>>
2021-09-06 15:30:26.879 | INFO | [UI] page_campaign
2021-09-06 15:30:26.879 | INFO | Already at page_campaign
2021-09-06 15:30:26.881 | INFO | [Mode_switch_1] hard
2021-09-06 15:30:26.881 | INFO | <<< UI ENSURE INDEX >>>
2021-09-06 15:30:27.084 | INFO | [campaign 0.037s] ['3--3', '3--1', '3--4', '3--2']
2021-09-06 15:30:27.084 | INFO | [Chapter] 3
2021-09-06 15:30:27.084 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
2021-09-06 15:30:27.084 | INFO | [Index] 3
2021-09-06 15:30:27.937 | WARNING | Campaign name error
2021-09-06 15:30:27.937 | ERROR | Campaign name error
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 206, in c72_mystery_farming
    az.run('campaign_7_2_mystery_farming')
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 187, in run
    if self.handle_reward():
  File "C:\fakepath\AzurLaneAutoScript\module\reward\reward.py", line 101, in handle_reward
    flag = self.reward()
  File "C:\fakepath\AzurLaneAutoScript\module\reward\reward.py", line 90, in reward
    count = self.daily_wrapper_run()
  File "C:\fakepath\AzurLaneAutoScript\module\reward\reward.py", line 356, in daily_wrapper_run
    az.run()
  File "C:\fakepath\AzurLaneAutoScript\module\sos\sos.py", line 191, in run
    super().run(f'campaign_{chapter}_5', folder=folder, total=total)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 211, in run
    mode=self.config.CAMPAIGN_MODE if self.config.COMMAND.lower() == 'main' else 'normal'
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_ui.py", line 124, in ensure_campaign_ui
    raise ScriptEnd('Campaign name error')
module.exception.ScriptEnd: Campaign name error
2021-09-06 15:30:28.038 | INFO | Saving error: ./log/error/1630913428038
```

**Comment by railzy** [comment]
可能是潜艇图每日收获调用了 `super.run()` 打图，而在 `super.run()` 中打图前重复触发了潜艇图收获，收获中清完了救援信号，再去清指定的潜艇图，此时不会检查信号而去直接寻找一开始设定的潜艇图，从而造成错误
我在代码中加入了一些 debug 用的 logger

reward.py line352~
```python
        if self.config.DO_SOS_IN_DAILY:
            from module.sos.sos import CampaignSos
            az = CampaignSos(self.config, device=self.device)
            if not az.record_executed_since():
                logger.info("__test__ start sos reward")
                az.run()
                logger.info("__test__ end sos reward")
                az.record_save()
                count += 1
                self.device.send_notification('Daily Sos', 'Daily sos campaign finished.')
```

sos.py line191~
```python
                # test logger
                logger.info(R"__test__ start super().run(f'campaign_{chapter}_5', folder=folder, total=total)")

                super().run(f'campaign_{chapter}_5', folder=folder, total=total)

                # test logger
                logger.info(R"__test__ end super().run(f'campaign_{chapter}_5', folder=folder, total=total)")
```

产生的log如下，太长了直接整个放上来
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7119530/log.txt)


可以发现 end 的数量比 start 少，每日清潜艇图不是 start sos reward ...... start super.run() ...... end super.run() 的流程，而是 start sos reward ...... start super.run() ...... start sos reward ...... start super.run() ....... 这样的流程，不断重复触发，直到潜艇每日全部完成，轮到之前 `super.run()` 里被收获插队而还没打的潜艇图，此时坐标和图都清完了，肯定找不到入口而报错

**Comment by LmeSzinc** [comment]
模仿每日SP，在前后调用一下
```
self.reward_backup_daily_reward_settings()
# ...
self.reward_recover_daily_reward_settings()
```
