### ISSUE TITLE
不能出击

### ISSUE THREAD

**Issue by IceCirnos** [LmeSzinc/AzurLaneAutoScript#610]
**Describe the bug**
选关卡时不能正确进入关卡

**Screenshots**
![2021-09-08_21-52-39-398898](https://user-images.githubusercontent.com/73627363/132530168-8a4dbe9a-9cbb-4d45-8a49-1f39ba4109f7.png)
![2021-09-08_21-52-42-317920](https://user-images.githubusercontent.com/73627363/132530324-401550d4-5b07-4cd4-8782-073f9f78f693.png)
![2021-09-08_21-52-42-774279](https://user-images.githubusercontent.com/73627363/132530378-c36bc80b-76de-4570-a11e-3f41ab882bc7.png)
![2021-09-08_21-52-43-388315](https://user-images.githubusercontent.com/73627363/132530408-e33f079c-67f1-418e-ac66-75aa7d3a1bc6.png)

**Log**
2021-09-08 21:52:29.851 | INFO | +---------------------------------------------+
2021-09-08 21:52:29.851 | INFO | |                    START                    |
2021-09-08 21:52:29.851 | INFO | +---------------------------------------------+
2021-09-08 21:52:29.853 | INFO | [Server] cn
2021-09-08 21:52:31.518 | INFO | [Command] C11_affinity_farming
2021-09-08 21:52:31.518 | INFO | <<< DEVICE >>>
2021-09-08 21:52:31.518 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
2021-09-08 21:52:31.548 | INFO | already connected to 127.0.0.1:7555
2021-09-08 21:52:33.684 | INFO | [Emotion fleet_1] 119
2021-09-08 21:52:33.684 | INFO | [Emotion fleet_2] 119
2021-09-08 21:52:33.685 | INFO | [Emotion_bug] 0/84
2021-09-08 21:52:33.685 | INFO | ==================== CAMPAIGN_1_1_AFFINITY_FARMING ====================
2021-09-08 21:52:33.685 | INFO | Count: [0]
2021-09-08 21:52:34.257 | INFO | [Screen_size] 1280x720
2021-09-08 21:52:34.268 | INFO | <<< UI ENSURE >>>
2021-09-08 21:52:34.772 | INFO | [UI] page_campaign
2021-09-08 21:52:34.772 | INFO | Already at page_campaign
2021-09-08 21:52:34.804 | INFO | [Mode_switch_1] hard
2021-09-08 21:52:34.804 | INFO | <<< UI ENSURE INDEX >>>
2021-09-08 21:52:34.925 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
2021-09-08 21:52:34.992 | INFO | [campaign 0.080s] ['7--2', '7--3', '7--4', '7--1']
2021-09-08 21:52:34.992 | INFO | [Chapter] 7
2021-09-08 21:52:34.992 | INFO | [Stage] 7-2, 7-3, 7-4, 7-1
2021-09-08 21:52:34.992 | INFO | [Index] 7
2021-09-08 21:52:34.992 | INFO | Click (  55,  366) @ CHAPTER_PREV
2021-09-08 21:52:35.267 | INFO | Click (  44,  369) @ CHAPTER_PREV
2021-09-08 21:52:35.549 | INFO | Click (  54,  377) @ CHAPTER_PREV
2021-09-08 21:52:35.773 | INFO | Click (  48,  369) @ CHAPTER_PREV
2021-09-08 21:52:36.016 | INFO | Click (  49,  369) @ CHAPTER_PREV
2021-09-08 21:52:36.262 | INFO | Click (  52,  369) @ CHAPTER_PREV
2021-09-08 21:52:38.091 | INFO | [campaign 0.028s] ['1--4', '1--2', '1--1', '1--3']
2021-09-08 21:52:38.091 | INFO | [Chapter] 1
2021-09-08 21:52:38.091 | INFO | [Stage] 1-4, 1-2, 1-1, 1-3
2021-09-08 21:52:38.092 | INFO | [Index] 1
2021-09-08 21:52:38.120 | INFO | [OCR_OIL 0.024s] 12646
2021-09-08 21:52:38.121 | INFO | -------------------- 1-1 --------------------
2021-09-08 21:52:38.121 | INFO | <<< ENTER MAP >>>
2021-09-08 21:52:38.695 | INFO | Click ( 139,  488) @ 1-1
2021-09-08 21:52:40.770 | INFO | [MAP_CLEAR_ALL_THIS_TIME] False
2021-09-08 21:52:40.770 | INFO | [Map_info] 99%, star_1, star_2, star_3, clear, 3_star, green, fast_forward
2021-09-08 21:52:40.770 | INFO | [STOP_IF_MAP_REACH] map_100
2021-09-08 21:52:40.770 | INFO | [Fast_Forward] on
2021-09-08 21:52:40.770 | INFO | Click (1042,  591) @ FAST_FORWARD_ON
2021-09-08 21:52:42.317 | INFO | [Fast_Forward] off
2021-09-08 21:52:42.334 | INFO | No auto search option.
2021-09-08 21:52:42.334 | INFO | <<< ENTER MAP CANCEL >>>
2021-09-08 21:52:42.335 | INFO | Click ( 261,   33) @ MAP_PREPARATION_CANCEL
2021-09-08 21:52:42.776 | INFO | Click ( 257,   31) @ MAP_PREPARATION_CANCEL
2021-09-08 21:52:43.520 | ERROR | No module named 'notifypy'
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 200, in c11_affinity_farming
    az.run('campaign_1_1_affinity_farming')
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 226, in run
    self.campaign.run()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 126, in run
    self.enter_map(self.ENTRANCE, mode=self.config.CAMPAIGN_MODE)
  File "C:\fakepath\AzurLaneAutoScript\module\map\map_operation.py", line 69, in enter_map
    self.device.send_notification('Reach condition:', self.config.STOP_IF_MAP_REACH)
  File "C:\fakepath\AzurLaneAutoScript\module\device\device.py", line 23, in send_notification
    from notifypy import Notify
ModuleNotFoundError: No module named 'notifypy'
2021-09-08 21:52:43.522 | INFO | Saving error: ./log/error/1631109163521

**Comment by LmeSzinc** [comment]
1. `2021-09-08 21:52:40.770 | INFO | [STOP_IF_MAP_REACH] map_100` 设置了 100% 通关后停止
2. 没装 `notifypy`
