### ISSUE TITLE
心情BUG触发重启后，MUMU模拟器adb卡死

### ISSUE THREAD

**Issue by SF-monkey** [LmeSzinc/AzurLaneAutoScript#612]
**Describe the bug**
心情BUG触发重启后，画面，整个模拟器卡死。需要重启模拟器。

**To Reproduce**
触发原因未知

**Log**
2021-09-10 02:15:42.822 | INFO | -------------------- BATTLE_4 --------------------
2021-09-10 02:15:42.822 | INFO | Auto search moving
2021-09-10 02:15:42.823 | INFO | Fleet: 1, fleet_current_index: 1
2021-09-10 02:15:42.879 | INFO | [LevelOcr 0.055s] [20, 0, 0, 100, 0, 0]
2021-09-10 02:15:42.879 | INFO | [LEVEL] 20, 0, 0, 100, 0, 0
2021-09-10 02:15:44.364 | INFO | <<< CAMPAIGN END >>>
2021-09-10 02:15:44.364 | INFO | [Emotion_bug] 86/81
2021-09-10 02:15:44.364 | INFO | <<< TRIGGERED RESTART AVOID EMOTION BUG >>>
2021-09-10 02:15:44.383 | INFO | <<< APP RESTART >>>
2021-09-10 02:15:44.383 | INFO | App stop: com.bilibili.azurlane
2021-09-10 02:15:44.937 | INFO | App start: com.bilibili.azurlane
2021-09-10 02:15:45.441 | INFO | <<< APP LOGIN >>>
2021-09-10 02:15:54.353 | INFO | USER_AGREEMENT_SCROLL set to 1.0
2021-09-10 02:15:54.354 | INFO | [USER_AGREEMENT_SCROLL] 0.00
2021-09-10 02:18:20.261 | ERROR | Command '['.\\toolkit\\Lib\\site-packages\\adbutils\\binaries\\adb.exe', '-s', '127.0.0.1:7555', 'shell', 'screencap', '-p']' timed out after 10 seconds
Traceback (most recent call last):
  File "C:\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\AzurLaneAutoScript\alas.py", line 140, in main
    az.run(self.config.CAMPAIGN_NAME)
  File "C:\AzurLaneAutoScript\module\campaign\run.py", line 185, in run
    if self.handle_app_restart():
  File "C:\AzurLaneAutoScript\module\campaign\run.py", line 148, in handle_app_restart
    self.app_restart()
  File "C:\AzurLaneAutoScript\module\handler\login.py", line 103, in app_restart
    self.handle_app_login()
  File "C:\AzurLaneAutoScript\module\handler\login.py", line 87, in handle_app_login
    self._handle_app_login()
  File "C:\AzurLaneAutoScript\module\handler\login.py", line 35, in _handle_app_login
    if self.handle_user_agreement():
  File "C:\AzurLaneAutoScript\module\handler\login.py", line 155, in handle_user_agreement
    USER_AGREEMENT_SCROLL.set_bottom(main=self)
  File "C:\AzurLaneAutoScript\module\ui\scroll.py", line 138, in set_bottom
    return self.set(1.00, main=main, random_range=random_range, skip_first_screenshot=skip_first_screenshot)
  File "C:\AzurLaneAutoScript\module\ui\scroll.py", line 121, in set
    main.device.screenshot()
  File "C:\AzurLaneAutoScript\module\device\device.py", line 60, in screenshot
    super().screenshot()
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\AzurLaneAutoScript\toolkit\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\AzurLaneAutoScript\module\device\screenshot.py", line 68, in screenshot
    self.image = self._screenshot_adb()
  File "C:\AzurLaneAutoScript\module\device\screenshot.py", line 49, in _screenshot_adb
    screenshot = self.adb_shell(['screencap', '-p'])
  File "C:\AzurLaneAutoScript\module\device\connection.py", line 68, in adb_shell
    return self.adb_command(cmd, serial)
  File "C:\AzurLaneAutoScript\module\device\connection.py", line 64, in adb_command
    return process.communicate(timeout=10)[0]
  File "C:\AzurLaneAutoScript\toolkit\lib\subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\AzurLaneAutoScript\toolkit\lib\subprocess.py", line 1298, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['.\\toolkit\\Lib\\site-packages\\adbutils\\binaries\\adb.exe', '-s', '127.0.0.1:7555', 'shell', 'screencap', '-p']' timed out after 10 seconds
error: closed
errerror:o closed
error: closed
error: closed
error: closed
error: closed
r: closed
error: closerror: closed
ed
error: closed

**Comment by LmeSzinc** [comment]
看描述的话，是模拟器自己的问题，与 Alas 无关，换一个呗
