### ISSUE TITLE
CV库出现爆内存错误

### ISSUE THREAD

**Issue by EzraRT** [LmeSzinc/AzurLaneAutoScript#615]
**Describe the bug**
识图时尝试分配超大内存，然后raise异常结束

**To Reproduce**
刷活动图a1

**Expected behavior**
应当正常刷图

**Screenshots**
![2021-09-16_18-05-09-948197](https://user-images.githubusercontent.com/29591166/133594236-24e504e9-8b3b-4371-b4f9-21b03bfc517e.png)

**Log**
2021-09-16 18:04:42.754 | INFO | +---------------------------------------------+
2021-09-16 18:04:42.754 | INFO | |                    START                    |
2021-09-16 18:04:42.754 | INFO | +---------------------------------------------+
2021-09-16 18:04:42.754 | INFO | [Server] cn
2021-09-16 18:04:43.583 | INFO | [Command] Event
2021-09-16 18:04:43.583 | INFO | <<< DEVICE >>>
2021-09-16 18:04:46.955 | INFO | [Adb_binary] adb.exe
2021-09-16 18:04:47.070 | INFO | [Emotion fleet_1] 119
2021-09-16 18:04:47.070 | INFO | [Emotion fleet_2] 119
2021-09-16 18:04:47.070 | INFO | [Emotion_bug] 0/77
2021-09-16 18:04:47.070 | INFO | ==================== A1 ====================
2021-09-16 18:04:47.070 | INFO | Count: [0]
2021-09-16 18:04:47.483 | INFO | [Screen_size] 1280x720
2021-09-16 18:04:47.489 | INFO | <<< UI ENSURE >>>
2021-09-16 18:04:47.882 | INFO | [UI] page_main
2021-09-16 18:04:47.883 | INFO | Goto page_event
2021-09-16 18:04:47.883 | INFO | [UI route] page_main - page_campaign_menu - page_event
2021-09-16 18:04:47.883 | INFO | <<< UI CLICK >>>
2021-09-16 18:04:48.276 | INFO | Click (1080,  327) @ MAIN_GOTO_CAMPAIGN
2021-09-16 18:04:48.276 | INFO | <<< MINITOUCH INIT >>>
2021-09-16 18:04:50.276 | INFO | Minitouch bind to port 20881
2021-09-16 18:04:50.345 | INFO | Minitouch forward port 20881
2021-09-16 18:04:50.347 | INFO | minitouch running on port: 20881, pid: 2458
2021-09-16 18:04:50.347 | INFO | max_contact: 10; max_x: 1279; max_y: 719; max_pressure: 2
2021-09-16 18:04:51.236 | INFO | <<< UI CLICK >>>
2021-09-16 18:04:51.242 | INFO | Click ( 651,  175) @ CAMPAIGN_MENU_GOTO_EVENT
2021-09-16 18:04:53.712 | INFO | [Mode_switch_2] ex
2021-09-16 18:04:53.718 | INFO | [Mode_switch_1] hard
2021-09-16 18:04:53.718 | INFO | <<< UI ENSURE INDEX >>>
2021-09-16 18:04:53.809 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
2021-09-16 18:04:53.838 | INFO | [campaign 0.038s] A1
2021-09-16 18:04:53.838 | INFO | [Chapter] a
2021-09-16 18:04:53.838 | INFO | [Stage] a1
2021-09-16 18:04:53.838 | INFO | [Index] 1
2021-09-16 18:04:53.840 | INFO | -------------------- A1 --------------------
2021-09-16 18:04:53.841 | INFO | <<< ENTER MAP >>>
2021-09-16 18:04:54.324 | INFO | Click ( 334,  268) @ a1
2021-09-16 18:04:55.794 | INFO | [MAP_CLEAR_ALL_THIS_TIME] True
2021-09-16 18:04:55.794 | INFO | [Map_info] 0%, 
2021-09-16 18:04:55.794 | INFO | [STOP_IF_MAP_REACH] map_3_star
2021-09-16 18:04:55.800 | INFO | No auto search option.
2021-09-16 18:04:55.800 | INFO | Click ( 911,  525) @ MAP_PREPARATION
2021-09-16 18:04:56.597 | INFO | Using fleet: [1, 2, 0]
2021-09-16 18:04:56.597 | INFO | [Light_orange_line] 0
2021-09-16 18:04:56.597 | INFO | Click (1138,  478) @ SUBMARINE_CLEAR
2021-09-16 18:04:57.290 | INFO | Click (1143,  336) @ FLEET_2_CLEAR
2021-09-16 18:04:57.926 | INFO | Click (1045,  208) @ FLEET_1_CHOOSE
2021-09-16 18:04:58.571 | INFO | Current selected: [1]
2021-09-16 18:04:58.571 | INFO | Click (1056,  186) @ FLEET_1_CHOOSE
2021-09-16 18:04:59.199 | INFO | Click (1046,  320) @ FLEET_2_CHOOSE
2021-09-16 18:04:59.856 | INFO | Current selected: [1]
2021-09-16 18:04:59.856 | INFO | Click (1100,  443) @ FLEET_2_BAR_INDEX_2
2021-09-16 18:05:00.530 | INFO | Expected emotion reduce: (6, 2)
2021-09-16 18:05:00.531 | INFO | Click (1032,  610) @ FLEET_PREPARATION
2021-09-16 18:05:06.008 | INFO | Enemy searching appeared.
2021-09-16 18:05:06.363 | INFO | Ensure no story
2021-09-16 18:05:09.561 | INFO | No fleet lock option.
2021-09-16 18:05:09.561 | INFO | <<< MAP INIT >>>
2021-09-16 18:05:09.561 | INFO | Load map_data, has_loop=False, use_loop=False
2021-09-16 18:05:09.561 | INFO | Load spawn_data, has_loop=False, use_loop=False
2021-09-16 18:05:09.561 | INFO | grid_connection: wall=False, portal=False
2021-09-16 18:05:09.562 | INFO | Load mechanism, land_base=False, maze=False
2021-09-16 18:05:09.563 | INFO | [Map_buff] 2
2021-09-16 18:05:09.564 | INFO | Skip strategy bar check.
2021-09-16 18:05:10.010 | INFO |           vanish_point: (  926,   -94)
2021-09-16 18:05:10.010 | INFO |          distant_point: (  939,   -94)
2021-09-16 18:05:10.019 | INFO | Horizontal coincident point unexpected: [246.063837   79.9439043]
2021-09-16 18:05:10.028 | INFO | Vertical coincident point unexpected: [1.01252066e+03 8.44726822e-03]
2021-09-16 18:05:10.028 | INFO | 0.072s      Horizontal: 9 (2 inner, 1 edge)
2021-09-16 18:05:10.028 | INFO | Edges: /_     Vertical: 50 (2 inner, 2 edge)
2021-09-16 18:05:10.028 | INFO | [homo_storage] ((49, 8), [(954.685, 55.73), (954.822, 55.73), (1051.744, 568.224), (1052.348, 568.224)])
2021-09-16 18:05:10.033 | ERROR | OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 69425700488 bytes in function 'cv::OutOfMemoryError'
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 159, in event
    az.run(self.config.EVENT_STAGE, folder=self.config.EVENT_NAME)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 226, in run
    self.campaign.run()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 131, in run
    self.map_init(self.MAP)
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 684, in map_init
    self.update()
  File "C:\fakepath\AzurLaneAutoScript\module\map\camera.py", line 103, in update
    self.view.load(self.device.image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\view.py", line 58, in load
    super().load(image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\detector.py", line 49, in load
    self.backend.load(image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\homography.py", line 82, in load
    self.detect(image)
  File "C:\fakepath\AzurLaneAutoScript\module\map_detection\homography.py", line 162, in detect
    image_trans = cv2.warpPerspective(image, self.homo_data, self.homo_size)
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 69425700488 bytes in function 'cv::OutOfMemoryError'

2021-09-16 18:05:10.034 | INFO | Saving error: ./log/error/1631786710034

**Comment by LmeSzinc** [comment]
修了，是新活动识图的问题
