### ISSUE TITLE
关闭自律寻敌后，关卡结束后报错

### ISSUE THREAD

**Issue by sissiunino** [LmeSzinc/AzurLaneAutoScript#660]
**Describe the bug**
在更新了“自动取消投票”后出现的问题，表现为如果不使用自律寻敌，关卡结束后100%报错。

**Log**
2021-10-17 09:16:01.177 | ERROR | No module named 'notifypy'
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 28, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 140, in main
    az.run(self.config.CAMPAIGN_NAME)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 226, in run
    self.campaign.run()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 145, in run
    self.execute_a_battle()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 99, in execute_a_battle
    result = self.battle_function()
  File "C:\fakepath\AzurLaneAutoScript\module\base\decorator.py", line 69, in wrapper
    return record['func'](self, *args, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 89, in battle_function
    result = func()
  File "C:\fakepath\AzurLaneAutoScript\campaign\campaign_main\campaign_7_2.py", line 92, in battle_5
    return self.fleet_2.clear_boss()
  File "C:\fakepath\AzurLaneAutoScript\module\map\map.py", line 306, in clear_boss
    self.clear_chosen_enemy(grids[0], expected='boss')
  File "C:\fakepath\AzurLaneAutoScript\module\map\map.py", line 20, in clear_chosen_enemy
    self.goto(grid, expected=expected)
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 419, in goto
    self._goto(location, expected=expected)
  File "C:\fakepath\AzurLaneAutoScript\module\map\fleet.py", line 290, in _goto
    self.combat(expected_end=self._expected_combat_end(expected), fleet_index=self.fleet_current_index)
  File "C:\fakepath\AzurLaneAutoScript\module\combat\combat.py", line 414, in combat
    save_get_items=save_get_items, expected_end=expected_end)
  File "C:\fakepath\AzurLaneAutoScript\module\combat\combat.py", line 375, in combat_status
    if self.handle_in_stage():
  File "C:\fakepath\AzurLaneAutoScript\module\handler\enemy_searching.py", line 34, in handle_in_stage
    self.device.send_notification('Sortie finished', 'Map cleared')
  File "C:\fakepath\AzurLaneAutoScript\module\device\device.py", line 23, in send_notification
    from notifypy import Notify
ModuleNotFoundError: No module named 'notifypy'
2021-10-17 09:16:01.178 | INFO | Saving error: ./log/error/1634451361178

**Comment by sissiunino** [comment]
> #481

成功解决问题了，非常感谢！
