### ISSUE TITLE
进入委托界面之后跳10054 远程主机强迫关闭连接 终止运行

### ISSUE THREAD

**Issue by dhujsi** [LmeSzinc/AzurLaneAutoScript#711]
2021-10-31 23:51:24.647 | INFO | +--------------------------------------------------+
2021-10-31 23:51:24.647 | INFO | |                    COMMISSION                    |
2021-10-31 23:51:24.647 | INFO | +--------------------------------------------------+
2021-10-31 23:51:26.330 | INFO | <<< UI ENSURE >>>
2021-10-31 23:51:26.343 | INFO | [UI] page_main
2021-10-31 23:51:26.344 | INFO | Goto page_reward
2021-10-31 23:51:26.344 | INFO | <<< UI GOTO PAGE_REWARD >>>
2021-10-31 23:51:26.488 | INFO | Click (  24,  164) @ MAIN_GOTO_REWARD
2021-10-31 23:51:28.718 | INFO | <<< REWARD RECEIVE >>>
2021-10-31 23:51:29.969 | INFO | <<< UI GOTO PAGE_COMMISSION >>>
2021-10-31 23:51:29.986 | INFO | Click ( 462,  280) @ REWARD_GOTO_COMMISSION
2021-10-31 23:51:31.415 | INFO | ==================== COMMISSION SCAN ====================
2021-10-31 23:51:31.416 | INFO | [Commission_switch] daily
2021-10-31 23:51:31.417 | INFO | Click (  62,  267) @ COMMISSION_URGENT
2021-10-31 23:51:33.355 | INFO | [Commission_switch] urgent
2021-10-31 23:51:33.355 | INFO | -------------------- SCAN DAILY --------------------
2021-10-31 23:51:33.356 | INFO | [Commission_switch] urgent
2021-10-31 23:51:33.356 | INFO | Click (  50,  172) @ COMMISSION_DAILY
2021-10-31 23:51:35.830 | INFO | [Commission_switch] daily
2021-10-31 23:51:35.830 | INFO | COMMISSION_SCROLL_AREA set to 0.0
2021-10-31 23:51:35.831 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-10-31 23:51:35.856 | INFO | Loading OCR model: ./bin/cnocr_models/cnocr
2021-10-31 23:51:36.010 | INFO | [COMMISSION 0.178s] 前沿基地防卫巡逻
2021-10-31 23:51:36.027 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
2021-10-31 23:51:36.085 | INFO | [COMMISSION 0.073s] 
2021-10-31 23:51:36.127 | INFO | [DURATION 0.043s] 01:20:02
2021-10-31 23:51:36.128 | INFO | [Commission] 前沿基地防卫巡逻 |  (Genre: extra_drill, Status: running, Duration: 1:20:02)
2021-10-31 23:51:36.203 | INFO | [COMMISSION 0.075s] 高阶自主训练
2021-10-31 23:51:36.221 | INFO | [COMMISSION 0.017s] 
2021-10-31 23:51:36.256 | INFO | [DURATION 0.035s] 10:00:00
2021-10-31 23:51:36.257 | INFO | [Commission] 高阶自主训练 |  (Genre: major_comm, Status: pending, Duration: 10:00:00)
2021-10-31 23:51:36.323 | INFO | [COMMISSION 0.066s] 舰队初阶演习
2021-10-31 23:51:36.341 | INFO | [COMMISSION 0.018s] 
2021-10-31 23:51:36.383 | INFO | [DURATION 0.041s] 04:00:00
2021-10-31 23:51:36.384 | INFO | [Commission] 舰队初阶演习 |  (Genre: extra_cube, Status: pending, Duration: 4:00:00)
2021-10-31 23:51:36.480 | INFO | [COMMISSION 0.096s] 高级林木护卫委托
2021-10-31 23:51:36.498 | INFO | [COMMISSION 0.018s] 
2021-10-31 23:51:36.531 | INFO | [DURATION 0.032s] 01:30:00
2021-10-31 23:51:36.532 | INFO | [Commission] 高级林木护卫委托 |  (Genre: extra_part, Status: pending, Duration: 1:30:00)
2021-10-31 23:51:36.533 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-10-31 23:51:36.534 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-10-31 23:51:36.534 | INFO | COMMISSION_SCROLL_AREA set to 1
2021-10-31 23:51:36.535 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-10-31 23:51:36.535 | INFO | Drag (1258,  325) -> (1258,  437)
2021-10-31 23:51:36.645 | ERROR | HTTPConnectionPool(host='127.0.0.1', port=4780): Max retries exceeded with url: http://127.0.0.1:56587/services/uiautomator (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4780): Max retries exceeded with url: http://127.0.0.1:56587/services/uiautomator (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 45, in run
    self.__getattribute__(command)()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 116, in commission
    RewardCommission(config=self.config, device=self.device).run()
  File "C:\fakepath\AzurLaneAutoScript\module\commission\commission.py", line 380, in run
    self.commission_start()
  File "C:\fakepath\AzurLaneAutoScript\module\commission\commission.py", line 293, in commission_start
    self._commission_scan_all()
  File "C:\fakepath\AzurLaneAutoScript\module\commission\commission.py", line 189, in _commission_scan_all
    daily = self._commission_scan_list()
  File "C:\fakepath\AzurLaneAutoScript\module\commission\commission.py", line 171, in _commission_scan_list
    if not self._commission_swipe():
  File "C:\fakepath\AzurLaneAutoScript\module\commission\commission.py", line 149, in _commission_swipe
    COMMISSION_SCROLL.next_page(main=self)
  File "C:\fakepath\AzurLaneAutoScript\module\ui\scroll.py", line 169, in next_page
    self.drag_page(0.8, main=main, random_range=random_range, skip_first_screenshot=skip_first_screenshot)
  File "C:\fakepath\AzurLaneAutoScript\module\ui\scroll.py", line 166, in drag_page
    self.set(target, main=main, random_range=random_range, skip_first_screenshot=True)
  File "C:\fakepath\AzurLaneAutoScript\module\ui\scroll.py", line 139, in set
    main.device.drag(p1, p2, shake=(0, 0), point_random=(0, 0, 0, 0), shake_random=(0, 0, 0, 0))
  File "C:\fakepath\AzurLaneAutoScript\module\device\control.py", line 190, in drag
    swipe_duration=swipe_duration, shake_duration=shake_duration)
  File "C:\fakepath\AzurLaneAutoScript\module\device\control.py", line 220, in _drag_uiautomator2
    self.drag_along(path)
  File "C:\fakepath\AzurLaneAutoScript\module\device\control.py", line 169, in drag_along
    self.device.touch.down(x, y)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 1023, in down
    obj.jsonrpc.injectInputEvent(ACTION_DOWN, x, y, 0)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 459, in __call__
    http_timeout)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 469, in _jsonrpc_retry_call
    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 622, in reset_uiautomator
    launch_test_app=depth > 0)  # uiautomator 2.0
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 640, in _force_reset_uiautomator_v2
    self.uiautomator.stop()
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 171, in stop
    res = self.u2obj.http.delete(self.service_url)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 587, in delete
    return self.request('DELETE', url, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 194, in request
    return super().request(method, url, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 111, in request
    self).request(method, url, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\requests\adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=4780): Max retries exceeded with url: http://127.0.0.1:56587/services/uiautomator (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2021-10-31 23:51:36.650 | WARNING | Saving error: ./log/error/163569549665
![2021-10-31_23-51-35-829026](https://user-images.githubusercontent.com/63281018/139593842-a2bfca9d-9ee2-46e8-a247-da8085b0566b.png)
0

**Comment by LmeSzinc** [comment]
这个 issue 和 #712 的问题一样，你需要先安装 uiautomator2。
一般来说，alas 会自动安装 u2，u2 本身在第一次连接的时候也会自动安装。但是由于你的代理，代理了本地连接，导致无法连接模拟器，无法安装。

> requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=4780): Max retries exceeded with url: http://127.0.0.1:56587/services/uiautomator (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

你需要修改你的代理的规则，然后打开模拟器，并在 console.bat 中安装执行：
```
python -m uiautomator2 init
```
