### ISSUE TITLE
自动进入后宅后10061目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by dhujsi** [LmeSzinc/AzurLaneAutoScript#712]
2021-10-31 18:04:07.204 | INFO | +--------------------------------------------+
2021-10-31 18:04:07.205 | INFO | |                    DORM                    |
2021-10-31 18:04:07.205 | INFO | +--------------------------------------------+
2021-10-31 18:04:08.517 | INFO | <<< UI ENSURE >>>
2021-10-31 18:04:08.736 | INFO | [UI] page_dorm
2021-10-31 18:04:08.736 | INFO | Goto page_dormmenu
2021-10-31 18:04:08.737 | INFO | <<< UI GOTO PAGE_DORMMENU >>>
2021-10-31 18:04:08.768 | INFO | Click (  42,   36) @ DORM_GOTO_MAIN
2021-10-31 18:04:11.221 | INFO | Click ( 589,  679) @ MAIN_GOTO_DORMMENU
2021-10-31 18:04:12.699 | INFO | <<< UI GOTO PAGE_DORM >>>
2021-10-31 18:04:12.706 | INFO | Click ( 657,  338) @ DORMMENU_GOTO_DORM
2021-10-31 18:04:14.339 | INFO | Dorm zoom out
2021-10-31 18:04:14.340 | INFO | <<< MINITOUCH INIT >>>
2021-10-31 18:04:16.340 | INFO | Minitouch bind to port 20187
2021-10-31 18:04:16.385 | INFO | Minitouch forward port 20187
2021-10-31 18:04:18.389 | ERROR | [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 45, in run
    self.__getattribute__(command)()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 124, in dorm
    RewardDorm(config=self.config, device=self.device).run()
  File "C:\fakepath\AzurLaneAutoScript\module\dorm\dorm.py", line 285, in run
    self.dorm_run(feed=self.config.Dorm_Feed, collect=self.config.Dorm_Collect)
  File "C:\fakepath\AzurLaneAutoScript\module\dorm\dorm.py", line 266, in dorm_run
    self._dorm_receive()
  File "C:\fakepath\AzurLaneAutoScript\module\dorm\dorm.py", line 138, in _dorm_receive
    self.device.minitouch_builder.down(x, y, contact_id=1).commit()
  File "C:\fakepath\AzurLaneAutoScript\module\base\decorator.py", line 95, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\fakepath\AzurLaneAutoScript\module\device\minitouch.py", line 183, in minitouch_builder
    self.minitouch_init()
  File "C:\fakepath\AzurLaneAutoScript\module\device\minitouch.py", line 200, in minitouch_init
    client.connect(('127.0.0.1', self._minitouch_port))
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2021-10-31 18:04:18.391 | WARNING | Saving error: ./log/error/1635674658390

**Comment by LmeSzinc** [comment]
#711
