### ISSUE TITLE
大作战每月开荒遇到 ValueError: sleep length must be non-negative

### ISSUE THREAD

**Issue by RhoninM** [LmeSzinc/AzurLaneAutoScript#734]
| ERROR | sleep length must be non-negative
Traceback (most recent call last):
  File "D:\Games\AzurLaneAutoScript\alas.py", line 25, in config
    config = AzurLaneConfig(config_name=self.config_name)
  File "D:\Games\AzurLaneAutoScript\module\config\config.py", line 77, in __init__
    task = self.get_next()
  File "D:\Games\AzurLaneAutoScript\module\config\config.py", line 182, in get_next
    return self.get_next()
  File "D:\Games\AzurLaneAutoScript\module\config\config.py", line 181, in get_next
    time.sleep(task.next_run.timestamp() - datetime.now().timestamp() + 1)
ValueError: sleep length must be non-negative

**Comment by LmeSzinc** [comment]
需要提供完整 log

**Comment by LmeSzinc** [comment]
08c033a6e19cef5305d0cfb0128df7cee5f0ac5c
