### ISSUE TITLE
主线图运行一段时间后会停止

### ISSUE THREAD

**Issue by Ka-gu-ya** [LmeSzinc/AzurLaneAutoScript#736]
在进行主线13-4的主线推图时，会有一定概率因为图片原因停下（log如下）。不是每次必定发生，而是过一段时间概率发生的bug。我唯一修改过的地方时选敌的优先级。

log：
20:34:14.094 | WARNING | Image to detect is not in_map
20:34:14.095 | ERROR | Failed to find a free tile
Traceback (most recent call last):
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\alas.py", line 217, in main
    name=self.config.Campaign_Name, folder=self.config.Campaign_Event, mode=self.config.Campaign_Mode)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\run.py", line 210, in run
    self.campaign.run()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\campaign_base.py", line 141, in run
    self.execute_a_battle()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\campaign_base.py", line 99, in execute_a_battle
    result = self.battle_function()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\base\decorator.py", line 69, in wrapper
    return record['func'](self, *args, **kwargs)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\campaign_base.py", line 89, in battle_function
    result = func()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\campaign\campaign_main\campaign_13_4.py", line 87, in battle_3
    self.pick_up_ammo()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\map.py", line 614, in clear_filter_enemy
    self.clear_chosen_enemy(grids[0])
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\map.py", line 25, in clear_chosen_enemy
    self.goto(grid, expected=expected)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\fleet.py", line 432, in goto
    self._goto(location, expected=expected)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\fleet.py", line 369, in _goto
    self.ensure_edge_insight()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\camera.py", line 205, in ensure_edge_insight
    self.map_swipe((x, y))
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\camera.py", line 65, in map_swipe
    self._map_swipe(vector)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\camera.py", line 46, in _map_swipe
    self.update()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\camera.py", line 123, in update
    raise e
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\camera.py", line 103, in update
    self.view.load(self.device.image)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map_detection\view.py", line 58, in load
    super().load(image)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map_detection\detector.py", line 49, in load
    self.backend.load(image)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map_detection\homography.py", line 82, in load
    self.detect(image)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map_detection\homography.py", line 180, in detect
    raise MapDetectionError('Failed to find a free tile')
module.exception.MapDetectionError: Failed to find a free tile
20:34:14.122 | WARNING | Saving error: ./log/error/1636202054122

**Comment by LmeSzinc** [comment]
需要完整 log

**Comment by Ka-gu-ya** [comment]
20:33:33.883 | INFO | -------------------- BATTLE_3 --------------------
20:33:33.884 | INFO | Using function: battle_3
20:33:33.884 | INFO | Pick up ammo: H2
20:33:33.884 | INFO | In sight: H2
20:33:33.884 | INFO | Focus to: E2
20:33:33.884 | INFO | Map swipe: (1, -3)
20:33:33.884 | INFO | Swipe ( 452,  205) -> ( 264,  587), 0.123
20:33:35.084 | INFO |            tile_center: 0.942 (good match)
20:33:35.094 | INFO | 0.055s  _   edge_lines: 1 hori, 0 vert
20:33:35.094 | INFO | Edges:       homo_loca: ( 35,  52)
20:33:35.098 | INFO |           grids_offset: (1, 0)
20:33:35.098 | INFO |            center_loca: (3, 2)
20:33:35.182 | INFO | Map swipe predict: (1, -3) (0.084s, 2 matches)
20:33:35.182 | INFO |                 Camera: E3
20:33:35.183 | INFO |                 Camera: E3
20:33:35.183 | INFO | Map swipe: (0, -1)
20:33:35.184 | INFO | Swipe ( 647,  250) -> ( 646,  386), 0.164
20:33:36.179 | INFO |            tile_center: 0.942 (good match)
20:33:36.188 | INFO | 0.056s  _   edge_lines: 1 hori, 0 vert
20:33:36.189 | INFO | Edges:       homo_loca: ( 32,  64)
20:33:36.191 | INFO |           grids_offset: (1, 0)
20:33:36.192 | INFO |            center_loca: (3, 1)
20:33:36.249 | INFO | Map swipe predict: (0, -1) (0.057s, 5 matches)
20:33:36.250 | INFO |                 Camera: E2
20:33:36.250 | INFO |                 Camera: E2
20:33:36.251 | INFO | Map swipe: (0, 0)
20:33:36.718 | INFO | Global H2 (camera=E2) -> Local G2 (center=D2)
20:33:36.720 | INFO | Click (1024,  354) @ G2
20:33:42.214 | INFO | Arrive H2
20:33:45.569 | INFO | Arrive H2 confirm. Result: nothing. Expected: 
20:33:45.570 | INFO | Click (1008,  349) @ G2
20:33:46.436 | INFO | [Got ammo] 3
20:33:46.437 | INFO | Filter enemy: [B7, C8, G3, E6, H5, F4], preserve=0
20:33:46.437 | INFO | <<< CLEAR FILTER ENEMY >>>
20:33:46.437 | INFO | Clear enemy: B7
20:33:46.437 | INFO | [Fleet_1: H2] Fleet_2: B4
20:33:46.452 | INFO | Save config ./config\alas.json, Main.Emotion.Fleet1Value=142, Main.Emotion.Fleet1Record=datetime.datetime(2021, 11, 6, 20, 33, 46), Main.Emotion.Fleet2Value=119, Main.Emotion.Fleet2Record=datetime.datetime(2021, 11, 6, 20, 33, 46)
20:33:46.455 | INFO | [Emotion fleet_1] 142
20:33:46.455 | INFO | [Emotion fleet_2] 119
20:33:46.455 | INFO | In sight: B7
20:33:46.456 | INFO | Focus to: E5
20:33:46.456 | INFO | Map swipe: (0, 3)
20:33:46.457 | INFO | Swipe ( 646,  592) -> ( 649,  203), 0.184
20:33:47.662 | INFO |            tile_center: 0.955 (good match)
20:33:47.670 | INFO | 0.054s      edge_lines: 0 hori, 0 vert
20:33:47.670 | INFO | Edges:       homo_loca: ( 35,  75)
20:33:47.674 | INFO |            center_loca: (4, 3)
20:33:47.743 | INFO | Map swipe predict: (0, 3) (0.068s, 2 matches)
20:33:47.744 | INFO |                 Camera: E5
20:33:47.744 | INFO |                 Camera: E5
20:33:47.744 | INFO | Map swipe: (0, 0)
20:33:48.235 | INFO | Global B7 (camera=E5) -> Local B6 (center=E4)
20:33:48.237 | INFO | Click ( 214,  567) @ B6
20:34:08.671 | WARNING | Walk timeout. Retrying.
20:34:08.672 | INFO | Ensure edge in sight.
20:34:09.186 | INFO |            tile_center: 0.955 (good match)
20:34:09.193 | INFO | 0.053s      edge_lines: 0 hori, 0 vert
20:34:09.194 | INFO | Edges:       homo_loca: ( 34,  73)
20:34:09.198 | INFO |            center_loca: (4, 3)
20:34:09.198 | INFO |                 Camera: E5
20:34:09.199 | INFO | Map swipe: (-4, -3)
20:34:09.199 | INFO | Swipe ( 259,  211) -> (1002,  589), 0.14
20:34:10.654 | INFO |            tile_center: 0.955 (good match)
20:34:10.661 | INFO | 0.053s      edge_lines: 0 hori, 0 vert
20:34:10.662 | INFO | Edges:       homo_loca: ( 34,  73)
20:34:10.666 | INFO |            center_loca: (4, 3)
20:34:10.777 | INFO | Map swipe predict: (0, 0) (0.111s, 31 matches)
20:34:10.777 | INFO |                 Camera: E5
20:34:10.778 | INFO |                 Camera: E5
20:34:10.778 | INFO | Map swipe: (-4, -3)
20:34:10.778 | INFO | Swipe ( 282,  205) -> (1025,  583), 0.116
20:34:12.366 | INFO |            tile_center: 0.634 (bad match)
20:34:12.524 | INFO |            tile_corner: 0.833 (5 matches)
20:34:12.531 | INFO | 0.220s      edge_lines: 0 hori, 0 vert
20:34:12.531 | INFO | Edges:       homo_loca: ( 68, 129)
20:34:12.535 | INFO |            center_loca: (4, 3)
20:34:12.619 | INFO | Map swipe predict: None (0.084s, no match)
20:34:12.619 | INFO |                 Camera: A2
20:34:12.620 | INFO |                 Camera: A2
20:34:12.620 | INFO | Map swipe: (-4, -3)
20:34:12.620 | INFO | Swipe ( 311,  256) -> (1020,  594), 0.149
20:34:13.886 | INFO |            tile_center: 0.558 (bad match)
20:34:14.020 | INFO |            tile_corner: 0.732 (bad match)
20:34:14.091 | INFO |         tile_rectangle: 0 rectangles (bad match)
20:34:14.094 | WARNING | Image to detect is not in_map
20:34:14.095 | ERROR | Failed to find a free tile
Traceback (most recent call last):
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\alas.py", line 217, in main
    name=self.config.Campaign_Name, folder=self.config.Campaign_Event, mode=self.config.Campaign_Mode)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\run.py", line 210, in run
    self.campaign.run()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\campaign_base.py", line 141, in run
    self.execute_a_battle()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\campaign_base.py", line 99, in execute_a_battle
    result = self.battle_function()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\base\decorator.py", line 69, in wrapper
    return record['func'](self, *args, **kwargs)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\campaign\campaign_base.py", line 89, in battle_function
    result = func()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\campaign\campaign_main\campaign_13_4.py", line 87, in battle_3
    self.pick_up_ammo()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\map.py", line 614, in clear_filter_enemy
    self.clear_chosen_enemy(grids[0])
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\map.py", line 25, in clear_chosen_enemy
    self.goto(grid, expected=expected)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\fleet.py", line 432, in goto
    self._goto(location, expected=expected)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\fleet.py", line 369, in _goto
    self.ensure_edge_insight()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\camera.py", line 205, in ensure_edge_insight
    self.map_swipe((x, y))
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\camera.py", line 65, in map_swipe
    self._map_swipe(vector)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\camera.py", line 46, in _map_swipe
    self.update()
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\camera.py", line 123, in update
    raise e
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map\camera.py", line 103, in update
    self.view.load(self.device.image)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map_detection\view.py", line 58, in load
    super().load(image)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map_detection\detector.py", line 49, in load
    self.backend.load(image)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map_detection\homography.py", line 82, in load
    self.detect(image)
  File "C:\software\AzurLaneAutoScript\AzurLaneAutoScript\module\map_detection\homography.py", line 180, in detect
    raise MapDetectionError('Failed to find a free tile')
module.exception.MapDetectionError: Failed to find a free tile
20:34:14.122 | WARNING | Saving error: ./log/error/1636202054122

**Comment by Ka-gu-ya** [comment]
模拟器抽风吗

**Comment by Ka-gu-ya** [comment]
每一次过图扫描时还有这种警告
![1DRGUA)4)~PZ4LMY8JVF2(8](https://user-images.githubusercontent.com/44470016/140611231-f0112fe3-7278-4c62-bf10-a0afa5175f74.png)

**Comment by LmeSzinc** [comment]
原因是，模拟器卡顿或者游戏卡顿时，把滑动当成点击，又刚好点到了一个敌人进入战斗，导致海图识别报错

**Comment by LmeSzinc** [comment]
#743
