### ISSUE TITLE
自律怪自动进战报错

### ISSUE THREAD

**Issue by ShiroRan** [LmeSzinc/AzurLaneAutoScript#738]
**22:18:53.355 | INFO | [enemy_missing] EN: 0, MY: 0, SI: 1, BO: 0, CA: 0
22:18:53.355 | INFO | [enemy_may____] EN: 3, MY: 0, SI: 3, BO: 0, CA: 2
22:18:53.355 | INFO | Focus to: F4
22:18:53.355 | INFO | Map swipe: (1, -2)
22:18:53.356 | INFO | Swipe ( 666,  286) -> ( 467,  559), 0.147
22:18:54.203 | INFO |           vanish_point: (  940,   186)
22:18:54.203 | INFO |          distant_point: (  335,   186)
22:18:54.215 | INFO | Horizontal coincident point unexpected: [ 1.15707838e+03 -9.89956797e-04]
22:18:54.217 | WARNING | Image to detect is not in_map
22:18:54.218 | ERROR | 'Points' object has no attribute 'x'
Traceback (most recent call last):
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\alas.py", line 192, in event_sp
    CampaignSP(config=self.config, device=self.device).run()
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\event\campaign_sp.py", line 16, in run
    super().run(name=self.config.Campaign_Name, folder=self.config.Campaign_Event, total=1)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\campaign\run.py", line 210, in run
    self.campaign.run()
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\campaign\campaign_base.py", line 141, in run
    self.execute_a_battle()
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\campaign\campaign_base.py", line 99, in execute_a_battle
    result = self.battle_function()
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\base\decorator.py", line 69, in wrapper
    return record['func'](self, *args, **kwargs)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\campaign\campaign_base.py", line 89, in battle_function
    result = func()
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\campaign\event_20211028_cn\sp.py", line 112, in battle_0
    if self.clear_siren():
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\map.py", line 438, in clear_siren
    self.clear_chosen_enemy(grids[0], expected=expected)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\map.py", line 25, in clear_chosen_enemy
    self.goto(grid, expected=expected)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\fleet.py", line 422, in goto
    self._goto(node, expected=expected if node == nodes[-1] else '')
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\fleet.py", line 387, in _goto
    self.full_scan_movable(enemy_cleared=result == 'combat')
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\fleet.py", line 518, in full_scan_movable
    must_scan=self.movable_before, mode='movable')
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\fleet.py", line 465, in full_scan
    siren_count=self.siren_count, carrier_count=self.carrier_count, mode=mode)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\camera.py", line 272, in full_scan
    self.focus_to(queue[0])
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\camera.py", line 236, in focus_to
    self.map_swipe(swipe)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\camera.py", line 65, in map_swipe
    self._map_swipe(vector)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\camera.py", line 46, in _map_swipe
    self.update()
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\camera.py", line 123, in update
    raise e
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map\camera.py", line 103, in update
    self.view.load(self.device.image)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map_detection\view.py", line 58, in load
    super().load(image)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map_detection\detector.py", line 49, in load
    self.backend.load(image)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map_detection\perspective.py", line 137, in load
    self.horizontal, inner=inner_h.group(), edge=edge_h)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map_detection\perspective.py", line 390, in line_cleanse
    clean = self.mid_cleanse(origin, is_horizontal=lines.is_horizontal, threshold=threshold)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map_detection\perspective.py", line 384, in mid_cleanse
    mids = convert_to_y(mids)
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map_detection\perspective.py", line 319, in convert_to_y
    .link(right_distant_point) \
  File "C:\Users\Shiro\Desktop\AzurLaneAutoScript\module\map_detection\utils.py", line 41, in link
    theta = -np.arctan((self.x - x) / (self.y - y))
AttributeError: 'Points' object has no attribute 'x'
22:18:59.784 | INFO | Start scheduler loop: alas
22:18:59.785 | INFO | [Server] cn
22:18:59.799 | INFO | Pending tasks: ['EventSp', 'EventAb', 'OpsiDaily', 'Event']
22:18:59.799 | INFO | [Task] EventSp
22:18:59.799 | INFO | Bind task EventSp
22:18:59.799 | INFO | Scheduler: Start task `EventSp`**

**Comment by LmeSzinc** [comment]
#736
