### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by pigeon-cn-0** [LmeSzinc/AzurLaneAutoScript#75]
2020-06-29 19:06:02.805 | INFO | Horizontal coincident point unexpected: [-586.34250865  124.70727411]
2020-06-29 19:06:02.806 | ERROR | Camera outside map: to the lower
Traceback (most recent call last):
  File "D:\alasl-text\AzurLaneAutoScript\module\map\camera.py", line 116, in update
    self.grids = Grids(self.device.image, config=self.config)
  File "D:\alasl-text\AzurLaneAutoScript\module\map\grids.py", line 19, in __init__
    super().__init__(image, config)
  File "D:\alasl-text\AzurLaneAutoScript\module\map\perspective.py", line 98, in __init__
    self.horizontal, inner=inner_h.group(), edge=edge_h)
  File "D:\alasl-text\AzurLaneAutoScript\module\map\perspective.py", line 387, in line_cleanse
    raise PerspectiveError('Camera outside map: to the %s' % ('lower' if lines.is_horizontal else 'left'))
module.exception.PerspectiveError: Camera outside map: to the lower

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\alasl-text\AzurLaneAutoScript\alas.py", line 24, in run
    self.__getattribute__(command.lower())()
  File "D:\alasl-text\AzurLaneAutoScript\alas.py", line 92, in main
    az.run(self.config.CAMPAIGN_NAME)
  File "D:\alasl-text\AzurLaneAutoScript\module\campaign\run.py", line 173, in run
    self.campaign.run()
  File "D:\alasl-text\AzurLaneAutoScript\module\campaign\campaign_base.py", line 110, in run
    self.execute_a_battle()
  File "D:\alasl-text\AzurLaneAutoScript\module\base\decorator.py", line 62, in wrapper
    return record['func'](self, *args, **kwargs)
  File "D:\alasl-text\AzurLaneAutoScript\module\campaign\campaign_base.py", line 88, in execute_a_battle
    result = func()
  File "D:\alasl-text\AzurLaneAutoScript\campaign\campaign_main\campaign_3_4.py", line 59, in battle_0
    self.fleet_2_push_forward()
  File "D:\alasl-text\AzurLaneAutoScript\module\map\map.py", line 445, in fleet_2_push_forward
    self.fleet_1.switch_to()
  File "D:\alasl-text\AzurLaneAutoScript\module\map\fleet.py", line 28, in fleet_1
    self.fleet_switch()
  File "D:\alasl-text\AzurLaneAutoScript\module\map\fleet.py", line 79, in fleet_switch
    self.update()
  File "D:\alasl-text\AzurLaneAutoScript\module\map\camera.py", line 121, in update
    return self.update(camera=camera)
  File "D:\alasl-text\AzurLaneAutoScript\module\map\camera.py", line 123, in update
    raise e
  File "D:\alasl-text\AzurLaneAutoScript\module\map\camera.py", line 116, in update
    self.grids = Grids(self.device.image, config=self.config)
  File "D:\alasl-text\AzurLaneAutoScript\module\map\grids.py", line 19, in __init__
    super().__init__(image, config)
  File "D:\alasl-text\AzurLaneAutoScript\module\map\perspective.py", line 98, in __init__
    self.horizontal, inner=inner_h.group(), edge=edge_h)
  File "D:\alasl-text\AzurLaneAutoScript\module\map\perspective.py", line 387, in line_cleanse
    raise PerspectiveError('Camera outside map: to the %s' % ('lower' if lines.is_horizontal else 'left'))
module.exception.PerspectiveError: Camera outside map: to the lower
2020-06-29 19:06:02.808 | INFO | Saving error: ./log/error/1593428762808
此问题在3-4挂机的时候遇到

**Comment by LmeSzinc** [comment]
能否提供完整log和最后一张截图? log/error文件夹下有自动保存的log和最后60张截图

我在 3-4 测试了有3000+出击, 还没发生过在换队时把镜头移动至地图外面的问题

**Comment by pigeon-cn-0** [comment]
[1593428762808.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/4845385/1593428762808.zip)
我打包了一个压缩包，希望有所帮助

**Comment by LmeSzinc** [comment]
我注意到CN和JP在切换队伍后, 相机定位不一样
请确认: 1. 是否有在脚本运行时操作游戏 2. 是否有使用科技或者修改过的scripts
如果都没有, 只能将原因归结为不同服之间的差异, 暂时不能解决

![cn_jp_diff](https://user-images.githubusercontent.com/37934724/86008342-32740800-ba4b-11ea-822e-b1a3540a752e.png)

**Comment by pigeon-cn-0** [comment]
在昨天还能正常使用，也许是今天更新的原因，我看了官推说修复了显示错误

**Comment by pigeon-cn-0** [comment]
我试图更换截图方式和更换关卡（前面三图），经过少量的测试，似乎只有3-4会导致这样的原因，也许我们应该关闭这个问题了
后续的问题是我的油在低于限制条件的时候并没有停止运行。
