### ISSUE TITLE
3-4出击报错

### ISSUE THREAD

**Issue by liuxinyuk** [LmeSzinc/AzurLaneAutoScript#76]
模拟器：mumu
默认配置，主线图3-4，普通

第一次启动设置了出击15次停止，count[0]没问题，开始count[1]的时候报错，尝试重启程序，依然出现报错（count[0]），且都是一样的错误，**表现在模拟器里就是：卡在选择3-4地图后的那个【立刻前往】界面，无法进行下一步**。看log可能是**enter_map**那边出了问题？

刷共斗图正常。
刷2-4也正常。

log：
2020-06-29 20:34:12.713 | INFO | -------------------- 3-4 --------------------
2020-06-29 20:34:12.713 | INFO | <<< ENTER MAP >>>
2020-06-29 20:34:13.438 | INFO | [Screen_size] 1280x720
2020-06-29 20:34:13.477 | INFO | Click ( 596, 410) @ 3-4
2020-06-29 20:34:15.525 | INFO | [Map_clear] 99%
2020-06-29 20:34:15.526 | INFO | [MAP_CLEAR_ALL_THIS_TIME] False
2020-06-29 20:34:15.528 | INFO | Set fast forward.
2020-06-29 20:34:15.529 | INFO | [Fast_Forward] off
2020-06-29 20:34:15.529 | ERROR | 
Traceback (most recent call last):
  File "E:\mumuAndroid\AzurLaneAutoScript\alas.py", line 24, in run
    self.__getattribute__(command.lower())()
  File "E:\mumuAndroid\AzurLaneAutoScript\alas.py", line 92, in main
    az.run(self.config.CAMPAIGN_NAME)
  File "E:\mumuAndroid\AzurLaneAutoScript\module\campaign\run.py", line 173, in run
    self.campaign.run()
  File "E:\mumuAndroid\AzurLaneAutoScript\module\campaign\campaign_base.py", line 103, in run
    self.enter_map(self.ENTRANCE, mode=self.config.CAMPAIGN_MODE)
  File "E:\mumuAndroid\AzurLaneAutoScript\module\map\map_operation.py", line 60, in enter_map
    self.handle_fast_forward()
  File "E:\mumuAndroid\AzurLaneAutoScript\module\handler\fast_forward.py", line 41, in handle_fast_forward
    changed = fast_forward.set(status=status, main=self)
  File "E:\mumuAndroid\AzurLaneAutoScript\module\base\switch.py", line 66, in set
    logger.attr(self.name, current)
  File "E:\mumuAndroid\AzurLaneAutoScript\module\logger.py", line 51, in attr
    raise Exception
Exception
2020-06-29 20:34:15.532 | INFO | Saving error: ./log/error/1593434055532

**Comment by LmeSzinc** [comment]
我的锅, 不小心将调试的代码commit进去了, 已修复

**Comment by liuxinyuk** [comment]
大佬维护这么大的项目已经很强了! 本来想用Airtest自己整一个的，3-4写到一半就放弃思考了hhhh🙂
