### ISSUE TITLE
委托卡死

### ISSUE THREAD

**Issue by ShiroRan** [LmeSzinc/AzurLaneAutoScript#763]
2021-11-22 01:16:00.615 | INFO | +--------------------------------------------------+
2021-11-22 01:16:00.616 | INFO | |                    COMMISSION                    |
2021-11-22 01:16:00.616 | INFO | +--------------------------------------------------+
2021-11-22 01:16:00.616 | INFO | <<< UI ENSURE >>>
2021-11-22 01:16:00.635 | INFO | Unknown ui page
2021-11-22 01:16:00.637 | INFO | Click ( 847,  515) @ POPUP_CONFIRM_UI_ADDITIONAL
2021-11-22 01:16:00.688 | INFO | Goto page_main
2021-11-22 01:16:00.688 | INFO | <<< UI GOTO PAGE_MAIN >>>
2021-11-22 01:16:02.513 | WARNING | Unrecognized ui_current, using previous: page_unknown
2021-11-22 01:16:02.514 | INFO | Goto page_reward
2021-11-22 01:16:02.514 | INFO | <<< UI GOTO PAGE_REWARD >>>
2021-11-22 01:16:02.522 | INFO | Click (  25,  165) @ MAIN_GOTO_REWARD
2021-11-22 01:16:04.910 | INFO | <<< REWARD RECEIVE >>>
2021-11-22 01:16:04.912 | INFO | Click ( 475,  289) @ REWARD_1
2021-11-22 01:16:06.020 | INFO | Click ( 436,  290) @ REWARD_1
2021-11-22 01:16:09.933 | INFO | Click ( 481,  199) @ EXP_INFO_S_REWARD
2021-11-22 01:16:12.146 | INFO | Click ( 452,  188) @ EXP_INFO_S_REWARD
2021-11-22 01:16:13.213 | INFO | Click ( 477,  199) @ GET_ITEMS_1
2021-11-22 01:16:14.297 | INFO | Click ( 448,  281) @ REWARD_GOTO_COMMISSION
2021-11-22 01:16:15.359 | INFO | Click ( 418,  284) @ REWARD_GOTO_COMMISSION
2021-11-22 01:16:16.386 | INFO | ==================== COMMISSION SCAN ====================
2021-11-22 01:16:16.386 | INFO | [Commission_switch] daily
2021-11-22 01:16:16.387 | INFO | Click (  52,  256) @ COMMISSION_URGENT
2021-11-22 01:16:17.974 | INFO | [Commission_switch] urgent
2021-11-22 01:16:17.975 | INFO | -------------------- SCAN DAILY --------------------
2021-11-22 01:16:17.975 | INFO | [Commission_switch] urgent
2021-11-22 01:16:17.976 | INFO | Click (  37,  146) @ COMMISSION_DAILY
2021-11-22 01:16:19.579 | INFO | [Commission_switch] urgent
2021-11-22 01:16:19.579 | INFO | Click (  52,  168) @ COMMISSION_DAILY
2021-11-22 01:16:21.135 | INFO | [Commission_switch] daily
2021-11-22 01:16:21.136 | INFO | COMMISSION_SCROLL_AREA set to 0.0
2021-11-22 01:16:21.137 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-11-22 01:16:21.236 | INFO | [COMMISSION 0.098s] 大型商船护卫
2021-11-22 01:16:21.275 | INFO | [COMMISSION 0.038s] 
2021-11-22 01:16:21.354 | INFO | [DURATION 0.077s] 00:59:14
2021-11-22 01:16:21.355 | INFO | [Commission] 大型商船护卫 |  (Genre: extra_book, Status: running, Duration: 0:59:14)
2021-11-22 01:16:21.458 | INFO | [COMMISSION 0.102s] 舰队高阶演习
2021-11-22 01:16:21.500 | INFO | [COMMISSION 0.041s] 
2021-11-22 01:16:21.568 | INFO | [DURATION 0.067s] 00:59:23
2021-11-22 01:16:21.570 | INFO | [Commission] 舰队高阶演习 |  (Genre: extra_cube, Status: running, Duration: 0:59:23)
2021-11-22 01:16:21.680 | INFO | [COMMISSION 0.109s] 高阶战术课程
2021-11-22 01:16:21.733 | INFO | [COMMISSION 0.052s] 
2021-11-22 01:16:21.791 | INFO | [DURATION 0.058s] 10:00:00
2021-11-22 01:16:21.792 | INFO | [Commission] 高阶战术课程 |  (Genre: major_comm, Status: pending, Duration: 10:00:00)
2021-11-22 01:16:21.879 | INFO | [COMMISSION 0.085s] 日常资源开发I
2021-11-22 01:16:21.918 | INFO | [COMMISSION 0.037s] I
2021-11-22 01:16:21.988 | INFO | [DURATION 0.067s] 01:00:00
2021-11-22 01:16:21.990 | INFO | [Commission] 日常资源开发I | Ⅰ (Genre: daily_resource, Status: pending, Duration: 1:00:00)
2021-11-22 01:16:21.991 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-11-22 01:16:21.992 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-11-22 01:16:21.993 | INFO | COMMISSION_SCROLL_AREA set to 1
2021-11-22 01:16:21.994 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-11-22 01:16:21.995 | INFO | Drag (1260,  333) -> (1258,  439)
2021-11-22 01:16:23.185 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:23.288 | INFO | [COMMISSION 0.103s] 舰队高阶演习
2021-11-22 01:16:23.329 | INFO | [COMMISSION 0.040s] 
2021-11-22 01:16:23.396 | INFO | [DURATION 0.066s] 00:59:20
2021-11-22 01:16:23.398 | INFO | [Commission] 舰队高阶演习 |  (Genre: extra_cube, Status: running, Duration: 0:59:20)
2021-11-22 01:16:23.489 | INFO | [COMMISSION 0.090s] 高阶战术课程
2021-11-22 01:16:23.528 | INFO | [COMMISSION 0.037s] 
2021-11-22 01:16:23.603 | INFO | [DURATION 0.075s] 10:00:00
2021-11-22 01:16:23.606 | INFO | [Commission] 高阶战术课程 |  (Genre: major_comm, Status: pending, Duration: 10:00:00)
2021-11-22 01:16:23.714 | INFO | [COMMISSION 0.106s] 日常资源开发I
2021-11-22 01:16:23.756 | INFO | [COMMISSION 0.041s] I
2021-11-22 01:16:23.833 | INFO | [DURATION 0.074s] 01:00:00
2021-11-22 01:16:23.835 | INFO | [Commission] 日常资源开发I | Ⅰ (Genre: daily_resource, Status: pending, Duration: 1:00:00)
2021-11-22 01:16:23.942 | INFO | [COMMISSION 0.106s] 高阶战术研发I
2021-11-22 01:16:23.984 | INFO | [COMMISSION 0.041s] I
2021-11-22 01:16:24.052 | INFO | [DURATION 0.067s] 01:00:00
2021-11-22 01:16:24.054 | INFO | [Commission] 高阶战术研发I | Ⅰ (Genre: daily_chip, Status: pending, Duration: 1:00:00)
2021-11-22 01:16:24.055 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:24.056 | INFO | -------------------- SCAN URGENT --------------------
2021-11-22 01:16:24.056 | INFO | [Commission_switch] daily
2021-11-22 01:16:24.057 | INFO | Click (  56,  265) @ COMMISSION_URGENT
2021-11-22 01:16:25.804 | INFO | [Commission_switch] urgent
2021-11-22 01:16:25.805 | INFO | COMMISSION_SCROLL_AREA set to 0.0
2021-11-22 01:16:25.806 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:25.806 | INFO | Drag (1258,  423) -> (1255,  310)
2021-11-22 01:16:27.007 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:27.862 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:27.862 | INFO | Drag (1255,  419) -> (1259,  310)
2021-11-22 01:16:29.016 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:29.497 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:30.045 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:30.046 | INFO | Drag (1254,  422) -> (1254,  310)
2021-11-22 01:16:38.873 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:38.874 | INFO | Drag (1260,  418) -> (1256,  310)
2021-11-22 01:16:40.364 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-11-22 01:16:40.475 | INFO | [COMMISSION 0.110s] 近海防卫巡逻
2021-11-22 01:16:40.517 | INFO | [COMMISSION 0.041s] 
2021-11-22 01:16:40.584 | INFO | [DURATION 0.066s] 02:30:17
2021-11-22 01:16:40.587 | INFO | [Commission] 近海防卫巡逻 |  (Genre: extra_drill, Status: running, Duration: 2:30:17)
2021-11-22 01:16:40.691 | INFO | [COMMISSION 0.102s] NYB装备运输
2021-11-22 01:16:40.733 | INFO | [COMMISSION 0.041s] 
2021-11-22 01:16:40.801 | INFO | [DURATION 0.067s] 01:00:00
2021-11-22 01:16:40.862 | INFO | [EXPIRE 0.060s] 04:15:08
2021-11-22 01:16:40.863 | INFO | [Commission] NYB装备运输 |  (Genre: urgent_box, Status: pending, Duration: 1:00:00, Expire: 4:15:08)
2021-11-22 01:16:40.967 | INFO | [COMMISSION 0.103s] 小型商船护卫
2021-11-22 01:16:41.010 | INFO | [COMMISSION 0.042s] 
2021-11-22 01:16:41.083 | INFO | [DURATION 0.073s] 06:00:00
2021-11-22 01:16:41.141 | INFO | [EXPIRE 0.056s] 01:43:22
2021-11-22 01:16:41.142 | INFO | [Commission] 小型商船护卫 |  (Genre: extra_book, Status: pending, Duration: 6:00:00, Expire: 1:43:22)
2021-11-22 01:16:41.250 | INFO | [COMMISSION 0.107s] 舰队中阶演习
2021-11-22 01:16:41.290 | INFO | [COMMISSION 0.039s] 
2021-11-22 01:16:41.363 | INFO | [DURATION 0.072s] 07:00:00
2021-11-22 01:16:41.430 | INFO | [EXPIRE 0.065s] 01:43:22
2021-11-22 01:16:41.432 | INFO | [Commission] 舰队中阶演习 |  (Genre: extra_cube, Status: pending, Duration: 7:00:00, Expire: 1:43:22)
2021-11-22 01:16:41.433 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-11-22 01:16:41.434 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-11-22 01:16:41.435 | INFO | COMMISSION_SCROLL_AREA set to 1
2021-11-22 01:16:41.436 | INFO | [COMMISSION_SCROLL_AREA] 0.01
2021-11-22 01:16:41.437 | INFO | Drag (1256,  326) -> (1260,  438)
2021-11-22 01:16:42.606 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:42.694 | INFO | [COMMISSION 0.088s] NYB装备运输
2021-11-22 01:16:42.738 | INFO | [COMMISSION 0.043s] 
2021-11-22 01:16:42.810 | INFO | [DURATION 0.070s] 01:00:00
2021-11-22 01:16:42.860 | INFO | [EXPIRE 0.049s] 04:15:05
2021-11-22 01:16:42.862 | INFO | [Commission] NYB装备运输 |  (Genre: urgent_box, Status: pending, Duration: 1:00:00, Expire: 4:15:05)
2021-11-22 01:16:42.970 | INFO | [COMMISSION 0.107s] 小型商船护卫
2021-11-22 01:16:43.016 | INFO | [COMMISSION 0.044s] 
2021-11-22 01:16:43.080 | INFO | [DURATION 0.063s] 06:00:00
2021-11-22 01:16:43.136 | INFO | [EXPIRE 0.054s] 01:43:19
2021-11-22 01:16:43.137 | INFO | [Commission] 小型商船护卫 |  (Genre: extra_book, Status: pending, Duration: 6:00:00, Expire: 1:43:19)
2021-11-22 01:16:43.229 | INFO | [COMMISSION 0.091s] 一舰队中阶演习
2021-11-22 01:16:43.272 | INFO | [COMMISSION 0.042s] 
2021-11-22 01:16:43.346 | INFO | [DURATION 0.072s] 07:00:00
2021-11-22 01:16:43.392 | INFO | [EXPIRE 0.045s] 01:43:19
2021-11-22 01:16:43.394 | INFO | [Commission] 一舰队中阶演习 |  (Genre: extra_cube, Status: pending, Duration: 7:00:00, Expire: 1:43:19)
2021-11-22 01:16:43.488 | INFO | [COMMISSION 0.093s] 大型商船护卫
2021-11-22 01:16:43.532 | INFO | [COMMISSION 0.044s] 
2021-11-22 01:16:43.601 | INFO | [DURATION 0.067s] 08:00:00
2021-11-22 01:16:43.656 | INFO | [EXPIRE 0.054s] 01:43:19
2021-11-22 01:16:43.657 | INFO | [Commission] 大型商船护卫 |  (Genre: extra_book, Status: pending, Duration: 8:00:00, Expire: 1:43:19)
2021-11-22 01:16:43.659 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:43.660 | INFO | -------------------- SHOWING COMMISSION --------------------
2021-11-22 01:16:43.661 | INFO | Daily commission
2021-11-22 01:16:43.661 | INFO | [Commission] 高阶战术研发I | Ⅰ (Genre: daily_chip, Status: pending, Duration: 1:00:00)
2021-11-22 01:16:43.662 | INFO | [Commission] 日常资源开发I | Ⅰ (Genre: daily_resource, Status: pending, Duration: 1:00:00)
2021-11-22 01:16:43.663 | INFO | [Commission] 高阶战术课程 |  (Genre: major_comm, Status: pending, Duration: 10:00:00)
2021-11-22 01:16:43.663 | INFO | [Commission] 大型商船护卫 |  (Genre: extra_book, Status: running, Duration: 0:59:14)
2021-11-22 01:16:43.664 | INFO | [Commission] 舰队高阶演习 |  (Genre: extra_cube, Status: running, Duration: 0:59:23)
2021-11-22 01:16:43.665 | INFO | Urgent commission
2021-11-22 01:16:43.665 | INFO | [Commission] 小型商船护卫 |  (Genre: night_book, Status: pending, Duration: 6:00:00, Expire: 1:43:22)
2021-11-22 01:16:43.666 | INFO | [Commission] 大型商船护卫 |  (Genre: night_book, Status: pending, Duration: 8:00:00, Expire: 1:43:19)
2021-11-22 01:16:43.667 | INFO | [Commission] 舰队中阶演习 |  (Genre: night_cube, Status: pending, Duration: 7:00:00, Expire: 1:43:22)
2021-11-22 01:16:43.668 | INFO | [Commission] NYB装备运输 |  (Genre: urgent_box, Status: pending, Duration: 1:00:00, Expire: 4:15:08)
2021-11-22 01:16:43.668 | INFO | [Commission] 近海防卫巡逻 |  (Genre: night_drill, Status: running, Duration: 2:30:17)
2021-11-22 01:16:43.669 | INFO | [Running] 3/4
2021-11-22 01:16:43.672 | INFO | [Filter_sort] NYB装备运输 |  (Genre: urgent_box, Status: pending, Duration: 1:00:00, Expire: 4:15:08) > 高阶战术研发I | Ⅰ (Genre: daily_chip, Status: pending, Duration: 1:00:00) > 日常资源开发I | Ⅰ (Genre: daily_resource, Status: pending, Duration: 1:00:00) > 舰队中阶演习 |  (Genre: night_cube, Status: pending, Duration: 7:00:00, Expire: 1:43:22) > shortest
2021-11-22 01:16:43.672 | INFO | Choose urgent commission
2021-11-22 01:16:43.673 | INFO | NYB装备运输 |  (Genre: urgent_box, Status: pending, Duration: 1:00:00, Expire: 4:15:08)
2021-11-22 01:16:43.673 | INFO | ==================== COMMISSION RUN ====================
2021-11-22 01:16:43.676 | INFO | [Commission_switch] urgent
2021-11-22 01:16:43.678 | INFO | COMMISSION_SCROLL_AREA set to 0.0
2021-11-22 01:16:43.679 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:43.680 | INFO | Drag (1254,  426) -> (1258,  310)
2021-11-22 01:16:45.096 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:45.653 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:45.653 | INFO | Drag (1257,  422) -> (1258,  310)
2021-11-22 01:16:46.872 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:47.310 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:47.820 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:47.821 | INFO | Drag (1255,  423) -> (1259,  310)
2021-11-22 01:16:48.944 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:49.422 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:49.920 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:49.921 | INFO | Drag (1256,  419) -> (1259,  310)
2021-11-22 01:16:51.088 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:51.511 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:52.080 | INFO | [COMMISSION_SCROLL_AREA] 0.99
2021-11-22 01:16:52.081 | INFO | Drag (1254,  426) -> (1254,  310)
2021-11-22 01:17:02.918 | ERROR | Command '['C:/Users/ShiroNagi/Desktop/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe', '-s', '127.0.0.1:62001', 'shell', 'screencap', '-p']' timed out after 10 seconds
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 123, in commission
    RewardCommission(config=self.config, device=self.device).run()
  File "C:\fakepath\AzurLaneAutoScript\module\commission\commission.py", line 385, in run
    self.commission_start()
  File "C:\fakepath\AzurLaneAutoScript\module\commission\commission.py", line 314, in commission_start
    self._commission_swipe_to_top()
  File "C:\fakepath\AzurLaneAutoScript\module\commission\commission.py", line 162, in _commission_swipe_to_top
    COMMISSION_SCROLL.set_top(main=self, skip_first_screenshot=True)
  File "C:\fakepath\AzurLaneAutoScript\module\ui\scroll.py", line 144, in set_top
    return self.set(0.00, main=main, random_range=random_range, skip_first_screenshot=skip_first_screenshot)
  File "C:\fakepath\AzurLaneAutoScript\module\ui\scroll.py", line 130, in set
    main.device.screenshot()
  File "C:\fakepath\AzurLaneAutoScript\module\device\device.py", line 49, in screenshot
    super().screenshot()
  File "C:\fakepath\AzurLaneAutoScript\module\base\timer.py", line 13, in function_timer
    result = function(*args, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\module\device\screenshot.py", line 70, in screenshot
    self.image = self._screenshot_adb()
  File "C:\fakepath\AzurLaneAutoScript\module\device\screenshot.py", line 51, in _screenshot_adb
    screenshot = self.adb_shell(['screencap', '-p'])
  File "C:\fakepath\AzurLaneAutoScript\module\device\connection.py", line 150, in adb_shell
    return self.adb_command(cmd, serial)
  File "C:\fakepath\AzurLaneAutoScript\module\device\connection.py", line 146, in adb_command
    return process.communicate(timeout=timeout)[0]
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\subprocess.py", line 1298, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['C:/Users/ShiroNagi/Desktop/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe', '-s', '127.0.0.1:62001', 'shell', 'screencap', '-p']' timed out after 10 seconds
2021-11-22 01:17:02.959 | WARNING | Saving error: ./log/error/1637515022959

**Comment by ShiroRan** [comment]
![2021-11-22_01-16-52-080047](https://user-images.githubusercontent.com/63772901/142774558-a8fe8c5e-976d-4896-b1d4-cd37bf887a46.png)

**Comment by LmeSzinc** [comment]
这个问题与 Alas 无关，是你的模拟器断开了连接，可能的原因有：
- 你的电脑上的其他软件结束了 ADB 服务，导致连接断开
- 你开启了别的模拟器，但是没有替换 ADB，不同的 ADB 结束了 Alas 正在使用的 ADB，导致连接断开
- 模拟器抽风

**Comment by ShiroRan** [comment]
> 这个问题与 Alas 无关，是你的模拟器断开了连接，可能的原因有：
> 
> * 你的电脑上的其他软件结束了 ADB 服务，导致连接断开
> * 你开启了别的模拟器，但是没有替换 ADB，不同的 ADB 结束了 Alas 正在使用的 ADB，导致连接断开
> * 模拟器抽风

那现在的alas在开始运行之前还是会自动替换adb是吗？

**Comment by ShiroRan** [comment]
> 这个问题与 Alas 无关，是你的模拟器断开了连接，可能的原因有：
> 
> * 你的电脑上的其他软件结束了 ADB 服务，导致连接断开
> * 你开启了别的模拟器，但是没有替换 ADB，不同的 ADB 结束了 Alas 正在使用的 ADB，导致连接断开
> * 模拟器抽风

破案了，因为是笔记本跑的，模拟器跟着系统自动休眠了，解决办法就是关闭系统的自动休眠，或者看看模拟器有没有像夜神那样的禁用休眠功能
