### ISSUE TITLE
OSError: broken data stream when reading image file

### ISSUE THREAD

**Issue by ShiroRan** [LmeSzinc/AzurLaneAutoScript#779]
2021-11-28 03:06:58.241 | INFO | +------------------------------------------------+
2021-11-28 03:06:58.242 | INFO | |                    EXERCISE                    |
2021-11-28 03:06:58.242 | INFO | +------------------------------------------------+
2021-11-28 03:06:58.247 | INFO | <<< UI ENSURE >>>
2021-11-28 03:06:58.258 | INFO | [UI] page_os
2021-11-28 03:06:58.259 | INFO | Goto page_exercise
2021-11-28 03:06:58.259 | INFO | <<< UI GOTO PAGE_EXERCISE >>>
2021-11-28 03:06:58.264 | INFO | Click (1238,   30) @ GOTO_MAIN
2021-11-28 03:06:59.234 | INFO | Click (1082,  354) @ MAIN_GOTO_CAMPAIGN
2021-11-28 03:07:00.172 | INFO | Click (1061,  610) @ CAMPAIGN_MENU_GOTO_EXERCISE
2021-11-28 03:07:00.555 | INFO | Bind task {'Exercise', 'General', 'Alas'}
2021-11-28 03:07:00.556 | INFO | Save config ./config\alas.json, Exercise.Exercise.OpponentRefreshValue=0, Exercise.Exercise.OpponentRefreshRecord=datetime.datetime(2021, 11, 28, 3, 7)
2021-11-28 03:07:00.558 | INFO | [Change_opponent_count] 0
2021-11-28 03:07:00.567 | INFO | [OCR_EXERCISE_REMAIN 0.009s] 5
2021-11-28 03:07:00.567 | INFO | ==================== EXERCISE REMAIN 5 ====================
2021-11-28 03:07:00.568 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:00.580 | INFO | Click ( 260,  288) @ OPPONENT_0_0
2021-11-28 03:07:01.591 | INFO | [POWER 0.024s] [2949, 1927]
2021-11-28 03:07:01.635 | INFO | [LEVEL 0.044s] [109, 0, 0, 1, 79, 80]
2021-11-28 03:07:01.635 | INFO | [OPPONENT_0] ( 2949) 109   0   0 | ( 1927)   1  79  80
2021-11-28 03:07:01.635 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:01.638 | INFO | Click (  53,   55) @ BACK_ARROW
2021-11-28 03:07:02.034 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:02.036 | INFO | Click ( 465,  302) @ OPPONENT_1_0
2021-11-28 03:07:03.097 | INFO | [POWER 0.021s] [16268, 14165]
2021-11-28 03:07:03.131 | INFO | [LEVEL 0.033s] [125, 125, 125, 120, 120, 120]
2021-11-28 03:07:03.132 | INFO | [OPPONENT_1] (16268) 125 125 125 | (14165) 120 120 120
2021-11-28 03:07:03.132 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:03.134 | INFO | Click (  52,   43) @ BACK_ARROW
2021-11-28 03:07:03.519 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:03.520 | INFO | Click ( 674,  243) @ OPPONENT_2_0
2021-11-28 03:07:04.612 | INFO | [POWER 0.022s] [15581, 15072]
2021-11-28 03:07:04.646 | INFO | [LEVEL 0.034s] [125, 125, 125, 120, 123, 125]
2021-11-28 03:07:04.646 | INFO | [OPPONENT_2] (15581) 125 125 125 | (15072) 120 123 125
2021-11-28 03:07:04.646 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:04.648 | INFO | Click (  36,   63) @ BACK_ARROW
2021-11-28 03:07:05.039 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:05.041 | INFO | Click ( 945,  265) @ OPPONENT_3_0
2021-11-28 03:07:06.111 | INFO | [POWER 0.023s] [14989, 11809]
2021-11-28 03:07:06.145 | INFO | [LEVEL 0.033s] [125, 125, 125, 120, 117, 110]
2021-11-28 03:07:06.146 | INFO | [OPPONENT_3] (14989) 125 125 125 | (11809) 120 117 110
2021-11-28 03:07:06.146 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:06.148 | INFO | Click (  50,   58) @ BACK_ARROW
2021-11-28 03:07:06.549 | INFO | [Order] [0 3 1 2]
2021-11-28 03:07:06.550 | INFO | -------------------- OPPONENT 0 --------------------
2021-11-28 03:07:06.550 | INFO | <<< OPPONENT: 0 >>>
2021-11-28 03:07:06.899 | INFO | Click ( 219,  224) @ OPPONENT_0_0
2021-11-28 03:07:07.899 | INFO | Click ( 618,  560) @ EXERCISE_PREPARATION
2021-11-28 03:07:08.681 | INFO | <<< TRY: 1 >>>
2021-11-28 03:07:08.682 | INFO | Combat preparation
2021-11-28 03:07:09.123 | INFO | Click (1136,  642) @ BATTLE_PREPARATION
2021-11-28 03:07:09.907 | INFO | Click (1159,  637) @ BATTLE_PREPARATION
2021-11-28 03:07:13.222 | INFO | Combat execute
2021-11-28 03:07:13.615 | INFO | [97% - 98%]
2021-11-28 03:07:18.842 | INFO | [97% - 58%]
2021-11-28 03:07:23.986 | INFO | [97% - 00%]
2021-11-28 03:07:26.381 | INFO | Click (1031,  657) @ BATTLE_STATUS_S
2021-11-28 03:07:26.705 | INFO | Click (1007,  624) @ GET_ITEMS_1
2021-11-28 03:07:27.350 | INFO | Click (1018,  652) @ CLICK_SAFE_AREA
2021-11-28 03:07:27.730 | INFO | Click (1005,  675) @ CLICK_SAFE_AREA
2021-11-28 03:07:28.111 | INFO | Click (1008,  657) @ CLICK_SAFE_AREA
2021-11-28 03:07:28.514 | INFO | <<< COMBAT END >>>
2021-11-28 03:07:28.524 | INFO | [OCR_EXERCISE_REMAIN 0.009s] 4
2021-11-28 03:07:28.524 | INFO | ==================== EXERCISE REMAIN 4 ====================
2021-11-28 03:07:28.525 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:28.528 | INFO | Click ( 200,  195) @ OPPONENT_0_0
2021-11-28 03:07:29.696 | INFO | [POWER 0.022s] [13937, 13774]
2021-11-28 03:07:29.729 | INFO | [LEVEL 0.032s] [125, 125, 125, 125, 125, 125]
2021-11-28 03:07:29.729 | INFO | [OPPONENT_0] (13937) 125 125 125 | (13774) 125 125 125
2021-11-28 03:07:29.729 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:29.731 | INFO | Click (  43,   49) @ BACK_ARROW
2021-11-28 03:07:30.120 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:30.122 | INFO | Click ( 428,  237) @ OPPONENT_1_0
2021-11-28 03:07:31.245 | INFO | [POWER 0.022s] [14572, 13772]
2021-11-28 03:07:31.278 | INFO | [LEVEL 0.032s] [120, 120, 120, 120, 120, 120]
2021-11-28 03:07:31.278 | INFO | [OPPONENT_1] (14572) 120 120 120 | (13772) 120 120 120
2021-11-28 03:07:31.278 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:31.280 | INFO | Click (  50,   71) @ BACK_ARROW
2021-11-28 03:07:31.691 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:31.692 | INFO | Click ( 676,  164) @ OPPONENT_2_0
2021-11-28 03:07:32.494 | INFO | [POWER 0.023s] [14041, 13768]
2021-11-28 03:07:32.527 | INFO | [LEVEL 0.034s] [112, 120, 120, 125, 110, 120]
2021-11-28 03:07:32.527 | INFO | [OPPONENT_2] (14041) 112 120 120 | (13768) 125 110 120
2021-11-28 03:07:32.527 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:32.530 | INFO | Click (  69,   53) @ BACK_ARROW
2021-11-28 03:07:32.923 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:32.924 | INFO | Click ( 940,  200) @ OPPONENT_3_0
2021-11-28 03:07:34.024 | INFO | [POWER 0.024s] [12603, 4310]
2021-11-28 03:07:34.059 | INFO | [LEVEL 0.035s] [125, 120, 125, 43, 76, 49]
2021-11-28 03:07:34.059 | INFO | [OPPONENT_3] (12603) 125 120 125 | ( 4310)  43  76  49
2021-11-28 03:07:34.059 | INFO | <<< UI CLICK >>>
2021-11-28 03:07:34.062 | INFO | Click (  57,   63) @ BACK_ARROW
2021-11-28 03:07:34.469 | INFO | [Order] [3 2 1 0]
2021-11-28 03:07:34.469 | INFO | -------------------- OPPONENT 3 --------------------
2021-11-28 03:07:34.470 | INFO | <<< OPPONENT: 3 >>>
2021-11-28 03:07:34.791 | INFO | Click ( 954,  225) @ OPPONENT_3_0
2021-11-28 03:07:35.873 | INFO | Click ( 669,  584) @ EXERCISE_PREPARATION
2021-11-28 03:07:36.670 | INFO | <<< TRY: 1 >>>
2021-11-28 03:07:36.671 | INFO | Combat preparation
2021-11-28 03:07:37.091 | INFO | Click (1109,  644) @ BATTLE_PREPARATION
2021-11-28 03:07:37.863 | INFO | Click (1086,  645) @ BATTLE_PREPARATION
2021-11-28 03:07:38.302 | INFO | Click (1102,  639) @ BATTLE_PREPARATION
2021-11-28 03:07:41.659 | INFO | Combat execute
2021-11-28 03:07:42.046 | INFO | [97% - 98%]
2021-11-28 03:07:47.124 | INFO | [97% - 99%]
2021-11-28 03:07:52.133 | INFO | [97% - 76%]
2021-11-28 03:07:57.140 | INFO | [97% - 54%]
2021-11-28 03:08:02.373 | INFO | [98% - 18%]
2021-11-28 03:08:07.454 | INFO | [98% - 00%]
2021-11-28 03:08:08.712 | INFO | Click (1020,  656) @ BATTLE_STATUS_S
2021-11-28 03:08:09.025 | INFO | Click (1015,  617) @ GET_ITEMS_1
2021-11-28 03:08:09.668 | INFO | Click (1009,  656) @ CLICK_SAFE_AREA
2021-11-28 03:08:10.082 | INFO | Click (1008,  665) @ CLICK_SAFE_AREA
2021-11-28 03:08:10.462 | INFO | Click (1014,  648) @ CLICK_SAFE_AREA
2021-11-28 03:08:10.856 | INFO | <<< COMBAT END >>>
2021-11-28 03:08:10.867 | INFO | [OCR_EXERCISE_REMAIN 0.010s] 3
2021-11-28 03:08:10.867 | INFO | ==================== EXERCISE REMAIN 3 ====================
2021-11-28 03:08:10.868 | INFO | <<< UI CLICK >>>
2021-11-28 03:08:10.870 | INFO | Click ( 238,  139) @ OPPONENT_0_0
2021-11-28 03:08:11.966 | INFO | [POWER 0.022s] [13814, 14013]
2021-11-28 03:08:12.000 | INFO | [LEVEL 0.033s] [120, 120, 124, 113, 125, 124]
2021-11-28 03:08:12.000 | INFO | [OPPONENT_0] (13814) 120 120 124 | (14013) 113 125 124
2021-11-28 03:08:12.001 | INFO | <<< UI CLICK >>>
2021-11-28 03:08:12.003 | INFO | Click (  59,   61) @ BACK_ARROW
2021-11-28 03:08:12.392 | INFO | <<< UI CLICK >>>
2021-11-28 03:08:12.394 | INFO | Click ( 394,  297) @ OPPONENT_1_0
2021-11-28 03:08:13.450 | INFO | [POWER 0.027s] [2436, 10445]
2021-11-28 03:08:13.485 | INFO | [LEVEL 0.035s] [1, 14, 11, 107, 1, 125]
2021-11-28 03:08:13.486 | INFO | [OPPONENT_1] ( 2436)   1  14  11 | (10445) 107   1 125
2021-11-28 03:08:13.486 | INFO | <<< UI CLICK >>>
2021-11-28 03:08:13.488 | INFO | Click (  75,   55) @ BACK_ARROW
2021-11-28 03:08:13.903 | INFO | <<< UI CLICK >>>
2021-11-28 03:08:13.905 | INFO | Click ( 714,  170) @ OPPONENT_2_0
2021-11-28 03:08:14.944 | INFO | [POWER 0.021s] [4245, 7774]
2021-11-28 03:08:14.986 | INFO | [LEVEL 0.041s] [98, 98, 98, 100, 98, 98]
2021-11-28 03:08:14.986 | INFO | [OPPONENT_2] ( 4245)  98  98  98 | ( 7774) 100  98  98
2021-11-28 03:08:14.986 | INFO | <<< UI CLICK >>>
2021-11-28 03:08:14.989 | INFO | Click (  59,   61) @ BACK_ARROW
2021-11-28 03:08:15.382 | INFO | <<< UI CLICK >>>
2021-11-28 03:08:15.383 | INFO | Click ( 929,  257) @ OPPONENT_3_0
2021-11-28 03:08:16.467 | INFO | [POWER 0.022s] [15118, 13824]
2021-11-28 03:08:16.502 | INFO | [LEVEL 0.034s] [125, 120, 125, 118, 125, 120]
2021-11-28 03:08:16.502 | INFO | [OPPONENT_3] (15118) 125 120 125 | (13824) 118 125 120
2021-11-28 03:08:16.502 | INFO | <<< UI CLICK >>>
2021-11-28 03:08:16.504 | INFO | Click (  56,   45) @ BACK_ARROW
2021-11-28 03:08:16.898 | INFO | [Order] [1 2 0 3]
2021-11-28 03:08:16.899 | INFO | -------------------- OPPONENT 1 --------------------
2021-11-28 03:08:16.899 | INFO | <<< OPPONENT: 1 >>>
2021-11-28 03:08:17.237 | INFO | Click ( 439,  244) @ OPPONENT_1_0
2021-11-28 03:08:18.263 | INFO | Click ( 657,  587) @ EXERCISE_PREPARATION
2021-11-28 03:08:19.053 | INFO | <<< TRY: 1 >>>
2021-11-28 03:08:19.053 | INFO | Combat preparation
2021-11-28 03:08:19.430 | INFO | Click (1149,  631) @ BATTLE_PREPARATION
2021-11-28 03:08:20.227 | INFO | Click (1131,  624) @ BATTLE_PREPARATION
2021-11-28 03:08:24.158 | INFO | Combat execute
2021-11-28 03:08:24.534 | INFO | [97% - 97%]
2021-11-28 03:08:29.886 | INFO | [79% - 78%]
2021-11-28 03:08:34.919 | INFO | [78% - 75%]
2021-11-28 03:08:40.147 | INFO | [75% - 53%]
2021-11-28 03:08:45.453 | INFO | [75% - 24%]
2021-11-28 03:08:50.790 | INFO | [70% - 11%]
2021-11-28 03:08:56.191 | INFO | [70% - 09%]
2021-11-28 03:09:01.352 | INFO | [00% - 00%]
2021-11-28 03:09:01.980 | INFO | Click (1019,  661) @ BATTLE_STATUS_S
2021-11-28 03:09:02.308 | INFO | Click (1017,  628) @ GET_ITEMS_1
2021-11-28 03:09:02.926 | INFO | Click (1013,  659) @ CLICK_SAFE_AREA
2021-11-28 03:09:03.315 | INFO | Click (1017,  651) @ CLICK_SAFE_AREA
2021-11-28 03:09:03.716 | INFO | Click (1009,  664) @ CLICK_SAFE_AREA
2021-11-28 03:09:04.096 | INFO | <<< COMBAT END >>>
2021-11-28 03:09:04.106 | INFO | [OCR_EXERCISE_REMAIN 0.009s] 2
2021-11-28 03:09:04.107 | INFO | ==================== EXERCISE REMAIN 2 ====================
2021-11-28 03:09:04.107 | INFO | <<< UI CLICK >>>
2021-11-28 03:09:04.109 | INFO | Click ( 160,  166) @ OPPONENT_0_0
2021-11-28 03:09:04.921 | INFO | [POWER 0.023s] [13531, 8007]
2021-11-28 03:09:04.954 | INFO | [LEVEL 0.032s] [125, 125, 99, 99, 92, 90]
2021-11-28 03:09:04.955 | INFO | [OPPONENT_0] (13531) 125 125  99 | ( 8007)  99  92  90
2021-11-28 03:09:04.955 | INFO | <<< UI CLICK >>>
2021-11-28 03:09:04.957 | INFO | Click (  57,   61) @ BACK_ARROW
2021-11-28 03:09:05.358 | INFO | <<< UI CLICK >>>
2021-11-28 03:09:05.360 | INFO | Click ( 484,  182) @ OPPONENT_1_0
2021-11-28 03:09:06.429 | INFO | [POWER 0.023s] [15306, 14685]
2021-11-28 03:09:06.471 | INFO | [LEVEL 0.041s] [125, 125, 125, 124, 124, 125]
2021-11-28 03:09:06.472 | INFO | [OPPONENT_1] (15306) 125 125 125 | (14685) 124 124 125
2021-11-28 03:09:06.472 | INFO | <<< UI CLICK >>>
2021-11-28 03:09:06.474 | INFO | Click (  51,   64) @ BACK_ARROW
2021-11-28 03:09:06.896 | INFO | <<< UI CLICK >>>
2021-11-28 03:09:06.897 | INFO | Click ( 692,  176) @ OPPONENT_2_0
2021-11-28 03:09:07.991 | INFO | [POWER 0.023s] [13003, 11689]
2021-11-28 03:09:08.026 | INFO | [LEVEL 0.035s] [125, 125, 120, 125, 120, 120]
2021-11-28 03:09:08.026 | INFO | [OPPONENT_2] (13003) 125 125 120 | (11689) 125 120 120
2021-11-28 03:09:08.026 | INFO | <<< UI CLICK >>>
2021-11-28 03:09:08.029 | INFO | Click (  59,   66) @ BACK_ARROW
2021-11-28 03:09:08.430 | INFO | <<< UI CLICK >>>
2021-11-28 03:09:08.432 | INFO | Click ( 873,  241) @ OPPONENT_3_0
2021-11-28 03:09:09.161 | ERROR | broken data stream when reading image file
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 179, in exercise
    Exercise(config=self.config, device=self.device).run()
  File "C:\fakepath\AzurLaneAutoScript\module\exercise\exercise.py", line 120, in run
    success = self._exercise_easiest_else_exp()
  File "C:\fakepath\AzurLaneAutoScript\module\exercise\exercise.py", line 70, in _exercise_easiest_else_exp
    self._opponent_fleet_check_all()
  File "C:\fakepath\AzurLaneAutoScript\module\exercise\exercise.py", line 27, in _opponent_fleet_check_all
    super()._opponent_fleet_check_all()
  File "C:\fakepath\AzurLaneAutoScript\module\exercise\opponent.py", line 106, in _opponent_fleet_check_all
    appear_button=NEW_OPPONENT, skip_first_screenshot=True)
  File "C:\fakepath\AzurLaneAutoScript\module\ui\ui.py", line 67, in ui_click
    self.device.screenshot()
  File "C:\fakepath\AzurLaneAutoScript\module\device\device.py", line 49, in screenshot
    super().screenshot()
  File "C:\fakepath\AzurLaneAutoScript\module\base\timer.py", line 13, in function_timer
    result = function(*args, **kwargs)
  File "C:\fakepath\AzurLaneAutoScript\module\device\screenshot.py", line 70, in screenshot
    self.image = self._screenshot_adb()
  File "C:\fakepath\AzurLaneAutoScript\module\device\screenshot.py", line 52, in _screenshot_adb
    return self._process_screenshot(screenshot)
  File "C:\fakepath\AzurLaneAutoScript\module\device\screenshot.py", line 38, in _process_screenshot
    return self._load_screenshot(screenshot)
  File "C:\fakepath\AzurLaneAutoScript\module\device\screenshot.py", line 32, in _load_screenshot
    return Image.open(BytesIO(screenshot.replace(b'\r\n', b'\n'))).convert('RGB')
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\PIL\Image.py", line 915, in convert
    self.load()
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\PIL\ImageFile.py", line 274, in load
    raise_oserror(err_code)
  File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\PIL\ImageFile.py", line 67, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: broken data stream when reading image file
2021-11-28 03:09:09.165 | WARNING | Saving error: ./log/error/1638029349165

**Comment by ShiroRan** [comment]
![2021-11-28_03-09-08-825397](https://user-images.githubusercontent.com/63772901/143721278-11eac3d6-f64b-456b-8a91-895700aae6a9.png)

**Comment by LmeSzinc** [comment]
> OSError: broken data stream when reading image file

截图损坏，无法读取。可以参照 #766 #763 。

**Comment by ShiroRan** [comment]
> 
环境：
系统：win10 21H2
CPU：I9-9900ks
内存：DDR4 3000c14 32G
显卡：RTX2080ti oc
模拟器：夜神模拟器7.0.1.8，显卡渲染模式：增强兼容模式（OpenGL+）；性能设置：4核，4G内存；手动替换过adb
alas设置：模拟器截图方案：ADB；控制方案：minitouch

跟#763的笔记本问题不太一样，台式电脑没有休眠也没有关屏幕，前几次卡死跟#766的情况很相似，在战斗结束之后卡死没跳出结算导致alas报错。
目前了解到很有可能出现这种情况的原因是游戏的问题或是电脑网络问题，我看着模拟器没有未响应，游戏没有出现小黄鸡加载，后续手操游戏没有反应。
