### ISSUE TITLE
开发船坞免费图纸卡住

### ISSUE THREAD

**Issue by junbluedd** [LmeSzinc/AzurLaneAutoScript#788]
开发船坞每天白嫖图纸卡住，貌似是当成了有max按钮的位置去点击加号
模拟器是bluestacks5-hyperv
**Screenshots**
![This is an image](https://github.com/junbluedd/gitgreen/blob/master/2021-12-01_10-45-40-597941.png?raw=true)
**log文件：**
2021-12-01 10:45:04.670 | INFO | +------------------------------------------------+
2021-12-01 10:45:04.671 | INFO | |                    SHIPYARD                    |
2021-12-01 10:45:04.671 | INFO | +------------------------------------------------+
2021-12-01 10:45:04.716 | INFO | [SHOP_GOLD_COINS 0.041s] 53194
2021-12-01 10:45:04.750 | INFO | [SHOP_GEMS 0.033s] 421
2021-12-01 10:45:04.750 | INFO | Gold coins: 53194, Gems: 421
2021-12-01 10:45:04.750 | INFO | <<< UI ENSURE >>>
2021-12-01 10:45:04.753 | INFO | [UI] page_main
2021-12-01 10:45:04.754 | INFO | Goto page_shipyard
2021-12-01 10:45:04.754 | INFO | <<< UI GOTO PAGE_SHIPYARD >>>
2021-12-01 10:45:04.771 | INFO | Click ( 729,  698) @ MAIN_GOTO_RESHMENU
2021-12-01 10:45:06.194 | INFO | Click ( 655,  350) @ RESHMENU_GOTO_SHIPYARD
2021-12-01 10:45:08.649 | INFO | <<< UI CLICK >>>
2021-12-01 10:45:08.651 | INFO | Click (  90,  675) @ SHIPYARD_SERIES_SELECT_ENTER
2021-12-01 10:45:09.547 | INFO | <<< UI CLICK >>>
2021-12-01 10:45:09.550 | INFO | Click ( 538,  323) @ SHIPYARD_SERIES_GRID_0_0
2021-12-01 10:45:11.034 | INFO | SHIPYARD_FACE_GRID set to left=1
2021-12-01 10:45:11.575 | INFO | [OCR_BP_COUNT 0.062s] [0, 0, 0, 0, 0, 0]
2021-12-01 10:45:11.575 | INFO | Can buy all 3 BPs
2021-12-01 10:45:11.599 | INFO | [SHIPYARD_TOTAL_DEV 0.017s] 0
2021-12-01 10:45:11.599 | INFO | Click (1168,  449) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:12.002 | INFO | Click (1158,  454) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:12.445 | INFO | Click (1177,  443) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:13.086 | INFO | [SHIPYARD_TOTAL_DEV 0.017s] 0
2021-12-01 10:45:13.087 | INFO | Click (1161,  444) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:13.456 | INFO | Click (1170,  445) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:13.882 | INFO | Click (1170,  447) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:14.530 | INFO | [SHIPYARD_TOTAL_DEV 0.025s] 0
2021-12-01 10:45:14.531 | INFO | Click (1159,  443) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:14.896 | INFO | Click (1175,  440) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:15.336 | INFO | Click (1165,  451) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:15.399 | INFO | Current interface does not allow consumption of 3 BPs

2021-12-01 10:45:15.399 | INFO | Capable of consuming at most 0 of the 3 BPs
2021-12-01 10:45:15.401 | INFO | Click (1127,  519) @ SHIPYARD_CONFIRM_DEV
2021-12-01 10:45:18.475 | INFO | Click (1125,  511) @ SHIPYARD_CONFIRM_DEV
2021-12-01 10:45:21.494 | INFO | Click (1121,  510) @ SHIPYARD_CONFIRM_DEV
2021-12-01 10:45:24.904 | INFO | Click (1119,  515) @ SHIPYARD_CONFIRM_DEV
2021-12-01 10:45:25.488 | WARNING | Failed to detect for normal exit routine, resort to OCR check
2021-12-01 10:45:25.501 | INFO | [SHIPYARD_TOTAL_DEV 0.012s] 0
2021-12-01 10:45:25.502 | INFO | Confirm action has completed, setting flag for exit
2021-12-01 10:45:26.041 | INFO | Can buy all 3 BPs
2021-12-01 10:45:26.099 | INFO | [SHIPYARD_TOTAL_DEV 0.051s] 0
2021-12-01 10:45:26.100 | INFO | Click (1171,  449) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:26.518 | INFO | Click (1155,  448) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:26.901 | INFO | Click (1163,  448) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:27.457 | INFO | [SHIPYARD_TOTAL_DEV 0.012s] 0
2021-12-01 10:45:27.458 | INFO | Click (1168,  455) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:27.843 | INFO | Click (1157,  447) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:28.176 | INFO | Click (1173,  441) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:28.794 | INFO | [SHIPYARD_TOTAL_DEV 0.016s] 0
2021-12-01 10:45:28.794 | INFO | Click (1164,  452) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:29.227 | INFO | Click (1163,  441) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:29.621 | INFO | Click (1171,  444) @ SHIPYARD_PLUS_DEV
2021-12-01 10:45:29.685 | INFO | Current interface does not allow consumption of 3 BPs

2021-12-01 10:45:29.685 | INFO | Capable of consuming at most 0 of the 3 BPs
2021-12-01 10:45:29.688 | INFO | Click (1108,  509) @ SHIPYARD_CONFIRM_DEV
2021-12-01 10:45:32.882 | INFO | Click (1124,  501) @ SHIPYARD_CONFIRM_DEV
2021-12-01 10:45:35.938 | INFO | Click (1122,  511) @ SHIPYARD_CONFIRM_DEV
2021-12-01 10:45:39.389 | INFO | Click (1116,  510) @ SHIPYARD_CONFIRM_DEV
2021-12-01 10:45:40.062 | WARNING | Failed to detect for normal exit routine, resort to OCR check
2021-12-01 10:45:40.085 | INFO | [SHIPYARD_TOTAL_DEV 0.022s] 0
2021-12-01 10:45:40.086 | INFO | Confirm action has completed, setting flag for exit
2021-12-01 10:45:40.602 | INFO | Can buy all 3 BPs
2021-12-01 10:45:40.624 | INFO | [SHIPYARD_TOTAL_DEV 0.012s] 0
2021-12-01 10:45:40.625 | WARNING | Too many click between 2 buttons: SHIPYARD_PLUS_DEV, SHIPYARD_CONFIRM_DEV
2021-12-01 10:45:40.625 | WARNING | History click: ['SHIPYARD_PLUS_DEV', 'SHIPYARD_PLUS_DEV', 'SHIPYARD_PLUS_DEV', 'SHIPYARD_CONFIRM_DEV', 'SHIPYARD_CONFIRM_DEV', 'SHIPYARD_CONFIRM_DEV', 'SHIPYARD_CONFIRM_DEV', 'SHIPYARD_PLUS_DEV', 'SHIPYARD_PLUS_DEV', 'SHIPYARD_PLUS_DEV', 'SHIPYARD_CONFIRM_DEV', 'SHIPYARD_CONFIRM_DEV', 'SHIPYARD_CONFIRM_DEV', 'SHIPYARD_CONFIRM_DEV', 'SHIPYARD_PLUS_DEV']
2021-12-01 10:45:40.625 | WARNING | Too many click between 2 buttons: SHIPYARD_PLUS_DEV, SHIPYARD_CONFIRM_DEV
2021-12-01 10:45:40.626 | WARNING | Saving error: ./log/error/1638326740626

**Comment by EzrealC** [comment]
我也遇到这个问题了

**Comment by nEEtdo0d** [comment]
Sorry to tag into this issue but got this with the shipyard update https://www.dropbox.com/sh/90fuotesqi4wls6/AAANtZggSkuzzpH6JT3QK54xa?dl=0

The even weirder thing, after retrying the task it was successful. 3/4 resulted in the above error folder, last try for some reason worked.

**Comment by LmeSzinc** [comment]
> Sorry to tag into this issue but got this with the shipyard update https://www.dropbox.com/sh/90fuotesqi4wls6/AAANtZggSkuzzpH6JT3QK54xa?dl=0
> 
> The even weirder thing, after retrying the task it was successful. 3/4 resulted in the above error folder, last try for some reason worked.

I think the existance of SHIPYARD_MINUS_* and SHIPYARD_PLUS_* should be checked before calcaulating the ocr area. The outside of image may be the matching result when the real one is missing.

**Comment by nEEtdo0d** [comment]
> > Sorry to tag into this issue but got this with the shipyard update https://www.dropbox.com/sh/90fuotesqi4wls6/AAANtZggSkuzzpH6JT3QK54xa?dl=0
> > The even weirder thing, after retrying the task it was successful. 3/4 resulted in the above error folder, last try for some reason worked.
> 
> I think the existance of SHIPYARD_MINUS_* and SHIPYARD_PLUS_* should be checked before calcaulating the ocr area. The outside of image may be the matching result when the real one is missing.

Something like this?
```
minus = globals()[f'SHIPYARD_MINUS_{append}']
plus = globals()[f'SHIPYARD_PLUS_{append}']
while not (self.appear(minus, offset=(20, 20)) and self.appear(plus, offset=(150, 20))):
    self.device.sleep((0.3, 0.5))
    self.device.screenshot()

ocr = globals()[f'OCR_SHIPYARD_TOTAL_{append}']
area = ocr.buttons[0]
ocr.buttons = [(minus.button[2] + 3, area[1], plus.button[0] - 3, area[3])]
```

**Comment by EzrealC** [comment]
> 日服plus和minus按钮位置是固定的，所以没有遇到按钮位移问题 ![Screenshot_2021 12 02_10 55 34 6531](https://user-images.githubusercontent.com/57893649/144349756-1eb2eded-62e3-449a-acbb-81b5382ea0e1.png)
> 
> 不过更新后报错了 ![2021-12-02_10-29-12-796927](https://user-images.githubusercontent.com/57893649/144350048-30d0847c-39bb-46d2-8d97-b1ee021062de.png) ![2021-12-02_10-29-17-267338](https://user-images.githubusercontent.com/57893649/144350030-a21a10ca-8cfb-415f-afeb-b3d3583ad9f0.png)
> 
> ```
> 2021-12-02 10:29:03.571 | INFO | +------------------------------------------------+
> 2021-12-02 10:29:03.572 | INFO | |                    SHIPYARD                    |
> 2021-12-02 10:29:03.572 | INFO | +------------------------------------------------+
> 2021-12-02 10:29:03.601 | INFO | <<< UI ENSURE >>>
> 2021-12-02 10:29:03.610 | INFO | [UI] page_mission
> 2021-12-02 10:29:03.610 | INFO | Goto page_main
> 2021-12-02 10:29:03.611 | INFO | <<< UI GOTO PAGE_MAIN >>>
> 2021-12-02 10:29:03.636 | INFO | Click (1241,   35) @ GOTO_MAIN
> 2021-12-02 10:29:05.572 | INFO | [SHOP_GOLD_COINS 0.038s] 37288
> 2021-12-02 10:29:05.615 | INFO | [SHOP_GEMS 0.042s] 1709
> 2021-12-02 10:29:05.616 | INFO | Gold coins: 37288, Gems: 1709
> 2021-12-02 10:29:05.616 | INFO | <<< UI ENSURE >>>
> 2021-12-02 10:29:05.622 | INFO | [UI] page_main
> 2021-12-02 10:29:05.623 | INFO | Goto page_shipyard
> 2021-12-02 10:29:05.624 | INFO | <<< UI GOTO PAGE_SHIPYARD >>>
> 2021-12-02 10:29:05.632 | INFO | Click ( 714,  687) @ MAIN_GOTO_RESHMENU
> 2021-12-02 10:29:06.933 | INFO | Click ( 711,  315) @ RESHMENU_GOTO_SHIPYARD
> 2021-12-02 10:29:09.897 | INFO | <<< UI CLICK >>>
> 2021-12-02 10:29:09.917 | INFO | Click ( 105,  679) @ SHIPYARD_SERIES_SELECT_ENTER
> 2021-12-02 10:29:10.356 | INFO | <<< UI CLICK >>>
> 2021-12-02 10:29:10.359 | INFO | Click ( 593,  324) @ SHIPYARD_SERIES_GRID_0_0
> 2021-12-02 10:29:12.162 | INFO | SHIPYARD_FACE_GRID set to left=1
> 2021-12-02 10:29:12.957 | INFO | [OCR_BP_COUNT 0.082s] [0, 0, 0, 88, 1, 0]
> 2021-12-02 10:29:12.958 | INFO | Can buy all 10 BPs
> 2021-12-02 10:29:13.026 | INFO | [SHIPYARD_TOTAL_DEV 0.031s] 0
> 2021-12-02 10:29:13.027 | INFO | Click (1163,  450) @ SHIPYARD_PLUS_DEV
> 2021-12-02 10:29:13.382 | INFO | Click (1169,  437) @ SHIPYARD_PLUS_DEV
> 2021-12-02 10:29:13.793 | INFO | Click (1157,  443) @ SHIPYARD_PLUS_DEV
> 2021-12-02 10:29:14.188 | INFO | Click (1169,  441) @ SHIPYARD_PLUS_DEV
> 2021-12-02 10:29:14.663 | INFO | Click (1164,  455) @ SHIPYARD_PLUS_DEV
> 2021-12-02 10:29:15.010 | INFO | Click (1163,  447) @ SHIPYARD_PLUS_DEV
> 2021-12-02 10:29:15.358 | INFO | Click (1165,  452) @ SHIPYARD_PLUS_DEV
> 2021-12-02 10:29:15.755 | INFO | Click (1156,  446) @ SHIPYARD_PLUS_DEV
> 2021-12-02 10:29:16.136 | INFO | Click (1163,  437) @ SHIPYARD_PLUS_DEV
> 2021-12-02 10:29:16.561 | INFO | Click (1159,  446) @ SHIPYARD_PLUS_DEV
> 2021-12-02 10:29:17.274 | ERROR | tile cannot extend outside image
> Traceback (most recent call last):
>   File "C:\fakepath\AzurLaneAutoScript\alas.py", line 48, in run
>     self.__getattribute__(command)()
>   File "C:\fakepath\AzurLaneAutoScript\alas.py", line 159, in shipyard
>     RewardShipyard(config=self.config, device=self.device).run()
>   File "C:\fakepath\AzurLaneAutoScript\module\shipyard\shipyard_reward.py", line 168, in run
>     count=self.config.Shipyard_BuyAmount)
>   File "C:\fakepath\AzurLaneAutoScript\module\shipyard\shipyard_reward.py", line 152, in shipyard_run
>     self._shipyard_buy(count=count)
>   File "C:\fakepath\AzurLaneAutoScript\module\shipyard\shipyard_reward.py", line 90, in _shipyard_buy
>     remain = self._shipyard_ensure_index(count)
>   File "C:\fakepath\AzurLaneAutoScript\module\shipyard\ui.py", line 81, in _shipyard_ensure_index
>     current = ocr.ocr(self.device.image)
>   File "C:\fakepath\AzurLaneAutoScript\module\ocr\ocr.py", line 101, in ocr
>     image_list = [self.pre_process(np.array(image.crop(area))) for area in self.buttons]
>   File "C:\fakepath\AzurLaneAutoScript\module\ocr\ocr.py", line 101, in <listcomp>
>     image_list = [self.pre_process(np.array(image.crop(area))) for area in self.buttons]
>   File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\PIL\Image.py", line 698, in __array__
>     new["data"] = self.tobytes()
>   File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\PIL\Image.py", line 748, in tobytes
>     e.setimage(self.im)
> SystemError: tile cannot extend outside image
> 2021-12-02 10:29:17.281 | WARNING | Saving error: ./log/error/1638412157281
> ```

更新之后国服也有这个问题，不过能点到按钮了

**Comment by nEEtdo0d** [comment]
Ah pretty similar idea using `wait_until_appear` instead of the brute force I was suggesting.

But I think EN will need to restore back to the previously committed assets differing from JP and other servers. It will be the odd one out in this case. Getting stuck in the `wait_until_appear` particularly for the `FATE` case whether MAX is displayed or not. Reverting back and all seems to be working.

I can see why its the UI is a mess though, I didn't realize the MAX button is only available in certain PRs and just completely absent in others.

**Comment by LmeSzinc** [comment]
> Ah pretty similar idea using `wait_until_appear` instead of the brute force as I was suggesting.
> 
> But I think EN will need to restore back to the previously committed assets differing from JP and other servers. It will be the odd one out in this case. Getting stuck in the `wait_until_appear` particularly for the `FATE` case, doesn't matter whether `MAX` is displayed or not. Reverting back and all the cases seem to be evaluating to `true` using those instead.
> 
> However if you don't think I should undo that commit (at least just the EN side), did you have a different idea to handle this?
> 
> I can see why you say the UI is a mess though, I didn't realize the MAX button is only available in certain PRs and just completely absent in others. It's very inconsistent...

You can revert the EN assets, but the logic should work in all cases.
