### ISSUE TITLE
 ERROR | zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by egoistsong** [LmeSzinc/AzurLaneAutoScript#819]
**Describe the bug**
在12-4和11-4练级队伍中，多次在第5和第6站时卡死
开始怀疑是因为设置了索敌逻辑改为为大型优先后出现的bug，后更改为根据地图文件也会出现相同bug

**To Reproduce**

选项为{”任意舰船血量低于 X 后，使用紧急维修”}    X 由默认0.3更改为0.6后出现bug，推测与血量控制功能有关。

**Expected behavior**

**Screenshots**
![2021-12-12_13-26-48-068603](https://user-images.githubusercontent.com/39834763/145708768-9837d5b1-3066-447c-9e40-108ebdd4fe33.png)
![2021-12-12_17-25-36-145107](https://user-images.githubusercontent.com/39834763/145708796-35ac9079-1163-4759-a870-75abd9e4347b.png)
![2021-12-12_12-22-28-347275](https://user-images.githubusercontent.com/39834763/145708934-eb4d37aa-74c4-47d5-98a7-4901b73da70b.png)

**Log**
17:25:28.980 | INFO | -------------------- BATTLE_5 --------------------
17:25:28.980 | INFO | Using function: battle_0
17:25:28.981 | INFO | <<< CLEAR ENEMY >>>
17:25:28.981 | INFO | Grids: [C4, H5, J2]
17:25:28.981 | INFO | targetEnemyScale:default_mode
17:25:28.981 | INFO | Clear enemy: C4
17:25:28.981 | INFO | [Fleet_1: E3] Fleet_2: E8
17:25:28.981 | INFO | In sight: C4
17:25:28.982 | INFO | Focus to: D2
17:25:28.982 | INFO | Map swipe: (0, 0)
17:25:28.982 | INFO | Global C4 (camera=D2) -> Local C4 (center=D2)
17:25:28.984 | INFO | Click ( 474,  555) @ C4
17:25:32.655 | INFO | Skip map cat attack
17:25:32.655 | INFO | Click (1203,  666) @ MAP_CAT_ATTACK
17:25:35.056 | INFO | Combat preparation.
17:25:35.066 | INFO | Bind task {'Main', 'Alas', 'General'}
17:25:35.067 | INFO | Save config ./config\alas.json, Main.Emotion.Fleet1Value=143, Main.Emotion.Fleet1Record=datetime.datetime(2021, 12, 12, 17, 25, 35), Main.Emotion.Fleet2Value=119, Main.Emotion.Fleet2Record=datetime.datetime(2021, 12, 12, 17, 25, 35)
17:25:35.070 | INFO | [Emotion fleet_1] 143
17:25:35.070 | INFO | [Emotion fleet_2] 119
17:25:35.070 | WARNING | HP invalid: [0.0, 0.0, 0.0]
17:25:35.071 | INFO | [Automation] ON
17:25:36.146 | INFO | EMERGENCY_REPAIR_AVAILABLE
17:25:36.146 | ERROR | zero-size array to reduction operation minimum which has no identity
Traceback (most recent call last):
  File "F:\Game\BLHX\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "F:\Game\BLHX\AzurLaneAutoScript\alas.py", line 241, in main
    name=self.config.Campaign_Name, folder=self.config.Campaign_Event, mode=self.config.Campaign_Mode)
  File "F:\Game\BLHX\AzurLaneAutoScript\module\campaign\run.py", line 210, in run
    self.campaign.run()
  File "F:\Game\BLHX\AzurLaneAutoScript\module\campaign\campaign_base.py", line 137, in run
    self.execute_a_battle()
  File "F:\Game\BLHX\AzurLaneAutoScript\module\campaign\campaign_base.py", line 95, in execute_a_battle
    result = self.battle_function()
  File "F:\Game\BLHX\AzurLaneAutoScript\module\base\decorator.py", line 69, in wrapper
    return record['func'](self, *args, **kwargs)
  File "F:\Game\BLHX\AzurLaneAutoScript\module\campaign\campaign_base.py", line 85, in battle_function
    result = func()
  File "F:\Game\BLHX\AzurLaneAutoScript\campaign\campaign_main\campaign_12_4.py", line 65, in battle_0
    return self.battle_default()
  File "F:\Game\BLHX\AzurLaneAutoScript\module\campaign\campaign_base.py", line 15, in battle_default
    if self.clear_enemy():
  File "F:\Game\BLHX\AzurLaneAutoScript\module\map\map.py", line 204, in clear_enemy
    self.clear_chosen_enemy(grids[0])
  File "F:\Game\BLHX\AzurLaneAutoScript\module\map\map.py", line 26, in clear_chosen_enemy
    self.goto(grid, expected=expected)
  File "F:\Game\BLHX\AzurLaneAutoScript\module\map\fleet.py", line 444, in goto
    self._goto(location, expected=expected)
  File "F:\Game\BLHX\AzurLaneAutoScript\module\map\fleet.py", line 291, in _goto
    self.combat(expected_end=self._expected_combat_end(expected), fleet_index=self.fleet_show_index)
  File "F:\Game\BLHX\AzurLaneAutoScript\module\combat\combat.py", line 483, in combat
    balance_hp=balance_hp, emotion_reduce=emotion_reduce, auto=auto_mode, fleet_index=fleet_index)
  File "F:\Game\BLHX\AzurLaneAutoScript\module\combat\combat.py", line 130, in combat_preparation
    if balance_hp and self.handle_emergency_repair_use():
  File "F:\Game\BLHX\AzurLaneAutoScript\module\combat\combat.py", line 213, in handle_emergency_repair_use
    if np.min(np.array(self.hp)[np.array(self.hp) > 0.001]) < self.config.HpControl_RepairUseSingleThreshold \
  File "F:\Game\BLHX\AzurLaneAutoScript\toolkit\lib\site-packages\numpy\core\fromnumeric.py", line 2618, in amin
    initial=initial)
  File "F:\Game\BLHX\AzurLaneAutoScript\toolkit\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
17:25:36.151 | WARNING | Saving error: ./log/error/1639301136151

**Comment by LmeSzinc** [comment]
需要完整咯高

**Comment by egoistsong** [comment]
[error.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7700082/error.zip)

**Comment by LmeSzinc** [comment]
> [error.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7700082/error.zip)

这个压缩包中没有关于 `ERROR | zero-size array to reduction operation minimum which has no identity` 错误的完整log

**Comment by egoistsong** [comment]
[zero-size.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7701162/zero-size.zip)
抱歉，压缩时选择错了文件

**Comment by egoistsong** [comment]
后续没再复现，可能是抽风了
