### ISSUE TITLE
日服进入深渊海域和塞壬要塞立刻报错（Unable to find OS globe zone）

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#825]
启用深渊海域功能后，舰队进入深渊海域就会立刻报错停止

![2021-12-13_15-46-58-581285](https://user-images.githubusercontent.com/70339606/145772829-eb20d987-b4fc-4d29-84d4-6de51e173046.png)

![2021-12-13_15-47-01-932836](https://user-images.githubusercontent.com/70339606/145772848-546969d3-ba82-4915-b2ca-3009acb3d394.png)

2021-12-13 15:46:42.743 | INFO | +---------------------------------------------------+
2021-12-13 15:46:42.744 | INFO | |                    OPSIABYSSAL                    |
2021-12-13 15:46:42.744 | INFO | +---------------------------------------------------+
2021-12-13 15:46:43.831 | INFO | ==================== OS INIT ====================
2021-12-13 15:46:43.850 | INFO | <<< UI ENSURE >>>
2021-12-13 15:46:43.858 | INFO | [UI] page_main
2021-12-13 15:46:43.858 | INFO | Goto page_os
2021-12-13 15:46:43.859 | INFO | <<< UI GOTO PAGE_OS >>>
2021-12-13 15:46:43.866 | INFO | Click (1055,  383) @ MAIN_GOTO_CAMPAIGN
2021-12-13 15:46:43.866 | INFO | <<< MINITOUCH INIT >>>
2021-12-13 15:46:45.867 | INFO | Minitouch bind to port 20972
2021-12-13 15:46:46.229 | INFO | Minitouch forward port 20972
2021-12-13 15:46:46.262 | INFO | minitouch running on port: 20972, pid: 8547
2021-12-13 15:46:46.262 | INFO | max_contact: 2; max_x: 32767; max_y: 32767; max_pressure: 0
2021-12-13 15:46:47.144 | INFO | Click (1084,  336) @ MAIN_GOTO_CAMPAIGN
2021-12-13 15:46:47.640 | INFO | Click ( 783,  502) @ CAMPAIGN_MENU_GOTO_OS
2021-12-13 15:46:49.063 | INFO | Loading OCR model: ./bin/cnocr_models/jp
2021-12-13 15:46:49.150 | INFO | [MAP_NAME 0.099s] ダ力一ル
2021-12-13 15:46:49.150 | INFO | Map name processed: ダカール
2021-12-13 15:46:49.151 | INFO | [Zone] [7|达咯尔|Dakar|ダカール|達卡]
2021-12-13 15:46:49.161 | INFO | [HP]  98%  98%  98%  98%  98%  98%
2021-12-13 15:46:49.164 | INFO | [Repair icon] [False, False, False, False, False, False]
2021-12-13 15:46:49.164 | INFO | No ship found to be below threshold 40%, continue OS exploration
2021-12-13 15:46:49.165 | INFO | In port, skip running first auto search
2021-12-13 15:46:49.165 | INFO | Ash beacon fully collected today
2021-12-13 15:46:49.166 | INFO | ==================== OS CLEAR ABYSSAL ====================
2021-12-13 15:46:49.166 | INFO | <<< OS GET NEXT OBSCURE >>>
2021-12-13 15:46:49.167 | INFO | <<< UI CLICK >>>
2021-12-13 15:46:49.180 | INFO | Click ( 829,  668) @ STORAGE_ENTER
2021-12-13 15:46:50.149 | INFO | <<< STORAGE LOGGER USE ALL >>>
2021-12-13 15:46:50.149 | INFO | STORATE_SCROLL set to 1.0
2021-12-13 15:46:50.150 | INFO | [STORATE_SCROLL] 0.00
2021-12-13 15:46:50.150 | INFO | Drag (1259,  291) -> (1263,  412)
2021-12-13 15:46:51.290 | INFO | [STORATE_SCROLL] 1.00
2021-12-13 15:46:51.317 | INFO | [Storage_logger] 0
2021-12-13 15:46:51.317 | INFO | All loggers in storage have been used
2021-12-13 15:46:51.317 | INFO | <<< STORAGE CHECKOUT ITEM ABYSSAL >>>
2021-12-13 15:46:51.318 | INFO | STORATE_SCROLL set to 0.0
2021-12-13 15:46:51.318 | INFO | [STORATE_SCROLL] 1.00
2021-12-13 15:46:51.319 | INFO | Drag (1263,  394) -> (1263,  269)
2021-12-13 15:46:52.442 | INFO | [STORATE_SCROLL] 0.00
2021-12-13 15:46:52.500 | INFO | [Storage_ABYSSAL] 5
2021-12-13 15:46:52.502 | INFO | Click ( 680,  144) @ TEMPLATE_STORAGE_ABYSSAL
2021-12-13 15:46:53.130 | INFO | Click ( 651,  518) @ STORAGE_COORDINATE_CHECKOUT
2021-12-13 15:46:56.514 | INFO | Already selected at ABYSSAL
2021-12-13 15:46:56.519 | INFO | Click ( 481,  298) @ ZONE_ENTRANCE
2021-12-13 15:46:57.073 | INFO | Click ( 801,  513) @ POPUP_CONFIRM_GLOBE_ENTER
2021-12-13 15:47:00.028 | INFO | [MAP_NAME 0.042s] 地中海C異常海域
2021-12-13 15:47:00.028 | INFO | Map name processed: 地中海C異常
2021-12-13 15:47:00.439 | INFO | [MAP_NAME 0.041s] 地中海C異常海域
2021-12-13 15:47:00.439 | INFO | Map name processed: 地中海C異常
2021-12-13 15:47:00.846 | INFO | [MAP_NAME 0.047s] 地中海C異常海域
2021-12-13 15:47:00.846 | INFO | Map name processed: 地中海C異常
2021-12-13 15:47:01.216 | INFO | [MAP_NAME 0.041s] 地中海C異常海域
2021-12-13 15:47:01.216 | INFO | Map name processed: 地中海C異常
2021-12-13 15:47:01.591 | INFO | [MAP_NAME 0.043s] 地中海C異常海域
2021-12-13 15:47:01.591 | INFO | Map name processed: 地中海C異常
2021-12-13 15:47:01.932 | WARNING | Zone init timeout
2021-12-13 15:47:01.976 | INFO | [MAP_NAME 0.042s] 地中海C異常海域
2021-12-13 15:47:01.976 | INFO | Map name processed: 地中海C異常
2021-12-13 15:47:01.976 | ERROR | Unable to find OS globe zone: 地中海c異常
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\module\os\map_operation.py", line 105, in get_current_zone
    self.zone = self.name_to_zone(name)
  File "C:\fakepath\AzurLaneAutoScript\module\os\globe_zone.py", line 122, in name_to_zone
    raise ScriptError(f'Unable to find OS globe zone: {name}')
module.exception.ScriptError: Unable to find OS globe zone: 地中海c異常

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 228, in opsi_abyssal
    OSCampaignRun(config=self.config, device=self.device).opsi_abyssal()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\os_run.py", line 53, in opsi_abyssal
    self.campaign.os_abyssal()
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 431, in os_abyssal
    self.clear_abyssal()
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 422, in clear_abyssal
    self.zone_init()
  File "C:\fakepath\AzurLaneAutoScript\module\os\map_operation.py", line 162, in zone_init
    return self.get_current_zone()
  File "C:\fakepath\AzurLaneAutoScript\module\os\map_operation.py", line 119, in get_current_zone
    raise MapDetectionError(*e.args)
module.exception.MapDetectionError: Unable to find OS globe zone: 地中海c異常
2021-12-13 15:47:02.023 | WARNING | Saving error: ./log/error/1639381622023

**Comment by DebuAqua** [comment]
![2021-12-13_20-08-17-033015](https://user-images.githubusercontent.com/70339606/145810159-57a8e268-44db-4f20-986b-16fde1969e82.png)

![2021-12-13_20-08-17-347821](https://user-images.githubusercontent.com/70339606/145810190-d18f699f-2187-4982-a4ec-ef06edf01158.png)


![2021-12-13_20-08-20-020001](https://user-images.githubusercontent.com/70339606/145810173-3aef7d9e-0235-4882-b303-5a9c5b7d9708.png)

2021-12-13 20:07:37.594 | INFO | +------------------------------------------------------+
2021-12-13 20:07:37.594 | INFO | |                    OPSISTRONGHOLD                    |
2021-12-13 20:07:37.594 | INFO | +------------------------------------------------------+
2021-12-13 20:07:37.620 | INFO | ==================== OS INIT ====================
2021-12-13 20:07:37.632 | INFO | <<< UI ENSURE >>>
2021-12-13 20:07:37.639 | INFO | [UI] page_commission
2021-12-13 20:07:37.639 | INFO | Goto page_os
2021-12-13 20:07:37.640 | INFO | <<< UI GOTO PAGE_OS >>>
2021-12-13 20:07:37.645 | INFO | Click (1243,   30) @ GOTO_MAIN
2021-12-13 20:07:38.758 | INFO | Click (1103,  312) @ MAIN_GOTO_CAMPAIGN
2021-12-13 20:07:39.499 | INFO | Click ( 774,  473) @ CAMPAIGN_MENU_GOTO_OS
2021-12-13 20:07:40.908 | INFO | [MAP_NAME 0.047s] ジブラルタル
2021-12-13 20:07:40.908 | INFO | Map name processed: ジブラルタル
2021-12-13 20:07:40.909 | INFO | [Zone] [2|直布罗特|Gibraltar|ジブラルタル|直布羅陀]
2021-12-13 20:07:40.918 | INFO | [HP]  98%  98%  98%  98%  98%  98%
2021-12-13 20:07:40.921 | INFO | [Repair icon] [False, False, False, False, False, False]
2021-12-13 20:07:40.921 | INFO | No ship found to be below threshold 40%, continue OS exploration
2021-12-13 20:07:40.921 | INFO | In port, skip running first auto search
2021-12-13 20:07:40.921 | INFO | Ash beacon fully collected today
2021-12-13 20:07:40.922 | INFO | ==================== OS CLEAR STRONGHOLD ====================
2021-12-13 20:07:40.923 | INFO | <<< UI CLICK >>>
2021-12-13 20:07:40.931 | INFO | Click (1170,  652) @ MAP_GOTO_GLOBE
2021-12-13 20:07:44.037 | INFO | Swipe ( 471,  463) -> ( 515,  416), 0.128
2021-12-13 20:07:45.807 | INFO | Loading OS globe map
2021-12-13 20:07:46.065 | INFO | [homo_storage] ((4, 3), [(445, 180), (879, 180), (376, 497), (963, 497)])
2021-12-13 20:07:46.174 | INFO |           globe_center: (1885.0, 1028.0)
2021-12-13 20:07:46.174 | INFO | 0.109s      similarity: 0.533
2021-12-13 20:07:46.175 | INFO | [Globe_center] 2
2021-12-13 20:07:46.175 | INFO | ==================== FIND SIREN STRONGHOLD ====================
2021-12-13 20:07:46.176 | INFO | -------------------- FIND SIREN STRONGHOLD IN REGION 4 --------------------
2021-12-13 20:07:46.176 | INFO | Find siren stronghold around [62|NA海域东南B|NA Ocean SE Sector B|NA海域南東B|NA海域東南B]
2021-12-13 20:07:46.177 | INFO | Zone 61 is not a siren stronghold
2021-12-13 20:07:46.177 | INFO | Zone 62 is not a siren stronghold
2021-12-13 20:07:46.178 | INFO | Zone 65 is not a siren stronghold
2021-12-13 20:07:46.178 | INFO | Zone 71 is not a siren stronghold
2021-12-13 20:07:46.179 | INFO | Find siren stronghold around [66|NA海域东南F|NA Ocean SE Sector F|NA海域南東F|NA海域東南F]
2021-12-13 20:07:46.179 | INFO | Swipe ( 240,  579) -> ( 715,  248), 0.143
2021-12-13 20:07:47.475 | INFO |           globe_center: (1595.0, 1264.0)
2021-12-13 20:07:47.475 | INFO | 0.102s      similarity: 0.462
2021-12-13 20:07:47.476 | INFO | [Globe_center] 62
2021-12-13 20:07:47.477 | INFO | Zone 51 is not a siren stronghold
2021-12-13 20:07:47.477 | INFO | Zone 52 is not a siren stronghold
2021-12-13 20:07:47.477 | INFO | Zone 63 is not a siren stronghold
2021-12-13 20:07:47.478 | INFO | Zone 66 is not a siren stronghold
2021-12-13 20:07:47.478 | INFO | Find siren stronghold around [64|NA海域东南D|NA Ocean SE Sector D|NA海域南東D|NA海域東南D]
2021-12-13 20:07:47.478 | INFO | Swipe ( 496,  505) -> ( 652,  328), 0.162
2021-12-13 20:07:48.511 | INFO |           globe_center: (1497.0, 1392.0)
2021-12-13 20:07:48.512 | INFO | 0.108s      similarity: 0.496
2021-12-13 20:07:48.512 | INFO | [Globe_center] 66
2021-12-13 20:07:48.513 | INFO | Zone 53 is not a siren stronghold
2021-12-13 20:07:48.513 | INFO | Zone 54 is not a siren stronghold
2021-12-13 20:07:48.514 | INFO | Zone 64 is not a siren stronghold
2021-12-13 20:07:48.515 | INFO | Find siren stronghold around [73|陆间海C|Mediterranee C|地中海C|陸間海C]
2021-12-13 20:07:48.515 | INFO | Swipe ( 882,  307) -> (  91,  541), 0.151
2021-12-13 20:07:49.926 | INFO |           globe_center: (1987.0, 1224.0)
2021-12-13 20:07:49.926 | INFO | 0.101s      similarity: 0.539
2021-12-13 20:07:49.927 | INFO | [Globe_center] 71
2021-12-13 20:07:49.928 | INFO | Zone 72 is not a siren stronghold
2021-12-13 20:07:49.928 | INFO | Zone 73 is not a siren stronghold
2021-12-13 20:07:49.928 | INFO | Find siren stronghold finished
2021-12-13 20:07:49.928 | INFO | -------------------- FIND SIREN STRONGHOLD IN REGION 3 --------------------
2021-12-13 20:07:49.929 | INFO | Find siren stronghold around [25|NA海域西南E|NA Ocean SW Sector E|NA海域南西E|NA海域西南E]
2021-12-13 20:07:49.929 | INFO | Swipe ( 106,  285) -> ( 897,  374), 0.158
2021-12-13 20:07:51.351 | INFO |           globe_center: (1501.0, 1160.0)
2021-12-13 20:07:51.352 | INFO | 0.106s      similarity: 0.417
2021-12-13 20:07:51.352 | INFO | [Globe_center] 65
2021-12-13 20:07:51.353 | INFO | Zone 23 is not a siren stronghold
2021-12-13 20:07:51.354 | INFO | Zone 25 is not a siren stronghold
2021-12-13 20:07:51.354 | INFO | Find siren stronghold around [32|西南洋脊B|Southwest Ocean Ridge B|南西海嶺B|西南洋脊B]
2021-12-13 20:07:51.355 | INFO | Swipe ( 116,  441) -> ( 907,  283), 0.162
2021-12-13 20:07:52.783 | INFO |           globe_center: (1015.0, 1274.0)
2021-12-13 20:07:52.783 | INFO | 0.110s      similarity: 0.585
2021-12-13 20:07:52.784 | INFO | [Globe_center] 158
2021-12-13 20:07:52.785 | INFO | Zone 22 is not a siren stronghold
2021-12-13 20:07:52.785 | INFO | Zone 31 is not a siren stronghold
2021-12-13 20:07:52.786 | INFO | Zone 32 is not a siren stronghold
2021-12-13 20:07:52.786 | INFO | Zone 44 is not a siren stronghold
2021-12-13 20:07:52.787 | INFO | Find siren stronghold around [34|西南洋脊D|Southwest Ocean Ridge D|南西海嶺D|西南洋脊D]
2021-12-13 20:07:52.787 | INFO | Swipe ( 597,  519) -> ( 833,  351), 0.146
2021-12-13 20:07:53.870 | INFO |           globe_center: (867.0, 1396.0)
2021-12-13 20:07:53.870 | INFO | 0.106s      similarity: 0.631
2021-12-13 20:07:53.871 | INFO | [Globe_center] 32
2021-12-13 20:07:53.872 | INFO | Zone 14 is not a siren stronghold
2021-12-13 20:07:53.872 | INFO | Zone 24 is not a siren stronghold
2021-12-13 20:07:53.872 | INFO | Zone 33 is not a siren stronghold
2021-12-13 20:07:53.873 | INFO | Zone 34 is not a siren stronghold
2021-12-13 20:07:53.873 | INFO | Find siren stronghold around [21|NA海域西南A|NA Ocean SW Sector A|NA海域南西A|NA海域西南A]
2021-12-13 20:07:53.874 | INFO | Swipe ( 147,  251) -> ( 402,  582), 0.181
2021-12-13 20:07:55.031 | INFO |           globe_center: (709.0, 1158.0)
2021-12-13 20:07:55.032 | INFO | 0.108s      similarity: 0.600
2021-12-13 20:07:55.033 | INFO | [Globe_center] 31
2021-12-13 20:07:55.034 | INFO | Zone 21 is not a siren stronghold
2021-12-13 20:07:55.034 | INFO | Find siren stronghold around [42|西大陆架B|West Continental Shelf B|西大陸棚B|西大陸棚B]
2021-12-13 20:07:55.035 | INFO | Swipe ( 250,  281) -> ( 415,  559), 0.138
2021-12-13 20:07:56.112 | INFO |           globe_center: (607.0, 960.0)
2021-12-13 20:07:56.112 | INFO | 0.105s      similarity: 0.664
2021-12-13 20:07:56.113 | INFO | [Globe_center] 21
2021-12-13 20:07:56.113 | INFO | Zone 42 is not a siren stronghold
2021-12-13 20:07:56.114 | INFO | Find siren stronghold around [12|卡利比安海B|Caribbean Sea B|カリブ海B|加勒比海B]
2021-12-13 20:07:56.114 | INFO | Swipe ( 402,  584) -> ( 666,  253), 0.15
2021-12-13 20:07:57.271 | INFO |           globe_center: (443.0, 1198.0)
2021-12-13 20:07:57.271 | INFO | 0.108s      similarity: 0.647
2021-12-13 20:07:57.272 | INFO | [Globe_center] 22
2021-12-13 20:07:57.272 | INFO | Swipe ( 291,  536) -> ( 346,  294), 0.151
2021-12-13 20:07:58.363 | INFO |           globe_center: (409.0, 1374.0)
2021-12-13 20:07:58.364 | INFO | 0.111s      similarity: 0.621
2021-12-13 20:07:58.364 | INFO | [Globe_center] 24
2021-12-13 20:07:58.365 | INFO | Zone 11 is not a siren stronghold
2021-12-13 20:07:58.365 | INFO | Zone 12 is not a siren stronghold
2021-12-13 20:07:58.366 | INFO | Zone 13 is not a siren stronghold
2021-12-13 20:07:58.366 | INFO | Find siren stronghold finished
2021-12-13 20:07:58.366 | INFO | -------------------- FIND SIREN STRONGHOLD IN REGION 1 --------------------
2021-12-13 20:07:58.366 | INFO | Find siren stronghold around [83|NA海域西C|NA Ocean W Sector C|NA海域西C|NA海域西C]
2021-12-13 20:07:58.367 | INFO | Swipe ( 854,  249) -> ( 186,  580), 0.156
2021-12-13 20:07:59.732 | INFO |           globe_center: (823.0, 1136.0)
2021-12-13 20:07:59.732 | INFO | 0.107s      similarity: 0.560
2021-12-13 20:07:59.733 | INFO | [Globe_center] 25
2021-12-13 20:07:59.734 | INFO | Swipe ( 414,  317) -> ( 274,  552), 0.165
2021-12-13 20:08:00.886 | INFO |           globe_center: (911.0, 968.0)
2021-12-13 20:08:00.886 | INFO | 0.108s      similarity: 0.601
2021-12-13 20:08:00.887 | INFO | [Globe_center] 83
2021-12-13 20:08:00.888 | INFO | Zone 83 is not a siren stronghold
2021-12-13 20:08:00.889 | INFO | Zone 85 is not a siren stronghold
2021-12-13 20:08:00.889 | INFO | Find siren stronghold around [43|西大陆架C|West Continental Shelf C|西大陸棚C|西大陸棚C]
2021-12-13 20:08:00.889 | INFO | Swipe ( 321,  279) -> ( 357,  516), 0.157
2021-12-13 20:08:01.937 | INFO |           globe_center: (889.0, 796.0)
2021-12-13 20:08:01.937 | INFO | 0.109s      similarity: 0.637
2021-12-13 20:08:01.937 | INFO | [Globe_center] 43
2021-12-13 20:08:01.938 | INFO | Zone 41 is not a siren stronghold
2021-12-13 20:08:01.939 | INFO | Zone 43 is not a siren stronghold
2021-12-13 20:08:01.939 | INFO | Zone 81 is not a siren stronghold
2021-12-13 20:08:01.940 | INFO | Zone 82 is not a siren stronghold
2021-12-13 20:08:01.940 | INFO | Find siren stronghold around [84|NA海域西D|NA Ocean W Sector D|NA海域西D|NA海域西D]
2021-12-13 20:08:01.940 | INFO | Swipe ( 558,  256) -> ( 448,  587), 0.171
2021-12-13 20:08:03.143 | INFO |           globe_center: (957.0, 558.0)
2021-12-13 20:08:03.143 | INFO | 0.109s      similarity: 0.609
2021-12-13 20:08:03.144 | INFO | [Globe_center] 81
2021-12-13 20:08:03.145 | INFO | Zone 84 is not a siren stronghold
2021-12-13 20:08:03.145 | INFO | Zone 91 is not a siren stronghold
2021-12-13 20:08:03.145 | INFO | Find siren stronghold around [92|NA海域西北B|NA Ocean NW Sector B|NA海域北西B|NA海域西北B]
2021-12-13 20:08:03.146 | INFO | Swipe ( 562,  280) -> ( 421,  546), 0.146
2021-12-13 20:08:04.260 | INFO |           globe_center: (1043.0, 368.0)
2021-12-13 20:08:04.260 | INFO | 0.110s      similarity: 0.621
2021-12-13 20:08:04.261 | INFO | [Globe_center] 92
2021-12-13 20:08:04.262 | INFO | Zone 92 is not a siren stronghold
2021-12-13 20:08:04.262 | INFO | Zone 93 is not a siren stronghold
2021-12-13 20:08:04.263 | INFO | Zone 94 is not a siren stronghold
2021-12-13 20:08:04.263 | INFO | Zone 103 is not a siren stronghold
2021-12-13 20:08:04.263 | INFO | Zone 105 is not a siren stronghold
2021-12-13 20:08:04.264 | INFO | Find siren stronghold around [95|NA海域西北E|NA Ocean NW Sector E|NA海域北西E|NA海域西北E]
2021-12-13 20:08:04.264 | INFO | Swipe ( 544,  325) -> ( 395,  489), 0.145
2021-12-13 20:08:05.280 | INFO |           globe_center: (1137.0, 248.0)
2021-12-13 20:08:05.280 | INFO | 0.108s      similarity: 0.531
2021-12-13 20:08:05.281 | INFO | [Globe_center] 92
2021-12-13 20:08:05.282 | INFO | Zone 95 is not a siren stronghold
2021-12-13 20:08:05.282 | INFO | Zone 104 is not a siren stronghold
2021-12-13 20:08:05.282 | INFO | Find siren stronghold around [102|西北航道B|Northwest Passage B|北西航路B|西北航道B]
2021-12-13 20:08:05.283 | INFO | Swipe ( 143,  420) -> ( 934,  367), 0.166
2021-12-13 20:08:06.665 | INFO |           globe_center: (651.0, 286.0)
2021-12-13 20:08:06.665 | INFO | 0.110s      similarity: 0.586
2021-12-13 20:08:06.666 | INFO | [Globe_center] 105
2021-12-13 20:08:06.667 | INFO | Zone 102 is not a siren stronghold
2021-12-13 20:08:06.667 | INFO | Zone 106 is not a siren stronghold
2021-12-13 20:08:06.668 | INFO | Find siren stronghold around [101|西北航道A|Northwest Passage A|北西航路A|西北航道A]
2021-12-13 20:08:06.668 | INFO | Swipe ( 319,  352) -> ( 639,  436), 0.119
2021-12-13 20:08:07.732 | INFO |           globe_center: (455.0, 226.0)
2021-12-13 20:08:07.732 | INFO | 0.108s      similarity: 0.513
2021-12-13 20:08:07.733 | INFO | [Globe_center] 103
2021-12-13 20:08:07.734 | INFO | Zone 101 is not a siren stronghold
2021-12-13 20:08:07.734 | INFO | Find siren stronghold finished
2021-12-13 20:08:07.734 | INFO | -------------------- FIND SIREN STRONGHOLD IN REGION 2 --------------------
2021-12-13 20:08:07.735 | INFO | Find siren stronghold around [131|NA海域东北A|NA Ocean NE Sector A|NA海域北東A|NA海域東北A]
2021-12-13 20:08:07.735 | INFO | Swipe ( 917,  522) -> ( 126,  382), 0.156
2021-12-13 20:08:09.081 | INFO |           globe_center: (945.0, 328.0)
2021-12-13 20:08:09.081 | INFO | 0.108s      similarity: 0.642
2021-12-13 20:08:09.082 | INFO | [Globe_center] 84
2021-12-13 20:08:09.083 | INFO | Swipe ( 693,  461) -> ( 224,  420), 0.164
2021-12-13 20:08:10.317 | INFO |           globe_center: (1237.0, 358.0)
2021-12-13 20:08:10.317 | INFO | 0.109s      similarity: 0.616
2021-12-13 20:08:10.318 | INFO | [Globe_center] 93
2021-12-13 20:08:10.319 | INFO | Zone 131 is not a siren stronghold
2021-12-13 20:08:10.319 | INFO | Zone 133 is not a siren stronghold
2021-12-13 20:08:10.320 | INFO | Zone 134 is not a siren stronghold
2021-12-13 20:08:10.320 | INFO | Zone 135 is a siren stronghold
2021-12-13 20:08:10.320 | INFO | Globe focus_to: 135
2021-12-13 20:08:10.322 | INFO | Click ( 823,  543) @ ZONE_135
2021-12-13 20:08:11.133 | INFO |           globe_center: (1517.0, 464.0)
2021-12-13 20:08:11.133 | INFO | 0.111s      similarity: 0.605
2021-12-13 20:08:11.134 | INFO | [Globe_center] 134
2021-12-13 20:08:11.662 | INFO |           globe_center: (1535.0, 472.0)
2021-12-13 20:08:11.662 | INFO | 0.113s      similarity: 0.490
2021-12-13 20:08:11.663 | INFO | [Globe_center] 132
2021-12-13 20:08:12.157 | INFO |           globe_center: (1535.0, 472.0)
2021-12-13 20:08:12.157 | INFO | 0.109s      similarity: 0.449
2021-12-13 20:08:12.158 | INFO | [Globe_center] 132
2021-12-13 20:08:12.160 | INFO | [Globe_pinned] [135|NA海域东北E|NA Ocean NE Sector E|NA海域北東E|NA海域東北E]
2021-12-13 20:08:12.162 | INFO | Confirm it is a siren stronghold
2021-12-13 20:08:12.167 | INFO | Click ( 479,  308) @ ZONE_ENTRANCE
2021-12-13 20:08:17.399 | INFO | [MAP_NAME 0.044s] NA海域北東Eセイレーン
2021-12-13 20:08:17.399 | INFO | Map name processed: NA海域北東Eセイレーン
2021-12-13 20:08:17.765 | INFO | [MAP_NAME 0.040s] NA海域北東Eセイレーン
2021-12-13 20:08:17.765 | INFO | Map name processed: NA海域北東Eセイレーン
2021-12-13 20:08:18.046 | INFO | Click (1190,   35) @ STORY_SKIP
2021-12-13 20:08:18.440 | INFO | [MAP_NAME 0.040s] NA海域北東Eセイレーン
2021-12-13 20:08:18.440 | INFO | Map name processed: NA海域北東Eセイレーン
2021-12-13 20:08:18.749 | INFO | [MAP_NAME 0.041s] NA海域北東Eセイレーン
2021-12-13 20:08:18.749 | INFO | Map name processed: NA海域北東Eセイレーン
2021-12-13 20:08:19.081 | INFO | [MAP_NAME 0.043s] NA海域北東Eセイレーン
2021-12-13 20:08:19.081 | INFO | Map name processed: NA海域北東Eセイレーン
2021-12-13 20:08:19.413 | INFO | [MAP_NAME 0.042s] NA海域北東Eセイレーン
2021-12-13 20:08:19.413 | INFO | Map name processed: NA海域北東Eセイレーン
2021-12-13 20:08:19.725 | INFO | [MAP_NAME 0.044s] NA海域北東Eセイレーン
2021-12-13 20:08:19.726 | INFO | Map name processed: NA海域北東Eセイレーン
2021-12-13 20:08:20.020 | WARNING | Zone init timeout
2021-12-13 20:08:20.063 | INFO | [MAP_NAME 0.042s] NA海域北東Eセイレーン
2021-12-13 20:08:20.063 | INFO | Map name processed: NA海域北東Eセイレーン
2021-12-13 20:08:20.064 | ERROR | Unable to find OS globe zone: na海域北東eセイレーン
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\module\os\map_operation.py", line 105, in get_current_zone
    self.zone = self.name_to_zone(name)
  File "C:\fakepath\AzurLaneAutoScript\module\os\globe_zone.py", line 122, in name_to_zone
    raise ScriptError(f'Unable to find OS globe zone: {name}')
module.exception.ScriptError: Unable to find OS globe zone: na海域北東eセイレーン

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 232, in opsi_stronghold
    OSCampaignRun(config=self.config, device=self.device).opsi_stronghold()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\os_run.py", line 60, in opsi_stronghold
    self.campaign.os_stronghold()
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 463, in os_stronghold
    self.clear_stronghold()
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 455, in clear_stronghold
    self.zone_init()
  File "C:\fakepath\AzurLaneAutoScript\module\os\map_operation.py", line 162, in zone_init
    return self.get_current_zone()
  File "C:\fakepath\AzurLaneAutoScript\module\os\map_operation.py", line 119, in get_current_zone
    raise MapDetectionError(*e.args)
module.exception.MapDetectionError: Unable to find OS globe zone: na海域北東eセイレーン
2021-12-13 20:08:20.065 | WARNING | Saving error: ./log/error/1639397300065
