### ISSUE TITLE
深渊海域被卡在第二层的门口

### ISSUE THREAD

**Issue by yanyihui** [LmeSzinc/AzurLaneAutoScript#829]
**Describe the bug**
第二层机关打不开

**To Reproduce**
没操作全自动

**Expected behavior**
踩机关，然后去打boss

**Screenshots**

![2021-12-14_00-20-38-104820](https://user-images.githubusercontent.com/57699016/146012261-a78ec042-cf92-408d-9f02-997ef30dfbdd.png)

**log**
2021-12-14 00:20:07.205 | INFO | +---------------------------------------------------+
2021-12-14 00:20:07.206 | INFO | |                    OPSIABYSSAL                    |
2021-12-14 00:20:07.206 | INFO | +---------------------------------------------------+
2021-12-14 00:20:07.246 | INFO | ==================== OS INIT ====================
2021-12-14 00:20:07.272 | INFO | <<< UI ENSURE >>>
2021-12-14 00:20:07.305 | INFO | [UI] page_build
2021-12-14 00:20:07.305 | INFO | Goto page_os
2021-12-14 00:20:07.306 | INFO | <<< UI GOTO PAGE_OS >>>
2021-12-14 00:20:07.310 | INFO | Click (1242,   45) @ GOTO_MAIN
2021-12-14 00:20:09.865 | INFO | Click (1074,  337) @ MAIN_GOTO_CAMPAIGN
2021-12-14 00:20:11.924 | INFO | Click ( 831,  451) @ CAMPAIGN_MENU_GOTO_OS
2021-12-14 00:20:15.496 | INFO | [MAP_NAME 0.110s] 利维浦
2021-12-14 00:20:15.497 | INFO | Map name processed: 利维浦
2021-12-14 00:20:15.499 | INFO | [Zone] [1|利维浦|Liverpool|リバープール|利物浦]
2021-12-14 00:20:15.534 | INFO | [HP]  98%  98%  98%  98%  98%  98%
2021-12-14 00:20:15.540 | INFO | [Repair icon] [False, False, False, False, False, False]
2021-12-14 00:20:15.541 | INFO | No ship found to be below threshold 40%, continue OS exploration
2021-12-14 00:20:15.541 | INFO | In port, skip running first auto search
2021-12-14 00:20:15.585 | INFO | [ASH_COLLECT_STATUS 0.044s] 0/100
2021-12-14 00:20:15.587 | INFO | ==================== OS CLEAR ABYSSAL ====================
2021-12-14 00:20:15.587 | INFO | <<< OS GET NEXT OBSCURE >>>
2021-12-14 00:20:15.588 | INFO | <<< UI CLICK >>>
2021-12-14 00:20:15.618 | INFO | Click ( 667,  647) @ STORAGE_ENTER
2021-12-14 00:20:16.699 | INFO | <<< STORAGE LOGGER USE ALL >>>
2021-12-14 00:20:16.747 | INFO | [Storage_logger] 0
2021-12-14 00:20:16.756 | INFO | All loggers in storage have been used
2021-12-14 00:20:16.756 | INFO | <<< STORAGE CHECKOUT ITEM ABYSSAL >>>
2021-12-14 00:20:16.817 | INFO | [Storage_ABYSSAL] 1
2021-12-14 00:20:16.819 | INFO | Click ( 676,  163) @ TEMPLATE_STORAGE_ABYSSAL
2021-12-14 00:20:17.733 | INFO | Click ( 633,  512) @ STORAGE_COORDINATE_CHECKOUT
2021-12-14 00:20:24.109 | INFO | Already selected at ABYSSAL
2021-12-14 00:20:24.118 | INFO | Click ( 489,  302) @ ZONE_ENTRANCE
2021-12-14 00:20:24.476 | INFO | Click ( 788,  515) @ POPUP_CONFIRM_GLOBE_ENTER
2021-12-14 00:20:28.332 | INFO | [MAP_NAME 0.094s] 西北航道F-深渊海域
2021-12-14 00:20:28.333 | INFO | Map name processed: 西北航道F
2021-12-14 00:20:28.333 | INFO | [Zone] [106|西北航道F|Northwest Passage F|北西航路F|西北航道F]
2021-12-14 00:20:28.345 | INFO | [Fleet_Lock] on
2021-12-14 00:20:28.346 | INFO | Click (1189,  543) @ OS_FLEET_LOCKED
2021-12-14 00:20:29.986 | INFO | [Fleet_Lock] off
2021-12-14 00:20:29.986 | INFO | <<< QUESTION GOTO >>>
2021-12-14 00:20:29.987 | INFO | [homo_storage] ((10, 7), [(110.307, 103.657), (1012.311, 103.657), (-32.959, 600.567), (1113.057, 600.567)])
2021-12-14 00:20:30.210 | INFO |            tile_center: 0.905 (good match)
2021-12-14 00:20:30.212 | INFO | 0.187s      edge_lines: 0 hori, 0 vert
2021-12-14 00:20:30.212 | INFO | Edges:       homo_loca: ( 54,  58)
2021-12-14 00:20:30.226 | INFO |            center_loca: (5, 4)
2021-12-14 00:20:30.239 | INFO | 0.012s         predict: 84
2021-12-14 00:20:30.240 | INFO | -- -- -- -- -- -- -- -- -- -- -- --
2021-12-14 00:20:30.240 | INFO | -- -- -- -- -- -- -- -- -- -- -- --
2021-12-14 00:20:30.240 | INFO | .. -- -- -- -- -- -- -- -- -- -- --
2021-12-14 00:20:30.241 | INFO | .. -- -- -- -- -- -- -- -- -- -- ..
2021-12-14 00:20:30.241 | INFO | .. -- -- -- -- FL -- -- -- -- -- ..
2021-12-14 00:20:30.241 | INFO | .. -- -- -- -- -- -- -- -- -- -- ..
2021-12-14 00:20:30.241 | INFO | .. -- -- -- -- -- -- -- -- -- -- ..
2021-12-14 00:20:30.242 | INFO | .. .. -- -- -- -- -- -- -- -- -- ..
2021-12-14 00:20:30.385 | INFO |             -- -- --            
2021-12-14 00:20:30.386 | INFO |       -- -- -- -- -- -- --      
2021-12-14 00:20:30.386 | INFO |    -- -- -- -- -- -- -- -- --   
2021-12-14 00:20:30.386 | INFO |    -- -- -- -- QU -- -- -- --   
2021-12-14 00:20:30.386 | INFO | -- -- -- -- -- -- -- -- -- -- --
2021-12-14 00:20:30.387 | INFO | -- -- -- -- -- FL -- -- -- -- EN
2021-12-14 00:20:30.387 | INFO | -- -- -- -- -- -- -- -- -- -- --
2021-12-14 00:20:30.387 | INFO |    -- -- -- -- -- -- -- -- --   
2021-12-14 00:20:30.388 | INFO |    -- -- -- -- -- -- -- -- --   
2021-12-14 00:20:30.388 | INFO |       -- -- -- -- -- -- --      
2021-12-14 00:20:30.388 | INFO |             -- -- --            
2021-12-14 00:20:30.389 | INFO | Radar (0, -2) -> Local F3 (fleet=F5)
2021-12-14 00:20:30.389 | INFO | Click ( 650,  229) @ F3
2021-12-14 00:20:30.439 | INFO | <<< WAIT UNTIL WALK STABLE >>>
2021-12-14 00:20:30.440 | INFO | Screenshot interval set to 0.35s
2021-12-14 00:20:31.178 | INFO |            tile_center: 0.908 (good match)
2021-12-14 00:20:31.180 | INFO | 0.150s      edge_lines: 0 hori, 0 vert
2021-12-14 00:20:31.196 | INFO | Edges:       homo_loca: ( 54,  57)
2021-12-14 00:20:31.210 | INFO |            center_loca: (5, 4)
2021-12-14 00:20:31.211 | INFO | [homo_loca] [54 57]
2021-12-14 00:20:31.838 | INFO |            tile_center: 0.925 (good match)
2021-12-14 00:20:31.840 | INFO | 0.129s      edge_lines: 0 hori, 0 vert
2021-12-14 00:20:31.840 | INFO | Edges:       homo_loca: ( 53,  58)
2021-12-14 00:20:31.852 | INFO |            center_loca: (5, 4)
2021-12-14 00:20:31.852 | INFO | [homo_loca] [53 58]
2021-12-14 00:20:32.452 | INFO |            tile_center: 0.939 (good match)
2021-12-14 00:20:32.469 | INFO | 0.136s      edge_lines: 0 hori, 0 vert
2021-12-14 00:20:32.488 | INFO | Edges:       homo_loca: ( 53,  58)
2021-12-14 00:20:32.519 | INFO |            center_loca: (5, 4)
2021-12-14 00:20:32.520 | INFO | [homo_loca] [53 58]
2021-12-14 00:20:33.125 | INFO |            tile_center: 0.585 (bad match)
2021-12-14 00:20:33.640 | INFO |            tile_corner: 0.820 (1 matches)
2021-12-14 00:20:33.642 | INFO | 0.649s      edge_lines: 0 hori, 0 vert
2021-12-14 00:20:33.642 | INFO | Edges:       homo_loca: ( 52,  57)
2021-12-14 00:20:33.658 | INFO |            center_loca: (5, 4)
2021-12-14 00:20:33.660 | INFO | [homo_loca] [52.94654348 57.94659102]
2021-12-14 00:20:34.319 | INFO |            tile_center: 0.895 (2 matches)
2021-12-14 00:20:34.320 | INFO | 0.152s      edge_lines: 0 hori, 0 vert
2021-12-14 00:20:34.320 | INFO | Edges:       homo_loca: ( 52,  57)
2021-12-14 00:20:34.336 | INFO |            center_loca: (5, 4)
2021-12-14 00:20:34.337 | INFO | [homo_loca] [52.99991333 57.49998988]
2021-12-14 00:20:34.338 | INFO | Walk stabled
2021-12-14 00:20:34.338 | INFO | Screenshot interval set to 0.1s
2021-12-14 00:20:34.510 | INFO |            tile_center: 0.895 (2 matches)
2021-12-14 00:20:34.512 | INFO | 0.165s      edge_lines: 0 hori, 0 vert
2021-12-14 00:20:34.512 | INFO | Edges:       homo_loca: ( 52,  57)
2021-12-14 00:20:34.524 | INFO |            center_loca: (5, 4)
2021-12-14 00:20:34.534 | INFO | 0.010s         predict: 84
2021-12-14 00:20:34.535 | INFO | -- -- -- -- -- -- -- -- -- -- -- --
2021-12-14 00:20:34.535 | INFO | -- -- -- -- -- -- -- -- -- -- -- --
2021-12-14 00:20:34.535 | INFO | .. -- -- -- -- -- -- -- -- -- -- --
2021-12-14 00:20:34.536 | INFO | .. -- -- -- -- -- -- -- -- -- -- ..
2021-12-14 00:20:34.536 | INFO | .. -- -- -- -- FL -- -- -- -- -- ..
2021-12-14 00:20:34.536 | INFO | .. -- -- -- -- -- -- -- -- -- -- ..
2021-12-14 00:20:34.537 | INFO | .. -- -- -- -- -- -- -- -- -- -- ..
2021-12-14 00:20:34.537 | INFO | .. .. -- -- -- -- -- -- -- -- -- ..
2021-12-14 00:20:34.625 | INFO |             -- -- --            
2021-12-14 00:20:34.625 | INFO |       -- -- -- -- -- -- --      
2021-12-14 00:20:34.626 | INFO |    -- -- -- -- -- -- -- -- --   
2021-12-14 00:20:34.626 | INFO |    -- -- -- -- QU -- -- -- --   
2021-12-14 00:20:34.626 | INFO | -- -- -- -- -- -- -- -- -- -- --
2021-12-14 00:20:34.626 | INFO | -- -- -- -- -- FL -- -- -- -- --
2021-12-14 00:20:34.627 | INFO | -- -- -- -- -- -- -- -- -- -- --
2021-12-14 00:20:34.627 | INFO |    -- -- -- -- -- -- -- -- --   
2021-12-14 00:20:34.627 | INFO |    -- -- -- -- -- -- -- -- --   
2021-12-14 00:20:34.628 | INFO |       -- -- -- -- -- -- --      
2021-12-14 00:20:34.628 | INFO |             -- -- --            
2021-12-14 00:20:34.629 | INFO | Radar (0, -2) -> Local F3 (fleet=F5)
2021-12-14 00:20:34.629 | INFO | Click ( 635,  228) @ F3
2021-12-14 00:20:34.692 | INFO | <<< WAIT UNTIL WALK STABLE >>>
2021-12-14 00:20:34.694 | INFO | Screenshot interval set to 0.35s
2021-12-14 00:20:35.402 | INFO |            tile_center: 0.883 (4 matches)
2021-12-14 00:20:35.403 | INFO | 0.155s      edge_lines: 0 hori, 0 vert
2021-12-14 00:20:35.404 | INFO | Edges:       homo_loca: ( 53,  58)
2021-12-14 00:20:35.415 | INFO |            center_loca: (5, 4)
2021-12-14 00:20:35.416 | INFO | [homo_loca] [53.4288201  58.15349071]
2021-12-14 00:20:35.879 | WARNING | Map walk out of step.
2021-12-14 00:20:38.105 | ERROR | walk_out_of_step
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 228, in opsi_abyssal
    OSCampaignRun(config=self.config, device=self.device).opsi_abyssal()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\os_run.py", line 53, in opsi_abyssal
    self.campaign.os_abyssal()
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 431, in os_abyssal
    self.clear_abyssal()
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 423, in clear_abyssal
    result = self.run_abyssal()
  File "C:\fakepath\AzurLaneAutoScript\module\os\fleet.py", line 548, in run_abyssal
    self.question_goto(has_fleet_step=True)
  File "C:\fakepath\AzurLaneAutoScript\module\os\fleet.py", line 398, in question_goto
    self.wait_until_walk_stable(confirm_timer=Timer(1.5, count=4))
  File "C:\fakepath\AzurLaneAutoScript\module\os\fleet.py", line 266, in wait_until_walk_stable
    raise MapWalkError('walk_out_of_step')
module.exception.MapWalkError: walk_out_of_step
2021-12-14 00:20:38.114 | WARNING | Saving error: ./log/error/1639412438114

**Comment by LmeSzinc** [comment]
深渊机关解锁的过程中，不应该有消息框，这里的消息内容我也分辨不出。
建议检查游戏客户端设置中的 `大型作战设置` - `减少TB引导` 是否已经打开
