### ISSUE TITLE
进入深渊海域报错的问题没有彻底解决

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#832]
#825 在另一深渊海域会复现

![2021-12-15_15-11-39-002657](https://user-images.githubusercontent.com/70339606/146141744-bc5a2eca-632b-428b-816e-f8e112df131b.png)
![2021-12-15_15-11-42-369565](https://user-images.githubusercontent.com/70339606/146141771-137b7355-cb99-4fd3-b1d6-979e461b4f13.png)

2021-12-15 15:11:22.253 | INFO | +---------------------------------------------------+
2021-12-15 15:11:22.253 | INFO | |                    OPSIABYSSAL                    |
2021-12-15 15:11:22.253 | INFO | +---------------------------------------------------+
2021-12-15 15:11:23.264 | INFO | ==================== OS INIT ====================
2021-12-15 15:11:23.284 | INFO | <<< UI ENSURE >>>
2021-12-15 15:11:23.291 | INFO | [UI] page_main
2021-12-15 15:11:23.292 | INFO | Goto page_os
2021-12-15 15:11:23.292 | INFO | <<< UI GOTO PAGE_OS >>>
2021-12-15 15:11:23.318 | INFO | Click (1025,  331) @ MAIN_GOTO_CAMPAIGN
2021-12-15 15:11:23.319 | INFO | <<< MINITOUCH INIT >>>
2021-12-15 15:11:25.320 | INFO | Minitouch bind to port 20698
2021-12-15 15:11:25.354 | INFO | Minitouch forward port 20698
2021-12-15 15:11:25.356 | INFO | minitouch running on port: 20698, pid: 6016
2021-12-15 15:11:25.356 | INFO | max_contact: 2; max_x: 32767; max_y: 32767; max_pressure: 0
2021-12-15 15:11:26.334 | INFO | Click ( 767,  480) @ CAMPAIGN_MENU_GOTO_OS
2021-12-15 15:11:27.754 | INFO | Loading OCR model: ./bin/cnocr_models/jp
2021-12-15 15:11:27.827 | INFO | [MAP_NAME 0.087s] NYシティ
2021-12-15 15:11:27.827 | INFO | Map name processed: NYシティ
2021-12-15 15:11:27.828 | INFO | [Zone] [0|NY|NY City|NYシティ|紐約]
2021-12-15 15:11:27.840 | INFO | [HP]  98%  98%  98%  96%  98%  98%
2021-12-15 15:11:27.843 | INFO | [Repair icon] [False, False, False, False, False, False]
2021-12-15 15:11:27.843 | INFO | No ship found to be below threshold 40%, continue OS exploration
2021-12-15 15:11:27.844 | INFO | In port, skip running first auto search
2021-12-15 15:11:27.844 | INFO | Ash beacon fully collected today
2021-12-15 15:11:27.845 | INFO | ==================== OS CLEAR ABYSSAL ====================
2021-12-15 15:11:27.846 | INFO | <<< OS GET NEXT OBSCURE >>>
2021-12-15 15:11:27.846 | INFO | <<< UI CLICK >>>
2021-12-15 15:11:27.891 | INFO | Click ( 642,  662) @ STORAGE_ENTER
2021-12-15 15:11:28.895 | INFO | <<< STORAGE LOGGER USE ALL >>>
2021-12-15 15:11:28.951 | INFO | [Storage_logger] 0
2021-12-15 15:11:28.951 | INFO | All loggers in storage have been used
2021-12-15 15:11:28.951 | INFO | <<< STORAGE CHECKOUT ITEM ABYSSAL >>>
2021-12-15 15:11:28.986 | INFO | [Storage_ABYSSAL] 1
2021-12-15 15:11:28.988 | INFO | Click ( 195,  154) @ TEMPLATE_STORAGE_ABYSSAL
2021-12-15 15:11:29.631 | INFO | Click ( 602,  518) @ STORAGE_COORDINATE_CHECKOUT
2021-12-15 15:11:33.324 | INFO | Already selected at ABYSSAL
2021-12-15 15:11:33.327 | INFO | Click ( 450,  307) @ ZONE_ENTRANCE
2021-12-15 15:11:33.566 | INFO | Click ( 786,  514) @ POPUP_CONFIRM_GLOBE_ENTER
2021-12-15 15:11:34.520 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
2021-12-15 15:11:34.585 | INFO | [Amount_ocr 0.077s] [4040, 50, 1, 1]
2021-12-15 15:11:34.604 | INFO | [ACTION_POINT_REMAIN 0.018s] 85
2021-12-15 15:11:34.604 | INFO | Action points: 85(1335), oil: 4040
2021-12-15 15:11:34.605 | INFO | Click ( 903,  329) @ ACTION_POINT_GRID_3_0
2021-12-15 15:11:35.220 | INFO | Click ( 804,  549) @ ACTION_POINT_USE
2021-12-15 15:11:35.793 | INFO | [Amount_ocr 0.043s] [4040, 50, 1, 0]
2021-12-15 15:11:35.812 | INFO | [ACTION_POINT_REMAIN 0.019s] 185
2021-12-15 15:11:35.812 | INFO | Action points: 185(1235), oil: 4040
2021-12-15 15:11:35.812 | INFO | Having enough action points
2021-12-15 15:11:35.812 | INFO | <<< UI CLICK >>>
2021-12-15 15:11:35.865 | INFO | Click ( 448,  548) @ ACTION_POINT_CANCEL
2021-12-15 15:11:36.801 | INFO | Click ( 458,  305) @ ZONE_ENTRANCE
2021-12-15 15:11:37.376 | INFO | Click ( 795,  517) @ POPUP_CONFIRM_GLOBE_ENTER
2021-12-15 15:11:40.498 | INFO | [MAP_NAME 0.046s] 東大陸棚A・異常海域
2021-12-15 15:11:40.580 | INFO | Map name processed: 東大陸棚A・
2021-12-15 15:11:40.960 | INFO | [MAP_NAME 0.047s] 東大陸棚A・異常海域
2021-12-15 15:11:40.961 | INFO | Map name processed: 東大陸棚A・
2021-12-15 15:11:41.321 | INFO | [MAP_NAME 0.049s] 東大陸棚A・異常海域
2021-12-15 15:11:41.322 | INFO | Map name processed: 東大陸棚A・
2021-12-15 15:11:41.697 | INFO | [MAP_NAME 0.045s] 東大陸棚A・異常海域
2021-12-15 15:11:41.698 | INFO | Map name processed: 東大陸棚A・
2021-12-15 15:11:42.026 | INFO | [MAP_NAME 0.040s] 東大陸棚A・異常海域
2021-12-15 15:11:42.027 | INFO | Map name processed: 東大陸棚A・
2021-12-15 15:11:42.369 | WARNING | Zone init timeout
2021-12-15 15:11:42.415 | INFO | [MAP_NAME 0.044s] 東大陸棚A・異常海域
2021-12-15 15:11:42.416 | INFO | Map name processed: 東大陸棚A・
2021-12-15 15:11:42.417 | ERROR | Unable to find OS globe zone: 東大陸棚a・
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\module\os\map_operation.py", line 113, in get_current_zone
    self.zone = self.name_to_zone(name)
  File "C:\fakepath\AzurLaneAutoScript\module\os\globe_zone.py", line 122, in name_to_zone
    raise ScriptError(f'Unable to find OS globe zone: {name}')
module.exception.ScriptError: Unable to find OS globe zone: 東大陸棚a・

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 228, in opsi_abyssal
    OSCampaignRun(config=self.config, device=self.device).opsi_abyssal()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\os_run.py", line 53, in opsi_abyssal
    self.campaign.os_abyssal()
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 431, in os_abyssal
    self.clear_abyssal()
  File "C:\fakepath\AzurLaneAutoScript\module\os\operation_siren.py", line 422, in clear_abyssal
    self.zone_init()
  File "C:\fakepath\AzurLaneAutoScript\module\os\map_operation.py", line 170, in zone_init
    return self.get_current_zone()
  File "C:\fakepath\AzurLaneAutoScript\module\os\map_operation.py", line 127, in get_current_zone
    raise MapDetectionError(*e.args)
module.exception.MapDetectionError: Unable to find OS globe zone: 東大陸棚a・
2021-12-15 15:11:42.457 | WARNING | Saving error: ./log/error/1639552302457

**Comment by LmeSzinc** [comment]
OCR 结果多出一些标点符号，去掉就好了
