### ISSUE TITLE
更新时遇到 AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Lab-Heathcliff** [LmeSzinc/AzurLaneAutoScript#840]
昨天下午日常重启电脑，完了以后发现alas一直进不去了，一看报标题这个问题

==================== Git Init ====================
"C:/Users/Heathcliff/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in C:/Users/Heathcliff/Desktop/AzurLaneAutoScript/.git/
[ success ]
==================== Set Git Proxy ====================
Traceback (most recent call last):
  File "C:\Users\Heathcliff\Desktop\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Heathcliff\Desktop\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Heathcliff\Desktop\AzurLaneAutoScript\deploy\installer.py", line 220, in <module>
    Installer().install()
  File "C:\Users\Heathcliff\Desktop\AzurLaneAutoScript\deploy\installer.py", line 214, in install
    self.git_install()
  File "C:\Users\Heathcliff\Desktop\AzurLaneAutoScript\deploy\installer.py", line 143, in git_install
    keep_changes=self.bool('KeepLocalChanges')
  File "C:\Users\Heathcliff\Desktop\AzurLaneAutoScript\deploy\installer.py", line 101, in git_repository_init
    if self.to_bool(proxy):
  File "C:\Users\Heathcliff\Desktop\AzurLaneAutoScript\deploy\installer.py", line 44, in to_bool
    value = value.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

issues里貌似没找到一样的，网上搜了下说是查看downgrade然后把None改成自己更改的字段名就能解决，但纯小白完全不明白该改成啥，希望能有大佬来指指路。
ps:如果解决方法比重装要复杂，请直接告诉我(つД`)

**Comment by LmeSzinc** [comment]
在 `config/deploy.yaml` 里，把 `GitProxy` 改成 `false`，成功打开之后再改回来，就可以了

**Comment by Lab-Heathcliff** [comment]
感谢，问题已解决(oﾟ▽ﾟ)o
