### ISSUE TITLE
vmos pro里的虚拟机显示远程终端因无响应而关闭连接

### ISSUE THREAD

**Issue by uairyu** [LmeSzinc/AzurLaneAutoScript#858]
PC：win7 x64
安卓： 红米10x miui11.0.5 系统版本10
虚拟机环境：Vmos pro 1.8.0 下的5.1
并非是pc上的安卓模拟器，而是Vmos pro这个app下的虚拟机，能正常用adb连接上，并且用 adb exec-out screencap -p >1.jpg 是能导出虚拟机的图片出来，是正常的图片。下面图为虚拟机的设置界面
可以到该链接下载该app https://wwd.lanzoup.com/i5ghky6fh9g 密码:3ygo
![OL1 H2%8_IH~4@JM7075{M](https://user-images.githubusercontent.com/42320246/147807159-70380cc4-7333-431a-8b31-6dbd85ee08cb.png)
![9$ZVM))4 }82ZQ401_MYCMO](https://user-images.githubusercontent.com/42320246/147807162-61e2f96b-cac7-46d0-bd3f-e098c161d837.png)

出现的问题：
 远程终端因无响应而关闭连接

14:11:38.976 | INFO | [Server] cn
14:11:38.993 | INFO | Bind task {'Alas', 'General'}
14:11:39.041 | INFO | Start scheduler loop: alas
14:11:39.054 | INFO | [Server] cn
14:11:39.074 | INFO | Bind task {'Alas', 'General'}
14:11:39.075 | INFO | Pending tasks: ['Event']
14:11:39.076 | INFO | [Task] Event (Enable, 2020-01-01 00:00:00)
14:11:39.076 | INFO | Bind task {'Alas', 'General', 'Event'}
14:11:39.077 | INFO | Scheduler: Start task `Event`
14:11:41.526 | INFO | <<< DEVICE >>>
14:11:41.527 | INFO | [Adb_binary] G:/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe
14:11:41.918 | INFO | already connected to 192.168.3.221:5668
14:11:58.910 | ERROR | ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "", line 2, in raise_from
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "G:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "G:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "G:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "", line 2, in raise_from
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "G:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "G:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "G:\AzurLaneAutoScript\toolkit\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\AzurLaneAutoScript\alas.py", line 40, in device
    device = Device(config=self.config)
  File "G:\AzurLaneAutoScript\module\device\connection.py", line 33, in __init__
    self.device = self.connect(self.serial)
  File "G:\AzurLaneAutoScript\module\device\connection.py", line 187, in connect
    device = u2.connect(serial)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 1880, in connect
    return connect_usb(addr)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 1921, in connect_usb
    return Device(serial)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 248, in __init__
    wlan_ip = self.wlan_ip
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 431, in wlan_ip
    ip = self.http.get("/wlan/ip").text.strip()
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 214, in request
    self.__client._prepare_atx_agent()
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 304, in _prepare_atx_agent
    self._setup_atx_agent()
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__.py", line 315, in _setup_atx_agent
    _initer.install()
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 385, in install
    self.check_atx_agent_version()
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 399, in check_atx_agent_version
    port).text.strip()
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "G:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by LmeSzinc** [comment]
Alas 不只需要 ADB，uiautomator2 需要通过 HTTP 访问安卓上的 ATX-agent，minitouch 点击也需要与安卓上的 minitouch 服务建立连接，vmos 似乎没有暴露出这些服务来，所以在连接是出现未响应的问题

**Comment by uairyu** [comment]
> Alas 不只需要 ADB，uiautomator2 需要通过 HTTP 访问安卓上的 ATX-agent，minitouch 点击也需要与安卓上的 minitouch 服务建立连接，vmos 似乎没有暴露出这些服务来，所以在连接时出现没有响应的问题

但我把alas设置里面的模拟器截图方案和控制方案都设为ADB也不行

**Comment by LmeSzinc** [comment]
minitouch 和 aScreenCap 你不选 Alas 就不用，但无论你选什么，必须建立 uiautomator2 连接，不少操作 u2 会比 ADB 快，有些操作 ADB 甚至根本做不了

**Comment by uairyu** [comment]
> minitouch 和 aScreenCap 你不选 Alas 就不用，但无论你选什么，必须建立 uiautomator2 连接，不少操作 u2 会比 ADB 快，有些操作 ADB 甚至根本做不了

那目前是否有什么解决方法，麻烦一点我也想试试看，还是说vmos无解？？因为电脑配置不算好不足以边开模拟器边干其它工作，只能用手机，手机又想后台挂游戏才用上vmos

**Comment by laijirong** [comment]
没有使用虚拟机，我用adb改了手机分辨率，系统UI分辨率变成1280x720（720x1280）了，但是一进游戏立马又变成了1920x1080，然后就是各种错位点击😢

**Comment by zzyyuanmi** [comment]
在 VMOS 下 uiautomator2 所依赖的 atx-agent 无法正常运行，我在那个仓库提过 issue 但那边表示没有计划支持😥

openatx/uiautomator2#764

就挺可惜的，因为我也觉得 VMOS 是非常适合挂脚本的工具，性能损失小还能低功耗熄屏挂机。

另外用真机改分辨率是能正常跑的，就是麻烦了点。

**Comment by uairyu** [comment]
> 没有使用虚拟机，我用adb改了手机分辨率，系统UI分辨率变成1280x720（720x1280）了，但是一进游戏立马又变成了1920x1080，然后就是各种错位点击cry
> 
> 我的锅，试出来了，不需要改成720x1280以使得自己看起来是正常的1280x720，因为操作的是手机，和guide里面的平板可能刚好横竖相反（？），现在可以正常操作，小米6，lineage18.1
> 
> 也许你可以试试裸机链接；或者手动用ADB链接你的手机看看是否是端口有问题

不想要真机，因为VMOS能后台运行一个操作系统，真正的后台挂碧蓝，不需要把游戏前台显示，也能熄屏挂脚本，真机就不符我的需求了

**Comment by pein0saga** [comment]
> VMOS

鱼和熊掌不能兼得，还是钱的问题，出个天价的VMOS VIP PLUS ULTRA可以满足需求
