### ISSUE TITLE
启动Alas后是白屏。

### ISSUE THREAD

**Issue by Exziro** [LmeSzinc/AzurLaneAutoScript#876]
之前使用一直正常
按照说明进行了多次刷新但是依旧是白屏
我将文件夹删除并且重新进行了安装
但是依然是白屏状态。
想请教一下如何解决 谢谢
![捕获1](https://user-images.githubusercontent.com/19307715/149298147-7efa8060-6831-4ab8-9684-5582847797c7.PNG)
![捕获2](https://user-images.githubusercontent.com/19307715/149298153-9bf12120-5c8a-4f7d-86bc-2238eee9da06.PNG)

**Comment by 18870** [comment]
Try the following

1. Ctrl+R to refresh
2. Update Alasapp to v0.3.5
3. Kill all python.exe, alas.exe in task manager
4. Change port in deploy.yaml
5. Reboot your computer
6. Reinstall Alas

==================================

尝试以下操作

1. Ctrl+R 刷新
2. 更新 Alasapp 至 v0.3.5
3. 如果有，在任务管理器中杀掉所有 python.exe，alas.exe
4. 在 deploy.yaml 中更换一个端口
5. 重启电脑
6. 重装 Alas

**Comment by Exziro** [comment]
请教一下 “4.在 deploy.yaml 中更换一个端口”这个 是文件里的WeBuiPort：22267这个参数么？
如果是的话请问一般改成什么比较好？我尝试改成了3000但是还依然是白屏。
其它操作全部有尝试但结果并没有什么好的效果。可以的话还能提供一些操作么？

**Comment by 18870** [comment]
试试 `WebuiHost: ::`
(两个冒号`::`)
可能是你的localhost解析到了ipv6地址上

**Comment by StortInter** [comment]
> 试试 `WebuiHost: ::` (两个冒号`::`) 可能是你的localhost解析到了ipv6地址上

`WebuiHost:`修改为`::`会报错，改成`[::]`则不会报错

已尝试过刷新、杀进程、更换IP及端口，但是白屏问题仍然没有解决

**Comment by 18870** [comment]
Electron里的地址是 `http://localhost:{port}`
试试用浏览器打开 http://127.0.0.1:{port}, http://[::1]:{port}, http://localhost:{port}
~~app就是个浏览器而已~~

**Comment by StortInter** [comment]
问题解决了
重新更新依赖便可： `pip install -r requirements.txt` （具体参数需要按自己情况修改）；或者把`deploy.yaml`中的`InstallDependencies`设为`true`
原因应该是缺少相关依赖导致Python进程启动失败，但是没有报错所以表现为Electron白屏（毕竟不能打开一个不存在的网页）

**Comment by Exziro** [comment]
InstallDependencies我这里默认是true, 依赖的话，请问怎么看哪个依赖有问题呢？我这边问题依然存在。请问方便的话能提供一下依赖参照么？

**Comment by chjptc** [comment]
![image](https://user-images.githubusercontent.com/91282011/149427575-c10936ad-1d91-4aba-bbd1-757a479de00a.png)
![image](https://user-images.githubusercontent.com/91282011/149427611-4128ba19-6f91-43cc-bb6a-448447bfaa7a.png)
I have the same problem, and when I try to connect to http://localhost:{port}, it says failed to connect.

**Comment by 18870** [comment]
> 感谢 方法7不行会报一些错，方法8没有问题 可以在浏览器打开。按照方法9操作后，alas.exe打开后也正常了。

在启动之前确保任务管理器中杀掉所有 python.exe，alas.exe
- 方法9是使用了旧版本，尝试切换回 `master` 分支看看是否还能打开 ~~，打不开我就坐大牢了~~
- 能给出方法7的报错吗（需要先切换回master分支）
- 使用方法7/8时如果在浏览器能打开，尝试是否能在 alas 上打开
- 如果方法7/8正常使用，尝试用 `python gui.py -d` 启动

> WARNING: The candidate selected for download or install is a yanked version: 'wrapt' candidate  

我目测 wrapt 没有影响，应该是能装上就行

我在虚拟机里安装alas能成功打开，并不能复现这个问题

**Comment by Exziro** [comment]
`2022-01-14 21:52:33.444 | INFO | +---------------------------------------------+
2022-01-14 21:52:33.460 | INFO | |                    START                    |
2022-01-14 21:52:33.460 | INFO | +---------------------------------------------+
2022-01-14 21:52:34.366 | INFO | <<< WEBUI CONFIGS >>>
2022-01-14 21:52:34.366 | INFO | [Theme] default
2022-01-14 21:52:34.366 | INFO | [Language] zh-CN
2022-01-14 21:52:34.366 | INFO | [Password] False
2022-01-14 21:52:34.366 | INFO | [CDN] False
[32mINFO[0m:     Started server process [[36m1568[0m]
[32mINFO[0m:     Waiting for application startup.
read: ./module/config/argument/menu.json
read: ./module/config/argument/args.json
read: ./module/config/i18n\zh-CN.json
read: ./module/config/i18n\en-US.json
read: ./module/config/i18n\ja-JP.json
read: ./module/config/i18n\zh-TW.json
2022-01-14 21:52:34.600 | INFO | Add task <check_update (delay=300)>
2022-01-14 21:52:34.600 | INFO | Add task <schedule_restart (delay=86400)>
2022-01-14 21:52:34.600 | INFO | Start task handler
2022-01-14 21:52:34.600 | INFO | <<< RESTART ALAS >>>
2022-01-14 21:52:34.600 | INFO | Start alas complete
[32mINFO[0m:     Application startup complete.
"E:/AlasApp_0.3.3/AlasApp_0.3.5/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
From https://github.com/LmeSzinc/AzurLaneAutoScript
 * branch              master     -> FETCH_HEAD
[ success ]
2022-01-14 21:52:36.053 | INFO | No update
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E235C08>
transport: <_SelectorSocketTransport fd=1448 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E350108>
transport: <_SelectorSocketTransport fd=792 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E342488>
transport: <_SelectorSocketTransport fd=1416 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E3BDD08>
transport: <_SelectorSocketTransport fd=1276 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E34E7C8>
transport: <_SelectorSocketTransport fd=1276 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E343288>
transport: <_SelectorSocketTransport fd=1324 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E3A56C8>
transport: <_SelectorSocketTransport fd=1332 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E3AAD48>
transport: <_SelectorSocketTransport fd=1332 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E3AA748>
transport: <_SelectorSocketTransport fd=1328 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E381F88>
transport: <_SelectorSocketTransport fd=1328 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E41AF48>
transport: <_SelectorSocketTransport fd=1328 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Fatal error in server handler
protocol: <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x000001A12E41A248>
transport: <_SelectorSocketTransport fd=1332 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\server.py", line 108, in handler
    reader, writer, server_state=self.server_state, config=config
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\_handlers\http.py", line 75, in handle_http
    protocol.connection_made(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 94, in connection_made
    self.client = get_remote_addr(transport)
  File "E:\AlasApp_0.3.3\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\lib\site-packages\uvicorn\protocols\utils.py", line 13, in get_remote_addr
    return (str(info[0]), int(info[1])) if isinstance(info, tuple) else None
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'`

这是用7方法出现的问题，然后访问浏览器出现的错误是127.0.0.1 未发送任何数据。
8 没有任何问题 浏览器可以打开 但是alas.exe还是白屏 
尝试用你说的这个
> 如果方法7/8正常使用，尝试用 python gui.py -d 启动
错误也是上面7方法出现的错误。

**Comment by 18870** [comment]
试试这个
https://github.com/nonebot/nonebot2/issues/20#issuecomment-703582940
> 使用命令重置winsock目录后正常，应该是个例了……
> `netsh winsock reset`

**Comment by Exziro** [comment]
出现错误是在使用命令后，再使用浏览器链接后出现的

> 在 deploy.yaml 里添加了一个选项禁用 reload，启动一次 alas 后会生成。改成 false 试试

这个改过后还是白屏。

按您说的后面这个方法重置winsock目录后 重启计算机，白屏问题终于解决了！
感谢老哥这一系列的reivew

**Comment by cxt986524267** [comment]
经过测试，关于白屏问题，可以通过开关wegame解决，原理不明，是否可复现不明（雾）

**Comment by Exziro** [comment]
> 经过测试，关于白屏问题，可以通过开关wegame解决，原理不明，是否可复现不明（雾） 猜测是可以通过winsock reset解决的白屏问题都可以通过这种方法解决，但这种方法不用重启电脑。

是这样的。我也发现这个规律了。好像是因为wegame占得端口和本身模拟器的端口还是和这个软件的端口有冲突？我也是瞎猜的。所以一般打lol都关了。

**Comment by Gehbt** [comment]
说一个我自己解决一个特定情况下的白屏的记录：
#### 前提：
- console.bat中执行alas.py可以成功运行，但是运行gui.py会产生以下错误
`ERROR:    [Errno 10013] error while attempting to bind on address ('0.0.0.0', 22267): 以一种访问权限不允许的方式做了一个访问套接字的尝试。`
- `netstat -ano | findstr 22267`的结果为空

#### 解决方案：
先执行命令`netsh interface ipv4 show excludedportrange protocol=tcp`查看到**被保留**的端口(的范围)
我这里的结果:
```
协议 tcp 端口排除范围

开始端口    结束端口
----------    --------
...
22198       22297
...
50000       50059     *
...
* - 管理的端口排除。
```
这里可以选择一个不在保留范围内的端口号,我这里是选择了50051
然后将`.\config\deploy.yaml`里的配置修改成`WebuiPort: 50051`，
再次运行gui.py就可以运行成功了

#### 后话：
- 搜索里说可能和HyperV有关，我这里就是装有wsl和docker，导致了被保留的端口很多，但是似乎每台电脑的`50000~50059`都是排除的保留端口？(我看了两台主机是这样的)
- 保留端口也有能够被使用的时候，但就是有时会出现被占用但是找不到占用进程的情况。
- 我也尝试过用`netsh winsock reset`，但是这样会让我的TeamViewer ID更改产生麻烦。
- 另一种解决方法，即增加动态端口的范围：`netsh int ipv4 set dynamicport tcp start=22267 num=5`，**但我没试过**

**Comment by Diffused7245** [comment]
deploy.yaml中，
`WebuiHost: localhost`
这么写就能既监听IPV6，又不会导致客户端白屏了。

IPV6都是公网IP，需要自己配防火墙，否则可能被扫到。
运营商的云手机系统屏蔽了V4入站连接，哪怕是组网软件的内网V4也不通，只能用v6了。

用 http://[::1]:22267/ 和 http://127.0.0.1:22267 都可以正常打开网页控制界面。
