### ISSUE TITLE
OSError: [Errno 22] Invalid argument 国服指的是什么？ 

### ISSUE THREAD

**Issue by jackson171** [LmeSzinc/AzurLaneAutoScript#882]
OSError: [Errno 22] Invalid argument
18:23:17.084 | WARNING | OSError([Errno 22] Invalid argument), retrying in 3 seconds...
18:23:21.013 | ERROR | [Errno 22] Invalid argument
Traceback (most recent call last):
  File "I:\Alasapp\AzurLaneAutoScript\module\base\retry.py", line 52, in __retry_internal
    return f()
  File "I:\Alasapp\AzurLaneAutoScript\module\base\timer.py", line 15, in function_timer
    print('%s: %s s' % (function.__name__, str(round(t1 - t0, 10))))
  File "I:\Alasapp\AzurLaneAutoScript\toolkit\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "I:\Alasapp\AzurLaneAutoScript\toolkit\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "I:\Alasapp\AzurLaneAutoScript\toolkit\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "I:\Alasapp\AzurLaneAutoScript\toolkit\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [Errno 22] Invalid argument
18:23:21.014 | WARNING | OSError([Errno 22] Invalid argument), retrying in 3 seconds...
Scheduler stopped.

启动更新后，仍同一报错

**Comment by 18870** [comment]
#881

**Comment by jackson171** [comment]
> #881

卸载后重新安装很有效，谢谢
