### ISSUE TITLE
10-4道中寻路出现Battle function exhausted

### ISSUE THREAD

**Issue by NeuWings** [LmeSzinc/AzurLaneAutoScript#90]
10-4捞船练级时候出现的错误,似乎是寻路时候位置导致的,再次测试浮现了一次.
运行环境雷电模拟器4.0.29.

Logs:
2020-07-10 12:53:18.881 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.881 | INFO | Using function: battle_0
2020-07-10 12:53:18.881 | INFO | Fleet 2 step on
2020-07-10 12:53:18.881 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.881 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.881 | INFO | Using function: battle_0
2020-07-10 12:53:18.881 | INFO | Fleet 2 step on
2020-07-10 12:53:18.881 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.881 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.881 | INFO | Using function: battle_0
2020-07-10 12:53:18.882 | INFO | Fleet 2 step on
2020-07-10 12:53:18.882 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.882 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.882 | INFO | Using function: battle_0
2020-07-10 12:53:18.882 | INFO | Fleet 2 step on
2020-07-10 12:53:18.882 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.882 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.882 | INFO | Using function: battle_0
2020-07-10 12:53:18.882 | INFO | Fleet 2 step on
2020-07-10 12:53:18.882 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.882 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.882 | INFO | Using function: battle_0
2020-07-10 12:53:18.882 | INFO | Fleet 2 step on
2020-07-10 12:53:18.882 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.882 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.882 | INFO | Using function: battle_0
2020-07-10 12:53:18.882 | INFO | Fleet 2 step on
2020-07-10 12:53:18.882 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.882 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.882 | INFO | Using function: battle_0
2020-07-10 12:53:18.882 | INFO | Fleet 2 step on
2020-07-10 12:53:18.882 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.882 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.882 | INFO | Using function: battle_0
2020-07-10 12:53:18.882 | INFO | Fleet 2 step on
2020-07-10 12:53:18.882 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.883 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.883 | INFO | Using function: battle_0
2020-07-10 12:53:18.883 | INFO | Fleet 2 step on
2020-07-10 12:53:18.883 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.883 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.883 | INFO | Using function: battle_0
2020-07-10 12:53:18.883 | INFO | Fleet 2 step on
2020-07-10 12:53:18.883 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.883 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.883 | INFO | Using function: battle_0
2020-07-10 12:53:18.883 | INFO | Fleet 2 step on
2020-07-10 12:53:18.883 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.883 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.884 | INFO | Using function: battle_0
2020-07-10 12:53:18.884 | INFO | Fleet 2 step on
2020-07-10 12:53:18.884 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.884 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.884 | INFO | Using function: battle_0
2020-07-10 12:53:18.884 | INFO | Fleet 2 step on
2020-07-10 12:53:18.884 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.884 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.884 | INFO | Using function: battle_0
2020-07-10 12:53:18.884 | INFO | Fleet 2 step on
2020-07-10 12:53:18.884 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.884 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.884 | INFO | Using function: battle_0
2020-07-10 12:53:18.884 | INFO | Fleet 2 step on
2020-07-10 12:53:18.884 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.885 | INFO | -------------------- BATTLE_3 --------------------
2020-07-10 12:53:18.885 | INFO | Using function: battle_0
2020-07-10 12:53:18.885 | INFO | Fleet 2 step on
2020-07-10 12:53:18.885 | INFO | Fleet_2 step on got roadblocks.
2020-07-10 12:53:18.885 | WARNING | Battle function exhausted.
2020-07-10 12:53:18.886 | ERROR | Battle function exhausted.
Traceback (most recent call last):
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 24, in run
    self.__getattribute__(command.lower())()
  File "C:\fakepath\AzurLaneAutoScript\alas.py", line 99, in main
    az.run(self.config.CAMPAIGN_NAME)
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 173, in run
    self.campaign.run()
  File "C:\fakepath\AzurLaneAutoScript\module\campaign\campaign_base.py", line 117, in run
    raise ScriptError('Battle function exhausted.')
module.exception.ScriptError: Battle function exhausted.
2020-07-10 12:53:18.888 | INFO | Saving error: ./log/error/1594356798888

含截图的压缩包另行附上了.
[1594353513045.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/4901143/1594353513045.zip)
[1594356798888.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/4901152/1594356798888.zip)

(另外我才刚开始试用,日常部分会在战术研修选择界面卡住,不知道是不是个人问题...闲了测几次再来看提不提issue吧.)

**Comment by LmeSzinc** [comment]
已修复, 
二队踩格子 (fleet_2_step_on) 在目标格子都有敌人或都被一队清理过时, 会返回错误的结果

另外卡战术研修的问题已经修过了, 请更新

**Comment by NeuWings** [comment]
了解,感谢回复.
这就去更新测试下.
